### ISSUE TITLE
The collected data is lost

### ISSUE THREAD

**Issue by shixinghong** [prometheus/prometheus#10115]
![2c8135e6990bdfc154e0b18e8a226ab](https://user-images.githubusercontent.com/56341144/148188246-312915d9-831c-461c-8446-72fe4710fea3.png)

As shown in FIG,There is only less than one day's data in prometheus.
Then I checked the data directory of prometheus(Look at the picture below)
The directory size of chunks is 21M,But the index file has reached 1.9G!
So what is the reason for this situation?

![4ade93023a9cf71b0d4b1e79cb14244](https://user-images.githubusercontent.com/56341144/148188265-a52eb6ce-0ef0-449d-8fe6-373a78479ab5.png)

This is the version information of the server environment

![114fd2d08439718fb71b4d8ffc62a81](https://user-images.githubusercontent.com/56341144/148188281-c24b4fa2-7f92-47cc-b94e-084a81efbaef.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
