### ISSUE TITLE
Align OpenTelemetry Options with upstream

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#10225]
We should align our tracing options with upstream:

- Endpoint for HTTP must contain the protocol (http/https), therefore being a full URL.
- Insecure must only affect GRPC, and default to false.
- We must support HTTP/GRPC headers.
- We must support "compression".
- We must support configurable Timeout.
- We must support specifying the protocol for HTTP (protobuf/json).

https://opentelemetry.io/docs/reference/specification/protocol/exporter/#configuration-options

**Comment by matej-g** [comment]
@roidelapluie Happy to continue this

**Comment by roidelapluie** [comment]
Awesome!

**Comment by matej-g** [comment]
Just few additions:
- Although the protocol for options specifies, that the HTTP endpoint must be a full URL, the URL actually is [built](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracehttp/client.go#L205) by the OTEL exporter based on the provided options. Meaning currently, the OTEL exporter expects the endpoint to not include schema, but the `http` / `https` is prepended based on the [`WithInsecure()` option](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracehttp/client.go#L304). I believe this aligns fine with how are options currently in Prometheus, i.e. `endpoint` includes the host:port and `insecure` option will tell the OTEL exporter to use either http(s). Otherwise we might want to first bring up this change in the upstream.
- Protocol choice option is, at the time, not implemented in the exporter.
- For the other options, we should be able to add them just fine.
