### ISSUE TITLE
`avg()` should ignore non existing values

### ISSUE THREAD

**Issue by blackliner** [prometheus/prometheus#10434]
**What did you do?**
I have AWS instances coming and going (autoscaling). My goal is to to find the nodes with the highest average CPU utilization in the current time range:
`avg by (instance) ((1 - rate(node_cpu_seconds_total{mode="idle"}[$__range])) and node_cpu_seconds_total )`

**What did you expect to see?**
`avg()` to not include non existing values

**What did you see instead? Under which circumstances?**
I think avg is calculating wrong values. As can be seen in the screenshot, the node first starts up at 9:00am with about 80% utilization. The calculated average is 70.2%, but that clearly is not true. It looks like avg is extrapolating the first valid value all the way to the left, which would explain the high average.
![image](https://user-images.githubusercontent.com/23190927/157798538-a000b512-e9de-4dfe-bd1d-14fe7439c762.png)
If I go ahead in time, the values become more meaningful::
![image](https://user-images.githubusercontent.com/23190927/157798558-abe3bcc6-f94c-4248-9bf6-7224b92c9ea5.png)

**Comment by roidelapluie** [comment]
Can you try

avg by (instance) ((1 - rate(node_cpu_seconds_total{mode="idle"}[$__rate_interval])) and node_cpu_seconds_total and node_cpu_seconds_total offset $__rate_interval  )

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by blackliner** [comment]
@roidelapluie yes I tried your suggestion, but IMHO this is faulty default behavior of the avg method, to take numbers that do not exist into account

**Comment by roidelapluie** [comment]
The issue is not avg but it is coming from rate(), which does extrapolate when data does not cover the full range: https://www.youtube.com/watch?v=67Ulrq6DxwA
