### ISSUE TITLE
Prometheus is not providing used and available space for AWS EFS based PVC

### ISSUE THREAD

**Issue by amareshgreat** [prometheus/prometheus#10630]
### What did you do?

Hello,
looking for a solution for PVC usages and alert when PVC reaches some limit(80%), currently we have deployed Prometheus helm chart in kubernetes cluster and we are getting PVC data from kubelet_volume_stats_capacity_bytes, kubelet_volume_stats_available_bytes, kubelet_volume_stats_used_bytes.

however above key is not collecting data for the PVC which is based on EFS storage class.
this key "kube_persistentvolumeclaim_resource_requests_storage_bytes" is collecting data for EFS based PV/PVC, but it doesn't provide the used and available space.
EFS based storageclass is created using EFS CSI driver.

looking for some help how we can monitor the PVC which is based on EFS CSI storage class.

Thank you,
Amaresh Kumar

### What did you expect to see?

we expect to get the PVC total, used, available space collected by prometheus

### What did you see instead? Under which circumstances?

prometheus isn't collecting PVC total, used, available space for AWS EFS based PVC

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
