### ISSUE TITLE
Prometheus resets alerts

### ISSUE THREAD

**Issue by tal-ayalon** [prometheus/prometheus#10770]
### What did you do?

We are having problem with Prometheus alert.
It looks like every once in a while, Prometheus stops alerting about active alerts, even though the metrics value is still in "true" condition for the alert.
As you can see in this picture, the metric always returns the value of 1:
![image](https://user-images.githubusercontent.com/74187228/170863105-d587d4c9-63b9-4ebc-99fd-f2f16f0dc0a3.png)

The alert is configured to alert if the value of the query is one but the problem is that every once in a while, there is a missing alert so the time duration is reseting:
![image](https://user-images.githubusercontent.com/74187228/170863110-d003e180-1b58-4826-a55d-6a6f6e74ff1d.png)

### What did you expect to see?

I expected that Prometheus will keep showing that the Alert is in "true" state and the alert to be in "active" status

### What did you see instead? Under which circumstances?

Didn't do something

### Prometheus version

```text
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
```

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
