### ISSUE TITLE
performance improvement idea: drop metric names later

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#10921]
Currently, many simple functions such as `abs()` call `DropMetricName()` on every sample.

https://github.com/prometheus/prometheus/blob/0906f2eafa3506d411f2053ecba160a6c5ca0387/promql/functions.go#L536-L539

It would be more efficient to leave till the end and do once per series.  `DropMetricName` is hashed, so the additional work on every step of a range query is not huge, but we could eliminate that work and the hash table.

This is not a trivial change: there are about four different ways that functions get called and it took me a while just to follow all the logic.  I do think it should be possible to refactor this area more simply and understandably.

For functions that take a vector, any metric name in the output is ignored!
https://github.com/prometheus/prometheus/blob/0906f2eafa3506d411f2053ecba160a6c5ca0387/promql/engine.go#L1400-L1405

**Comment by bboreham** [comment]
Some discussion about not dropping the metric name: #11397

**Comment by beorn7** [comment]
With #14477 in, one might argue we are now doing what's being asked for here.

However, the new behavior is behind a feature flag, and if it is not set, we do the same thing as before (if I have read the code correctly).

It might very well be that the delayed name removal turns out to be a mistake, and then we are back to square one.

I guess we could still do the name removal late (as done in #14477) but make sure that _logically_ things still work as if the name is not removed later (e.g. error out if in between there are duplicate label sets _not_ considering the name; make it impossible to label-replace the name label in between, …).

I _hope_ that #14477 will be the way to go for the future (although it creates some problems when dissecting a query and explore it in parts, may it be manually or with Promlens), but hope is not a strategy…

@bboreham your call if you want to leave this open.

**Comment by beorn7** [comment]
Hello from the bug scrub.

@bboreham we decided to close this for now, but please re-open if you want to keep this in the loop.
