### ISSUE TITLE
how to pass dynamic variables in mskfile_sd file for msk prometheus

### ISSUE THREAD

**Issue by kalavathiy** [prometheus/prometheus#11073]
### What did you do?

i have given bootstrap brokers in the msk file sd as sttatic.I want to pass them as dynamic varibales in scrape configPlease help m eto suggest on this

### What did you see instead? Under which circumstances?

i want to pass dynamic data in

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
