### ISSUE TITLE
Add sum of squares for histogram and summary for stddev calculation

### ISSUE THREAD

**Issue by vadimonus** [prometheus/prometheus#11126]
## Proposal
Stddev is third by importante analytic metric for data (after avg and count). As i can see, currenty prometheus does not calculate stddev for histograms. Suprisely found, that https://github.com/prometheus/prometheus/issues/7030, https://github.com/prometheus/prometheus/issues/3998 was closed without solution, no way was found to calculate this.

But solution is very simple, collector should return  _sum_of_squares metric in addition to _count and _sum metrics. 
Example:

First collection
prometheus_http_request_duration_seconds_count 1000
prometheus_http_request_duration_seconds_sum 1000
prometheus_http_request_duration_seconds_sum_of_squares 1000

Data values 0 8 8 2 3 are processed between collections

Second collection
prometheus_http_request_duration_seconds_count 1005
prometheus_http_request_duration_seconds_sum 1021
prometheus_http_request_duration_seconds_sum_of_squares 1132

count diff - 5, sum diff - 21, summ of squares diff = 132, avg = 21/5=4.2, average square = 132/5 = 28,2, 
stdvar = average square - square of average = 28.2-4.2^2 = 10.56, stddev = sqrt (stdvar) = 3.249615.

Let's assume we had next collection (using same values for example wich does not change avg and stddev)

Data values 0 0 8 8 8 8 2 2 3 3 are processed between collections

Third collection
prometheus_http_request_duration_seconds_count 1015
prometheus_http_request_duration_seconds_sum 1063
prometheus_http_request_duration_seconds_sum_of_squares 1396

For second inteval
count diff - 10, sum diff - 42, summ of squares diff = 264, avg = 24/10=4.2, average square = 264/10 = 28,2, 
stdvar = average square - square of average = 28.2-4.2^2 = 10.56, stddev = sqrt (stdvar) = 3.249615.

For both intervals together
count diff - 15, sum diff - 63, summ of squares diff = 396, avg = 63/15=4.2, average square = 396/15 = 28,2, 
stdvar = average square - square of average = 28.2-4.2^2 = 10.56, stddev = sqrt (stdvar) = 3.249615.

These are correctly calculated sdtdev & stdvar for given dataset of 15 number, but with only 3 counters transferred from collector to server.
But if we try to calculate stddev on server, we will get 0, because avg value is 4,2 for both intervals, meaning no deviation, and that's incorrect.

**Comment by beorn7** [comment]
I think we are dealing with two different things here:

1. #7030 and #3998 were proposals to calculate stddev from an existing histogram, without any changes to the histogram itself. IIUC that was rejected back then because it is way too common that some observations end up in the +Inf bucket. With the upcoming Native Histograms, this decision can be revisited as most cases will have all observations slotted into regular buckets, so that a stddev calculation might make sense. (Some more research needed, though.)
2. What @vadimonus suggests here is a change that starts at the exposition level. It needs an additional field exposed by Histograms and Summaries, similar to the existing `..._sum` and `..._count`, namely `..._sum_of_squares`. This was actually discussed as part of the OpenMetrics specification, see https://github.com/OpenObservability/OpenMetrics/issues/64 . The conclusion back then was that float64 doesn't give us enough precision to meaningfully expose a sum of squares. This decision was also flagged for reconsideration once higher precision numbers are supported by OpenMetrics and/or Prometheus.

WRT (1), I have added an item to our TODO list to consider a function estimating stddev from a Native Histogram.

WRT (2), I am inclined to stick with the conclusion OpenMetrics arrived at until contrary evidence is presented.

**Comment by beorn7** [comment]
And WRT (2) again: In case the precision issues don't apply to your specific scenario, you are free, of course, to expose a separate counter called `prometheus_http_request_duration_seconds_sum_of_squares` from your binary, and then use normal PromQL to process it. It's just not something currently supported by the instrumentation libraries. You needed to code that on your own with a custom collector, which is still easy enough for a niche use case, I would say.

**Comment by vadimonus** [comment]
@beorn7 , thanks for replies. I did no find discussions, that you provided, so created this one.

The main aim of my proposal was to provide some function in promsql, that depends on _sum_of_squares counter and someway standartize that histograms and summary can have such counter. This will act as a signal to client libraries developers to add such counters to client libraries - it's very simple improvment and can be done easily. I'm sure, many client libraries will implement this as soon, as name for this counter will be standartized.

Precision of float64 is discussable. For many use cases this should be enough. Roughly, if float32 is enough for sum in some metric, then float64 would be enough for sum_of_squares.
However, Postgresq uses eight-byte float in internal counter for both sum and sum of squares, whan calculating stddev and that is enough. Take a look at https://github.com/postgres/postgres/blob/3e071b2cf584052b0799ebbc4d38ecfdb5bd701a/src/backend/utils/adt/float.c#L2986 , it uses youngs-cramer algorithm (https://www.jstor.org/stable/1267176) to minimize error when calculating sum_of_squares. Maybe, you find that useful.

Closing this discussion as duplicate

**Comment by beorn7** [comment]
> Precision of float64 is discussable.

I think such a discussion should happen in the context of exposition formats. Currently, https://github.com/OpenObservability/OpenMetrics/ and https://github.com/open-telemetry come to mind. If you have the ambition to push your case, I would recommend to engage with the respective communities.
