### ISSUE TITLE
Remote_ Read is configured, but cannot read the metric written in informdb

### ISSUE THREAD

**Issue by yehaotong** [prometheus/prometheus#11177]
### What did you do?

I'm in Prometheus Remotewrite and remotewrite are correctly configured in yaml, and I also saw Prometheus write data to informdb using show measurements in informdb. This does not seem to be a problem, but I manually create a table such as http_ reqeust_total and constantly customize some data into it. Then I query http_reqesut_total through Prometheus graph, but I can't find it.

### What did you expect to see?

I hope that I can query the data written from other channels in informdb through Prometheus

### What did you see instead? Under which circumstances?

I cannot query metric from influxdb

**Comment by yehaotong** [comment]
when I query on prometheus,I saw the influxdb has this log:
lvl=info msg="Prometheus can't read cursor" log_id=0cLRYF6l000 service=httpd cursor_type=int64 series="[{__name__ traefik_reqesut_total} {code 200}]"
what is the problem?

**Comment by dgl** [comment]
It looks like you have various different misspellings of `request`. Otherwise you've not given us enough to go on, but my guess is this is likely a question for influx DB, influx cannot serve all data via Prometheus remote_read (see https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/#how-prometheus-metrics-are-parsed-in-influxdb).

**Comment by nsaikrishna15** [comment]
same issue with influxdb
