### ISSUE TITLE
codemirror-promql - "outdated" dependencies 

### ISSUE THREAD

**Issue by 0x0dr1y** [prometheus/prometheus#11188]
### What did you do?

Installed codemirror-promql and codemirror packages in the latest version. 

### What did you expect to see?

It should work with the latest version. 

### What did you see instead? Under which circumstances?

First of all, that is no real bug, but a current limitation: 

If you have multiple versions of @codemirror/state, codemirror will start to complain and stop working <- this is intended. The main issue is that codemirror-promql uses an "outdated" version of codemirror and is due to this no longer being compatible with the latest version. 

I don't know how dependency updates are handled currently within your organization, but it would be cool to automate those updates, or at least check on them frequently. 

Thanks for your time, and sorry for missusing the Bug section for this.

**Comment by roidelapluie** [comment]
cc @Nexucis

**Comment by Nexucis** [comment]
`codemirror-promql` or `lezer-promql` use `peerDependencies` to depend on `codemirror` or `lezer`. 

For example: 

https://github.com/prometheus/prometheus/blob/main/web/ui/module/codemirror-promql/package.json#L48-L54

Hopefully because we said `codemirror-promql` is compatible with any version above `6.0.0` you can install the latest version of codemirror without waiting an upgrade of the `codemirror-promql` dependencies. 

As you can see by using this tool https://semver.npmjs.com/, if you enter `@codemirror/autocomplete` and the range `^6.0.0`, `6.1.0` is available.

**Comment by Nexucis** [comment]
What npm version are you using ?
What dependencies do you have in your `package.json` ?

**Comment by Nexucis** [comment]
I have a project where I'm using `@prometheus-io/codemirror-promql` and I am using it with the last version of `codemirror` with no issue.

here an extract of the `package.json`. 

```json
{
[...]
    "@codemirror/autocomplete": "6.2.0",
    "@codemirror/commands": "6.1.0",
    "@codemirror/language": "6.2.1",
    "@codemirror/lint": "6.0.0",
    "@codemirror/search": "6.2.0",
    "@codemirror/state": "6.1.1",
    "@codemirror/view": "6.2.4",
    "@lezer/common": "1.0.1",
    "@lezer/highlight": "1.0.0",
    "@prometheus-io/codemirror-promql": "0.38.0",
}
```

**Comment by beorn7** [comment]
Hello from the bug scrub!

This seems to have worked already 2y ago. Closing.
