### ISSUE TITLE
promql (histograms): Refine interpolation behavior

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11215]
Native histograms use interpolation to estimate quantiles (with `histogram_quantile`) or to estimate the fraction of observations falling within an interval (with `histogram_fraction`). Currently, the interpolation is linear, which is almost certainly suboptimal for the exponential bucketing schema we are using. Instead, it should be some kind of exponential interpolation (have a look at [beta distribution](https://en.wikipedia.org/wiki/Beta_distribution) perhaps?). Or even no interpolation (arguably, the harmonic mean of a bucket minimizes the maximum possible relative error, while interpolation minimizes the expectation value of the error, but maximizes the theoretical maximum error). Or even make it configurable (even more relevant for custom bucket layouts, e.g. for linear buckets, linear interpolation would be a good fit).

Also, we have to come to terms if it is fine to assume the zero bucket is only filled with positive (negative) observations if all other observations are in positive (negative) buckets (respectively), which is the currently implemented behavior.

Finally, with float counters, we make sure to never extrapolate "below zero", see [code](https://github.com/prometheus/prometheus/blob/c92673fb1480cd6e3404a004522cbb851be4115d/promql/functions.go#L92-L104). We could/should implement the same for histograms. (Presumably by making sure that no bucket and no count is ever extrapolated below zero.)

**Comment by tbg** [comment]
Not to clutter this issue, but I've noticed two practical issues with quantiles that are loosely related to interpolation.[^1]
Would appreciate your thoughts on these.

## Should pick last, not first, matching bucket in run of equal counts

Consider the following state in `bucketQuantile`[^2]:

```
bucket counts = [10, 20, 20, 20, 31], rank=18 (i.e. q=18/31)
```

The `sort.Search` will then select the bucket `b=1` (i.e. the first `20`), but it ought to have selected the last one (`b=3`), and use its bucket boundary for the interpolation. (Which would have run into additional problems due to a divide-by-zero since we'll end up with `count=0` near the end of the method). As is, we get a result that's too small, and drastically too small in the common case of exponential bucket spacing.

The most extreme example is that of equal bucket counts: `counts = [10, 10, 10, 10, ...]` and, say, the first bucket boundary is `0.0` and the last one `10.0 <= x <= +Inf`. Every measurement added to this histogram went into the `>= 10` bucket - and yet we're returning `0` as the `histogram_quantile(1.0, _)`. It should return `10`.

I have a change for this coded up locally but unfortunately it modifies some of the existing test cases (since they have a repeating adjacent bucket count[^3]) so I wanted to check if there's something I'm missing before I finish it up.

## Run of empty buckets before +Inf prevents proper interpolation

The second issue isn't exactly easy to fix, and has to do with omitting buckets with a zero count. I seem to frequently see in our (CockroachDB's) internal monitoring that high quantiles over rates of latency histograms return bogus low values. I extracted one such instance, which is abbreviated below:

```
# index_in_buckets_slice / upper_bucket_boundary / count
[...]
idx 94: <=22.020095ms: 142.240000
idx 95: <=23.068671ms: 142.240000
idx 96: <=24.117247ms: 142.320000
[...]
idx 144: <=192.937983ms: 142.320000
idx 145: <=201.326591ms: 142.320000
idx 146: <=+Inf: 142.320000
```

From what's described above, one problem is that we'll get a `p100` of `24.117247ms` instead of `201.326591ms`. But the true `p100` should be `10s`, since I happen to know that the histogram has its last bucket boundary there. However, it seems that very few measurements ever fall into the bucket(s) between `201.326591ms` and `10s` and instead fall into the `+Inf` bucket, and of course that bucket doesn't lend itself to interpolation. Since the empty buckets between idx 145 and the `+Inf` bucket are omitted, `histogram_quantiles` couldn't return anything more useful than `201.326591ms` even if we fixed the first problem (as is, it returns `24.117247ms`, despite a constant stream of 10s+ measurements flowing into this latency metric!)

I doubt that this second problem is easy to fix - or rather, it should be fixed on our end by picking better bucket boundaries, which to our credit we have[^4] though I have yet to check that these buckets actually prevent the problem in practice.

[^1]: https://github.com/cockroachdb/cockroach/pull/88127#issuecomment-1251087403
[^2]: https://github.com/prometheus/prometheus/blob/main/promql/quantile.go#L100-L101
[^3]: https://github.com/prometheus/prometheus/blob/2bb457dcce500053e115a6fc05984aee7fdf321a/promql/testdata/histograms.test#L14-L15
[^4]: https://github.com/cockroachdb/cockroach/pull/85990

**Comment by beorn7** [comment]
I think some confusion has happened here.

This issue is about the new Native Histograms. Currently, all related code exclusively lives in a [branch](https://github.com/prometheus/prometheus/tree/sparsehistogram). The code in [main](https://github.com/prometheus/prometheus/tree/main) is only dealing with the conventional Histograms.

If there is really an issue with the code for conventional Histograms, it should go into a separate issue.

Having said that, I don't really see the described issue. Conventional Histograms have _cumulative_ buckets. So the described buckets `[10, 20, 20, 20, 31]` would look like `[10, 10, 0, 0, 11]` as regular buckets (and `[10, 10, 10, 10, ...]` would look like `[10, 0, 0, 0, ...]`). So in the given example, the observation with rank=18 is definitely in bucket #1 (zero based counting), and the question is merely if we should estimate the quantile value as the arithmetic mean of the bucket boundaries, the harmonic mean of the bucket boundaries, or some linear or exponential interpolation.

**Comment by tbg** [comment]
Thanks @beorn7 for the prompt reply - definitely not the right thread to be discussing this here, I'll mull your reply over and open a new issue. I'm hiding my comment as "off topic" to avoid distracting future readers of this issue.

**Comment by beorn7** [comment]
#14677 implements "exponential interpolation", which I think we should go with. The description explains the idea and also has some rationale why I did not go for a more basic or a fancier approach.

**Comment by beorn7** [comment]
The same #14677 also makes the call of sticking with the heuristics that the zero bucket is assumed to be only positive for an only-positive histogram (and vice versa for only-negative histograms).

I still have to think about the "do not extrapolate below zero" thing.

**Comment by beorn7** [comment]
#14677 is merged.

I think the "do not extrapolate below zero" trick is too tricksy in the context of native histograms with their many buckets. So let's leave it as is.
