### ISSUE TITLE
Revisit making time zone configurable for logging

### ISSUE THREAD

**Issue by thernstig** [prometheus/prometheus#11358]
## Proposal
**Use case. Why is this important?**

Prometheus currently logs timestamps in UTC like `ts=2022-09-20T09:00:37.982Z`. There is no way to set the timestamp to include the time zone offset. I.e. to replace `Z` with e.g. `+01:00` to log in a specific local time, possibly set via the `TZ` variable. Which follows the [iana Time Zone Database](https://www.iana.org/time-zones).

This is important because in some organizations with a widespread amount of microservices/applications they require a consistent logging format in regards to the time zone. A predominant logging format in Unix is the syslog protocol, defined in https://www.rfc-editor.org/rfc/rfc5424.html. If organizations require this to be followed in logs, there is no way to achieve this in Prometheus.

**Considerations**
Both [the FAQ](https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc) and the previous issue https://github.com/prometheus/prometheus/issues/500 regarding this were closed without action. But this is a very valid feature request and as such brought up again.

It is also understood logging can be normalized in aggregation services when inserted into databases (such as Open Search or similar), but the question here is about the actual logs going to stdout/file directly since that might still be a place where applications want to follow the syslog format, logging in a particular time zone with a time zone offset.

Please do not close this as an invalid request as there are strong use cases in organizations wanting to follow the syslog specification.

**Comment by beorn7** [comment]
With current Prometheus versions (I assume because of the migration to log/slog), the logging happens in the timezone that is configured in your environment. For example, on my laptop, I get log timestamps like this: `time=2024-10-18T23:45:55.022+02:00` (timezone is CEST). I wholeheartedly recommend to always run your servers with UTC, or at least avoid any timezone that is tainted by so-called “daylight saving time”, which is neither daylight saving nor a time.

Anyway, the feature requested here has been addressed. Closing.

**Comment by melroy89** [comment]
> With current Prometheus versions (I assume because of the migration to log/slog), the logging happens in the timezone that is configured in your environment. For example, on my laptop, I get log timestamps like this: `time=2024-10-18T23:45:55.022+02:00` (timezone is CEST). I wholeheartedly recommend to always run your servers with UTC, or at least avoid any timezone that is tainted by so-called “daylight saving time”, which is neither daylight saving nor a time.
> 
> Anyway, the feature requested here has been addressed. Closing.

Uh.. So now I got UTC+2 timezone issues, because in EU we changed to UTC+1 Winter time, and fail2ban is complaining:

https://github.com/fail2ban/fail2ban/issues/2882#issuecomment-2449460164

Why is Prometheus still reporting `+2:00` it should now report `+1:00` since during winter time it will become UTC+1, right? Anyhow, problems .

**Comment by beorn7** [comment]
Prometheus is using the underlying log/slog package. Any timezone weirdness should therefore be solved in that Go standard library package.
