### ISSUE TITLE
Lots of CVEs detected from old dependencies

### ISSUE THREAD

**Issue by jcpunk** [prometheus/prometheus#11406]
### What did you do?

Looking at the security report at https://artifacthub.io/packages/helm/prometheus-community/prometheus

There are a number of vulnerabilities listed.

### What did you expect to see?

Some automation opening tickets or resolving these issues.

### What did you see instead? Under which circumstances?

A bunch of known vulnerabilities from the dependencies of the default helm chart.

**Comment by beorn7** [comment]
Please do not report security incidents via GitHub issues. Should a report turn out to expose an actually serious security problem, it would be highly problematic to have it reported in the open before a fix has been provided.

See https://prometheus.io/docs/operating/security/ for instructions how to report security incidents (and also take into account the note about security scanners).

**Comment by beorn7** [comment]
We do have automation in place that flags security problems in dependencies. The reports on https://artifacthub.io/packages/helm/prometheus-community/prometheus aren't very helpful, though, because they flag dependencies that aren't actually used, and they flag issues of obsolete versions, which have been fixed long ago.
