### ISSUE TITLE
Why does disconnection occur in the figure? I think there is time in the http return value

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [prometheus/prometheus#11455]
### What did you do?

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/76942485/195383984-36fc4488-0aac-44d4-8cac-6f58a47c8181.png">
Why does disconnection occur in the figure? I think there is time in the http return value

### What did you see instead? Under which circumstances?

Why does disconnection occur in the figure? I think there is time in the http return value

### Prometheus version

2.25.1

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
