### ISSUE TITLE
prometheus server failed to run  when helm upgrade using official prometheus chart

### ISSUE THREAD

**Issue by aries1998** [prometheus/prometheus#11471]
### What did you do?

Just change the values of  runAsUser to root of promethues components (server , alertmanager , pushmanager , nodeExporter)

The following content added to  values.yaml  .  When upgrading , all the other components (alertmanger , pushgateway, nodeExporter) works as expect of running as root except prometheus server.
```
  securityContext:
  ¦ runAsUser: 0
  ¦ runAsNonRoot: false
```
helm upgrade command: helm upgrade --reuse-values --atomic --values=values_prometheus.yaml prometheus prometheus-community/prometheus -n monitor

### What did you expect to see?

all prometheus components run as root from nobody.

### What did you see instead? Under which circumstances?

when upgrading , the old prometheus server container is still  running , so the lock file is occupied by old server.

```
root@k8s-master:~/.../workspace/k8s/prometheus# k get pod -n monitor | grep prometheus-server
prometheus-server-599f5c574-ttj5l               2/3     CrashLoopBackOff   9 (3m ago)   24m
prometheus-server-65dfd9c9d9-nbvxv              3/3     Running            0            29m
```

error meesage of newly create prometheus server 
```
root@k8s-master:~/.../workspace/k8s/prometheus# k logs  prometheus-server-599f5c574-ttj5l  prometheus-server -n monitor  | tail -n 5
ts=2022-10-18T12:02:28.954Z caller=main.go:882 level=info msg="Scrape manager stopped"
ts=2022-10-18T12:02:28.954Z caller=main.go:849 level=info msg="Notify discovery manager stopped"
ts=2022-10-18T12:02:28.954Z caller=notifier.go:608 level=info component=notifier msg="Stopping notification manager..."
ts=2022-10-18T12:02:28.954Z caller=main.go:1110 level=info msg="Notifier manager stopped"
ts=2022-10-18T12:02:28.954Z caller=main.go:1119 level=error err="opening storage failed: lock DB directory: resource temporarily unavailable"
```

### System information

ubuntu 20.04

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
It is possible that the issue you are experiencing is not a bug in Prometheus, but rather a result of using an unsupported filesystem or of two Prometheus instances attempting to lock the same data directory.

I recommend checking the filesystem being used for the data directory to ensure that it is supported by Prometheus, and also making sure that there is only one Prometheus instance running and accessing the data directory.

As a general best practice, it is not recommended to run Prometheus as the root user due to security concerns. Some filesystems may not support running Prometheus as root, or may change the UID to nobody when root is used. It is generally best to run Prometheus as a non-root user, such as the prometheus user.

If you continue to experience this issue after checking these things, please let us know and we will do our best to assist you in finding a resolution. Thank you for using Prometheus.

*Note: generated with the help of chatgpt*
