### ISSUE TITLE
Multiple {{ $value }} in rules

### ISSUE THREAD

**Issue by jinnuae40** [prometheus/prometheus#11483]
### Proposal

Dear team, 
I am trying to get multiple values in one rule.

When using the expression below, I am looking for a way to receive the disk size from the alarm together with a percentage.
`expr: 100 - (avg by (instance_name, instance)(irate(node_cpu_seconds_total{job="ec2-node",mode="idle", instance_name!~"^KR.*-EKS.*"}[2m])) * 100) > 70`

I checked the short discussion about it in the link below, is there anything in progress?
URL: https://groups.google.com/g/prometheus-users/c/Rah4Ck_AoDM

Thanks !

**Comment by hoffie** [comment]
I think the linked thread covers it pretty well:
- If you need to alert on two different values independently, use two rules.
- If you want to alert if two different expressions both return results, combine them accordingly (e.g. using `and`, `or`, `unless`).
- If you want to include multiple values in an alert's metadata, [you can do that as well using alert templating](https://groups.google.com/g/prometheus-users/c/Rah4Ck_AoDM/m/xztWhE2nCAAJ). It sounds like this is what you might be after?

All in all, this sounds like a usage question which is better asked in one of the community channels like the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or the [forums](https://discuss.prometheus.io) rather than in a GitHub issue.

**Comment by jinnuae40** [comment]
Dear @hoffie,
I'm so glad you replied so quickly.
If you don't think it's a suitable space, I'll move it soon.
Before that, please kindly let me ask you one more question.

If I combine expressions with `and, or, unless`, then how can I get those values accordingly?
Should I use like $value[0], $value[1]? (I'm so sorry if it's a basic question.)

**Comment by hoffie** [comment]
> If I combine expressions with `and, or, unless`, then how can I get those values accordingly? Should I use like $value[0], $value[1]?

I think you can't. The expression will return exactly one. Use option (3) from above if you need another (possibly related) value in your alert.

**Comment by jinnuae40** [comment]
Thank you for your help @hoffie.
I did and operator as you suggest in the option 2.

I tried to track less than 200GB if less than 10% of free space is available.
So I used the query below, and found out that the first query of 'and' is assigned to the $ value.
`((node_filesystem_size_bytes{job="ec2-node", instance_name!~"^KR.*-EKS.*", fstype=~"ext4|xfs"} - node_filesystem_avail_bytes{job="ec2-node", instance_name!~"^KR.*-EKS.*", fstype=~"ext4|xfs"}) / 1024 / 1024 / 1024 < 200) and ((1-node_filesystem_avail_bytes{job="ec2-node", instance_name!~"^KR.*-EKS.*", fstype=~"ext4|xfs"} / node_filesystem_size_bytes{job="ec2-node", instance_name!~"^KR.*-EKS.*", fstype=~"ext4|xfs"}) * 100 > 90)`

Thanks for the conversation.
Have a great day !
