### ISSUE TITLE
NativeHistogram p95 load too much times

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#11548]
### What did you do?

I scape a demo app with 100 native histogram metrics, all metrics with configuration:

![image](https://user-images.githubusercontent.com/1459834/200552952-1f184b08-bcaa-4cbd-8b65-bbb5eb1c2dd9.png)

I start two Prometheus , one enable native histogram, another not, when caculate all series's p95, I find native histogram load time is  about 2x than normal.  If there are more series, native histogram load time is more than normal histogram.

### What did you expect to see?

The native histogram load time similar like normal histogram.

### What did you see instead? Under which circumstances?

when 100 series, native histogram is about 2x normal histogram cost time, if 1000 series, about 5x time cost.

**Comment by beorn7** [comment]
What's the `factor` you are using?

You cannot directly compare the performance of native and conventional histograms because they have a very different feature flag. For a somewhat fair comparison, you should use a `NativeHistogramBucketFactor` of 2 (if you are using `prometheus.DefBuckets). Even then, the native histograms are doing so much more than the conventional histograms, but with a factor of 1.1 or something, you are comparing a native histogram with a quite high resolution to a conventional histogram with a very very low resolution.

**Comment by songjiayang** [comment]
> 

hi @beorn7 ,  here is my test code, https://github.com/grafanafans/play-with-prometheus-native/blob/main/docker-compose.yml#L37, above test I use `1.2` factor.

**Comment by beorn7** [comment]
I assume your comparison resulted in the expected results. If you continue to experience low performance, please follow up to this issue. Closing for now…
