### ISSUE TITLE
Reuse the postings index when head and ooo head are overlapped

### ISSUE THREAD

**Issue by damnever** [prometheus/prometheus#11628]
### Proposal

Currently, the head index and the ooo head index are the same, when both head and ooo head fall into the same query range, we can reuse the postings index to avoid duplicate computation and reduce memory usage.

**Comment by bboreham** [comment]
Do you have a benchmark that illustrates the problem?

**Comment by damnever** [comment]
I am talking about this in theory, the [PostingsForMatchers](https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/tsdb/querier.go#L228) will be excuted twice if both heads fall into the same query range.

I would like to hear more constructive input before I write any code.

**Comment by bboreham** [comment]
My constructive feedback is to show a benchmark.

**Comment by damnever** [comment]
@bboreham I can't follow you, and with my limited experience, I am hoping you explain the "benchmark" a little bit, is there anything we can talk about before a real benchmark? Ideas, experiences, and numbers in theory could be helpful.

**Comment by damnever** [comment]
@bboreham As you wish, I have submitted #11644 with a **benchmark** to illustrate the problem, I hope that you find it useful.

**Comment by bboreham** [comment]
> abnormal queries that remain active indefinitely

Can you explain how this happens?

**Comment by damnever** [comment]
> > abnormal queries that remain active indefinitely
> 
> Can you explain how this happens?

Some clients may periodically send identical queries, such as recording rules. Assuming the interval is 5 seconds, if the query execution exceeds this duration, the postings cache from the head may remain valid indefinitely, thus causing problems.

**Comment by bboreham** [comment]
Thanks for creating a benchmark. From profiling it seems that most of the work is in merging two sets of series.  And in fact they are actually the same set of series.

This led me to think of another way to solve the problem: create an iterator that walks the series for both head and OOO-head, and merges just the chunks.  This would avoid any cache lifetime issues.

[Returning to this because I noticed a related issue in a production system at work - it spent a lot of time executing regexps, and it did the same work for head and ooo-head.]

**Comment by bboreham** [comment]
Draft PR at #14354
