### ISSUE TITLE
Get rid of the `EncOOOXOR` from the chunk encodings

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11835]
### Proposal

[EncOOOXOR](https://github.com/prometheus/prometheus/blob/f88a0a7d83bb9ef4387ff158d43f5a0c580fffdf/tsdb/chunkenc/chunk.go#L54) was added as part of OOO support to indicate that this chunk, while XOR encoded, belongs to the OOO part of the Head block. This is used only in the ChunkDiskMapper when m-mapping so that when Prometheus restarts we can identify which chunks belong to the OOO Head.

Since this is not a new encoding, we should simplify this and remove EncOOOXOR, and instead do the same bit in ChunkDiskMapper itself to identify OOO chunks. This will also simplify things when we have OOO support for native histograms.

This won't be a breaking change because the same bit will be set to `1` in the ChunkDiskMapper; it is just how we do it is changing.

---

This issue is broken down from https://github.com/prometheus/prometheus/issues/11329

**Comment by mabhi** [comment]
@codesome I would like to work on this. 
Needed few pointers from your side regarding the ask here.  As per my understanding, `EncOOOXOR` const is referred when we query for  a chunk using `IsValidEncoding` or fetching a chunk `Get`  or creating chunks from byte slices `FromData`. Do we  want to remove `EncOOOXOR` completely from the file `chunk.go` and move the functionality inside the  `ChunkDiskMapper` type and the checks should be done only using `OutOfOrderMask`.

**Comment by codesome** [comment]
@mabhi thank you for your interest. Yes we want to remove `EncOOOXOR` completely and handle that bit only from `ChunkDiskMapper` since that is only used for the m-map chunks in ChunkDiskMapper. Think of it like this: The ChunkDiskMapper uses the first bit to know if the chunk is from out-of-order or not, and uses the last 7 bits of the byte to get the chunk encoding, by assuming that the chunk encoding won't cross 7 bits anytime in near/far future. Similarly you will need to extend the methods of ChunkDiskMapper to pass and get this out-of-order information without knowing about how ChunkDiskMapper manages this bit on the disk.

@jesusvazquez was also interested in this and has all the context around it. Maybe you can pair with him on this.

**Comment by jesusvazquez** [comment]
:wave: I'm available at the CNCF slack if you want to reach me out, my handler is `@jesusvazquez `.

My understanding of @codesome comment and from what I've read in the code is that we want to remove that EncOOOXOR and structs such as https://github.com/prometheus/prometheus/blob/6fd89a6fd2af4ed0469e86db7ab503dbd37fc535/tsdb/chunkenc/xor.go#L510-L517

Instead we want to place logic in the chunkdiskmapper to handle reading and writing ooo chunks. For example, when a chunk is read by the chunkdiskmapper the encoding is parsed https://github.com/prometheus/prometheus/blob/3330d85ba8cd6c53e74af23ab96e9e2c134bec39/tsdb/chunks/head_chunks.go#L697-L698 and then its passed down to https://github.com/prometheus/prometheus/blob/3330d85ba8cd6c53e74af23ab96e9e2c134bec39/tsdb/chunks/head_chunks.go#L750

Only because EncOOOXOR exists today, the chunks are recognized as valid. If we remove the encoding then we'd have to change the logic above to swap the OOO bit in the encoding but somehow tell the pool "hey I'm passing you an ooo chunk".
