### ISSUE TITLE
histograms: Support expansion of native histogram values in templating

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11910]
In particular alert templates (i.e. what to do if an alert description contains `{{ $value }}` and the value is a native histogram), but let's not forget console templates.

**Comment by matthiasr** [comment]
Thoughts:

A pure text representation of the values will be difficult to read for a human. We could additionally add functions that render it in different ways – like `$value | histogramASCII` to build a graphical approximation out of ASCII art, `$value | histogramD3` for a context where d3.js is available to do the rendering. If we want to go that far, even one to produce a Base64 encoded PNG for inline `data:` URLs.

We need a safe default behavior, but most of the time the user will know that they expect a histogram as `$value`. Different representations will work in different contexts. Functions to transform the representation let the user choose one that is appropriate in the context.

This may break down when the same text (alert description) is used in different contexts (email, Slack, Pagerduty notification). For these cases it might be helpful if the default text representation is uniquely identifiable, so that a filter in the receiver specific template can walk over the whole text and do something to any histogram it finds.

**Comment by beorn7** [comment]
@marctc plans to work on this.

**Comment by beorn7** [comment]
Now @suntala is giving it a try.

**Comment by suntala** [comment]
Hey @beorn7, 
@britishrum and I would like to be assigned to this one please.

**Comment by beorn7** [comment]
@britishrum apparently GH requires you to actually comment on this issue before I can assign it to you. :thinking:

**Comment by britishrum** [comment]
@beorn7 commenting now, could you try again please?

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/pull/13731 solved this for text expansion (note the palindromic PR number!).

I'm actually not so sure if a fancier representation is worth the effort. Let's first see how often histograms are actually used in templates.

Introducing something like a rendering context would be a whole new concept in template expansion. If somebody things that's useful and want to invest the work, I won't stop them. But I'm going to close this issue now so that we know that we have covered the bases. If somebody has concrete plans to work on the fancier renderings, I suggest to open a new issue for it, maybe focused on the concept of a rendering context and not so much specifically histograms. (Cf. the ongoing discussion about little mini dashboards in alerts, which is still an open topic for the dev-summit. Maybe this can all go along.)
