### ISSUE TITLE
WINDOWS_CPU_TIME_TOTAL to return IIS Worker Process App Pool Name

### ISSUE THREAD

**Issue by louij2** [prometheus/prometheus#11946]
### Proposal
Windows Exporter 
It's very useful because currently, you can only return the PID or W3WP as a label which makes it hard to find out easily what the IIS App Pool is called because these will recycle and a new PID is created. 

Therefore if we had a label for the App Pool name then we can quickly see that it is a problem with a certain website or API.

**Comment by roidelapluie** [comment]
Thanks for your suggestion! We appreciate your input on this matter. However, please note that this issue tracker is specifically for Prometheus. Since you are suggesting an enhancement to the Windows Exporter, we kindly recommend you to open a new issue on their issue tracker.

https://github.com/prometheus-community/windows_exporter
