### ISSUE TITLE
Aggregations like avg, min and max produce incorrect results for native histograms

### ISSUE THREAD

**Issue by fpetkovski** [prometheus/prometheus#11973]
### What did you do?

At the moment, there are many aggregations which produce either incorrect or inconsistent behavior when evaluated against a vector of mixed types (floats + native histograms). For example, the `avg` aggregation is calculated as a `sum / count` of all samples in a vector. The count is incremented once for each sample, but only float samples are added to the sum. 

This is optimized in the engine to use a moving mean instead of a sum, but the principle is the same:
https://github.com/prometheus/prometheus/blob/8a8f594b16847831972dd41c9ae606b6dec5afc4/promql/engine.go#L2466-L2486

### What did you expect to see?

I would expect aggregations that are not supported on native histograms to not take such samples into account.

### What did you see instead? Under which circumstances?

I noticed the issue while working on https://github.com/thanos-community/promql-engine/pull/177. It is fairly easy to reproduce using a test by calculating one of the unsupported aggregations against a mixed type vector: https://github.com/thanos-community/promql-engine/pull/177/files#diff-cbf9ce27965b15f1e13be995f164fd6b33a19381364c4be3e8c047d528994495R3195-R3200

I can help with resolving this edge cases once we have consensus on the expected outcome.

### Prometheus version

```text
0.42.0
```

**Comment by beorn7** [comment]
I think with #11687 this should behave more reasonably. I'll keep an eye on it while finishing up that PR.

**Comment by beorn7** [comment]
@fpetkovski now that #11687 is merged, could you verify that the new behavior matches your expectations?

**Comment by beorn7** [comment]
OK, I guess we count histogram samples for purposes of the averaging, but we should completely ignore them.

However, since we are about to implement multiplication and division for histograms, see #12262, I think we should just handle `avg` fully, i.e. create an "average histogram" for the "histograms only" case and return nothing for mixed cases (corresponding to `sum`, which also supports both histograms and floats – this case will also return a warning once #12152 is in).

**Comment by zenador** [comment]
Added avg to the open PR according to @beorn7 's comment above. This uses the simple avg method, where we just keep adding to the sum and divide it by the group count at the end. We could easily reuse `histogramValue` instead of creating the new `histogramMean` if we keep this, but I'm using the latter for now in case we want to change the method. We could also do a moving mean like we do with floats, which I managed to implement (not in the PR) for cases where the schema is all the same. However it's not in the PR because we can't guarantee that, and we currently cannot do A-B where B has a smaller schema than A.

**Comment by beorn7** [comment]
I'll have a look ASAP (apologies again for the delays - trying to get through my backlog in the limited time I have).

**Comment by jan--f** [comment]
@zenador @beorn7 PR #12262 merged. Seems like this should have addressed the avg computation too?
@fpetkovski any chance you could check if you still see inconsistent behavior?

**Comment by beorn7** [comment]
I have an (ancient) TODO on my list to go through all functions and aggregators and make sure they behave as expected (and add tests using the fancy test framework we have). I have some vague memory that some cases aren't covered yet.

**Comment by NeerajGartia21** [comment]
Is there something here that I can help with? I'd be happy to look into these functions and aggregators.

**Comment by beorn7** [comment]
Yes, now that you have worked on the tests anyway, you might be the perfect person to do this. Let's talk.

**Comment by beorn7** [comment]
OK, after some chatting, @NeerajGartia21 is the assignee now.

**Comment by NeerajGartia21** [comment]
Thanks @beorn7 for assigning it to me.

**Comment by beorn7** [comment]
I think the remaining TODOs here are better tracked in #13934. I'll close this here in lieu of #13934.

**Comment by beorn7** [comment]
I have also added #13934 to the v3 project.
