### ISSUE TITLE
How can thanos sidecar pass prometheus user and password in every api request?

### ISSUE THREAD

**Issue by georges-git** [prometheus/prometheus#11980]
### What did you do?

Implemented the basic auth in prometheus in web.yml. 
How can thanos sidecar pass this prometheus user and password in every api request?

### What did you see instead? Under which circumstances?

Don't know how to configure thanos so it can pass the prometheus basic auth info in every api request.

**Comment by roidelapluie** [comment]
Hello @georges-git, thank you for reaching out. However, this issue seems to be related to configuring Thanos to pass Prometheus basic auth information in API requests. As this is more related to Thanos configuration, I suggest you raise this issue in the Thanos community to get proper guidance.

I am closing this issue for now, feel free to open a new one if you face any issues with Prometheus in the future. Thank you for using Prometheus!
