### ISSUE TITLE
How to change the rule to variable calculation

### ISSUE THREAD

**Issue by JellyZero** [prometheus/prometheus#12027]
### Proposal

Can some names in the rule be replaced with variables? For example, if I want to calculate an indicator 'sum (rate (http_request_duration_seconds_count {job="myservice", code=~"(5. | 429)"} [{{. window}}])', what if I don't want to write the name of the job here?

**Comment by roidelapluie** [comment]
This is very similar to a previous feature request for a "let" or "where" statement in PromQL that would allow for assigning explanatory names to the sub-expressions. That issue can be found here: https://github.com/prometheus/prometheus/issues/6146

Since this seems to be a duplicate, I would suggest commenting your proposal there instead.

Thank you.
