### ISSUE TITLE
[Feature Request] Pagination support for rule listing APIs

### ISSUE THREAD

**Issue by alvinlin123** [prometheus/prometheus#12120]
### Proposal

I have gotten many feedbacks on use cases that needs large amount of rules (20K+), in order to support efficient displaying of rules in UI like Grafana, I think we need some form of pagination for list rule API. Else, similar to the [discussion in the Alertmanager repo]( https://github.com/prometheus/alertmanager/issues/924) it may take a while to load large amount of rules before they can be displayed in browser.

**Comment by alvinlin123** [comment]
My team started to work on this, and would love to hear inputs from the community when we have some initial design in coming weeks.

**Comment by qinxx108** [comment]
### API change

**Comment by codesome** [comment]
Makes sense to me. @qinxx108 and I discussed a couple of ways we could do this during office hours. @qinxx108 can you post some more detail about the token idea for pagination? And how you would move around pages (forward and backwards, can you jump multiple pages?), and what happens when you add new rules and delete rules while you are paginating (it is likely OK to give inconsistent results with addition/deletion of rules until you refresh).

@roidelapluie @juliusv WDYT about adding pagination here?

**Comment by codesome** [comment]
Another idea to think about that does not involve the tokens: We just need to provide the page number and limit per page in the request. And the backend will sort the rules based on some key, and calculate what rules should be on that page. For example, if rules per page was 50, and asked for page number 4, we just give the rules 151 to 200 from the sorted list, and also tells whats the max number of pages possible.
Pros: simple, dynamic (can see updated set of added/deleted rules).
Cons: Let's say you move from page 1 to page 2, it's possible you miss seeing some rules. For example, let's say the page limit was 2. Page 1 had `[r1, r2]`, page 2 was supposed to have `[r3, r4]`. But when you are on page 1, `r2`, gets deleted. So the pagination is changed. Now when you move to page 2, you see `[r4, r5]` (since page 1 becomes `[r1, r3]` after the deletion. You will have to come back to page 1 to see `r3`.

**Comment by roidelapluie** [comment]
I agree with the proposal and understand the need for pagination, especially considering the numerous requests for it in the past. I also appreciate the avoidance of page numbers in favor of tokens, as suggested here. It seems like a more efficient and flexible approach.

Thinking about the UI usecase, I'm interested in seeing how navigating back to the previous page would be implemented in practice.

**Comment by roidelapluie** [comment]
> Another idea to think about that does not involve the tokens: We just need to provide the page number and limit per page in the request. And the backend will sort the rules based on some key, and calculate what rules should be on that page. For example, if rules per page was 50, and asked for page number 4, we just give the rules 151 to 200 from the sorted list, and also tells whats the max number of pages possible. Pros: simple, dynamic (can see updated set of added/deleted rules). Cons: Let's say you move from page 1 to page 2, it's possible you miss seeing some rules. For example, let's say the page limit was 2. Page 1 had `[r1, r2]`, page 2 was supposed to have `[r3, r4]`. But when you are on page 1, `r2`, gets deleted. So the pagination is changed. Now when you move to page 2, you see `[r4, r5]` (since page 1 becomes `[r1, r3]` after the deletion. You will have to come back to page 1 to see `r3`.

I would advise against the page number approach due to the dynamic nature of rules being added and removed. Furthermore, considering the possibility of future paginations for targets, which are even more dynamic, the token-based system appears to be a more suitable solution than page numbers.

**Comment by juliusv** [comment]
If we do pagination at all, maybe an approach in the middle would be a good compromise: do it pagination-based, but track the generation ID of the current rule set (just an auto-incrementing integer every time the rule set changes), return that ID from the API, and show a warning like "Rules have changed since this page was loaded, results may be inconsistent". That is a simple solution that doesn't require a lot of state keeping, while still allowing arbitrary jumping to pages.

Another alternative would be to not implement pagination at all and just say that a single Prometheus server has some limits.

**Comment by gillesdemey** [comment]
Firstly I have some concerns about the scope of the proposal; there are several resource types that aren't taken in to account here. A user of Prometheus might have many groups, many rules in a group (although this is generally not recommended) and a lot of alerts for any given rule.

Secondly I don't believe that adding pagination to the singular `/api/v1/rules` endpoint is the best way forward long-term since adding additional pagination for the other resource types mentioned above to this endpoint would be very complicated.

Lastly I do like the pagination proposal using tokens (I don't believe going directly to a particular page is all that useful), with a `starting_after` and `ending_before` parameter but this implies using identifiers (which we currently don't have in Prometheus).

I'm working on another proposal to add additional API endpoints (to which we can add pagination) and is a topic that is orthogonal to this discussion of "how" to do pagination.

**Comment by jeromeinsf** [comment]
@alvinlin123 correct me if I am wrong, but I believe the intent is to also provide pagination for the other resources as well.
@gillesdemey do you mind linking to your other proposal ?

**Comment by gillesdemey** [comment]
I've posted my proposal here; happy to get your feedback ✌️  https://github.com/prometheus/prometheus/issues/12320

**Comment by gotjosh** [comment]
We discussed this briefly as part of the Dev Summit today, and it seems that @qinxx108 suggested we move way from any sort of pagination and instead resort to setting a limit - as pagination is not enough to solve the problem of e.g. a single alert rule with 60,000 series sending a "big" payload.

The temperature check for https://github.com/prometheus/prometheus/issues/12320 was positive but sadly, we didn't have enough quorum to make a decision. We'll discuss it again in the next dev summit.

**Comment by beorn7** [comment]
Hello from the bug scrub!

We assume this issues has been fixed by #14017. Please follow up if we are mistaken.
