### ISSUE TITLE
Alerts page should display expanded ANNOTATIONS

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#1219]
Even though the expansion happens in Prometheus, it is only _visible_ in Alertmanager. It should be available on `/alerts`.

**Comment by brian-brazil** [comment]
I think this should be available as debug information, but not displayed by default. Displaying all payloads could get very cluttered.

**Comment by matthiasr** [comment]
Agree.

**Comment by SleepyBrett** [comment]
Disagree strongly. When scraping a Kubernetes cluster and alerting out to Slack, the title of the alert is a blob of label values stuffed together. It looks like this:

[FIRING:1] DiskFilling (us-west-2a i-xxxxx m4.large us-west-2 subnet-xxx m4.large /dev/xvda9 us-west-2 us-west-2a / ip-xxxx.us-west-2.compute.internal kubernetes-cluster ip-xxx.net node critical)

This is only useful if I examine it very deeply. However in an annotation I've provided a friendly message:

description="Disk {{ $labels.device }} on host {{ $labels.instance }} ({{ $labels.aws_amazon_com_instance_id }}) is filling up. Disk is {{ $value }} full at the time of alerting."

That is a meaningful alert to wake someone up with a page.

IMO labels, while an important way to do routing are not appropriate for end users *except* as additional information. I want an actionable and meaningful "alert title".

**Comment by fabxc** [comment]
This issue is about the display of alerts in the Prometheus UI and a
different concern than what you describe.

Your annotations are about a single alert. A notification as the one you've
shown for Slack is about N alerts. Thus it often has N different
descriptions.

Especially notification integrations with short messages like Slack oder
PagerDuty are a first point of contact and should be short. Labels are the
most information dense for this  puropose. More elaborate information is
generally one click away.
That said, you can make it more descriptive via Alertmanagers templating if
you like.
