### ISSUE TITLE
can no longer build for linux from macos

### ISSUE THREAD

**Issue by dreweasland** [prometheus/prometheus#12273]
### What did you do?

1. clone the repo down locally
2. `export GOOS=linux && export GOARCH=amd64`
3. `make build`

I've verified the assets build fine, and if I build prometheus from my mac for macos, it works just fine, it's only when attempting to build for linux - which worked fine in the past, but I haven't build prometheus locally since almost 10 major versions ago.

### What did you expect to see?

A working prometheus once I move the newly created binaries to my linux server.

### What did you see instead? Under which circumstances?

Error opening React index.html: open web/ui/static/react/index.html: no such file or directory

**Comment by mahesh-hegde** [comment]
PS: I am not a member, just someone interested in contributing.

I grepped for `Error opening React index.html` because that appears to be human-written error message part. It's in `web/web.go:392:`

https://github.com/prometheus/prometheus/blob/0d049feac760444cbbafadbe8794843a6f47dba4/web/web.go#L392

It appears to be a go filesystem embedding which is generated by `scripts/compress_assets.sh`. But in your case it's trying to open the file path from repository root.

There are 2 files `embed_assets.go` vs `ui.go` in `web/ui` which get switched at build time using `builtinassets` tag. (Both define `Assets`, and one of them has a negated tag).

It maybe worth checking any config changes you made.

Or maybe you can try giving the tags yourself after `make` has compiled all the assets. something like `go build -tags builtinassets`.

https://stackoverflow.com/questions/38950909/c-style-conditional-compilation-in-golang

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Apologies for the delay in looking at this.

We assume this has been resolved. If people cross-compiling are still having problems then please log a new issue.
