### ISSUE TITLE
Notable CPU increase going from 2.41 to 2.44RC 

### ISSUE THREAD

**Issue by Stono** [prometheus/prometheus#12303]
### What did you do?

I'm testing the 2.44RC as I was curious about the memory improvements in https://github.com/prometheus/prometheus/pull/10991#issuecomment-1525560898

**Context**
We have two prometheus instances, a `collector` and a `primary`.  The collector takes raw metrics, and has recording rules, to roll up high cardinality metrics into lower ones.  For example; we'll roll up `istio_request_duration_milliseconds_bucket`, a histogram, into `federate:istio_request_duration_milliseconds_bucket:p95:rate1m`.  

That metric is then federated up to the `primary` instance for querying (via grafana) and longer term storage.

Therefore `collector` is the short-term, high cardinality instance.  `primary` is the long term, low cardinality instance.

We do some recording in `primary` too looking at larger windows (for example; seasonality on `federate:istio_request_duration_milliseconds_bucket:p95:rate1m`).

Following the recent upgrade to both instances, we noticed that CPU on the `collector` went down (yay), but the CPU on the `primary` went up, and became quite a bit more spiky.

You can see the two instances on this graph, one going down, the other going up - following the upgrade:

<img width="821" alt="Screenshot 2023-04-27 at 21 34 47" src="https://user-images.githubusercontent.com/1486729/235149639-c1e02388-325e-420b-abd7-9cf7e0e9f7c6.png">

Here is a 90s CPU sample from the `primary`; you can see the majority of the time is being spent in the recording rules (not surprising):
[pprof.prometheus.samples.cpu.003.pb.gz](https://github.com/prometheus/prometheus/files/11353552/pprof.prometheus.samples.cpu.003.pb.gz)

I intend to roll back to 2.41 to get another CPU profile however i'm currently looking into an increased memory footprint on the same instance (which may or may not be related) with @bboreham, so need to leave it alone for a few days.

The primary difference here is that the problem instance has recording rules looking at up to 4 weeks of historical data, whereas the other is not.

### What did you expect to see?

Not a large increase in CPU

### What did you see instead? Under which circumstances?

Increase in CPU on one instance, not on the other,

### System information

docker

### Prometheus version

```text
2.44.0RC-0
```

### Prometheus configuration file

```yaml
Too large to put in here but happy to send via slack
```

**Comment by bboreham** [comment]
In Slack discussion I think we decided some increased memory you observed was down to a big compaction taking place at that time.

From the profile, the CPU usage as you note is in rules evaluation; I did wonder if Native Histogram changes would be involved there, but don't see much change in the busiest regions.

@codesome @beorn7 any thoughts?

**Comment by Stono** [comment]
OK so I rolled back from `2.44-RC` to `2.43` at 13:31 and you can see the cpu usage has normalised back to where it was on 2.41

<img width="830" alt="Screenshot 2023-05-02 at 13 45 00" src="https://user-images.githubusercontent.com/1486729/235670117-4bfa444c-0213-431d-aa97-69903518b939.png">

I've grabbed another CPU sample:
[pprof.prometheus.samples.cpu.003.pb.gz](https://github.com/prometheus/prometheus/files/11373145/pprof.prometheus.samples.cpu.003.pb.gz)

Hope this helps.

**Comment by bboreham** [comment]
Yes, absolutely, thanks for reporting the change.

It would be best if we could compare two profiles doing ostensibly the same work, one on one version and one on the other.
Maybe that's what you uploaded, but right now it's not clear to me.

**Comment by beorn7** [comment]
Just FYI: I would be very surprised if any native-histogram related changes between 2.43 and 2.44 would increase CPU usage. But who knows, only profiling can show.

I would also make sure to compile both versions with the same Go version, so that we can rule out changes in the Go compiler or runtime.

**Comment by Stono** [comment]
I'm just using the pre-built binaries from the releases page (`linux-amd64.tar.gz`).
We're running in docker; on an alpine base, that is not changing between these releases.
Prometheus gets it's own dedicated VM too.
Relatively confident the only thing changing between these releases here, is the prometheus version.

I've provided two profiles but they're only 90s windows.  
I could run them for an extended period on each version?

**Comment by beorn7** [comment]
@bboreham is the profiling expert. Let's see what he is about to say. :)

Only an FYI about the Go versions used for the pre-built binaries:

```
$ prometheus-2.43.0.linux-amd64/prometheus --version
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
$ prometheus-2.44.0-rc.0.linux-amd64/prometheus --version
prometheus, version 2.44.0-rc.0 (branch: HEAD, revision: d70688038e5d444ab8beac53722df15d244038e4)
  build user:       root@c3e52c6dd464
  build date:       20230426-09:46:54
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by bboreham** [comment]
There are two profiles linked:
https://github.com/prometheus/prometheus/files/11353552/pprof.prometheus.samples.cpu.003.pb.gz
... this is in a message opening "I'm testing the 2.44RC"
https://github.com/prometheus/prometheus/files/11373145/pprof.prometheus.samples.cpu.003.pb.gz
... this after "I rolled back from 2.44-RC to 2.43"

I'll assume the two profiles are associated with those versions.

The profile for 2.44 shows 346 cpu-seconds; 2.43 334 or about 4% less.  
The most marked difference I see is in the `sampleRing` code:

2.44.0-rc0 (slower)
```
Time: Apr 28, 2023 at 11:48am (UTC)
Duration: 90.19s, Total samples = 346.56s (384.26%)
Active filters:
   show=sampleRing
Showing nodes accounting for 61.71s, 17.81% of 346.56s total
Dropped 1 node (cum <= 1.73s)
      flat  flat%   sum%        cum   cum%
    28.62s  8.26%  8.26%     28.62s  8.26%  github.com/prometheus/prometheus/storage.(*sampleRing).addF
    11.76s  3.39% 11.65%     20.25s  5.84%  github.com/prometheus/prometheus/storage.(*sampleRingIterator).Next
    10.75s  3.10% 14.75%     10.75s  3.10%  github.com/prometheus/prometheus/storage.(*sampleRing).reduceDelta
     8.49s  2.45% 17.20%      8.49s  2.45%  github.com/prometheus/prometheus/storage.(*sampleRing).atF (inline)
     2.09s   0.6% 17.81%      2.09s   0.6%  github.com/prometheus/prometheus/storage.(*sampleRingIterator).At
```

2.43.0 (faster)
```
Time: May 2, 2023 at 12:40pm (UTC)
Duration: 90.15s, Total samples = 334.85s (371.45%)
Active filters:
   show=sampleRing
Showing nodes accounting for 49.67s, 14.83% of 334.85s total
      flat  flat%   sum%        cum   cum%
    18.58s  5.55%  5.55%     18.58s  5.55%  github.com/prometheus/prometheus/storage.(*sampleRing).add
    13.42s  4.01%  9.56%     13.42s  4.01%  github.com/prometheus/prometheus/storage.(*sampleRing).at (inline)
     8.31s  2.48% 12.04%      8.31s  2.48%  github.com/prometheus/prometheus/storage.(*sampleRing).reduceDelta
     7.05s  2.11% 14.14%     20.47s  6.11%  github.com/prometheus/prometheus/storage.(*sampleRingIterator).Next
     2.31s  0.69% 14.83%      2.31s  0.69%  github.com/prometheus/prometheus/storage.(*sampleRingIterator).At
```

So I will ping @beorn7 again, as he modified this code recently.

**Comment by Stono** [comment]
> The profile for 2.44 shows 346 cpu-seconds; 2.43 334 or about 4% less.

Yeah so that may be pure chance, we have a lot of recording rules on 30 or 60s intervals; so it could have been timing.  My intention is to perhaps profile for 10 minutes per version to ensure a broader capture.  Will try and do that later today or tomorrow and get back to you.

**Comment by beorn7** [comment]
@Stono are you, by any chance, using native histograms in any way? Adding to the `sampleRing` has been optimized for "pure" cases of only float samples or native histograms in the ring. The (presumably) very rare case of mixed samples is expected to be slower.

However, from looking at the profile, it seems likely you are not using native histograms. Here is a hypothesis:

The `github.com/prometheus/prometheus/storage.(*sampleRing).add` method in 2.43 corresponds to 2.44's `github.com/prometheus/prometheus/storage.addF` function. The code structure is essentially the same, just that the newer function acts on smaller structs (`fSample` rather than `sample`), therefore using less memory and creating less GC pressure.

The new `addF` function is called from `github.com/prometheus/prometheus/storage.(*sampleRing).addF`, so essentially the content of that method is the overhead. Here the code for reference:

```Go
func (r *sampleRing) addF(s fSample) {
	switch {
	case len(r.buf) > 0:
		// Already have interface samples. Add to the interface buf.
		r.buf = addSample(s, r.buf, r)
	case len(r.hBuf)+len(r.fhBuf) > 0:
		// Already have specialized samples that are not fSamples.
		// Need to call the checked add method for conversion.
		r.add(s)
	default:
		r.fBuf = addF(s, r.fBuf, r)
	}
}
```

So the overhead is to check the length of three slices and an additional function call. I assumed this would be really small compared to what `addF` (or the old `add` method) was doing. But in your profile, the overhead seems significant:

```
Active filters:
   show=sampleRing|addF
Showing nodes accounting for 61.71s, 17.81% of 346.56s total
Dropped 1 node (cum <= 1.73s)
      flat  flat%   sum%        cum   cum%
    17.02s  4.91%  4.91%     17.02s  4.91%  github.com/prometheus/prometheus/storage.addF
    11.76s  3.39%  8.30%     20.25s  5.84%  github.com/prometheus/prometheus/storage.(*sampleRingIterator).Next
    11.60s  3.35% 11.65%     28.62s  8.26%  github.com/prometheus/prometheus/storage.(*sampleRing).addF
```

We are in the `addF` function for 17s, while we are in the `addF` method (one level up the stack) almost 9s longer.

For better measurements, it would be good, indeed, to get a longer profile where we can be more certain that the same query load is happening. At the end of the day, we also have to look at the _timing_ of the queries (not just the CPU usage) and the memory usage. We might have traded some CPU cycles in the `addF` method for less memory and fewer CPU cycles during GC. It should be noted that both the query micro benchmarks as well as the prombench end-to-end benchmarks showed overall an improvement from 2.43 to 2.44, but details might depend on the "shape" of the query.

Having said all that, we could optimize the decision tree in the `addF` method (by tracking the type of the previous samples in the `sampleRing` in an explicit variable, and maybe by manually inlining the `addF` function), but I would only like to do that if the impact is relevant in common cases.

**Comment by beorn7** [comment]
See https://github.com/prometheus/prometheus/pull/12326 for an attempt to reduce the overhead (to mostly just the additional function call and a simple comparison). I think the code is arguably much prettier now without a million `len(...) > 0`. So even if it doesn't make a dent, I might prefer it.

**Comment by beorn7** [comment]
@Stono could you check out https://github.com/prometheus/prometheus/releases/tag/v2.44.0-rc.2 ? It might help a bit in your use case.

**Comment by beorn7** [comment]
Thanks for the profiles. I looked at them and couldn't spot a smoking gun. I guess things aren't worrying at the moment, so I'll close this for now, while keeping it in mind if similar reports come in.
Things really seem to depend on usage patterns, e.g. https://twitter.com/0xDC_/status/1658090804936622082?s=20

**Comment by Stono** [comment]
Yip I posted something similar, @beorn7 : https://twitter.com/karlstoney/status/1651557442470150144
However I was premature in posting it; and the changes only really became obvious to me a bit later and once rolled out on all of our instances.
