### ISSUE TITLE
xrate, xincrease revisit

### ISSUE THREAD

**Issue by benitogf** [prometheus/prometheus#12386]
### Proposal

Hello, I saw the last dev submit and heard about the option to try things under a feature flag,
was wondering if it would be possible to revisit this https://github.com/prometheus/prometheus/issues/3746 

it's clear that many people would like to be able to have this without having to switch to a fork or some other variant of prometheus

not sure if this was already adresses somewhere else, couldn't find anything concrete but a bunch of escatered discussions:

https://groups.google.com/g/prometheus-users/c/qmutsg1c55g
https://groups.google.com/g/prometheus-users/c/_aK7im7elUs

hopping that we could keep a constructive discussion about it open here 👏

**Comment by beorn7** [comment]
Hello from the bug scrub!

The whole so-called "xrate issue" is well known and has been discussed countless times. The conclusion so far is that none of the alternatives have been proven to be a clear enough improvement to add them to Prometheus. Anyone is free to propose any alternative via the [proposal process](https://github.com/prometheus/proposals), but it should take into account the past discussions and not just restate what was discussed and did not lead to a convincing conclusion.

(My personal opinion is that we need more meta-data in Prometheus for a satisfying improvement of the rate calculation, so that would be an issue to tackle first.)
