### ISSUE TITLE
Move PromQL to a dedicated package

### ISSUE THREAD

**Issue by els0r** [prometheus/prometheus#12477]
#### Motivation

We recently came across a case, where we only wanted to validate PromQL queries of a CRD in our cluster before handing them off to another tool that would run them.

The `parser.ParseExpr` got the job done, but then it got interesting when we wanted to build the feature. The problem being that all dependencies in https://github.com/prometheus/prometheus/blob/main/go.mod are needed to access functionality of the PromQL language.

#### Proposed Change

Carve out `PromQL` related code into its own package `github.com/prometheus/prometheus/promql`. This would only list the needed dependencies for parsing etc. vs. having to pull i.e. `github.com/Azure/azure-sdk-for-go` just to validate correctness of a PromQL statement.

We'd love to understand if this is feasible, or if not, what speaks against it.

Thank you for considering,
Lennart / Open Systems AG

**Comment by beorn7** [comment]
Hello from the bug scrub!

There were plenty of discussions (and actions) WRT dividing prometheus/prometheus into sub-modules or separate repos. (E.g. there was once a separate TSDB repository, but we reverted this because it proved to be impractical to work with).

There is an [item on the agenda of the dev summit](https://docs.google.com/document/d/1uurQCi5iVufhYHGlBZ8mJMK_freDFKPG0iYBQqJ9fvA/edit?pli=1&tab=t.0#bookmark=id.e2o5thc90g25) that discusses the wider issue. Depending on the outcome, you might see something happening here.

As this issue is just touching a specific aspect of it, we are closing it for now.
