### ISSUE TITLE
Prometheus scrape  not able to recover from tcp write broken pipe 

### ISSUE THREAD

**Issue by nikhil-bhat** [prometheus/prometheus#13094]
### What did you do?

Configured prometheus to scrape kube-state-metrics.
Untill the kube-state-metrics was restarted,  kept on seeing E1101 13:59:01.721845       1 metrics_handler.go:215] "Failed to write metrics" err="failed to write help text: write tcp 10.8.36.224:8080->10.8.0.91:40238: write: broken pipe"

### What did you expect to see?

New connection attempts from prometheus should have been able to scrape prometheus metrics from kube-state-metrics

### What did you see instead? Under which circumstances?

Constant logs indicating  kept on seeing write: broken pipe

### System information

Linux 5.15.90 

### Prometheus version

```text
2.47.2
```

### Logs
![image](https://github.com/prometheus/prometheus/assets/6253611/ac6caf8c-2fe5-4c23-8fae-caffd2361c36)

_No response_

**Comment by afirth** [comment]
better luck at https://github.com/kubernetes/kube-state-metrics perhaps, but I am seeing the same and suspect a scrape timeout. I.e. prometheus has closed the connection to KSM. Query `topk(10, scrape_duration_seconds{}>8) by (service)` will likely show KSM. 

https://github.com/kubernetes/kube-state-metrics/issues/995 and https://github.com/kubernetes/kube-state-metrics/pull/1028 indicate this is could be due to many pods coming up/down rapidly, causing mutex locks (which prevent reading)

**Comment by bboreham** [comment]
This looks to me like it would be caused by the scrape taking longer than the timeout.

> What did you expect to see?
> New connection attempts from prometheus

This is exactly what I see in the evidence you supplied - errors followed by a pause of 10 or 20 seconds, followed by more errors.

You didn't supply your configuration so I cannot confirm this matches your scraping interval.

**Comment by freshaier** [comment]
ts=2024-06-04T09:33:13.833Z caller=compact.go:576 level=info component=tsdb msg="write block" mint=1717480800000 maxt=1717488000000 ulid=01HZH9EW3J5ZX41AFAETGK5Q85 duration=1m7.191065162s ooo=false
ts=2024-06-04T09:33:18.832Z caller=head.go:1345 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=2.986079922s
ts=2024-06-04T09:33:19.119Z caller=checkpoint.go:101 level=info component=tsdb msg="Creating checkpoint" from_segment=476296 to_segment=476358 mint=1717488000000
ts=2024-06-04T09:34:32.804Z caller=head.go:1307 level=info component=tsdb msg="WAL checkpoint complete" first=476296 last=476358 duration=1m13.685868168s
ts=2024-06-04T09:35:16.263Z caller=api.go:1769 level=error component=web msg="error writing response" bytesWritten=0 err="write tcp 10.228.226.183:9092->10.228.226.183:50686: write: broken pipe"
ts=2024-06-04T10:01:06.809Z caller=api.go:1769 level=error component=web msg="error writing response" bytesWritten=0 err="write tcp 10.228.226.183:9092->10.228.226.183:42552: write: broken pipe"
What about this kind of error,prometheus version is V2.52.0-rc1,thank You~ @ bboreham

**Comment by bboreham** [comment]
That's completely different - that is reported from the HTTP API handler, so not related to scraping.

Making a guess, maybe a caller closed their socket before receiving the answer to a query?
I don't think I can tell without more information.  Do you have tracing set up?

We could augment that error message with information about the route being called.

Suggest you open a new issue if you have more details.

**Comment by freshaier** [comment]
好的，您的邮件已收到，谢谢^^
