### ISSUE TITLE
PromQL: add histogram_avg function for Native Histograms

### ISSUE THREAD

**Issue by linasm** [prometheus/prometheus#13281]
### Proposal

**Feature Request**

Add `histogram_avg(v instant-vector)` function for Native Histograms for computing the average of observed values, which would essentially replace the current workaround suggested in the documentation (`histogram_sum(...) / histogram_count(...)`).

**Motivation**

1. _Query Language Completeness / Consistency_

PromQL offers `avg` functions on other dimensions. Not having it for Native Histogram observations feels like a gap there:
| Series    | Time | Histogram observations |
| -------- | ------- |------- |
| `sum`  | `sum_over_time` | `histogram_sum` |
| `count`  | `count_over_time` | `histogram_count` |
| `avg`  | `avg_over_time` | **N/A** |
| `stddev` | `stddev_over_time` | `histogram_stddev` | 
| `stdvar ` | `stdvar_over_time ` | `histogram_stdvar` | 

2. _Performance_

A single function would be more performant than executing two functions and a join.

In case this gets a green light, might be able to find some hands to help with the implementation.

**Comment by linasm** [comment]
@beorn7 any thoughts on this?

**Comment by beorn7** [comment]
Thank you very much. This PR fell through the cracks over the holidays. (Feel free to @-mention me on histogram related PRs. The histogram related code is sprinkled all over the codebase so I cannot be auto-assigned to histogram-related PRs.)

**Comment by beorn7** [comment]
About the actual thing: I'm not sure we want this. The other functions you list are all necessary because there is no other way of getting those results. (And WRT `histogram_sum` and `histogram_count`, there is even the question if we want to make them obsolete by creating new syntax like `my_native_histogram.count`.)

We recently discussed guidelines when to add new PromQL functions at the dev summit, and the bottom line was that we want to avoid functions that are just syntactic sugar, unless they are saving a lot of syntax.

About the performance: We could always optimize the query behind the scenes (difficult with the current implementation of the engine, but it is something we want for other queries anyway), so I would say that performance gain is one of the weaker arguments for introducing a new PromQL function.

I think this needs a wider consensus. I'll put this on the agenda of the dev summit, but I would also like to invite our seniors to comment on it (including but not limited to @juliusv @roidelapluie @bboreham @bwplotka ).

**Comment by linasm** [comment]
Sure, I was expecting some discussion to be required for an introduction of a new function. 

Regarding
> The other functions you list are all necessary because there is no other way of getting those results.

I guess this does not apply to `avg` aggregation and `avg_over_time` function (which could also be expressed in terms of their `sum`/`count` counterparts).

**Comment by beorn7** [comment]
>  I think we should move forward with your PR. I'll review the code at my next convenience.

Sorry for my confusion. I wrote this while believing to comment on a PR, not an issue.

So the proper wording here should be: Yes, let's do it. If you plan to implement it yourself or collaborate with others to do so, please go ahead.

**Comment by linasm** [comment]
Thanks Beorn. @faustuzas kindly please take this over when ready.
