### ISSUE TITLE
postcss version 8.4.24 has security vulnerability CVE-2023-44270

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#13324]
### What did you do?

I do security vulnerability scanning on prometheus and found postcss version 8.4.24 report CVE-2023-44270

### What did you see instead? Under which circumstances?

checkout path：prometheus-2.48.0/web/ui/react-app/package.json/[@prometheus-io/app:0.48.0]/[sanitize-html:2.11.0]/[postcss:8.4.24]
question：PostCSS before version 8.4.31 exist this security vulnerability

**Comment by roidelapluie** [comment]
This vulnerability affects linters using PostCSS to parse external untrusted CSS. This is not the case for Prometheus. We will update the dependency in the main branch but it is not needed to issue a new release for this, because the assets are compiled at build time from trusted sources, not at runtime.
