### ISSUE TITLE
2.49.0: Change to Accept header sends wrong q= value, causing e.g. RabbitMQ native endpoint to throw HTTP 400

### ISSUE THREAD

**Issue by frittentheke** [prometheus/prometheus#13401]
### What did you do?

I upgraded Prometheus from 2.48.1 to the recently released 2.49.0 without any changes to the config.

### What did you expect to see?

I expected all scraping targets to work successfully (as there seem to be no breaking changes in the release notes).

### What did you see instead? Under which circumstances?

Scraping the native Prometheus endpoint of RabbitMQ 3.12 (https://www.rabbitmq.com/prometheus.html#overview-prometheus) ends up in HTTP 400s:

```
HTTP/1.1 400 Bad Request
content-length: 0
date: Mon, 15 Jan 2024 14:46:23 GMT
server: Cowboy
```

I then sniffed the traffic and compared the request Prometheus sent before (2.48.1) and after (2.49.0) and saw the following differences:

```
< User-Agent: Prometheus/2.48.1
< Accept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
---
> User-Agent: Prometheus/2.49.0
> Accept: application/openmetrics-text;version=1.0.0;q=0.5,application/openmetrics-text;version=0.0.1;q=0.4,text/plain;version=0.0.4;q=0.3,*/*;q=2
```

### System information

Linux 6.2.0-39-generic x86_64

### Prometheus version

```text
prometheus, version 2.48.1 (branch: HEAD, revision: 63894216648f0d6be310c9d16fb48293c45c9310)
  build user:       root@71f108ff5632
  build date:       20231208-23:33:22
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels


vs.


prometheus, version 2.49.0 (branch: HEAD, revision: 683a46cc9999dedf66dd0a4c77644b8d0031d063)
  build user:       root@a83669167414
  build date:       20240115-10:51:05
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Logs

```text
prometheus[633395]: ts=2024-01-15T14:21:13.219Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool=rabbitmq target=http://REDACTED:6666/metrics msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
```

**Comment by frittentheke** [comment]
It appears that the q-value of "2" might be the issue here. The HTTP RFC (https://www.rfc-editor.org/rfc/rfc9110.html#quality.values) regarding this value states that the allowed range 

> is normalized to a real number in the range 0 through 1, where 0.001 is the least preferred and 1 is the most preferred

**Comment by ginkel** [comment]
AFAICS there is a fix in `main`, which however, does not seem to be part of the 2.49.0 release, cf. https://github.com/prometheus/prometheus/issues/13369

**Comment by tsuna** [comment]
We hit this too in another unrelated Java/Tomcat app, probably the same Java library under the hood that barks when the `Accept` header isn't perfectly well formatted. It would be nice to call out this issue on the release notes.

**Comment by bwplotka** [comment]
Nice catch, I somehow thought the fix is included in the latest release, but checked wrongly. 2.48.1 on the way....

**Comment by bwplotka** [comment]
2.49.1 release with the [fix](https://github.com/prometheus/prometheus/pull/13313) for this issue is in progress, should be in ~1h

**Comment by bwplotka** [comment]
Fix is now released https://groups.google.com/g/prometheus-announce/c/D6RfOzypmr0 Thanks everyone! 💪🏽

**Comment by hacklschorsch** [comment]
> Thanks for catching so early!

The change made it into Nixos-23.11 and broke our staging system beginning of this week.
We're waiting for the fix to arrive downstream.

Can I say that I think this shouldn't happen in a release?

Can we add a test to make sure Prometheus is sending out valid HTTP requests?

**Comment by bwplotka** [comment]
Ack. Broke meaning somebody ran 2.49.0 from Nixos 23.11 and reported the problem? Or just in theory broken?

Anyway, definitely more tests would be nice, thanks for reminding us! Help wanted (added [issue](https://github.com/prometheus/prometheus/issues/13556))

The other aspect is that not enough systems/users try/upgrade to RC images. This issue was there for ~1  month (albeit during xmas season) since RC.0 ([2023-12-12](https://github.com/prometheus/prometheus/releases/tag/v2.49.0-rc.0)-[2024-01-15](https://github.com/prometheus/prometheus/releases/tag/v2.49.0)) (and even longer on main), yet no one noticed. It would be amazing to either remove RC process or make use of it. 🤗

**Comment by hacklschorsch** [comment]
(Negative-plugging Nix // I just checked and NixOS-23.11 still doesn't have 2.49.1... IDK how the maintainer managed to hit that one hour window, and then missed the new release, but I want to point out that this happens and there's no such thing as "the bug was out there just one hour" and people who install Prometheus from the NixOS stable branch *now*, three weeks after you pushed out the fix, are going to hit this bug.)

> Broke meaning somebody ran 2.49.0 from Nixos 23.11 and reported the problem? Or just in theory broken?

Our staging environment can be broken, that's why we have it;  Most of the distributed system is still running, only the monitoring of one of the main components isn't and is throwing us alerts instead ("Scraping down").
I could fix this by reverting the merge commit, but I think I'll just wait until 2.49.1 finds its way to us instead.
