### ISSUE TITLE
Add  Test Sending Alerts Functionality To Prometheus

### ISSUE THREAD

**Issue by CaoZhechuan** [prometheus/prometheus#13430]
### Summary
After the alarm rules are configured for prometheus, users cannot check whether alarm links are unblocked. In actual production, you need to adjust the alarm threshold to simulate the alarm for testing. Adding this feature makes it easy for prometheus users to test alarm links.

#### Problem Statement:
Currently, prometheus cannot manually send test alarms, users do not have the flexibility to test alarms in production.

#### Proposed Solution:
In the alerts page, you can manually trigger an alarm and have prometheus send an alertmanagers in the alarm configuration.
Expected Outcome: Once implemented, users can manually trigger any alarm.
#### Use Cases:
In the alerts page, click the corresponding sending alarm test button to simulate sending the corresponding alarm information.

#### Flexibility:
Users can select the link for which the alarm is generated.

**Comment by machine424** [comment]
You may want to take a look at https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/

**Comment by beorn7** [comment]
The problem with "manually trigger an alert" is that Prometheus alerts aren't generally restricted to comparing a value to a threshold. Alerts can be arbitrary PromQL expressions, and "firing" is defined by that expression returning a non-empty vector. In many cases, the vector elements that would show up cannot be predicted, so there is no general way of providing a "please fire this alert" button.

Having said that, there is a lack of alert testing that has been discussed for a long time, but that's more about dry-running an alert expression for historical data, ar in other words answering the question "would this newly created alert expression have fired in the past". See #1154 for that.

Maybe that would also help you in your use case. In any case, I recommend to add to the discussion over there. I'll close this issue here to not fragment the discussion too much.
