### ISSUE TITLE
Security: Sub-components version disclosure in prometheus 2.47.2

### ISSUE THREAD

**Issue by VeenaThimmegowda** [prometheus/prometheus#13579]
### What did you do?

Low-level vulnerabilities have been identified in the Invicti tool on Grafana version 10.2.1. The disclosed sub-component versions are as follows.
Jquery (3.7.0)
Momentjs (2.29.4)
Attached report snapshots:
![image](https://github.com/prometheus/prometheus/assets/38758323/4136c708-6215-4106-b61e-d4407411bc99)
![image](https://github.com/prometheus/prometheus/assets/38758323/86a958f3-50af-4ae9-890f-3ef0d49d5c39)

Attached Prometheus devtools snapshots:
![image](https://github.com/prometheus/prometheus/assets/38758323/5209350a-c904-4f25-afbe-1ef485f0ba17)
![image](https://github.com/prometheus/prometheus/assets/38758323/5fd14da4-a1ca-4b84-86c0-036e8707e053)

### What did you expect to see?

Normally we shouldn't get any sub-component version

### What did you see instead? Under which circumstances?

Sub-components versions are disclosed.

### Prometheus version

```text
Prometheus version: 2.47.2
```

**Comment by bboreham** [comment]
Thank you for your interest in the Prometheus project.  For future reference please note the security policy at https://prometheus.io/docs/operating/security/ which asks you to do something other than open a public issue.

If you have details about how these version numbers can be exploited by an attacker who does not already have access to all of your Prometheus data, please follow the process above.  Otherwise I doubt this is interesting.

**Comment by roidelapluie** [comment]
Closing as per Bryan's comment.
