### ISSUE TITLE
New Prometheus UI

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#13601]
### Proposal

As agreed when we decided what was required for the Prometheus 3.0, we want a new UI.

### What does it mean

- Functionalities and pages remain the same 
- We want to rework each them to have a better display and potentially fix some performance issues. That's specially the case for the pages Alert / Rules that we know are frozen when there are too many elements to display even with the current infinite scrolling.
- We also want to add at least two new functionalities coming from PromLens:
   - A concret and smooth metrics finder
   - The nice PromQL debugger
- Specifically for the Alert / Rules page we want to use the PromQL highlighter.
- In order to have a new look and feel, we will use [mantine](https://mantine.dev/). This decision will impact other UIs like AlertManager.

### How we will start

We are going to work on a separate branch. We will remove immediately the previous UI and start on the fresh one from scratch.
We will merge the branch on `main` once every previous functionalities are covered.

**Comment by Maniktherana** [comment]
Hey, I'm looking to contribute to prometheus. Can I help out with this? I'm familiar with react

**Comment by juliusv** [comment]
@Maniktherana Gladly! I'm currently working on an initial sketch of the new Mantine-based UI that is coming along nicely. I'll share it as code in the next week(s), and then we can more easily find specific parts to collaborate on - whether those are specific features, design improvements, or code cleanups. Let me know in case you have any specific interests in mind already!

**Comment by Gaurav-1306** [comment]
hello @juliusv , I wanted to start contributing for the ui, I have experience in react so if possible you could assign me some task or refer me to a task list that I can contribute to for Prometheus3.0

**Comment by kushalShukla-web** [comment]
hey @juliusv  , so is there any figma link for the new UI ?

**Comment by juliusv** [comment]
Sorry for the issue radio silence here - I've just been plowing through things myself over the last half year because that was the easiest for me, but now the new UI is merged via https://github.com/prometheus/prometheus/pull/14872.

It is enabled by default, but you can still switch back to the old UI for now using the `--enable-feature=old-ui` flag.

The new UI lives in the [web/ui/mantine-ui](https://github.com/prometheus/prometheus/tree/main/web/ui/mantine-ui) directory, although that directory name could change in the future to be less focused on the Mantine component framework.

There's still a few missing features in the new UI, and it's not battle-tested yet, so there will be more ongoing development obviously. But I'll close this issue here, as the main work has been done.
