### ISSUE TITLE
Improve display of alerts in /alerts

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1371]
The alerts on /alerts are currently ordered by their order in the rule files. As rule file names are not visible in that table, the order appears to be random. One way would be to sort all alerts alphabetically.

**Comment by juliusv** [comment]
...or alternatively, group them by rule file. This could be better because thematically related alerts that are not necessarily alphabetically adjacent will stay grouped together.

**Comment by brian-brazil** [comment]
By rule group would make the most sense, once we have those.

**Comment by juliusv** [comment]
@brian-brazil Since rule groups cannot span files, it could even be nested. File -> Group.

**Comment by pbhudiaBAE** [comment]
I can have a look into this

**Comment by pbhudiaBAE** [comment]
![alerts](https://user-images.githubusercontent.com/46529282/55617556-e5d84900-5783-11e9-8454-066547134635.png)

I know this feature/issue has been mentioned a few times #3579 

Here's what I've managed to do so far.
The alerts are grouped by their group name. The group name row isn't a chevron but just the name of the group. When I refresh the page however the Group rows shuffle (I haven't changed/added any code on how alerts within groups should be organised since I am unsure of how it works exactly, it might be a change in web.go).

Here's a link to my branch
[https://github.com/BAESystemsAI/prometheus/tree/SortingAlertsv1](https://github.com/BAESystemsAI/prometheus/tree/SortingAlertsv1)

Any suggestions/ help would be really appreciated.

**Comment by juliusv** [comment]
@pbhudiaBAE Looks like a great start! For the group sorting, you see how we use a `byAlertStateAndNameSorter` to sort alerts - we'd need something similar for the groups in web.go.

**Comment by pbhudiaBAE** [comment]
![webln500 go](https://user-images.githubusercontent.com/46529282/55868689-822f9080-5b74-11e9-9a6c-36b856bfc47a.png)
![webgoln900](https://user-images.githubusercontent.com/46529282/55868693-8491ea80-5b74-11e9-8686-a2d345cc1de8.png)

@juliusv Thanks. Having trouble sorting the groups. I tried to implement a similar method as to how alerts are grouped but I get the following error:

web/web.go:501:33: cannot use alerts (type *rules.AlertingGroups) as type []*rules.AlertingGroups in field value
web/web.go:503:9: cannot use groupSorter.Groups (type []*rules.AlertingGroups) as type *rules.AlertingGroups in assignment
web/web.go:947:21: invalid operation: s.Groups[i] < s.Groups[j] (operator < not defined on pointer)

I'm fairly new to Go and pointers aren't my strongest suit. Any suggestions/ help would be great :)

**Comment by juliusv** [comment]
@pbhudiaBAE No problem, could you file a draft pull request (https://github.blog/2019-02-14-introducing-draft-pull-requests/)? That way it'll be easier to comment and all...

**Comment by pbhudiaBAE** [comment]
@juliusv I've made a draft pull request #5448. Ignore the first one, I accidentally made it open and couldn't make it a draft again. The latest commit failed the tests because it doesn't build due to those pointer issues in web.go.

**Comment by pbhudiaBAE** [comment]
Can this issue be closed now since #5448 has been merged

**Comment by simonpasquier** [comment]
Thanks, closing it.
