### ISSUE TITLE
Support Unregistering discovery manager metrics

### ISSUE THREAD

**Issue by dashpole** [prometheus/prometheus#13892]
### Proposal

Collector issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32123

We previously ran into https://github.com/prometheus/prometheus/issues/13507 were able to work around that with a constant label that identifies the collector component so that we can run multiple independent discovery managers in the same process.

However, we are now running into the issue where we can't recreate a component with the same name, but different configuration, which is done by some of the users of the collector.

There is a TODO here: https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L69 tracking this as well, so it seems like it was intended to be implemented, but hasn't been yet.
cc @ptodev 

We would like to be able to stop and restart discovery managers.  The problem right now is that metrics are created in NewManager(), and can't be unregistered: https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L104-L105

There are a few ways this could be implemented:

* Add an UnregisterMetrics function to discovery.Manager.
* Add an option to allow the caller to provide discovery.Metrics.  This allows the caller to manage the registration/unregistration of discovery metrics.

**Comment by ptodev** [comment]
I believe we need to use both of the suggested ways, but for different types of metrics. The SD manager uses two types of metrics:

- [Metrics for the manager itself](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L104-L109). Those are registered inside the `NewManager` function. I think it wouldn't make sense to move the registration of those metrics outside of `NewManager`, because they depend on the manager name. They should be unregistered via one of two ways:
  1. A new external `UnregisterMetrics` function that's part of `discovery.Manager`. 
  2. An new internal  `unregisterMetrics` function which is called when the manager is stopped. This could be part of a new `Stop()` function, similar to the [scrape manager's one](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/scrape/manager.go#L204)? Alternatively, it could be done at the end of the [Run()](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L173), but this is probably not safe.
- [Metrics for the SD mechanisms](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L96). Those are instantiated outside of `NewManager`. Hence, they should be unregistered outside of it. We could add a new function, similar to the one in the [CreateAndRegisterSDMetrics](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/discovery/manager.go#L70C6-L70C32) one.

We may also need to change the scrape manager in a similar way, so that we are able to unregister the metrics created [inside of NewManager](https://github.com/prometheus/prometheus/blob/113938aeb894e60c5706ff9ca993344a990a96e7/scrape/manager.go#L47-L50).

**Comment by ptodev** [comment]
Ok, thank you! I'd forgotten that there is a way to unregister the non-manager metrics already.

**Comment by jesusvazquez** [comment]
> Ok, thank you! I'd forgotten that there is a way to unregister the non-manager metrics already.

I was also not aware of this 👍
