### ISSUE TITLE
Show gomaxprocs on status page

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1468]
It'd be helpful to have access to golang runtime information somewhere.

**Comment by CrazyByDefault** [comment]
What other Go runtime information would be relevant, other than gomaxprocs?

**Comment by grobie** [comment]
GOGC I guess.

**Comment by brian-brazil** [comment]
Prometheus stats like ingestion rate, chunk counts and time series would be useful.

**Comment by serathius** [comment]
I noone is working on it, can i take it?

**Comment by brian-brazil** [comment]
Sure.

**Comment by serathius** [comment]
@brian-brazil What's best way to access stats like chunk and time series counts?
Some of them are available as a metric in `DefaultGatherer`, but to access them we would need to search them by name.
Ingestion rate would need to be calculated, but based on which metric?

**Comment by brian-brazil** [comment]
You'd need to add an API to get them from the TSDB. Ingestion rate will be a bit tricky, as that changes over time.

**Comment by serathius** [comment]
@brian-brazil Is this ok? https://github.com/serathius/prometheus/commit/0873cc83482ac15a99bdf9e83e911715e818134e 
To config reload and wal corruptions described https://github.com/prometheus/prometheus/issues/1481 I would need to add `Status` to `WAL` interface and also pass it from `main.go`

**Comment by brian-brazil** [comment]
It feels dirty to use metrics like that.

**Comment by serathius** [comment]
I agree. Do you know other less hacky method?

**Comment by brian-brazil** [comment]
Maybe track it more directly in the TSDB?

**Comment by serathius** [comment]
Yes we could track metric value in separate variable and always update it when metric is updated. It creates second source of truth, and would be hard to avoid breaking it in future. 
Dirty part can be hidden in function `ToFloat64` implemented like in https://github.com/prometheus/client_golang/issues/58

**Comment by serathius** [comment]
I added other runtime information to status page using `ToFloat64` here https://github.com/serathius/prometheus/commit/a8018eb0070c77989b255ee93cb9055f22ed66e8#diff-3acf7247bfcbc5bf815ae1f421d34342R24

**Comment by brian-brazil** [comment]
@beorn7 What's your opinion on using metrics as shown in the above code example for use elsewhere?

**Comment by beorn7** [comment]
It's tempting to use metrics for that. However, one of the reasons for not providing "Getters" on metric types is to avoid encouraging exactly this usage pattern.

My take so far was the following: If I have a need to track some value for use outside of metrics collection by Prometheus, I track that value completely outside of the Prometheus metrics library code. I then use https://godoc.org/github.com/prometheus/client_golang/prometheus#NewGaugeFunc or https://godoc.org/github.com/prometheus/client_golang/prometheus#NewCounterFunc to funnel that separately tracked value into the Prometheus metrics collection. Let's say (imaginary example!) I need to track the number of chunks because I want to throttle ingestion if it passes a certain threshold. I should not funnel that value through the Prometheus library. This would just be needlessly complex including a roundtrip of converting an int into a float and back. Sure, the Prometheus library conveniently wraps atomic increments and decrements, but that's really one line with the atomic package anyway. _Note that this approach avoids the duplicated sources of truth mentioned in https://github.com/prometheus/prometheus/issues/1468#issuecomment-371069294 as the one source of truth is the separately tracked value, which is merely mirrored into the Prometheus universe at collection time with the GaugeFunc or CounterFunc._

The use case for this issue is perhaps slightly different as you don't need those numbers for some internal use but to display a status page, which – arguably – is a curated and nicer looking human-readable version of `/metrics`. However, if we really want to go down that path of considering all those status information “just metrics”, we should not pollute the interface of the tsdb.DB by adding a `Status` method. We should realize that tsdb.DB already _has_ a way to expose metrics: https://godoc.org/github.com/prometheus/tsdb#Open takes a prometheus.Registerer, and _that's_ how metrics are communicated by the tsdb.DB. That means, we can call the `Gather` method of the registry we have passed in as a `Registerer` whenever we render the status page, and then populate `status.ConfigStatus` from the resulting `[]*dto.MetricFamily` slice. That will be a bit fiddly at this one code location (thanks to the clunky protobuf representation in Go), but at least you would not need to propagate code changes all the way down to the tsdb package.

**Comment by brian-brazil** [comment]
That makes sense. There'll be other non-TSDB metrics we want (and also calculating some rates) so working from the default registry is probably what makes sense here.

**Comment by serathius** [comment]
Using `Gather` was my first idea, but I skipped it because it's more complicated and also relies on reversing logic of construction metric name. So still it will need to have knowledge about name and namespace of metric and rely on it not changing. In the worst case something in chain changes the resulting name, and we have empty status page.
But if it does not pose a problem, we can go with it.

**Comment by brian-brazil** [comment]
There's no namespaces in the proto, it's the same structure and data as what you're working with via WriteTo.

**Comment by beorn7** [comment]
Note that the `Gather` method returns MetricFamilies, while the `Write` writes into a dto.Metric. There is a longer history and (partially flawed) rationale behind this distinction, but in any case, what you get with `Gather` has all the names in it.
