### ISSUE TITLE
UI: Integrating forked library for metricsQL

### ISSUE THREAD

**Issue by EduardZaydler** [prometheus/prometheus#14867]
### Proposal

I hope this issue finds you well.

I wanted to reach out regarding [codemirror metricsQL library](https://github.com/clavinjune/prometheus-codemirror-metricsql), which builds upon your work. While I'm not directly involved with this fork, I've found it incredibly useful.

Codemirror metricsQL library offers new features that greatly enhance original [codemirror promQl](https://www.npmjs.com/package/@prometheus-io/codemirror-promql) capabilities

Request:
Would it be possible to consider integrating these enhancements into the main repository? This would undoubtedly benefit the entire community.

I completely understand if this isn't something you can take on, but if you need any assistance with reviewing, testing, or providing feedback on the forked library, I'd be more than happy to help.

Thank you for your time and consideration.

**Comment by juliusv** [comment]
@EduardZaydler could you explain which kinds of features the fork adds in comparison to the upstream version, beyond incompatible language extensions? We'd generally be happy to talk about improvements, but in Prometheus itself we wouldn't want to add editor support for a language that extends PromQL in an incompatible way.

**Comment by EduardZaydler** [comment]
Certainly, I understand that VictoriaMetrics is not 100% compatible with PromQL, and my point was that all the benefits of merging would come down to the language extension for MetricsQL. Thought it might be a good idea to extend the existing extension since the MetricsQL extension is based on PromQL. But if this isn't what you'd like to focus on, I'll explore other options.

**Comment by juliusv** [comment]
@EduardZaydler I see. Just dropping in a UI library for MetricsQL into the Prometheus server will not give you MetricsQL though - the backend doesn't support it, and neither do other PromQL-compatible tools and parts of the server. In the end, I'd welcome it if VM folks worked directly with the Prometheus project to define new PromQL features instead of building an incompatible fork that splits the user base.

**Comment by EduardZaydler** [comment]
I understand. thought it`s possible to consider integration not for use with the Prometheus server, but rather as a separate tool for VictoriaMetrics as the origin of fork is here. Maybe i should`ve approach the guys from VM first. Thank you for the answers.

**Comment by juliusv** [comment]
> thought it's possible to consider integration not for use with the Prometheus server, but rather as a separate tool for VictoriaMetrics as the origin of fork is here.

It would really only work with VictoriaMetrics, so yeah, this wouldn't make much sense for anyone else. It would only be confusing since it would allow you to write expressions in the frontend that the backend doesn't support.

If you do talk to VM folks and they have general codemirror-promql improvements that are separate from language extensions that are worth contributing back, we'd be totally happy to get such PRs of course.

Closing this for now then.
