### ISSUE TITLE
signal SIGBUS: bus error code=0x2

### ISSUE THREAD

**Issue by icylord** [prometheus/prometheus#15344]
exists bus error in both 2.54.1 and 2.55.0
run on k8s using kube-prometheus-stack helm chart, the data was stored in pvc provisioned by JuiceFS

stack dump:

[prometheus-prom-stack-kube-prometheus-prometheus-0_prometheus (9).log](https://github.com/user-attachments/files/17640638/prometheus-prom-stack-kube-prometheus-prometheus-0_prometheus.9.log)
[prometheus-prom-stack-kube-prometheus-prometheus-0_prometheus (10).log](https://github.com/user-attachments/files/17640639/prometheus-prom-stack-kube-prometheus-prometheus-0_prometheus.10.log)

**Comment by beorn7** [comment]
Smells a bit like JuiceFS and mmap'ing don't play well with each other (although it should work).

**Comment by icylord** [comment]
> Smells a bit like JuiceFS and mmap'ing don't play well with each other (although it should work).

I have two clusters both running Prometheus and JuiceFS, but only the cluster with nodes having a kernel version of Linux 4.19.90-52.32 experiences bus error issues. The other cluster running Linux 5.15.0-60-generic does not have this phenomenon. I guess it might be related to some kernel version? JuiceFS is base on FUSE.

**Comment by dgl** [comment]
This is almost certainly a kernel version issue, very similar to the issues Prometheus sees on OpenBSD due to the page cache not being consistent with file I/O via read/write calls.

Depending what API JuiceFS uses this could be one of:
- https://github.com/torvalds/linux/commit/8bcbbe9c7c8e49281fc2e0a6c5455b87c85a9c2a
- https://github.com/torvalds/linux/commit/ad2ba64dd489805e7ddf5fecf166cae1e09fc5c0

Given you see it working on 5.15, I think all we can recommend is upgrade the other kernel or if you have support for Linux ask your vendor to backport the fixes.
