### ISSUE TITLE
v3 alerts UI laggy almost non-responsive when we have thousands of rules

### ISSUE THREAD

**Issue by alileza** [prometheus/prometheus#15551]
### What did you do?

Alerts page shows just fine, but when start typing on filter search, chrome browser just stop responding, the event not even being receive to the input search.

We have around 413 rule groups

On the video attached below, shown that it takes about 10seconds for the value to show on the input box after I type it. Even after it shown it still hanging

https://github.com/user-attachments/assets/cffd97e7-c5bb-4c00-9183-6fa39db05547

so pretty much on this https://github.com/prometheus/prometheus/blob/main/web/ui/mantine-ui/src/pages/AlertsPage.tsx#L196 key-in, it takes more than 5 seconds until the value being added to the TextInput

### What did you expect to see?

I expect to be able to see and search alert rules, I did try with v2 with exact same configuration, v2 perform fine on showing & searching alerts

### What did you see instead? Under which circumstances?

page is laggy and non responsive.

### System information

 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

### Prometheus version

```text
version	3.0.0
revision	c5d009d57fcccb7247e1191a0b10d74b06295388
branch	HEAD
buildUser	root@aa286d0eb00a
buildDate	20241114-16:40:43
goVersion	go1.23.3
```

### Prometheus configuration file

```yaml
Non relevant to the issue
```

### Alertmanager version

```text
Non relevant to the issue
```

### Alertmanager configuration file

```yaml
Non relevant to the issue
```

**Comment by juliusv** [comment]
@alileza Thanks for the report! Yeah, if that was much faster in v2, we should definitely try to optimize that. To better reproduce your use case, could you also share how many rules you have in total (not only the number of rule groups)?

**Comment by alileza** [comment]
@juliusv we have around 2385 rules at the moment

**Comment by juliusv** [comment]
Thanks! Yes, I've built a large rule file myself, and it's definitely much slower with the new UI. I don't know yet what the main reason is (whether it's just Mantine being more bloated or some structural issue that is easier to fix). I hope to look closer at this soon, but if I can't get it faster on its own, we may need to introduce paging or a similar limiting strategy (only rendering currently visible parts of the page is an option of course, but the downside of that is that it breaks Ctrl-F search).

**Comment by juliusv** [comment]
@alileza So I ended up adding pagination for rule groups and then virtualized scrolling for long lists of rules within a group in https://github.com/prometheus/prometheus/pull/15677, both for the /rules and the /alerts pages. Demo video with 50 groups and 50 rules each (2500 rules):

https://github.com/user-attachments/assets/fc21352b-5c8c-4aad-be00-91bab0e49ab1

Let me know what you think!

Maybe it's also possible to improve things on a more micro level (making individual rule rendering less bloated), but this pagination was probably necessary anyway. Probably will be a good idea for targets at some point as well, instead of the target pool dropdown when you have many pools.

**Comment by l0tzi** [comment]
Hi @juliusv, we are still facing this issue with the latest version (3.2.1). We grouped our alerts a bit different (~200 - 300 alerts / group). Using the groups per page feature helps improving performance, but isn't easy to use - you have to check every page if a search query matches an alert.
As soon as you start to type a string in the search field the website is completly unresponsive, even the following typed characters aren't recognized because javascript is running very long. Maybe a short delay before running javascript waiting for the end of the user input similar like in Prometheus2 would fix this.

**Comment by juliusv** [comment]
@l0tzi yeah this can definitely be improved further. Could you share how many rules you have in total, just so I can replicate something similar locally? Although I have a very fast desktop that can probably handle more than a lot of laptops out there.

**Comment by l0tzi** [comment]
We have around 500 alerts, grouped by 4 (300, 150, 50, 1). Our environment is not very fast to be honest. We work remotely on a virtualized client with lack of computing and graphics performance.
