### ISSUE TITLE
Prometheus 0.18.0 fails to start with short version of Alertmanger URL

### ISSUE THREAD

**Issue by xbglowx** [prometheus/prometheus#1579]
I am trying to upgrade from Prometheus 0.17.0 to 0.18.0 and noticed that Prometheus is failing to start due to:

`2016-04-22_23:43:36.52662 time="2016-04-22T23:43:36Z" level=error msg="invalid Alertmanager URL: http://prometheus-alertmanager.service.q:9093" source="main.go:65"`

I first thought Prometheus couldn't resolve the URL, but after doing some straces, I didn't even see Prometheus trying to resolve the name. Prometheus 0.18.0 currently doesn't like it when there is a single character after the last `.` of the URL. Maybe there is regex in Prometheus which is assuming that all URLs will be FQDN and there are no single character TLDs?

Works:
`http://prometheus-alertmanager.t.te`

Doesn't work:
`http://prometheus-alertmanager.t.t`

**Comment by juliusv** [comment]
0.18.0 introduced https://github.com/prometheus/prometheus/pull/1456, which uses `govalidator.IsURL()` to validate the Alertmanager URL. And this is the regex it uses: https://github.com/asaskevich/govalidator/blob/master/patterns.go#L33

The `{2,}` in the end seems to point to the fact that is requires at least two letters in the TLD, if there is one. Not sure if some standard somewhere says that it *has* to be at least 2 chars (couldn't find it immediately), or if it should be fixed in govalidator. Certainly there is no public 1-letter TLD in existence today.

**Comment by matthiasr** [comment]
But requiring a TLD at all implies that relative domains can't be used. This would make e.g. using it in Kubernetes unnecessarily hard, so I think this should be relaxed a bit.

**Comment by juliusv** [comment]
@matthiasr So it allows having no TLD at all (just `http://f` validates fine), but if the last component is dot-something, it needs to be at least 2 chars long. Of course, you could still have relative URLs where there are more than 2 name components, but the last one should not be the TLD yet.

All for relaxing this.

**Comment by juliusv** [comment]
I filed an issue with govalidator, let's see: https://github.com/asaskevich/govalidator/issues/125

**Comment by juliusv** [comment]
It's fixed upstream.
