### ISSUE TITLE
Error opening memory series storage

### ISSUE THREAD

**Issue by Spritekin** [prometheus/prometheus#1600]
Hi,
I got this message while restarting my prometheus.

time="2016-04-28T03:55:26Z" level=error msg="Error opening memory series storage: resource temporarily unavailable" source="main.go:139"

The data is on a NFS storage at /prometheus/data.

I changed the target directory to /prometheus/data2 and it starts fine. But of course no data available.

I'm running prometheus 0.17 from the official docker image (only with my yaml files added).

I was hoping anyone would shed a light.

**Comment by brian-brazil** [comment]
We do not recommend using NFS for Prometheus.

This is likely a file locking issue, which is notoriously difficult to get working with NFS.

**Comment by Spritekin** [comment]
Alriiight... thank you Brian!

**Comment by beorn7** [comment]
Prometheus keeps a file lock to protect against concurrent use of the same storage directory by two different Prometheus instances. I assume this is what broke here.

**Comment by waqark3389** [comment]
Any workaround to this? I moved my prometheus directory including everything inside it from /opt/prometheus/prometheus-1.0.0.linux-amd64/ to /opt/prometheus/ and am getting the same above error while attempting to start.

**Comment by brian-brazil** [comment]
Are you sure you killed the old prometheus?

**Comment by waqark3389** [comment]
Yeah I did. I think its due to the fact that I am using systemd file. I will double check my systemd service file as I've just read that two instances can cause this.

**Comment by waqark3389** [comment]
Apologies, was a problem with my systemd script. Changed to the following and all works fine.

**Comment by dalgibbard** [comment]
FWIW; we've hit this issue or similar twice now whilst using MapR (NFS) as the backend storage for running Prometheus in Mesos/Marathon. Seems that prometheus locks up if the backend storage has a 'moment'. And then it's a bit hit and miss as to whether the lock remains in the backend or not. Moving the 'DIRTY' file away, and back again seems to be sufficient to get Prometheus running again if the lock is persisted, but the Prometheus process refuses to stop; even when stopping docker the process becomes defunct/zombie...
This is prometheus 1.2.1 at the mo (soon to update) - do you happen to know if newer versions handle backend storage troubles more gracefully? (and specifically which version(s) it was fixed in if so?)

Thanks! :)
