### ISSUE TITLE
Aurora style job names

### ISSUE THREAD

**Issue by jjneely** [prometheus/prometheus#1602]
Would folks consider adding `/` (forward slash) to the JobName regular expression?  This would allow Aurora-style job names to be used as scrape target job names without mangling.

https://github.com/prometheus/prometheus/blob/master/config/config.go#L31

**Comment by brian-brazil** [comment]
In general we can't change our data model to match the permitted characters of every possible system, it's pretty much fixed by now.

There's nothing stopping you using something with a slash as a value for a job label, but you'll need to do it via relabelling.

I would generally recommend sticking to valid label names as job labels, as we might (might) have an easier way to use them in the future that'll only work for job names which follow that constraint.

**Comment by jjneely** [comment]
So...closing.

With your advise, and digging further into my issue of monitoring the same job in QA vs PROD on a shared execution cluster I discovered that relabeling was the right solution here.

I have a Prometheus scrape job setup per Aurora job (ZooKeeper ServerSet) where I'm using relabeling to add qa/prod labels.  Of course this needs unique job names in the Prometheus configuration to parse correctly.  So I made the `job_name` unique.  

This did cause a lot of issues especially with the prometheus jobs I was monitoring.  Relabeling `job` back to the actual job name ("prometheus" in this case) made things work as they should.
