### ISSUE TITLE
Topological sorting of rules

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#17]
Rules need to be evaluated in topological sort order in order to respect data dependencies between them.

**Comment by stapelberg** [comment]
I think as a first step it’d be a good idea to evaluate rules in the order in which they were defined in the config file.

**Comment by fabxc** [comment]
Currently we are reading the files and their rules in order. On each evaluation iteration, we evaluate concurrently, though, because naive sequential evaluation can take longer than the evaluation interval. In that case iterations are missed.

Side not: if the a single query in the concurrent evaluation takes longer, a whole iteration will be missed for all rules. We should not be waiting for all rules in an iteration to finish and only skip iterations for the slow queries.

**Comment by brian-brazil** [comment]
> I think as a first step it’d be a good idea to evaluate rules in the order in which they were defined in the config file.

I've proposed that previously, some users are already at a point where that don't work for the reason @fabxc explains.

The last time we talked about this the plan was to add syntax to let you define a groups of rules, which would be run in order. Different groups could run at the same time then. This could also be used to enable things like allowing rules to access remote storage (which you wouldn't want enabled by default).

**Comment by fabxc** [comment]
Mh, it seems like we can solve this internally. Not sure whether taking the issue to the user is the best approach here.

Building a dependency graph will also be more optimal than one hierarchy of logical grouping by the user.

**Comment by brian-brazil** [comment]
> Building a dependency graph will also be more optimal than one level of logical grouping by the user.

This is only one aspect to the problem. What we also need to do is spread out the load of the rule evaluations, allow for cases when there's loops or things we can't determine about a dependency graph.

I'm think ordered groups of rules with some micro-optimisation where it's safe is the route to take.

**Comment by fabxc** [comment]
I would think that cyclic dependencies error when reading the rules. Or are
there reasonable cases where it should be allowed?
With that, evaluating one chain of rules without blocking independent ones
is not an issue.

**Comment by brian-brazil** [comment]
> I would think that cyclic dependencies error when reading the rules. Or are
there reasonable cases where it should be allowed?

There are advanced use cases where it comes up. It's also possible that there's rules that aren't actually cyclic, but where it's not possible for us to determine that due to e.g. use of regexes. You also wouldn't want to couple rule evaluation between jobs, as that could lead to a problem in one job taking out evaluation in another.

**Comment by fabxc** [comment]
Can you elaborate on the "use of regexes" part. I know that there were plans to have `relabel()` in the QL at some point - are you referring to that?

**Comment by juliusv** [comment]
@fabxc For example, if someone uses a regex matcher on the metric name in the rule expression, you can't analyze anymore whether the resulting metric name(s) would need some rule to be executed first. Same for other labels (you could have parts of one metric being selected in one rule, and other parts in another rule).

**Comment by fabxc** [comment]
Ah, those regexes – of course, thanks!

**Comment by juliusv** [comment]
Superseded by https://github.com/prometheus/prometheus/issues/1095.
