### ISSUE TITLE
Rename series API

### ISSUE THREAD

**Issue by qed-** [prometheus/prometheus#1870]
It would be very useful to have a way to rename series via the HTTP API.
Ideally this would also allow retrospectively adding a label to a series, and merging with any existing series that has the same name/labels.

**Comment by brian-brazil** [comment]
I don't think this is something we'd offer directly, rather it'd be built as a tool on top of deleting and #535 backfill.

**Comment by qed-** [comment]
Isn't that approach a bit heavy handed? 
I'd have thought it would be reasonably simple to modify the metadata describing a series (and update any indexes etc.) rather than copy the entire series.

**Comment by fabxc** [comment]
Realistically, doing this in flight seems to be a very rare use case and
comes with a lot of complications. Updating an index is not always trivial.
With the current one it would actually work. With a more sophisticated one,
one would probably prefer to modify the past at all cost due to complexity.

It also means a) that you are still getting new samples for the old series
name and hence it gets recreated immediately or b) that the series is
already renamed in the scrape targets and now you have to shuffle around on
disk a lot to actually get new samples aligned with the old, now renamed,
sample stream.

At the cost/benefit scale this feature just performs really badly,
unfortunately.

**Comment by fabxc** [comment]
Closing this due to the reasons above. We might be able to reconsider at some point but currently it doesn't seem feasible.
