### ISSUE TITLE
ui: Improve autocompletion

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1924]
We had iterated quite a bit on autocompletion in the expression browser, see #907 and #1181 . However, we reverted them all in #1303 because of the problems reported in #1185 . We never came back to it, but we should. Problem so far was that nobody felt really qualified about those UI intricacies.

@davkal (who asked for this issue).

**Comment by applegrain** [comment]
Is this related to #3187, improving the matching algorithm for the expression browser?

**Comment by davkal** [comment]
At the minimum, I believe this issue was to make the suggester work mid-query, not just at the beginning, e.g., for queries like `go_gc_duration_seconds + go`, where you dont get suggestions for the second `go` prefix.  #3187 is more about the weighting (or lack thereof) in the fuzzy matching algorithm.

**Comment by juliusv** [comment]
Closing in favor of https://github.com/prometheus/prometheus/issues/6160
