### ISSUE TITLE
Alert clients repeatedly post the alerts of ended. 

### ISSUE THREAD

**Issue by barnettZQG** [prometheus/prometheus#1945]
I implement a alertmanager and  listens for alerts on an API endpoint at /api/v1/alerts.
![image](https://cloud.githubusercontent.com/assets/18493394/18246544/cc2ef3c6-739e-11e6-96f1-e357a5346e5b.png)
but,I found that Prometheus would repeat send already the end of the alert information, as shown in figure can see.
Why is this?

**Comment by fabxc** [comment]
We want to notify the Alertmanager about resolved alerts. For reliability
we do not rely on an alerts successfully being sent once to mean that they
were actually processed. After all Alertmanager could have been restarted
right after. Thus, we re-send alerts as long as they are firing.
The same is true for resolved alerts. There we keep resending them for 15
more minutes before actually removing them from the internal state. After
15 minutes you should no longer see them.

**Comment by barnettZQG** [comment]
Understand.So I should according to the startsAt and endsAt time to determine whether the same alert again already exists.

**Comment by fabxc** [comment]
Yes, generally the semantics are very much geared towards Alertmanager, which has a merging and deduplication procedure for incoming alerts.
If you want to consume them as an end user, you should do so via Alertmanager's notification rather than writing your own layer. If you want to run your own thing, you'll have to deal with duplication.

Closing the issue as it's expected behavior but we can discuss further here if you have any questions.

**Comment by barnettZQG** [comment]
yes,thank you

**Comment by rajendrakumara** [comment]
Hi,

"After 15 minutes you should no longer see them".

Is 15 minutes configurable, in the above context.

Thanks,
Rajendra Kumar. A

**Comment by juliusv** [comment]
No, this is currently hardcoded:
https://github.com/prometheus/prometheus/blob/master/rules/alerting.go#L145-L147
