### ISSUE TITLE
query returning empty metric if functions are used

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1986]
I just notice if I use functions in an expression the response contains an empty metric, all labels are just lost. Is it by design? 

My application relies on labels a lot, missing labels breaks the business logic.

Specific to my problem the function I use is avg()

**Comment by grobie** [comment]
I assume you mean in general aggregators and not functions here: https://prometheus.io/docs/querying/operators/#aggregation-operators. Aggregation operators by design combine multiple time series and produce new ones. If you don't specify a `by()` or `without()` clause they will collapse all time series into one. To avoid that, be more specific on which labels you want to make the aggregation happen.

Example: `avg without(instance)(your_metric)` will keep all labels except the `instance` label.

**Comment by zxwing** [comment]
@grobie thanks, it starts working now; however, the __name__ metric is still missing, is there any way to keep it? I don't need to operate on multi-series.

**Comment by brian-brazil** [comment]
The name is only kept if it's still the same metric, for example `x * 2` is no longer `x` so the name is removed.

**Comment by zxwing** [comment]
got you. Thank you!
