### ISSUE TITLE
metrics labels can Support Chinese?

### ISSUE THREAD

**Issue by najun79** [prometheus/prometheus#1988]
takeout_requests_total{instance="",job="takeout_requests_total",mealscount="0",mealsname="��������",userid="user",username="������"} 3
takeout_requests_total{instance="",job="takeout_requests_total",mealscount="0",mealsname="�ϱ���ը����",userid="user",username="������"} 3
takeout_requests_total{instance="",job="takeout_requests_total",mealscount="1",mealsname="��������",userid="user",username="������"} 3
takeout_requests_total{instance="",job="takeout_requests_total",mealscount="1",mealsname="�ϱ���ը����",userid="user",username="������"} 6

labels mealsname is Chinese（utf8），takeout_requests_total can be send to pushgateway and Correctly received，but prom/Prometheus can not pull it.metrics labels can Support Chinese?

**Comment by songjiayang** [comment]
check your db charset ?

**Comment by najun79** [comment]
utf-8

**Comment by beorn7** [comment]
Label values fully support UTF-8. If you run into any issues, a detailed error report would be very helpful.

**Comment by aecolley** [comment]
Github comments seem to support 正體字 / 简化字, but the text in the `mealsname` of the original post appears to be [gibberish](https://en.wikipedia.org/wiki/Mojibake) (mostly Unicode "replacement characters", with the occasional Greek or Armenian letter). This makes me doubt that the text is really UTF-8. It's quite possible that the data are being passed over the net in the wrong charset, of course. Can you get intelligible responses from the pushgateway's own `/metrics`?

There's always the possibility that the characters being replaced by `�` are outside the Unicode BMP, requiring 4-byte UTF-8 encodings. That's probably not a well-tested case. But, of course, it should be.

I notice that a bare request to Prometheus's own `/metrics` produces a response with the header `Content-Type: text/plain;version=0.0.4` without a `charset` parameter; a correct HTTP/1.1 client will [default to ISO-8859-1](https://tools.ietf.org/html/rfc2616#section-3.7.1). I can't immediately tell whether the bytes are ISO-8859-1 or UTF-8, because apparently `"prométheus" is not a valid job name`. So, this is worth further investigation IMHO.

**Comment by beorn7** [comment]
> I notice that a bare request to Prometheus's own /metrics produces a response with the header Content-Type: text/plain;version=0.0.4 without a charset parameter; a correct HTTP/1.1 client will default to ISO-8859-1. I can't immediately tell whether the bytes are ISO-8859-1 or UTF-8, because apparently "prométheus" is not a valid job name. So, this is worth further investigation IMHO.

That's a good point. If the text format is used, we should definitely specify the charset in the content type. I filed https://github.com/prometheus/docs/issues/557 about it.

However, in this particular case, I don't think it explains the issue. First, a charset header is not required by the protobuf format. If the UTF-8 string makes it onto the Pushgateway, it will be scraped correctly by the Prometheus server (as it uses the protobuf format). Second, if I'm not missing anything, the Prometheus server will always interpret the payload of an HTTP request as UTF-8, no matter what might or might not be in the header.

Perhaps the problem happens in the last step, namely delivering the query result via the HTTP API?

**Comment by brian-brazil** [comment]
@najun79  can you confirm if the issue is only in the HTTP API?

**Comment by brian-brazil** [comment]
No response, presuming this issue isn't with Prometheus.

**Comment by Youngcoder** [comment]
if label value is chinese, prometheus give an error message: invalid label value "\xd5\xd7\xcd\xf8\xc2\"

**Comment by brian-brazil** [comment]
This is not valid utf-8: https://play.golang.org/p/NAcJaCo7Pu
