### ISSUE TITLE
Consider supporting TLS renegotiation

### ISSUE THREAD

**Issue by vipetrul** [prometheus/prometheus#1998]
It appears that when HTTPS endpoint has TLS renegotiation enabled, then Prometheus receives "local error: no renegotiation" error upon scraping.

It is OK if HTTPS endpoint is using TLS 1 protocol, as long as TLS renegotiation is disabled on the server.

Golang version. 1.6

No action is needed on this ticket, just wanted to report observed behavior.
Unfortunately underlying issue with TLS renegotiation was fixed, hence I cannot provide you with a link to a live example.

**Comment by jimmidyson** [comment]
Looks like it should be in go 1.7 - golang/go#5742

**Comment by grobie** [comment]
Weve had a long discussion about this last night, I suggested the same and tried scraping the problematic URL with a go1.7 compiled prometheus server and got the same reponse `local error: no renegotiation`.

**Comment by roidelapluie** [comment]
I have started the implementation: https://github.com/prometheus/common/pull/221

However I think there is not enough activity on this issue to implement it, so I closed it. I noticed during implementing it that TLS 1.3 does not have renegotiation at all.
In addition to that, there is no +1 or reaction since 2016.

Therefore, I would like this issue to be closed.

**Comment by brian-brazil** [comment]
Yeah, this is a bad idea security wise and pretty niche. You can always use a proxy if you've odd target that requires this.
