### ISSUE TITLE
Support http/2

### ISSUE THREAD

**Issue by ZeeShen** [prometheus/prometheus#2124]
Do you have any plan to support scrape metrics via http/2? 
For grpc servers, it will be convenient to expose a metrics interface in http/2.

**Comment by hwinkel** [comment]
so unify CNCF APIs towards HTTP/2 ?

**Comment by juliusv** [comment]
Does Prometheus not support HTTP/2 already? It was my understanding that starting with Go 1.6, the standard library HTTP server transparently did HTTP/2 when needed. Local tests seem to confirm this against the https://http2.golang.org/ test server.

**Comment by fabxc** [comment]
That's matches my latest state of knowledge.
Did you try it out and found it not working?

On Sat, Nov 5, 2016 at 2:46 PM Julius Volz <notifications@github.com> wrote:

Does Prometheus not support HTTP/2 already? It was my understanding that
starting with Go 1.6, the standard library HTTP server transparently did
HTTP/2 when needed. Local tests seem to confirm this against the
https://http2.golang.org/ test server.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/prometheus/issues/2124#issuecomment-258642807>,
or mute the thread

**Comment by ZeeShen** [comment]
Maybe I should change issue to `best practice to export metrics from grpc server?`. The problems I've had:
1. Grpc server doesn't support `Get`, but scrape request is via [`get`](https://github.com/prometheus/prometheus/blob/master/retrieval/scrape.go#L315)
2. How to define metrics rpc in protocol? Return something like `message MetricsResponse  {repeated MetricFamily metrics = 1;}` ?

Anyway, thank you for your reply. As http/2 is already supported, I'll close this issue.
