### ISSUE TITLE
How to calculate disk resource will consume

### ISSUE THREAD

**Issue by wangweihong** [prometheus/prometheus#2146]
For example , I  scrape a target every 5 second and store data in a 40GB disk. I want to calculate how long will it spend to consume all my disk resource. What should I do?

**Comment by beorn7** [comment]
That also depends on the amount of samples you have per scrape. And on the compressibility of your sample data. Typical production data takes 3 to 4 bytes per sample on disk, plus some baseline space for the indices. You could also configure varbit encoding, see https://prometheus.io/blog/2016/05/08/when-to-use-varbit-chunks/ , which might compress down to 1.3 bytes/sample (at the price of query performance).

**Comment by wangweihong** [comment]
@beorn7  Thanks for your reply. I'm new to prometheus and don't know where to get the amount of samples. I set up prometheus to monitor itself and try to find some infos of sample ,  but I don't know what its metrics mean. Can you please tell me where to get the amount of samples and the docs about promethus's metrics?

**Comment by beorn7** [comment]
If you go to the `/metrics` endpoint of a prometheus server, you see all the metrics with doc strings.
The metric you are looking for is `prometheus_local_storage_ingested_samples_total`.

**Comment by elluvium** [comment]
I'm using `openshift/prometheus:v2.2.1` image with local target and there is no such metric `prometheus_local_storage_ingested_samples_total`. What I'm doing wrong?

**Comment by beorn7** [comment]
You are using Prometheus 2.x, which is _very_ different from Prometheus 1.x. Remember, this ticket was closed 2 years ago. I guess now you would use `prometheus_tsdb_head_samples_appended_total`. 

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. (A _closed_ GitHub issue is even less suited.) On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by elluvium** [comment]
Ok, got it. Much appreciated for your answer even on closed ticket.
