### ISSUE TITLE
prometheus server crash with OOM

### ISSUE THREAD

**Issue by jinhang** [prometheus/prometheus#2300]
time="2016-12-21T16:01:47+08:00" level=info msg="Done checkpointing in-memory metrics and chunks in 8.6828682s." source="persistence.go:573"
runtime: out of memory: cannot allocate 720896-byte block (1342177280 in use)
fatal error: out of memory

time="2016-12-21T16:16:15+08:00" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=433329 maxChunksToPersist=536870912 maxToleratedMemChunks=-1181116006 memoryChunks=467574 source="storage.go:895"
panic: runtime error: makeslice: len out of range

goroutine 163 [running]:
panic(0xbf1ea0, 0x46935148)
/usr/local/go/src/runtime/panic.go:500 +0x331
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).maybeEvict(0x1379a240)
/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1057 +0x62
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).handleEvictList(0x1379a240)
/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1022 +0x168
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
/go/src/github.com/prometheus/prometheus/storage/local/storage.go:367 +0x348

**Comment by jinhang** [comment]
windows : 16RAM mem
start prometheus with default parameters

**Comment by juliusv** [comment]
Is this the same as https://github.com/prometheus/prometheus/issues/2299? Why did you close that one without a comment and opened a new one? Please be considerate in how you report and deal with issues.

Again, as stated in #2299, your problem is that you are setting the `-storage.local.memory-chunks` flag value way too high (then Prometheus thinks it should keep way too many chunks in memory, but your machine does not have infinite memory). Try setting it to a couple of hundred thousands or maybe a few millions at most, with your 16GB of memory.

**Comment by juliusv** [comment]
Ehm, I meant https://github.com/prometheus/prometheus/issues/2293 which was closed by you. The other one was closed by someone else. Still, not helpful to have three issues about the same thing.
