### ISSUE TITLE
Expression browser metric autocomplete misses certain search terms

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2380]
Metric name fragments that are not a metric prefix (but contained somewhere in a metric name) *and* contain an underscore are not shown by the fuzzy-matching autocompleter in the expression browser.

For example, enter `disk` on http://demo.robustperception.io:9090/ to see that there are metrics `node_disk_bytes_read`, etc. Then enter `disk_` to see that all those suggestions disappear.

This is likely related to https://github.com/prometheus/prometheus/commit/50f8e35c54b7c4035f3267e9b106f4523d4a18bf. /cc @lightpriest

**Comment by lightpriest** [comment]
Yes, it's probably because of this change. The fuzzy matching breaks words by space. To perform the lookup, I remove the underscore from the metric name before looking up, and add it back after.

I wonder what will be the solution here. What would you expect the behavior to be? It might be treated as a space, or it might be treated as an underscore.

If treated as a space, then typing an underscore is meaningless, but the user was actually trying to do something - reduce the suggested options?
If treated as an underscore, maybe the code should fallback to the regular string matching? This will reduce the suggestion list, but in some cases might generate a different set of results.

**Comment by juliusv** [comment]
@lightpriest Hmm, not sure yet! Do you know why it does work if the search term is a metric prefix (like `node_boot` -> `node_boot_time`), but not if it's in the middle somewhere (`boot_time`)?

**Comment by lightpriest** [comment]
@juliusv #2396 includes a fix for this issue. It also includes a change the library itself to provide better results.

I tried replacing the fuzzy search lib with atom's one (https://github.com/atom/fuzzaldrin), but it's targeted at path subjects, giving higher scores to the last path element, treats slash specially, etc.
