### ISSUE TITLE
Scraping HTTP keep-alive

### ISSUE THREAD

**Issue by iobestar** [prometheus/prometheus#2498]
Why is scraping use 'Connection: close' header? 
Would it be ok to add config flag for this option (default: keep-alive disabled)?

**Comment by fabxc** [comment]
Actually I changed that for the dev-2.0 branch. I'd like to try making it a default there and only allow disabling once a use case appears. The number of required file descriptors will go up, but is still bounded.
Especially when scraping with TLS this saves unnecessary round trips.

**Comment by beorn7** [comment]
An easy solution could be to make it depend on the scrape interval. With a 1m scrape interval, keep-alive is pretty wasteful. With a 1s scrape interval, the opposite is true.

**Comment by fabxc** [comment]
I don't think that's generally applicable. First of all – what is wasteful in that context? Open FDs are not exactly expensive. Certainly not in the cardinality we are thinking of. So I'm not sure it's worth distinguishing to begin with, given that it additionally will catch people off guard if they reduce their scrape interval and suddenly have to adjust their ulimit.

In general, it's a question of of connects/second. And 10 targets at 1s have fewer of those than 10k targets at 1m scrape interval. On top, the total impact of a connect is amortized over number of series per scrape, which is also not known.
So several variables playing into it and from my benchmarks  keep-alive in general has notable positive impact on the CPU load added by the ingestion path.

**Comment by brian-brazil** [comment]
I thought we had keep-alive already, it must have regressed at some point.

**Comment by iobestar** [comment]
I don't see how scrape timeout affects keep-alive? 
The problem is connection closing initiated by ```DisableKeepAlives: true```. Adding a option for enabling/disabling keep-alive is a reasonable solution. 
Default value can be ```true``` but from version 2.x.x (in my opinion) because this is breaking change.
Adding this option with default value ```false``` in 1.5.x version should not be a problem :)

**Comment by beorn7** [comment]
One of the selling points of Prometheus and its pull model is that you can easily cope with very large amount of targets if you only scrape at a sufficiently low frequency.

The wasteful part is if the keep-alive timeout is slightly smaller than the scrape interval. Default idle timeout in Go is 30s, for example. Default scrape interval in Prometheus is 1m. With this combination of timings, every TCP connection is kept open for 30s for no benefit at all.

If you want to avoid the effect of surprising increases in open fd's after reducing the scrape interval, you also have to manage the idle timeout on connections to be larger than the scrape interval.

On the other hand, if you have to think about tweaking the ulimit, it proves we _are_ talking about cardinalities that matter. Assuming the 30s default idle timeout are tailored to be a good trade-off between cost of an open connection and re-establishing one, we can simply activate keep-alive for scrape intervals of up to 30s and switch it off otherwise.

**Comment by iobestar** [comment]
I agree with @beorn7 . If we can configure scrape interval then it would be reasonable to configure other HTTP client parameters (connection idle timeout, keep-alive, connection timeout) aswell. 

Default configuration can be as you propose: keep-alive enabled implicitly if scrape interval is under 30s. For TLS targets keep-alive should be enabled by default unrelated to scrape interval?

**Comment by fabxc** [comment]
So increase the keep alive timeout? The default value isn't relevant to the discussion and the described problem doesn't exist basically.

> you also have to manage the idle timeout on connections to be larger than the scrape interval.

Why? just make it 2x the scrape interval and all there is to it. There's no reason to set any other value.

I did some manual benchmarking and found connecting to be a significant CPU impact. And that holds true by the formula I mentioned regardless of your scrape interval.

> Assuming the 30s default idle timeout are tailored to be a good trade-off between cost of an open connection and re-establishing one, we can simply activate keep-alive for scrape intervals of up to 30s and switch it off otherwise.

Trade off between what? It's a value tuned to the average connection which may or may not be reused. In Prometheus we know almost any connection we start will be reused hundreds of times – it's just a different use case and the default has no place here.

What's the benefit of switching it off for intervals larger than 30s? What changes when setting it to 31s?

The only feasible option here is making it a boolean flag and let the user decide – globally for everything. Either you want it or don't. There is no magic boundary within our typical interval of 1s to 2m where it becomes feasible or unfeasible because the interval is not a sufficient parameter for the function estimating the cost/benefit.

**Comment by agaoglu** [comment]
It might be a better option to make it overridable per job/target definition. You know, some servers don't like keeping connections open and too shy to simply close on their end.

**Comment by iobestar** [comment]
Keep-alive is useless if scrape interval is greater than connection idle timeout. 

I agree with @agaoglu to make keep-alive overridable per job/target but if keep-alive is enabled then connection idle timeout must be set to (at least) scrape interval value.

**Comment by darkk** [comment]
> I don't think it's trivially true that 2x scrape interval as keep-alive timeout is a sane default

I think that the only sane default is "the default major browsers use" exactly because of proxies, NATs and others.

**Comment by AlekSi** [comment]
Are you interested in adding options to enable keep-alive connections (with default value `false`) to 1.8? I can work on it.

**Comment by brian-brazil** [comment]
That change was already inadvertently made for 1.8, it's being reverted in #3173

**Comment by AlekSi** [comment]
Isn't it about remote storage as opposed to scraping targets?

**Comment by brian-brazil** [comment]
The scope of the PR was much broader than the title indicated, thus the revert as this question remains unsettled.

**Comment by bboreham** [comment]
I believe the code in 2.0 has keep-alive on for all connections.

However see also #3510

**Comment by AlekSi** [comment]
Was it fixed in 2.0? Can this issue be closed?

**Comment by brian-brazil** [comment]
Yes, it's changed in 2.0.
