### ISSUE TITLE
Allow configuration push via HTTP endpoint?

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/prometheus#2513]
In certain modes of execution it would be convenient if Prometheus would expose a way to directly push configuration file updates via an HTTP endpoint rather then having to orchestrate filesystem / signal issuance access.

My specific use case is when Prometheus is being executed by Marathon under Mesos - although the configuration is persistent, arranging access to underlying filesystem and enabling users to issue signals to trigger a configuration reload is not trivial.

This problem could be solved by wrapping the Prometheus container in some custom proxying to provide such functionality, or with a configuration management engine of some sort, but both of these would be effectively doing the same thing - additionally, Prometheus is in a position to parse and validate it's config file and push an error back to the client at the point of upload.

Does this idea seem aligned with how Prometheus is used?

**Comment by Gouthamve** [comment]
We do have `POST /-/reload` to reload the config but I understand the problem here. So how I did it is put the file somewhere (S3) and run a script to update the config (manually, but I think Ansible can automate).

One issue with using HTTP to issue config is that there is no source of truth, it makes it easier but it also might cause debugging issues later. And I donot see any other monitoring/database system that offers config management via HTTP.

**Comment by wrouesnel** [comment]
Technically there's no source of truth with Ansible either - i.e. anyone with access can push any configuration they want - which is of course fine, if you're in the middle of "nothing's working and I need it to do this". But it does seem like a workaround for something Prometheus would more sensibly manage itself - i.e. I'd rather gate the configuration push endpoint with my http proxy then try and open up a totally separate path to the server.

**Comment by brian-brazil** [comment]
We've explicitly decided not to do this. You're free to build something on top of Prometheus to provide this.
