### ISSUE TITLE
Target order in Web UI not stable

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/prometheus#2536]
**What did you do?**
Reload the target page in the prometheus Web Admin UI

**What did you expect to see?**
That the order of the target is the same across page reload

**What did you see instead? Under which circumstances?**
The target are display in random order that vary from one request to the other

**Environment**
Ubuntu 16.04

* System information:
Linux 4.4.0-53-generic x86_64

* Prometheus version: 
prometheus, version 1.5.1 (branch: master, revision: c4686f79154ed4913415fc0855ae4544b3819b81)

**Comment by Gouthamve** [comment]
This is expected behaviour, we are ranging over a map. Can we know the
usecase for consistent ordering?

Thanks,
Goutham

On Tue, 28 Mar 2017, 14:26 Jean-Daniel, <notifications@github.com> wrote:

*What did you do?*
Reload the target page in the prometheus Web Admin UI

*What did you expect to see?*
That the order of the target is the same across page reload

*What did you see instead? Under which circumstances?*
The target are display in random order that vary from one request to the
other

*Environment*
Ubuntu 16.04

   -

   System information:
   Linux 4.4.0-53-generic x86_64
   -

   Prometheus version:
   prometheus, version 1.5.1 (branch: master, revision: c4686f7
   <https://github.com/prometheus/prometheus/commit/c4686f79154ed4913415fc0855ae4544b3819b81>
   )

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/prometheus/issues/2536>, or mute the thread

**Comment by Jean-Daniel** [comment]
Improving readability. 

Sometimes, I have to refresh the page to check the status of a target did change from Down to Up, and  having to search for the line position after each refresh is a little annoying, especially when the target list become large.

Sorting target by endpoint would also simplify the lookup of a specific target in the list.

**Comment by juliusv** [comment]
Agreed, having a consistent sort order would be nice for the refresh-and-check use case.

**Comment by juliusv** [comment]
Actually I'm not sure why it's not sorted already. https://golang.org/pkg/text/template/ says for `range`s in templates: "If the value is a map and the keys are of basic type with a defined order ("comparable"), the elements will be visited in sorted key order.". And `.TargetPools` is a `map[string][]*retrieval.Target`, and strings are definitely comparable :)

**Comment by juliusv** [comment]
Ah of course. The jobs are sorted, but the targets (`[]*retrieval.Target`) within a job are not. So we just need to sort that slice.

**Comment by juliusv** [comment]
PR out in https://github.com/prometheus/prometheus/pull/2548
