### ISSUE TITLE
Potential issue when sending SIGHUP before ready

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2563]
From a user on IRC:

The user reported Prometheus blocking on startup. Then:

"I was able to find the root cause of the problem. It was related to my program sending a SIGHUP to prometheus to reload it's configuration before prometheus registered the SIGHUP handler"

We should investigate whether our startup HUP signal handling is broken.

**Comment by Gouthamve** [comment]
If someone wants to look into this, here are some pointers:
Out HUP handler is registered just before this: https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L188

Since it is hard to actually send a HUP before stuff starts, I think the best thing we can do is to add `time.Sleep()` at that point and see if something is off. 
Then move the sleep to after `localstorage` starts. After `notifier.Start()` and so on to see if anything breaks anywhere.

If nothing breaks, I think it is safe to close this.

**Comment by alwindoss** [comment]
I am willing to work on this issue.
I am new to prometheus and relatively new to "go" and have worked on some hobby projects. Could someone help me through the initials here.

**Comment by grobie** [comment]
@krasi-georgiev can you confirm this is fixed with the main.go refactoring? This would be a great test.

**Comment by krasi-georgiev** [comment]
yes just tested with a `sleep`  before `close(reloadReady)` and it doesn't block the startup

will add it to the `main.go` tests issue
