### ISSUE TITLE
remote storage dockerized

### ISSUE THREAD

**Issue by prasenforu** [prometheus/prometheus#2649]
Not found any dockerised for remote_storage_adapter.

Because I am not able to find "remote_storage_adapter" executable file in docker "prom/prometheus" version 1.6

```
/prometheus # find / -name remote_storage_adapter
/prometheus #
```

In documents its mentioned 
```
InfluxDB example:
./remote_storage_adapter -influxdb-url=http://localhost:8086/ 
```
But in config its mentioned different port

```
add the following to your prometheus.yml:

# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
  - url: "http://localhost:9201/write"

# Remote read configuration (for InfluxDB only at the moment).
remote_read:
  - url: "http://localhost:9201/read"
```

Its little confusing, can someone please elaborate.

**Comment by juliusv** [comment]
This is only a code example in https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/remote_storage_adapter so far, so it is intentional that the example is not included in the release tarball.

In the future, when the code around remote storage has stabilized more, this will probably move to a separate repository with proper releases and such. For now, it will stay an example as it is.

As for the different ports, please keep usage questions to the mailing lists or IRC. In this case, there is one port that the remote storage adapter listens on, and another port over which the adapter reaches the actual remote storage backend (like InfluxDB on port 8086).
