### ISSUE TITLE
Prometheus 2: new parser fails to parse comments, parseFloat error

### ISSUE THREAD

**Issue by mwitkow** [prometheus/prometheus#2688]
**What did you do?**
run the latest `dev-2.0` branch with federation

**What did you expect to see?**
A working federation.

**What did you see instead? Under which circumstances?**

On a `/federate` endpoint that has:
```
# TYPE deployment:nodes_up::sum untyped
deployment:nodes_up::sum{app="gamex",dpl="qualify_27723",job="nodes",cluster="eu1-testing",instance="",monitor="simleaf-1"} 12 1494256282841
```

The scraping Prometheus instance sees:
```
strconv.ParseFloat: parsing "# TYPE deployment:nodes_up::sum untyped\ndeployment:nodes_up::sum{app=\"gamex\",dpl=\"qualify_27723\",job=\"nodes\",cluster=\"eu1-testing\",instance=\"\",monitor=\"simleaf-1\"}": invalid syntax
```

**Environment**
Manually built from commit:
https://github.com/prometheus/prometheus/commit/8c483e27d3d53b39ee0211c28eeeff7626c9ac99

@fabxc

**Comment by fabxc** [comment]
Oh, it's not actually the comments but the `:` in the metric name. The error message is just obscure because the parser is really not optimized for nice errors :)

It's actually defined [here](https://github.com/prometheus/prometheus/blob/dev-2.0/pkg/textparse/lex.l#L50) but I missed to use it properly.

**Comment by mwitkow** [comment]
Verified that it works for our federation set up. Cheers :beers:!
