### ISSUE TITLE
Prom2: /delete instead of /series/drop_series

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/prometheus#2760]
Deletes are almost in tsdb [[ref](https://github.com/prometheus/tsdb/pull/82)] and now I am looking into implementing in Prometheus itself.

We can delete in time-ranges now instead of a full series drop, keeping that in view `series/drop_series` is a bad endpoint. Should I make a new `/delete` end-point with `start` and `end` as compulsory parameters?

**Comment by fabxc** [comment]
I think this now opens a bigger discussion. Our API is essentially entirely read-only aside from `/series/drop_series`, which is currently disabled in 2.0.

Additionally, we'll want to expose DB administrative APIs ultimately like "pause compaction", "resume compaction", "take snapshot". An HTTP API will be our best bet there as well.

I consider deletes an administrative task as well rather than a core functionality of Prometheus. We should think about moving all those into a separate sub-API, which can easily be turned of via flag or blocked via proxies.

Thoughts on this? Separate admin port? Just a different path?

**Comment by brian-brazil** [comment]
#2173 were my plans for this. TL;DR: Mutating endpoints disabled by flag by default.

**Comment by fabxc** [comment]
Yes, I'm proposing here to move them all behind a distinct API. That's a) clearer separating purpose and b) more reasonable to implement than having a toggle across random API handlers.

**Comment by brian-brazil** [comment]
From a security standpoint, having the mutating endpoints under one path would make it easier for users to manager with a reverse proxy.

**Comment by Gouthamve** [comment]
Closed in #2910
