### ISSUE TITLE
Low-resolution querying may drop long time ranges

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2776]
When querying Prometheus with "low" resolution (default is often low enough), minute long time ranges are often not shown. Those seem to correlate exactly with blocks, but not confirmed yet.

Setting an explicit low query resolution makes the expected data reappear in the results.

**Comment by fabxc** [comment]
I'm seeing this pretty consistently while @Gouthamve cannot reproduce this. Would be good to know whether other's can. @mwitkow @grobie @beorn7

**Comment by mwitkow** [comment]
@fabxc I'm not sure what you mean by low resolution? A narrow time window?
Can you give an example of a `/query` param to try reproduce?

**Comment by fabxc** [comment]
Just range queries with a coarse-ish step size.

**Comment by mwitkow** [comment]
Can confirm. Querying for `5m` intervals work, but anything like `1m` or `30s` rates show holes in data.

Take a look at this. The gap around 11:00 when using `30s` rate
![image](https://cloud.githubusercontent.com/assets/9655971/26593541/5d75b45c-455c-11e7-896e-4306e22d602a.png)

vs the same data with a `5m` rate

![image](https://cloud.githubusercontent.com/assets/9655971/26593567/81daaa0a-455c-11e7-8a03-20ae82e7b4d4.png)

**Comment by fabxc** [comment]
Thanks for confirming – now to find out where it all went wrong.

**Comment by Gouthamve** [comment]
I can reproduce this locally now, some early findings:
1. Low resolution is not the cause of it: [Low res](https://i.imgur.com/8Ka7B7J.png) vs [High res](https://i.imgur.com/pw8SvXJ.png)
2. The same resolution over different time ranges can cause it: [shorter range](https://i.imgur.com/p71yhpK.png) vs [longer range](https://i.imgur.com/znhv6Zo.png)

And the worst part is, in 2) above, the break happened at 1800, and the block spans from 1315 to 2000, so this is definitely not due to block boundaries. Digging further.

**Comment by Gouthamve** [comment]
This is caused because of [this commit](https://github.com/prometheus/tsdb/commit/a51b2666d746738092b20196a79c02b8dc0c83ac) by me. When we cut a chunk, we are not setting a mint and it is defaulting to 0.

Later we are [Seeking to the right chunk using the chunk's MinTime](https://github.com/prometheus/tsdb/blob/master/querier.go#L676) which makes us seek to wrong chunks and skip some chunks. Fixing the mintime when cutting a chunk should fix this IMO.

**Comment by fabxc** [comment]
Chunk's min timestamp is fixed as part of prometheus/tsdb#94. Will check whether I can still produce the issue.

**Comment by mwitkow** [comment]
Can't reproduce it from our side with today's dev-2.0 cut so :champagne:
