### ISSUE TITLE
prom/prometheus:v2.0.0-beta.0 container crashes on start

### ISSUE THREAD

**Issue by hanikesn** [prometheus/prometheus#2952]
The prom/prometheus:v2.0.0-beta.0 container images crashes with the following error message:
```
prometheus: error: unknown short flag '-c'
```

**Comment by rgcamus** [comment]
#2942 ?

**Comment by Gouthamve** [comment]
Hi, yes this bug has been fixed by #2942 and is in HEAD. As a fix, you need to pass the flags manually to docker.

For example:
`docker run --rm -it prom/prometheus:v2.0.0-beta.0 --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus`

Closing this as the fix is in HEAD. Please re-open if you think otherwise.

**Comment by sethubala76** [comment]
docker run -it -d --name prometheus -p 9090:9090 -v /docker/prometheus:/etc/prometheus --link alertmanager prom/prometheus:v2.0.0-beta.0 --config.file=/etc/prometheus/prometheus.yml -alertmanager.url="http://alertmanager:9093/

Errored by -- 
docker logs a3e041ab2acc7a6aa18e8338ef325e0e453cb25f9a0a3a1c2245286fcb0fce24
prometheus: error: unknown short flag '-a'
