### ISSUE TITLE
rush  mode question

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#2978]
prom 1.6.1

in rush mode,why read io increase?
blue line is read io

![image](https://user-images.githubusercontent.com/9782796/28465523-a3b6b25e-6e5b-11e7-87d5-94abacd22254.png)

**Comment by timchenxiaoyu** [comment]
read io is still  increasing
<img width="719" alt="oi" src="https://user-images.githubusercontent.com/9782796/28504516-210802e4-704b-11e7-9426-0f31454abcde.png">

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by timchenxiaoyu** [comment]
I have create this https://groups.google.com/forum/#!topic/prometheus-users/ZuTAL2_GMD8
