### ISSUE TITLE
How to bring parameter in prometheus.rules

### ISSUE THREAD

**Issue by shanquanqiang** [prometheus/prometheus#2985]
rule_files:
  - 'prometheus.rules'

prometheus.rules:
oracle_redo_rate = irate(oracle_redo[3m])

If the time range is a variable,how to write the rules

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
