### ISSUE TITLE
When "increase" is not enough!

### ISSUE THREAD

**Issue by sia-s** [prometheus/prometheus#3000]
In one of my dashboards I show number of requests in last hour. I use increase function but it gives wrong results when data is missing:

![image](https://user-images.githubusercontent.com/13893594/28699230-407c9f22-72fd-11e7-9382-0725b65117a9.png)

![image](https://user-images.githubusercontent.com/13893594/28699222-35a871ca-72fd-11e7-9676-6e93973c42a9.png)

As you can see status count for "200" shows 1 but increase shows 0. The value of first sample of that series is 1 therefore "increase" extrapolates previous missing samples to be also 1 therefore calculates the increase to be zero. Is there any better way to write this simple query?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

See https://www.robustperception.io/existential-issues-with-metrics/
