### ISSUE TITLE
Does Prometheus support dynamic granularity storage like rrdtool?

### ISSUE THREAD

**Issue by krisoul** [prometheus/prometheus#3033]
Does Prometheus support dynamic granularity storage like rrdtool?

For example:
If I set scrape-interval=30s,
in last 1st month, data's granularity is 30s;
in last 2nd month, data's granularity is 60s;
in last 3rd month, data's granularity is 90s;
...

Just like the granularity can be adjusted dynamicly by the period in storage.

If not, will Prometheus support this function in the near future?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
