### ISSUE TITLE
How do I use Prometheus in my business case?

### ISSUE THREAD

**Issue by krisoul** [prometheus/prometheus#3034]
I want to store nearly 2000 machines' metrics and there are 70 metrics of each machine, 
and `scrape-interval = 10s`

so what kind of configuration or performance of my Prometheus server needs at least?

and In that case, how do I make the configuration?

like this:

```
-storage.local.retention=2160h 
-storage.local.memory-chunks=5242880 
-storage.local.max-chunks-to-persist=3097152 
-storage.local.num-fingerprint-mutexes=10240 
-storage.local.series-file-shrink-ratio=0.2 
-storage.local.checkpoint-interval=5m 
```

Looking forward to your suggestions.

Best regard!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by krisoul** [comment]
@brian-brazil 
I asked this question there, but still no response, so could you give some ideas?
