### ISSUE TITLE
Get https://ip:443/-/metrics?token=***: x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by denglitong** [prometheus/prometheus#3077]
Here is what I get in my Prometheus's target web page:

https://10.21.20.124:443/-/metrics
token="v8T6QaGu8ykbxiuVLa6o" | DOWN | group="web" instance="10.21.20.124:443" | 2.001s ago | Get https://10.21.20.124:443/-/metrics?token=v8T6QaGu8ykbxiuVLa6o: x509: failed to load system roots and no roots provided
-- | -- | -- | -- | --

And when I visit https://10.21.20.124/-/metrics?token=v8T6QaGu8ykbxiuVLa6o I can see the metrics data, so what should I do to fix it? Wait online, thanks very much!

**Comment by grobie** [comment]
Please ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

As the error message says, your Prometheus host system doesn't have any x509 (TLS, HTTPS) root certificates installed.

**Comment by denglitong** [comment]
thanks much! I add the `tls_config: insecure_skip_verify: true` in prometheus.yml, then it's up and works.
