### ISSUE TITLE
I have a problem with a target (connection reset by peer)

### ISSUE THREAD

**Issue by YraganTron** [prometheus/prometheus#3079]
I launch prometheus as a Docker image. Connection is not establishing with one of the targets (but it's good with the others). Here are a config and the error.
```text
global:
  scrape_interval: 25s
  evaluation_interval: 25s
  scrape_timeout: 20s

  external_labels:
    monitor: 'mobil-med-monitor'

rule_files:
  - '/etc/prometheus/cadvisor.rules'
  - '/etc/prometheus/nodes.rules'
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'ansible'
    metrics_path: '/ansible_manager_metrics'
    bearer_token: '123123'
    static_configs:
      - targets: ['some.service.stud.consul:443']
    scheme: https
    tls_config:
       ca_file: /tmp/rootCA.crt
#      insecure_skip_verify: true
```

```text
Get https://some.service.stud.consul:443/ansible_manager_metrics: read tcp 172.17.0.23:33290->192.168.4.152:443: read: connection reset by peer
```
There is no problem with the target itself, if I try to watch metrics manually it's working.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
