### ISSUE TITLE
Query Annotations

### ISSUE THREAD

**Issue by arunkumarpro1** [prometheus/prometheus#3085]
Is it possible to obtain the annotations of the alerts in the query results?

I tried using the HTTP API [https://127.0.0.1:9000/prom/api/v1/query?query=ALERTS{}](url). But it just gave me the alert name and some other fields, but not the annotations.

**Comment by brian-brazil** [comment]
No, they're only for the alertmanager.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
