### ISSUE TITLE
elastic search remote_storage  support

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3134]
will es be supported soon ?

**Comment by brian-brazil** [comment]
We've no plans to develop one, but you're free to do so.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Jaware** [comment]
ok,thanks,i prefer java,so i will write a gateway for es
