### ISSUE TITLE
Multiple alert rules of groups in one file

### ISSUE THREAD

**Issue by ArugakiWei** [prometheus/prometheus#3139]
The prometheus version i use is   2.0.0-beta.2, and i want to make some alert rules in one file, like this:

*first.rules:*
       
     groups:
      - name: test
          rules:
          - alert: test
          expr: go_memstats_heap_released_bytes<1

     groups:
     - name: test1
       rules:
       - alert: test1
       expr: go_memstats_heap_released_bytes<1

 There are many groups in first.rules.
But only the last alert rule of groups takes effect when i lanch prometheus，it is alert:test1 will take effect.

 Is there a problem with my operation？
Does this release support this？

Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
