### ISSUE TITLE
no token found

### ISSUE THREAD

**Issue by hannesm** [prometheus/prometheus#3154]
**What did you do?**

I installed prometheus 2.0.0-beta.2.linux-amd64 and installed a custom exporter.
I'd be delighted to hear what is wrong in my exporter, but I couldn't find much documentation about allowed characters etc.

**What did you expect to see?**

statistics :)

**What did you see instead? Under which circumstances?**

when fetching my own exporter, I receive the following error on the console where I started prometheus:
```
WARN[0659] append failed                                 err="no token found" source="scrape.go:648" target="{__address__="192.168.42.1:9080", __metrics_path__="/metrics", __scheme__="http", instance="192.168.42.1:9080", job="vmm"}"
```

**Environment**

* System information:

        Linux 4.4.0-87-generic x86_64 (ubuntu 16.04)

* Prometheus version:

	prometheus, version 2.0.0-beta.2 (branch: HEAD, revision: a52f082939a566d5269671e98be06fc6bdf61d09)
  build user:       root@41a0740ea598
  build date:       20170818-08:16:50
  go version:       go1.8.3

* Prometheus configuration file:
```
  - job_name: 'vmm'
    static_configs:
      - targets: ['192.168.42.1:9080']
```

* Logs:

when I manually download http://192.168.42:9080/metrics, I get the output available at https://berlin.ccc.de/~hannes/data.txt

**Comment by fabxc** [comment]
The bad metric is this one `sn_nqsb_io_EOI_without_any_in-service_interrupt`. No dashes allowed :)

Admittedly, the new parser certainly gives less valuable error messages. But it's probably rare enough in the general case since client libraries ensure correctness.
I'd generally recommend to use one of them for custom exporters. 

I'll look into adding line information at least though.

**Comment by hannesm** [comment]
@fabxc thanks for your reply.  I'd appreciate line number information in "no token found" -- or some documentation how to debug such a problem.

sorry for not spotting the `-` myself.  it works now.

**Comment by lynchc** [comment]
+1

**Comment by bavuonglong** [comment]
@fabxc I got the same error : no token found when integrate prometheus into spring boot app, the thing is inside output of /metrics, I see a metric has "-" character, it is ""gauge.response.star-star.favicon.ico": 129,
"counter.status.200.star-star.favicon.ico": 1,"
You can see full output here: https://pastebin.com/efH010Tz
Due to this is default metric from spring actuator, do you have any suggestion?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by calston** [comment]
This also means if your real target hostname has a dash in it then blackbox exporter is useless.
