### ISSUE TITLE
Help about storage of prometheus 

### ISSUE THREAD

**Issue by songcaixin** [prometheus/prometheus#3168]
I want to open the file of Data under Prometheus , which tool can be used to open the DB file?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
