### ISSUE TITLE
multiarch support for Docker official image

### ISSUE THREAD

**Issue by vielmetti** [prometheus/prometheus#3203]
Docker now has support for transparently providing multi-architecture builds for official images. The `mquery` tool at https://github.com/estesp/mquery gives one way to query current status, and the source code for mquery gives an example of using a CI system to produce this.

I'd like Prometheus to provide a Docker image that works on as many supported architectures as possible, including and especially arm64.

**What did you do?**

```
$ docker run --rm mplatform/mquery prom/prometheus
Manifest List: No
 Supports: amd64/linux
```
**What did you expect to see?**

Multi-architecture support with a "fat manifest" pointing to all supported Prometheus binaries from official image.

**What did you see instead? Under which circumstances?**

Only amd64 support in official image.

**Comment by alexellis** [comment]
There is already a 64-bit ARM Prometheus binary release, so this should be relatively straight-forward - i.e. placing that binary into a container and adding the default configuration. 

In terms of the "multi-arch" images - this is done through a manifest file which contains a map of named images and what architecture they are for. The first part is more important than this one, but both would be great.

**Comment by vaibhavsood** [comment]
+1 for ppc64le. prometheus has a ppc64le binary as well so that be included too. I'm willing to help out with any ppc64le changes that may be needed to support an official ppc64le Docker image

**Comment by vielmetti** [comment]
Attn @tianon who may be able to provide some guidance as to how to do this the easiest way.

**Comment by tianon** [comment]
With the official images, we try very hard to keep our multiarch images building all architectures from a single `Dockerfile` (to keep the added maintenance burden of supporting additional architectures lower, and to help ensure we keep parity).

As for actually pushing them with a manifest list (so that, for example, `docker run prometheus/prometheus` works properly on more than one architecture), you'll need to push the bits _somewhere_ in the target registry, then use something like https://github.com/estesp/manifest-tool to combine them into a single tag with the appropriate metadata (especially adding `variant`, in the case of `arm`).

For the official images, we use a separate namespace per architecture (https://github.com/docker-library/official-images#architectures-other-than-amd64), but I know at least the LinuxKit folks simply use separate tags per architecture in the same repository (https://hub.docker.com/r/linuxkit/kernel/tags/).

**Comment by sdurrheimer** [comment]
I need to take a look at this and see how we can integrate it in our build process.

**Comment by vielmetti** [comment]
Thanks @sdurrheimer - would it make more sense to open an issue in https://github.com/prometheus/promu to track it there?

**Comment by vielmetti** [comment]
#3619 looks like a related issue.

**Comment by alexellis** [comment]
Ping on thread. The community really needs this - other key projects are adopting multi-arch but I'm having to maintain custom hacks and images to work with Prometheus. Can we help you in some way with this for the greater good?

**Comment by grobie** [comment]
I understand a PR for promu would be the next step.

**Comment by vielmetti** [comment]
Closing this issue here, in favor of the issue (and hopefully forthcoming PR) in `promu`.
