### ISSUE TITLE
hi, I want calculate data sum of one day , data type is counter , What should I do ?

### ISSUE THREAD

**Issue by zhanglp92** [prometheus/prometheus#3221]

**Comment by zhanglp92** [comment]
hi, l want calculate data sum of one day ，data type is counter ，what should I do ？
One data point per day. 

thank you.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Look at increase()
