### ISSUE TITLE
prometheus delete Target some issue

### ISSUE THREAD

**Issue by zhanglp92** [prometheus/prometheus#3226]
I add target to prmetheus config ，
eg：
![image](https://user-images.githubusercontent.com/6869148/30964320-6c1989a2-a416-11e7-8d7d-5645e55667af.png)
prometheus graph ，
1、start my server 
2、delete target from prometheus config 
eg：
![image](https://user-images.githubusercontent.com/6869148/30964567-7f23405a-a417-11e7-92bd-25539a0a3e12.png)

help me ，thank you

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
