### ISSUE TITLE
Graphite write error

### ISSUE THREAD

**Issue by digambarGitHub** [prometheus/prometheus#3227]
I have data for each day. Sending that data to grafana on daily basis and that works good.
But when I try to send data for multiple days writer is throwing exception as below : 

`java.net.SocketException: Software caused connection abort: socket write error`

When I send data for first 2-3 days it sends without problem, after that this error continues.

Please suggest.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
