### ISSUE TITLE
Move both X and Y Axis Tick-Mark Labeling to Outside of Graph

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#325]
Per http://code.shutterstock.com/rickshaw/tutorial/introduction.html with the _Y-Axis Too_ section, we should move the axis labeling to outside of the graph.  This will prevent series from being rendered over both the tick mark values.

```
var y_axis = new Rickshaw.Graph.Axis.Y( {
        graph: graph,
        orientation: 'left',
        tickFormat: Rickshaw.Fixtures.Number.formatKMBT,
        element: document.getElementById('y_axis'),
} );
```

Note the external _element_ definition.

**Comment by nsauro** [comment]
So, I started looking at this, but..it *seems* like this might already be finished?

Looks like a yaxis element is defined: https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph.js#L551-L554

Then referenced:
https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph.js#L109

Then looks like the y axis utilizes this:
https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph.js#L621-L626
specifically L625.

I think x-axis is fine as is, or am I mistaken?

Disclaimer: I'm not super versed in JS, so pardon any bold claims :)

@Gouthamve  Tagged you since you were the last person to touch this.

**Comment by grobie** [comment]
Four year old issue, no one has complained about this. Let's just close @juliusv?

**Comment by juliusv** [comment]
Yeah, I think so too. Closing.
