### ISSUE TITLE
count metrc become 0 after instance die

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3281]
my service have 3 instance deployed in kubernetes,when one instance died,the count metric become 0,so when query using sum(count) by(serviceid),the result is wrong!
is there any solution for this cluster envirment?

**Comment by Jaware** [comment]
this is very critical,because we have many situations for calculating count like error,total number

**Comment by brian-brazil** [comment]
I'd suggest watching https://www.youtube.com/watch?v=67Ulrq6DxwA

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
