### ISSUE TITLE
cumulative  design  problem

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3282]
because both histogram and summary are cumulative,  when i want to write prometheus metirc to other db like elasticsearch,i can not get the right result  using other db's aggregation query.
 and other problems happen when one instance of my service died,because the count and sum become 0 after restart!
can prometheus provide metrics  this way? for example ,when one api is requested,the following metric is generated:    request_test(uri="/api/test",value=1,lantancy="2ms") 
 this time,because value is always 1,caculating the max count is very easy, lantancy aggregations like max ,min and avg   are alse easy😄

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
