### ISSUE TITLE
Please provide package repositories for important Linux distros

### ISSUE THREAD

**Issue by COLABORATI** [prometheus/prometheus#3310]
Please provide packges for important Linux distros like Debian, Ubuntu, Centos.
It seems awkward to me that I should check for a new version of these tools and install them manually.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
