### ISSUE TITLE
What's the maximum of scrape_interval I could set?

### ISSUE THREAD

**Issue by tangr** [prometheus/prometheus#3328]
When I set scrape_interval to 7m just as the below example, and stop the target for test, the rule will not enter firing state, the alert go into pending state, and then Inactive after 2mins.

So I think the the scrape_interval will not set to more than 2m, is it right? 

But I don't like the scrape to affect the system much, set the scrape_interval higher is better, or if the scrape running time of some exporter more than 3mins.  Another scene is the aws Cloudwatch API request cost is high, so reduce the scrape number is the appropriate approach.

* Prometheus version:

	1.8.0

* Prometheus configuration file:
```
 - job_name: 'test'
   scrape_interval: 7m
   static_configs:
     - targets: ['nodeexporter:9100']

ALERT instance_down_debug
  IF up == 0
  FOR 5m
  LABELS {severity="debug"}
  ANNOTATIONS {detail="Host {{ $labels.instance }} is down.", short="{{ $labels.instance }} down"}
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by tangr** [comment]
ok, thank you, brian.
