### ISSUE TITLE
federation prometheus can not show pervious data?

### ISSUE THREAD

**Issue by fumanne** [prometheus/prometheus#3418]
prometheus-A (configure federation), the source prometheus name prometheus-B, if  Both A and B stop and start again.  (start with same parameter)  B can show the previous data (like 3 days ago), but the A can not show previous data (seems all the previous data are lost)...both version is 1.8.2

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
