### ISSUE TITLE
negative values with irate for CPU usage

### ISSUE THREAD

**Issue by enutrofff** [prometheus/prometheus#3434]
Hi All,

I use this query to get the CPU utilization:

`100 - (irate(node_cpu{mode="idle", instance=~"Web:9100"}[5m])) * 100`

With this query, I got negative values in my graphs

![cpu_negative](https://user-images.githubusercontent.com/4835211/32550213-e6e78f5a-c494-11e7-8558-645da21475fd.png)

scrape_interval for this metric is:   15s

Please find below the raw values and timestamps around the artifact:

[cpu_minus.zip](https://github.com/prometheus/prometheus/files/1453892/cpu_minus.zip)

I'm using Prometheus version: 2.0.0-rc.1

why is this happening?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
