### ISSUE TITLE
Get charts by API

### ISSUE THREAD

**Issue by Kami-no** [prometheus/prometheus#3448]
Is there a way to get charts using API?

We have notifications using messenger with small specialized service. We wish to have charts for fired alerts in notifications like Grafana does. Is there API to get chart as an image that we will be able to get from Prometheus and attach it to the notification?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
