### ISSUE TITLE
consul_sd_config should support finding by {tag}.service

### ISSUE THREAD

**Issue by Wing924** [prometheus/prometheus#3452]
consul_sd_config currently only support finding by service names.
It should also support finding by {tag name}.service.

Ref. [Prometheus Configuration#<consul_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#<consul_sd_config>)

**Comment by brian-brazil** [comment]
This is possible with relabelling.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
