### ISSUE TITLE
pls add edns in configure about dns ds

### ISSUE THREAD

**Issue by gefire** [prometheus/prometheus#3479]
* System information:

	linux x64

* Prometheus version:

	2.0

i have 12 nodes server , i use consul dns server  for dns ds?  it can only return 3 nodes SRV , i saw the discovery/dns.go have a variables name edns , default is false ,  i turn it to true  and build it , can return all nodes ? so request add edns config pls!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
