### ISSUE TITLE
1.7.1 version step problem

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3500]
/api/v1/query_range?query=sum(rate(http_server_requests_count%7Bapp%3D%22signin%22%2Curi!%3D%22%2Fprometheus%22%7D%5B20s%5D)*60)%20by%20(job)&start=1511298445&end=1511320197&step=30
query is:
sum(rate(http_server_requests_count{app="signin"}[20s])*60) by (job)
the problem is that:when step is 30 the result is emply list,while step is 29 is ok,step is 31 still ok, so strange(｡•ˇ‸ˇ•｡)
is there any solution ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
