### ISSUE TITLE
prometheus metric data is null on kubernetes 1.8.2

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#3502]
I meeth this problem on kubernetes 1.8，with prometheus configmap add cadvisor job like this

job_name: 'kubernetes-cadvisor'
metrics_path: /metrics/cadvisor
tls_config:
ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
kubernetes_sd_configs:
role: node
relabel_configs:
source_labels: [address]
regex: '(.*):10250'
replacement: '${1}:10255'
target_label: address
My Environment：
kubernetes v1.8.2+coreos.0 with RBAC
prometheus v1.7.1
docker 1.13.1
Centos 7.3.1611

Problem Picture：
![1](https://user-images.githubusercontent.com/18571465/33115001-4e18a186-cf9a-11e7-95e1-3e099a403200.png)
![2](https://user-images.githubusercontent.com/18571465/33115023-5613a6a6-cf9a-11e7-8869-cf34411db9af.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
