### ISSUE TITLE
namespace disappear

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#3514]
prometheus 2.0.0  +k8s 1.7.6

curl http://10.39.0.113:10009/api/v1/query?query=container_memory_usage_bytes&time=1511761470.963

get metric ,sometime pod metric  disappear

**Comment by timchenxiaoyu** [comment]
<img width="1887" alt="wx20171127-135358 2x" src="https://user-images.githubusercontent.com/9782796/33252658-773d51e0-d37a-11e7-8c44-8695991aecce.png">

**Comment by timchenxiaoyu** [comment]
omit data, and no error log??

**Comment by Gouthamve** [comment]
Hi, I think this is due to the new staleness changes and cAdvisor spitting out inconsistent metrics. See https://github.com/google/cadvisor/issues/1704 and https://github.com/prometheus/prometheus/issues/2982.

Closing it off as a cAdvisor issue.

**Comment by m4agenbitter** [comment]
@Gouthamve I'm running into the same issue with an custom exporter.

I only scrape it every 10 minutes (wich is enough for my use case), but they will get reported as stale after 5 minutes.
However they aren't really stale at that point.

Can I change the default value of 5 minutes?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by dashpole** [comment]
The fix is released in version v0.28.3
