### ISSUE TITLE
Access to the metric name from the relabelling rules

### ISSUE THREAD

**Issue by dlespiau** [prometheus/prometheus#3526]
I'm facing a situation where I would like to add a label to a specific metric at scrape time, but don't seem to be able to as the metric name isn't part of the `__` variables exposed to the relabelling rules.

Would love a `__metric__` or `__metric_name__`.

**Comment by jamtur01** [comment]
Isn't this `__name__`?

**Comment by dlespiau** [comment]
Huuum, it could be! I'm looking at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#<relabel_config> and there's no `__name__` documented there.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Look at metric_relabel_configs.
