### ISSUE TITLE
Integrations link broken

### ISSUE THREAD

**Issue by jamtur01** [prometheus/prometheus#3537]
On the Prometheus configuration page in the file discovery section:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config

There's a link to integrations that resolves to:

https://github.com/prometheus/prometheus/blob/release-2.0/docs/operating/configuration/#%3Cfile_sd_config

It should resolve to:

https://prometheus.io/docs/operating/integrations/#file-service-discovery

In configuration.md it looks like it should be right.

```markdown
There is a list of
[integrations](/docs/operating/integrations/#file-service-discovery) with this
discovery mechanism.
```

Perhaps needs to be rebuilt?

**Comment by brian-brazil** [comment]
@grobie Should we be using full URLs for things like this?

**Comment by grobie** [comment]
Yes. Links to content on prometheus.io / prometheus/docs should be absolute URLs. All other links are assumed to reference pages/content inside of this repo.

**Comment by ameseee** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. Is there documentation on how to build the static docs to verify that the change renders correctly on prometheus.io?

**Comment by jamtur01** [comment]
@ameseee The README for the docs project has the instructions:

https://github.com/prometheus/docs/blob/master/README.md

**Comment by ameseee** [comment]
Thanks @jamtur01  - I've gotten the doc site running locally, but the make file seems to have hard coded values for the prometheus github to curl content. My fork of the prometheus repo has the updated link in docs/configuration/configuration.md, but I cannot verify that it works due to the hard coded make file. Is there a way to adjust the make file so only the prometheus repo will get pulled from my fork, or would you like me to submit a PR for the changed link without verifying locally?

**Comment by brian-brazil** [comment]
For a simple thing like this, a PR with the fix is okay. nanoc.yaml is the file you need to tweak to have it pull in from other places.
