### ISSUE TITLE
how can i build a proxy like zabbix-proxy?

### ISSUE THREAD

**Issue by maopaolinux** [prometheus/prometheus#3571]
Hi
    I want change my monitor system from zabbix to prometheus,because i use docker in my environment，i want known how can i build a proxy to send export data to prometheus,thank you

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
