### ISSUE TITLE
send inactive status  to alertmanager

### ISSUE THREAD

**Issue by yylt** [prometheus/prometheus#3580]
**What did you do?**
add some alertingrules into prometheus , and send alert status to alertmanager

**What did you expect to see?**
send pending(resolved) or firing(actived) status to alertmanger , 

**What did you see instead? Under which circumstances?**
 only send firing and inactive status, and rule/manage.go filter pending status , what's designed of alertingrules  in prometheus?

**Environment**
prometheus v1.8.2     5211b96
alertmanger v0.8.0     74e7e48

* System information:

	linux 3.14.0

* Prometheus configuration file:
ALERT rule_39f4ab27
IF node_monit{id="e0c7d97b2"} != 1
FOR 10m
LABELS {serverity='critical'}
ANNOTATIONS {current_value="{{value}}"}

* Alertmanager configuration file:

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
