### ISSUE TITLE
prometheus not running.

### ISSUE THREAD

**Issue by Meghna-singh** [prometheus/prometheus#3590]
Trying to run prometheus but getting this error

level=info ts=2017-12-15T10:46:23.745498382Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"
level=info ts=2017-12-15T10:46:23.745559054Z caller=main.go:216 build_context="(go=go1.9.2, user=root@615b82cb36b6, date=20171108-07:11:59)"
level=info ts=2017-12-15T10:46:23.745594335Z caller=main.go:217 host_details="(Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 meghna-Latitude-3560 (none))"
level=info ts=2017-12-15T10:46:23.749048549Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-12-15T10:46:23.749124255Z caller=main.go:314 msg="Starting TSDB"
level=info ts=2017-12-15T10:46:23.749111326Z caller=targetmanager.go:71 component="target manager" msg="Starting target manager..."
level=error ts=2017-12-15T10:46:23.749512882Z caller=main.go:323 msg="Opening storage failed" err="open DB in data/: Locked by other process"

**Comment by brian-brazil** [comment]
Turn off the other Prometheus that is running.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
