### ISSUE TITLE
http alert

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#3594]
I monitor a web http url through http_2xx mode, how to generate alert? how to set alert rules

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
