### ISSUE TITLE
multi arch docker images

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#3619]
It seems the docker images on hub.docker are only for amd64. 

It would be nice to make them multiarch and add support for: arm, arm64, ppc, s390x.

We've done with in CoreDNS, see https://github.com/coredns/coredns/blob/master/Makefile.release

**Comment by vielmetti** [comment]
Agreed. Looping @tianon in on this too.

**Comment by tianon** [comment]
I've had success with something like the following, but it requires building natively on all platforms: (which we'd be happy to help with if Prometheus wanted to participate in https://github.com/docker-library/official-images, which we'd also be happy to help facilitate)

```dockerfile
FROM alpine:3.7

WORKDIR /opt/prometheus
ENV PATH /opt/prometheus:$PATH

# https://github.com/prometheus/prometheus/releases
ENV PROMETHEUS_VERSION 2.0.0

RUN set -ex; \
	\
	apk add --no-cache --virtual .fetch-deps \
		ca-certificates \
		libressl \
	; \
	\
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		aarch64) promArch='arm64'   ;; \
		armhf)   promArch='armv6'   ;; \
		ppc64le) promArch='ppc64le' ;; \
		s390x)   promArch='s390x'   ;; \
		x86)     promArch='386'     ;; \
		x86_64)  promArch='amd64'   ;; \
	esac; \
	\
	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-${promArch}.tar.gz"; \
	tar \
		--extract \
		--file /tmp/prom.tar.gz \
		--strip-components 1 \
		--verbose \
	; \
	rm /tmp/prom.tar.gz; \
	\
	prometheus --version; \
	\
	apk del .fetch-deps

VOLUME /opt/prometheus/data

EXPOSE 9090
CMD ["prometheus"]
```

Otherwise, this should be pretty easy to accomplish with either cross-building (like what I believe that CoreDNS makefile is doing) or even multi-stage builds (perhaps with an `ARG` for "target architecture"):

```dockerfile
FROM alpine:3.7 AS download

ARG arch=amd64

RUN apk add --no-cache libressl ca-certificates && wget "...-linux.$arch..." # ...

ARG from=amd64/alpine:3.7
FROM $from

COPY --from=download /path/to/prometheus /path/

CMD ["prometheus"]
```
then building via `docker build --arg arch=386 --arg from=i386/alpine:3.7 ...` for example

**Comment by brian-brazil** [comment]
https://github.com/prometheus/promu/issues/89 is where to discuss this.
