### ISSUE TITLE
The function increase doesn't returned the correct value 

### ISSUE THREAD

**Issue by ahrtr** [prometheus/prometheus#3622]
The query is as below, in which the "test_call_count" is a counter,
`increase(test_call_count[10m])`

Test steps:
1. send a request using curl to the target, then the value of test_call_count was 1, but the value of increase(test_call_count[1h]) was 0;
2. send another request using curl to the target, then the value of test_call_count was 2, but the value of increase(test_call_count[1h]) was 1.0175438596491229. 

I was exepecting to get the number of HTTP requests as measured over the last 10 minutes. But it seems that the function "increase" can't meet my requirement. 

The version is prometheus:v2.0.0, and it's deployed on Oracle linux 7.3.

**Comment by brian-brazil** [comment]
https://www.robustperception.io/existential-issues-with-metrics/
https://www.youtube.com/watch?v=67Ulrq6DxwA

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
