### ISSUE TITLE
Can add the cascade feature?

### ISSUE THREAD

**Issue by leenux** [prometheus/prometheus#3623]
From https://prometheus.io/assets/architecture.svg and https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-itself
I found Prometheus can monitor-itself,if Prometheus can cascade and can collect metrics data of 'child Prometheus',Prometheus will break through the Intranet penetration for IoT devices.
The IoT devices offen live in LAN or intranet,Prometheus of cloud can't found the IoT devices directly.if a Prometheus server builded on gateway that can connect Internet and Intranet,it will be more perfect.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
