### ISSUE TITLE
Unable to start Prometheus  in Docker container

### ISSUE THREAD

**Issue by zibuyu1995** [prometheus/prometheus#3633]
**What did you do?**
I started prometheus using docker
```
docker run -d --name=prometheus -p 9090:9090 --web.enable-lifecycle prom/prometheus:latest
```
**What did you expect to see?**
A successful docker-compose up
**What did you see instead? Under which circumstances?**
```
➜  ~ docker run -d --name=prometheus -p 9090:9090 --web.enable-lifecycle prom/prometheus:latest
unknown flag: --web.enable-lifecycle
See 'docker run --help'.
```
**Environment**
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* System information:
```
Linux 4.4.0-62-generic x86_64
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
