### ISSUE TITLE
Alert Labels not updated while alert is firing

### ISSUE THREAD

**Issue by mweinelt** [prometheus/prometheus#3694]
**What did you do?**

Created an alert rule that passes the value as a label.

**What did you expect to see?**

The label value should be updated while the alert is firing.

**What did you see instead? Under which circumstances?**

The label value was stuck at the value when it initially triggered.

**Environment**

* System information:

Linux 4.9.0-5-amd64 x86_64

* Prometheus version:

prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

* Prometheus configuration file:
```
alert: RoomHighTemp
expr: arduino_temperature{job="c303env"}
  > 28
for: 10m
labels:
  severity: page
  value: '{{ $value }}'
annotations:
  description: The air temperature in C303 is above 28°C
  summary: Air temperature in C303 is {{ $value }}°C
```

* Example:

![alert](https://i.imgur.com/zjft1SE.png)

**Comment by brian-brazil** [comment]
Alerts are defined by their labels, having varying alert labels like this is a bad idea. Use annotations instead.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
