### ISSUE TITLE
Federation does not pass empty labels

### ISSUE THREAD

**Issue by pieterdejaeghere** [prometheus/prometheus#3706]
On a local prometheus server, if a metric exists with an empty label it shows up like this:

metricxyz{empty_label="", other_label="xyz"}

if another prometheus server pulls in this metric via federation, the result becomes:

metricxyz{other_label="xyz"}

I'd expect the result to be identical, being:
metricxyz{empty_label="", other_label="xyz"}

**Environment**

* System information:

Redhat7 Linux 3.10.0-514.10.2.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

* Prometheus configuration file:

  - job_name: federation
    scheme: http
    metrics_path: /federate
    scrape_interval: 300s
    scrape_timeout: 120s
    honor_labels: true
    params:
      'match[]':
        - '{job="xyz"}'
    static_configs:
      - targets:
        - 'other-server:9090'

**Comment by brian-brazil** [comment]
An empty label is the same thing as no label.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
