### ISSUE TITLE
Autocomplete on expression inputs is overzealous

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#3718]
See:

![autocomplete](https://user-images.githubusercontent.com/538008/35195514-0ea4532e-fec5-11e7-9158-d8252939364b.png)

When I type that expression and just press "Return", it will now select a completely unrelated historical expression and execute that instead. It's now quite hard to just query what you want to query when having "Search query history" enabled.

This should be smarter / more restrictive in the matching of history items, and/or it should not auto-select the first completion item, but rather whatever the user has typed (which would require the user to press DownArrow to select the first completion item instead).

**Comment by lovisas** [comment]
Not auto selecting the first completion item is something that definitively should be fixed. I'll take a go at making the matching against historical expressions smarter as well.

**Comment by juliusv** [comment]
@lovisas Awesome, thanks!

**Comment by lovisas** [comment]
Let me know if this is blocking anyone/anything and I'll split up the work in two smaller PRs to get it through quicker!

**Comment by beorn7** [comment]
We could consider the current behavior a bug (even a regression as we had the same problem before and then reverted the advanced autocompletion) and then release a fix in 2.1.1.
Or we could just release 2.2 quite soon. As discussed earlier, we are not shy releasing frequently if it delivers some value.

**Comment by juliusv** [comment]
Yeah, I did mark this issue as a bug and consider it one (that really impacts Prometheus use), so doing a 2.1.1 soon would be a good idea.

**Comment by lovisas** [comment]
Did some investigation this morning - the autocomplete behavior is there by default. The query history checkbox is just changing what metrics you have available in the dropdown and otherwise it works the same as if you were to have the history unchecked. 

1) I could modify the dropdown for the expression browser so that it does not select the top metric when clicking enter. This could just be for when the checkbox is checked, but I'd argue the behavior should be the same regardless of mode. Fastest fix would be to disable the submission of the query when you hit `return`, but that might just make the situation worse.
2) The problem you bring up could potentially be solved by just making the matching algorithm smarter.

**Comment by paddynewman** [comment]
+1 for a 2.1.1 release soon.
