### ISSUE TITLE
Require helm on Prometheus understanding 

### ISSUE THREAD

**Issue by AnkitVaidya01** [prometheus/prometheus#3784]
#What I am trying to do?

**Comment by Gouthamve** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by krasi-georgiev** [comment]
that is the question of the year :smiling_imp:
