### ISSUE TITLE
Require help on Prometheus understanding 

### ISSUE THREAD

**Issue by AnkitVaidya01** [prometheus/prometheus#3785]
#What I am trying to do?
1) I am trying to get memory footprints of my application pods running in kubernetes the way I get in dynatrace?
2) How can I track request if my application microservice is calling another microservice internally?

@brancz @grobie @tomwilkie @matthiasr @jimmidyson@fabxc

Note :- posted this question on community but wont get any review hence posting it here. :-)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

It is not polite to tag developers for user questions, you should only tag people when you know this is their particular area.
