### ISSUE TITLE
Snapshots, backup and restore

### ISSUE THREAD

**Issue by Spritekin** [prometheus/prometheus#3838]
Hi,

This is a request for general guidance or at least improved documentation in the backup/restore area and the use of snapshots.

I have prometheus 2.0 running in AWS ECS as a service, all works fine except I don't have backups. If something forces me to destroy and recreate the instance then we will lose all the data.

I was testing using a separate volume to keep the data so if I change the instance the volume will be attached to the new instance and all should be fine. However while this solves the problem of the volume being destroyed if the instance is replaced, this still doesn't solve the backup problem because I would need to stop the instance to do an EBS Volume snapshot (otherwise the snapshot might be useless).

So, does anybody has a battle tested solution for prometheus backups and a plan for restore  a new instance from a backup?

Regards,
Guimo

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
