### ISSUE TITLE
Host down but state running

### ISSUE THREAD

**Issue by golimer** [prometheus/prometheus#3851]
prometheus, version 2.1.0
node_exporter 

http://localhost:9090/targets hosts are  DOWN but `__meta_ec2_instance_state` returning me state `running`

<img width="1411" alt="screen shot 2018-02-15 at 22 13 35" src="https://user-images.githubusercontent.com/10711881/36278790-8559c706-129d-11e8-958b-5bafb1d1cdb9.png">
Question: how to relabel as stopped if state is DOWN?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
