### ISSUE TITLE
Create Prometheus as Windows Service

### ISSUE THREAD

**Issue by lukibahr** [prometheus/prometheus#3881]
Hello everyone, 

i've downloaded prometheus for windows and can successfully start it whilst i'm logged in via RDS. 
To run it in background, i've tried to wrap a service around but starting it as a MS Windows Service failed. 

`sc.exe create prometheus_server binPath="PATH_TO_EXE\prometheus.exe --config.file=PATH_TO_CONFIG\prometheus.yml"`

After starting the service, prometheus runs for a short time, until (i guess) the service manager runs into a timeout because of a missing response of a successful start. 

My current environment 

- Windows Sever 2012
- prometheus-2.2.0-rc.1.windows-amd64
- sample/default config file

Do you have any solution for that? Thanks and kind Regards
Lukas

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by lukibahr** [comment]
Thanks alot!
Regards
Lukas
