### ISSUE TITLE
Move lifecycle/admin APIs to separate ports

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#3891]
I'd like to propose moving lifecycle and admin APIs to separate ports. Currently they are garded by boolean flags that enable them on the regular web port.
If one wants to enable them but still restrict access, e.g. to only give a sidecar on the same machine access to trigger reloads, one needs to add a reverse proxy with more complex rules.

It would be nice if we could allow such simple cases by simply not having those bits listen on external interfaces.

**Comment by brian-brazil** [comment]
I'm not sure we should be getting into adding authorization-related features that only work for specific users that happen to have a certain network model.

**Comment by fabxc** [comment]
This is not adding an authorization feature. It simply draws a boundary that's easier for people to build their authz stuff on.

**Comment by brian-brazil** [comment]
> And I don't think that listening on localhost is a "certain network model" that only a subset of users have.

All users on localhost being trusted is not a model everyone has.

**Comment by fabxc** [comment]
It is still much easier in the general case to overlay authorization on ports instead of of HTTP paths.  The latter are only accessible to tools that can introspect HTTP traffic in some way. So any mechanism using TCP proxies, iptables, or whatnot cannot be used.

Not providing authz is fine, but we should target for an approach which the highest number of tools can integrate with.

**Comment by brian-brazil** [comment]
> It is still much easier in the general case to overlay authorization on ports instead of of HTTP paths. 

Why privilege one set of APIs? Users may wish to limit the ways in which ways the query APIs can be used, and at the end of the day that implies something that understands HTTP.

**Comment by fabxc** [comment]
This is a much less likely use case though that wanting to limit access to the admin and lifecycle APIs, which everyone will want to do in some fashion.

**Comment by brian-brazil** [comment]
It'd still be offering at least two ways to do things, it's not maintainable to offer N different ways of doing things each of which is justified by it making some particular use case easier. That's why I want us to stick to one way of doing things, which users can build on top of rather than trying to accommodate everything out of the box.

**Comment by RichiH** [comment]
@brancz @csmarchbanks @roidelapluie @simonpasquier are you still interested in this?

**Comment by roidelapluie** [comment]
Personally I'd find that useful and helpful.

**Comment by csmarchbanks** [comment]
Is there still opposition to implementing this? Having separate admin ports has become a reasonably common pattern in other services.

**Comment by brian-brazil** [comment]
I oppose it still on the same basis. Why should we support port-based authorisation in particular, as against every other form of authorisation? Anyone who needs this can bind to localhost and use a reverse proxy, as with all other forms of authorisation.

**Comment by roidelapluie** [comment]
Because it will help a lot of users.

Enabling lifecycle makes sense, e.g. it is much more reliable than signals to reload configuration. But you can not do this without also enabling all the lifecycle apis, like the ability to shut down the process.

Yes reverse proxies can be an answer to that, but they are also an answer to the TLS issue, for which we have decided to move on an implement TLS. Why wouldn't we help our userbase by allowing this? It is not something that will cost us a lot.

**Comment by brian-brazil** [comment]
> Because it will help a lot of users.

Will it, or will they have even more requirements that mean they need to use a reverse proxy anyway?

> it is much more reliable than signals to reload configuration.

What's your thinking there? Signals are much simpler than network and can't be blocked by e.g. firewalls, and signals work everywhere other than Windows.

> It is not something that will cost us a lot.

All features have a cost. What happens for example if users want one set of tls settings for one port and one for another? What happens when the admin endpoints work sometimes on the main port and sometimes don't?

**Comment by roidelapluie** [comment]
> > Because it will help a lot of users.
> 
> Will it, or will they have even more requirements that mean they need to use a reverse proxy anyway?

This would not be mandatory.

> > it is much more reliable than signals to reload configuration.
> 
> What's your thinking there? Signals are much simpler than network and can't be blocked by e.g. firewalls, and signals work everywhere other than Windows.

Signals are asynchronous and don't have a return code.
HTTP request will return only when the configuration is reloaded with a corresponding status code (200/500).

> > It is not something that will cost us a lot.
> 
> All features have a cost. What happens for example if users want one set of tls settings for one port and one for another?

I did not say it would be free but I don't see any blocker there, just things we need to agree on.

> What happens when the admin endpoints work sometimes on the main port and sometimes don't?

What do you mean?

**Comment by brian-brazil** [comment]
> This would not be mandatory.

I don't see how that addresses my point, which is that the number of users asking for this feature is much bigger than the ones for whom it'd actually remove their need for a reverse proxy.

> What do you mean?

The goal of this feature request is to break the admin API on the main port. That'd cause non-trivial support issues I expect, particularly when things like the operator are added to the mix.

**Comment by bwplotka** [comment]
I think it's nice as a feature, but it will really add some extra complexity, as so far we only used to have one port.

Still, I think we are just 3 maintainers who try to decide on this. We need more feedback from the community. How many users actually need this? 1? 10? 100? I think this really would tell us what's the priority of adding this, no?  WDYT @roidelapluie @brian-brazil

**Comment by brian-brazil** [comment]
As poor as a measure it is, the number of reacts to the original issue is pretty low considering it has been open for 2 years and no user has chimed in. Users aren't clamouring for this, and it feels fairly niche overall.

**Comment by bwplotka** [comment]
I need to agree with @brian-brazil - not urgent need here. We might have higher priorities than this. I would close it for now.

**Comment by brian-brazil** [comment]
While I'm personally for closing, there's sufficient disagreement here that I think it would be premature to do so.

**Comment by roidelapluie** [comment]
I am biased on this because I actually would use this. Now where there is an incident I turn those API's on by restarting prometheus to snapshot TSDB or delete metrics. Quite an invasive procedure, but as our open id connect reverse proxy is not on the same machine this is more secure.

But I agree that not many user seem to want it so yeah we could close it.

**Comment by csmarchbanks** [comment]
I also vote to close this. I just wanted to see if anything had changed in the last couple of years and provide closure to this issue rather than a bump and then more radio silence.

I agree with @roidelapluie that I would personally use this feature, but it's not something I am heavily invested in.

**Comment by brian-brazil** [comment]
Looks like the consensus is for closing then.
