### ISSUE TITLE
Is there any tutorial/documentaion where i can find a detailed prometheus-cassandra integration ?

### ISSUE THREAD

**Issue by mkj-git** [prometheus/prometheus#3903]
I want to fetch and display cassandra cluster latency, storage cpacity and other details in my own custom ui graph.
Is there any tutorial/documentaion where i can find a detailed prometheus-cassandra integration ?

**Comment by brian-brazil** [comment]
https://www.robustperception.io/monitoring-cassandra-with-prometheus/

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
