### ISSUE TITLE
can i manual set metric's timestamp like influxdb？

### ISSUE THREAD

**Issue by yunhappy** [prometheus/prometheus#3910]
i want collect metrics by using application log time not now。can do it？

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
