### ISSUE TITLE
Support binary operators on different labels

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#393]
I have some cpu variables:
instance_mode:node_cpu:rate5m{mode="idle"} 8
instance_mode:node_cpu:rate5m{mode="user"} 10

and I'd like to divide them by:
instance:node_num_cpus:sum 2

and get as output:
{mode="idle"} 4
{mode="user"} 5

This currently won't work, I'd like to be able to do something like:

instance_mode:node_cpu:rate5m
  / MODIFIER by (instance, mode)
instance:node_num_cpus:sum

We need a modifier to tell us which operand is which for this behaviour. I'm thinking maybe pivot_left/pivot_right or group_left/group_right as modifier names, whatever we choose it must be obvious which is which.

**Comment by brian-brazil** [comment]
@fabxc pointed out that this syntax isn't quite right, and following discussion something more like `MODIFIER(mode) by (instance)` is what you'd want.

**Comment by fabxc** [comment]
Example: `group_left(type) by (handler)`

From which side should the `type` label be taken, assuming it is available on both and has different values on matching samples?
Trying either side and throwing an error if it is present on both would be an option. The latter because this is likely a mistake and it should be `group_left by (handler, type)`. Or using the the label/value from the left side and default to the right (thus dropping the right side if both are present.)

**Comment by brian-brazil** [comment]
That's incorrect usage as we're expecting type to only be on one side, so an error of some form would seem appropriate.

**Comment by juliusv** [comment]
Done by @fabxc in https://github.com/prometheus/prometheus/pull/554.
