### ISSUE TITLE
Kubernetes nodes scrape problems

### ISSUE THREAD

**Issue by felixPG** [prometheus/prometheus#3948]
Hi:

After working with a kubernetes cluster since 3 months with prometheus without problems, today scrape does not work in one node (master kubernetes node), is work for little metrics, an other metrics does not work.

Example:

For **kube_node_labels** metric the node appear to be scraped:

![node_labelok](https://user-images.githubusercontent.com/30522864/37297197-636b33d0-261d-11e8-9f5f-49c64bb5abb3.png)

But for **node_uname_info, node_boot_time, node_time** cant see the IP of the node, in this case, should be **192.168.133.17** for **ietsmartc09spre**

![node_timeko](https://user-images.githubusercontent.com/30522864/37297356-c67fe060-261d-11e8-8644-43cd4306ca20.png)

I dont know what happend with this, all was working ok until today!
Thanks in advance!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by felixPG** [comment]
I reply to myself, the issue was because I forget to taint the kubernetes master and the node-exporter pod was unable to run on a master node without taint!
