### ISSUE TITLE
Recursively search for alert rule files

### ISSUE THREAD

**Issue by bechtoldt** [prometheus/prometheus#3954]
I tried to specify a directory in the main config, which obviously isn't supported:

```
rule_files:
  - /etc/prometheus-alerts/
```

```
$ tree prometheus-alerts
/etc/prometheus-alerts
|-- team1/
|   `-- configmap1/
|       |-- alert1.yaml
|       `-- alert2.yaml
`-- team2/
    |-- configmap1/
    |   |-- alert1.yaml
    |   |-- alert2.yaml
    |   `-- alert3.yaml
    `-- configmap2/
```

**Comment by brian-brazil** [comment]
rule_files is a lost of files, not directories. You can use a glob in the filename though (but not the directories).

**Comment by bechtoldt** [comment]
@brian-brazil in this case I expect to be able to to specific something like:

```
rule_files:
  - /etc/prometheus-alerts/*/*/*.yaml
```

But golang's file globs doesn't support that. That's my issue, I don't know the actual list of directories that contain these files.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by bechtoldt** [comment]
I've started thread https://groups.google.com/forum/#!topic/prometheus-users/ExJbj-pX-es .
