### ISSUE TITLE
Query to get only value

### ISSUE THREAD

**Issue by AlexandrSemak** [prometheus/prometheus#3961]
Hi All,

Now i have full result of query:

`curl -g 'http://127.0.0.1:9090/api/v1/query?query=node_cpu{job="nodeexporter",mode="idle"}'`

Result:
`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_cpu","cpu":"cpu0","instance":"nodeexporter:9100","job":"nodeexporter","mode":"idle"},"value":[1521026325.616,"438579.55"]}`

Can i get only value?
for example smt like:

`query?query=(node_cpu{job="nodeexporter",mode="idle"}/value)`
or
`query?query=(node_cpu{job="nodeexporter",mode="idle"}[.value])`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
