### ISSUE TITLE
azure sd with public IP

### ISSUE THREAD

**Issue by Deshke** [prometheus/prometheus#3970]
**What did you do?**

trying to scrape azure instances with their public IP

**What did you expect to see?**
metrics

**What did you see instead? Under which circumstances?**
the current azure implementation https://github.com/prometheus/prometheus/blob/master/discovery/azure/azure.go#L38 does not allow for Public Azure IP's to be scraped thus every azure location/ ressource group would need their own prometheus instances 

* Prometheus version:
any

**Comment by cstyan** [comment]
do we have any azure credit or already running instances I can use to test this?

**Comment by dmitsh** [comment]
I suspect that you are unable to get the metrics because you haven't configured the NSG (Network Security Group) to accept traffic on the required port(s).
You may want to create an Inbound Security Rule for that purpose, either in the Azure Portal, or via command line:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nsg-quickstart-portal
https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest

I've verified this case by running the following steps:

1. Create a Ubuntu 18.04 VM in Azure cloud
2. SSH to the VM and install Prometheus Node Exporter
3. Add Inbound Security Rule to allow TCP traffic for port 9100
4. curl http://<Public IP>:9100/metrics

**Comment by Deshke** [comment]
nope, this got fixed with https://github.com/prometheus/prometheus/pull/5475  and this ticket just did not get updated.
