### ISSUE TITLE
Strange problem with hot-reloading of the config

### ISSUE THREAD

**Issue by cabrinoob** [prometheus/prometheus#3976]
Hi,
I'am running Prometheus (2.1) on a K8S cluster (1.8.6) unsing Calico CNI (2.6).

I have installed prometheus via Helm using this chart : https://github.com/kubernetes/charts/tree/master/stable/prometheus

I also installed Grafana and import some dashboards. But many of them show only partial data (I/O data and CPU data are missing)

But, if I upgrade the config and call prometheus:9090/-/reload data starts to appear in my dashboards, but after less than a minute it disappear again : 

![holes in chart](https://i.imgur.com/n43tPmv.png)

Do I miss something?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
