### ISSUE TITLE
i try to federate between two prometheus on two different servers. but its not working i just started learning Prometheus 

### ISSUE THREAD

**Issue by Akkadi** [prometheus/prometheus#3982]
when i try to run prometheus it does not run. my .yml file look like this. where 10.95.4.36:9090 is the IP of the second server where pormetheus is running already. 

global:
  scrape_interval:     1s   # By default, scrape targets every 15 seconds.
  evaluation_interval: 1s  # By default, scrape targets every 15 seconds.
  
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:

  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: /metrics
    
(how to collect the" prometheus_engine_query_duration_seconds_count" metric for example)

    target_groups:
      - targets: ['10.95.4.36:9090']

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
