### ISSUE TITLE
Upgrade : Is there a way to convert Prometheus 1.8x timeseries to 2.x

### ISSUE THREAD

**Issue by nightlynerd** [prometheus/prometheus#3984]
The Migration guide to 2.x states the following

"The data format in Prometheus 2.0 has completely changed and is not backwards compatible with 1.8. To retain access to your historic monitoring data we recommend you run a non-scraping Prometheus instance running at least version 1.8.1 in parallel with your Prometheus 2.0 instance, and have the new server read existing data from the old one via the remote read protocol."

The above ensures that I can upgrade to Prometheus 2.x without loss of data. However, I now have to run 2 instance of Prometheus. Which implies managing HA for each. Is there a way by which I could read the historical time-series in the non-scraping Prometheus 1.8x instance and convert it to a 2.x format. That way there is a bounded amount of time when I will have to run both versions. Eventually, all content gets converted to 2.x format and can be served by Prometheus 2.x

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
