### ISSUE TITLE
The vendored kubernetes client is completely obsolete

### ISSUE THREAD

**Issue by nim-nim** [prometheus/prometheus#4021]
Prometheus badly needs to resync its kubernetes vendoring.

It is still vendoring the kubernetes client 3.0 that was released in July 2017. Since then kubernetes started syncing their package versions, so the current client is 1.10.0 like kubernetes itself.

During all those releases numerous bugs and security issues were fixed.
Prometheus is building with Go 1.10; but kubernetes itself is not supporting Go 1.10 and will never support it for such ancient releases as 3.0 client. Prometheus needs to get closer to the current kubernetes  version to get a chance to be supported when Go 1.10 support ships in kubernetes.

**Comment by FUSAKLA** [comment]
There was a pull request to upgrade but was closed unfortunatelly
https://github.com/prometheus/prometheus/pull/3895

**Comment by krasi-georgiev** [comment]
yep that was, me it is too big of change and without a proper e2e test it is a bit like shooting in the dark. 

The request to the k8s api server are going through the wire so why would it matter what golang version is Prometheus and k8s  built on?

if anyone can test it in some staging environment and can confirm that it doesn't brake anything we might consider merging it. 
Otherwise if it is not in an immediate need than we are building a proper e2e testing CI which should be ready in few month and would be safer to merge after a proper testing.

**Comment by FUSAKLA** [comment]
I could test it in our staging env that shouldn't be a problem.
I'd be glad to get it merged so I can continue on the https://github.com/prometheus/prometheus/issues/3876.
After the upgrade to newer version of the k8s client it would be pretty straightforward to add those metrics.

Will you have the time to rebase it any time soon or should I rebase it by myself?

**Comment by krasi-georgiev** [comment]
rebased and attached file if you want to test it, or make a new build form my branch.
https://github.com/prometheus/prometheus/pull/3895
https://github.com/prometheus/prometheus/files/1859485/prometheus.zip

**Comment by FUSAKLA** [comment]
Great thanks
I'll try to deploy it asap

**Comment by krasi-georgiev** [comment]
any progress with the tests?

**Comment by FUSAKLA** [comment]
It's up and running and I didn't see any problems for the last 12 days.

Unfortunately I didn't have much spare time so I didn't get to any load testing (the staging environment is not saturated that much). 

Hopefully will get to that soon but as I said, it looks promising.

**Comment by krasi-georgiev** [comment]
no rush, it is best to test properly.

**Comment by simonpasquier** [comment]
Closed by #4336
