### ISSUE TITLE
avg() doesn't deal with NaN's

### ISSUE THREAD

**Issue by zemek** [prometheus/prometheus#4023]
If you try to run `avg(query)` on a query that returns some `NaN` values, the entire avg is `NaN`.

It seems like it would be reasonable to just exclude these NaNs from the average so you don't have to do like `avg(query >= 0)` or something more complicated if you want both positive/negative numbers.

**Comment by zemek** [comment]
and if you wanted to create an alert if query has `NaN` values, you would need to write a separate alert anyway like `query != query`

**Comment by brian-brazil** [comment]
This is the correct behaviour. You are most likely aggregating incorrectly and trying to take an average of an average, which is statistically invalid.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
