### ISSUE TITLE
histogram_quantile problem

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#4035]
prometheus 2.2.1
![image](https://user-images.githubusercontent.com/3970304/38181997-ed83806c-3668-11e8-9941-b0613df78a03.png)

why the result is decided by φ? obvious wrong result!     am i not using it correctly?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
