### ISSUE TITLE
Hard coded CMD in Dockerfile doesn't allow setting API flags

### ISSUE THREAD

**Issue by calston** [prometheus/prometheus#4042]
The Dockerfile sets a bunch of flags in the CMD set. This doesn't have --web.enable-admin-api.

Ideally this flag should also have a config file option. Does it? There's nothing I can find documented. 

Alternately a startup script could allow environment variables to set additional arguments.

Current situation with Docker seems to be "No admin API for you lol" unless you build a custom container

**Comment by brian-brazil** [comment]
Docker allows you to change the cmd at runtime.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
