### ISSUE TITLE
Can we have prometheus yml to be picked from HTTP?

### ISSUE THREAD

**Issue by jroshanfdo** [prometheus/prometheus#4123]
Instead of having to place the prometheus.yml on every host , is it possible to have it picked up from http endpoint ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
