### ISSUE TITLE
Prometheus is not able to talk 

### ISSUE THREAD

**Issue by shashank0033** [prometheus/prometheus#4138]
I tried it but from the prometheus (kubernetes POD)I am getting below error 

time="2018-05-03T17:38:31Z" level=warning msg="Error sending 100 samples to remote storage: server returned HTTP status 400 Bad Request: {"error":"proto: wrong wireType = 2 for field StartTimestampMs"}" source="queue_manager.go:500" time="2018-05-03T17:38:31Z" level=warning msg="Error sending 100 samples to remote storage: server returned HTTP status 400 Bad Request: {"error":"proto: wrong wireType = 2 for field StartTimestampMs"}" source="queue_manager.go:500" time="2018-05-03T17:38:31Z" level=warning msg="Error sending 100 samples to remote storage: server returned HTTP status 400 Bad Request: {"error":"proto: wrong wireType = 2 for field StartTimestampMs"}" source="queue_manager.go:500"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
