### ISSUE TITLE
Timezone-aware time functions

### ISSUE THREAD

**Issue by ktosiek** [prometheus/prometheus#4160]
## Proposal
I'd like to be able to silence/disable alerts based on local time. Some of the services I monitor have daily maintenance periods expressed in `Europe/Warsaw` time. Without timezone-aware functions I have to either use a wider silenced period, or change the rules twice a year.

The proposal is to add an optional timezone argument to date/time functions (`days_in_month`, `day_of_week`, `day_of_month`, `year`, `month`, `hour`, `minute`). Prometheus would still run on UTC, and only places explicitly using the timezone would change.

**Comment by brian-brazil** [comment]
I see how this might be useful for you. When adding these functions in #1545 we decided to avoid any timezone support in order to keep things simple and offer only UTC, which is now what we do throughout Prometheus as unfortunately timezones are rather complex and ever changing.

One thing you could do is take into account the month/day in your alerts, as within most countries the DST switchover dates are fixed.

**Comment by ktosiek** [comment]
Timezones are ever changing, but fortunately go can use the system timezone database. This way the tricky parts are offloaded to the OS (distribution of timezone information), the runtime (actually using that information), or the user (choosing the timezone for specific rules/queries).

For now I'll try modelling the one timezone I need as a recording rule.

**Comment by rigtorp** [comment]
I also need a way to suppress alerts during regular downtime windows. These downtime windows are generally related to a timezone. Maybe there should even be concept of time periods in the config file and each alert can be associated with a named time period. Nagios have something like that and it can be used to disable checks, suppress alerts and control alert routing.

**Comment by chrisob** [comment]
@brian-brazil 

> One thing you could do is take into account the month/day in your alerts, as within most countries the DST switchover dates are fixed.

Do you have an example of this? I've been toiling a bit trying to construct an alerting rule that can account for DST changes, but it seems like it might not be possible with PromQL.

**Comment by chrisob** [comment]
Hooo boy, I could be wrong... I came up with this monster which _seems_ to fit this usecase:

```
# Alert between 0700 and 1700, accounting for DST changes between CEST and CET
vector(1) 
and (
  # CEST (UTC+2:00)
  (
    (
      ( month() > 3 and month() < 10 )
      or
      ( month() == 3 and day_of_month() >= 31 )
      or
      ( month() == 10 and day_of_month() <= 27)
    )
    and hour() >= 5 < 15
    and day_of_week() > 0 < 6
  )
# CET (UTC+1:00)
  or (
    hour() >= 6 < 16
    and day_of_week() > 0 < 6
  )
)
```

**Comment by tine2k** [comment]
@chrisob Thanks for this. However, I believe the expression "month() > 10 < 3" is wrong. It should be ANDed, nor ORed to match both december and january. Please double check.

**Comment by roidelapluie** [comment]
Please see https://roidelapluie.be/blog/2017/11/09/prometheus-dst/

**Comment by roidelapluie** [comment]
Please see https://github.com/roidelapluie/prometheus-timezone-holidays

**Comment by gouthamve** [comment]
Hi during our bugscrub, we've decided that this is out of scope for PromQL. Please see the repo from Julien above and see if it solves your usecase? If not, please feel free to re-open it

**Comment by rvt** [comment]
It's the oddest thing...
there are loads of date/time libraries that are well supported and prometheus decides they feel it's not needed. That you don't need it doesn't mean other need it!

**Comment by rigtorp** [comment]
I agree it's really frustrating. I even wanted to implement this, but after reading this issue and others I became very discouraged from working on Prom since any new features seem to be out of scope. I also need to be able to enable/disable scrape targets based on a schedule and same for alerts. That was also considered out of scope. It seems that only monitoring a webapp backend is in scope any other usecase is unsupported.
