### ISSUE TITLE
--web.external-url breaks healthcheck to localhost

### ISSUE THREAD

**Issue by nazarewk** [prometheus/prometheus#4163]
I am pretty sure this is exactly the same as https://github.com/prometheus/alertmanager/issues/1382

**Comment by anthraxn8b** [comment]
This is interesting. In my case prometheus (2.2.1) healthcheck seems to work fine on localhost even if an external-url is set.

**Comment by nazarewk** [comment]
I'm using `stable/prometheus` with as little changes as possible (so yeah, vanilla containers)

**Comment by anthraxn8b** [comment]
@nazarewk, could you please try to set `--web.external-url=https://yourDomain/yourPathPrefix --web.route-prefix=/` to enforce the rout prefix not to be inherited by the web external url?
Also alter your healthcheck to point to `wget --quiet --spider http://localhost:9090/graph` to avoid being redirected to `yourPathPrefix` (this happens to serve the external url correctly - as far as it looks like the original request path is no longer taken into account if the web external url is set).
Please tell me if it worked! THX!

**Comment by brian-brazil** [comment]
This looks like a misunderstanding of how --web.external-url works so it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by anthraxn8b** [comment]
@brian-brazil, you are right, but this means you have to create another account on another platform - and if you believe in an issue this would be the right place ;-)
