### ISSUE TITLE
scheme: http，it is invalid

### ISSUE THREAD

**Issue by LionKiss** [prometheus/prometheus#4189]
**In the original**
  - job_name: 'kubernetes-apiservers'
    scheme: https
    kubernetes_sd_configs:
    - role: endpoints
    **scheme: http**
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    **regex: default;kubernetes;https**

**I modified it according to requirements：**
  - job_name: 'kubernetes-apiservers'
    **scheme: http**
    kubernetes_sd_configs:
    - role: endpoints
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    **regex: default;kubernetes;http**

**Still is https request**
kubernetes.go:268: Failed to list *v1.Endpoints: Get https://172.16.2.123:8080/api/v1/endpoints?resourceVersion=0: net/http: invalid header field value \"Bearer XXXXXX\\n\" for key Authorization"

**Comment by brian-brazil** [comment]
You shared a password in your report, I have edited it out however I strongly recommend rotating this password.

These are invalid configuration file, it should be rejected by Prometheus. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue, and include the exact configuration files including exact indentation. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by LionKiss** [comment]
Okay,thank you
