### ISSUE TITLE
http api query failed using '+' 

### ISSUE THREAD

**Issue by beijiaxu** [prometheus/prometheus#4199]
## Proposal
**Use case. Why is this important?**
need memory_uage metric (node_memory_MemTotal - (node_memory_MemFree + node_memory_Cached + node_memory_Buffers))

## Bug Report
**What did you do?**
use graph query and query http api
**What did you expect to see?**
metric value
**What did you see instead? Under which circumstances?**
graph query success but http api failed
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 79: unexpected identifier \"avg_over_time\" in paren expression, expected \")\""
}

**Environment**
CentOS 7.3

* System information:
Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version:
2.2.1

* Alertmanager version:

* Logs:
no log print in journalctl

While using graph query metric, I can see '+' is encoded to '%2B', I tried to replace '+' with '%2B', http api query succeeded.
But I use web console to encodeURI('+'), it doesn't encode this word.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
