### ISSUE TITLE
Netdata Instance naming

### ISSUE THREAD

**Issue by Mesmer88** [prometheus/prometheus#4204]
I'm trying to integrate multiple Netdata servers with Prometheus and then Grafana.
Problem is that Prometheus sees Netdata targets as IP:port  This makes it quite dificult to use variables in Grafana to select the server: trying to use hostname and not IP.

Is there any way to change how Prometheus defines the instance?
Noticed there was a similar issue for Kubernetes.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
