### ISSUE TITLE
Inquire a data in a SCALA-script

### ISSUE THREAD

**Issue by huiminzeng** [prometheus/prometheus#4298]
## Proposal
**Use case. Why is this important?**
Hello Team! I am wondering whether there is any possibility that i can inquire a data in a scala-script.
For instance, I want to run a script and this script will interact with an API of another application (for instance, userList API of Rocket.Chat). As a result, i could get a list of users, and i need to extract  the information of the users who are online. 
So basically, there is still an extra program which returns the quantity of online users. Can Prometheus inquire this data?
Or this is not implemented currently?

Thanks!

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
Ubuntu 16.04
* System information:

	Linux 4.4.0-128-generic x86_64

* Prometheus version:

	prometheus:v2.2.0-rc.0

* Alertmanager version:

	alertmanager:v0.14.0

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
