### ISSUE TITLE
Rule overview: Combine groups with same name

### ISSUE THREAD

**Issue by tom932** [prometheus/prometheus#4317]
## Proposal
My situation:
  - I have different alert rule-files for different user groups, so the groups can add their own alerting rules in their own files. 
  - Some of them have similar alert groups, e.g. each group performs blackbox-checks on their services. 
  - Therefore, each of the files contains a rule group `blackbox` with 1 to many alerts.

In the rule overview in the Web-UI, there are now several groups with the name `blackbox` (and others), each containing 1 to many alerting rules. It would be nice, if all those groups were combined to one group, due to the same name.

**Environment**

* System information:

	Prometheus is running in official docker container

* Prometheus version:

	v2.2.1 running in docker container

* Alertmanager version:

	Not relevant, since prometheus feature request

**Comment by brian-brazil** [comment]
I don't see a way to make this work. A key property of rule groups is ordering, and there's no clear ordering across groups from different files.
Another key property is isolation, that one slow rule group from one team doesn't affect other rule groups. By silently combining rule groups just because they have the same name, users would lose that benefit.

If you wish to combine rule groups together, this would be best done via configuration management on your end.
