### ISSUE TITLE
Prometheus returned error “server returned HTTP status 401 Unauthorized” for .NET core api

### ISSUE THREAD

**Issue by renjithseban** [prometheus/prometheus#4352]
I have a .NET core api hosted in IIS which uses windows authentication. I'm using Prometheus to scrape metrics from this API. But I'm getting the error "server returned HTTP status 401 Unauthorized" for the api target. Can some help me how to configure prometheus for targets with Windows authentication?

When I tried to browse the metrics path separately, the browser is requesting for credentials and I'm able to view the metrics with my Windows authentication.

**Comment by simonpasquier** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
