### ISSUE TITLE
Time zone problem

### ISSUE THREAD

**Issue by yokiy0828** [prometheus/prometheus#4364]
Hello, the UTC time used by Prometheus, and my local is CST, resulting in grafana unable to display the current CPU monitoring. How do I modify the time zone?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
