### ISSUE TITLE
avg()[5m] doesn't work

### ISSUE THREAD

**Issue by koupeng** [prometheus/prometheus#4406]
* Use Case *
avg(errorlog{domain="1"})
* What I want *
avg(errorlog{domain="1"})[5m]
I want the avg function allow aggregating  a given instant vector and return an range vector with 5 minutes

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development because `avg()` works only with range vectors. In other words, `avg(errorlog{domain="1"})` doesn't make sense since you need at least 2 datapoints to compute the average.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
