### ISSUE TITLE
inmemory Prometheus

### ISSUE THREAD

**Issue by szuecs** [prometheus/prometheus#4412]
## Proposal

As Prometheus user, that scrapes and queries only 1-5 minutes rate data, I would like to have the option to not save files and work fully inmemory, because the performance of Prometheus v2.2.1 in small Kubernetes clusters is not as I would expect. 

### Background
I deploy prometheus as statefulset with scrape interval 15s and have 1000m CPU and 4G memory set.
You can see the full configuration at https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/cluster/manifests/prometheus.

Monitor the monitor dashboard (Go metrics and Prometheus QPS and number of scrapes)
![image](https://user-images.githubusercontent.com/50872/43167810-4e577fc0-8f9b-11e8-9141-6b23a3dc0b11.png)

CPU metrics details
![image](https://user-images.githubusercontent.com/50872/43167838-708fe636-8f9b-11e8-9d3d-7f7bf604017a.png)

Memory metrics
![image](https://user-images.githubusercontent.com/50872/43168186-a2bab928-8f9c-11e8-8ea4-b82c7f96655f.png)

**Comment by brian-brazil** [comment]
With such a setup, everything is already in memory. This sounds more like a usage question so it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by szuecs** [comment]
https://groups.google.com/forum/#!topic/prometheus-users/2ECqkS0ZYKo
