### ISSUE TITLE
Dockerfile is not granular enough

### ISSUE THREAD

**Issue by swsnider** [prometheus/prometheus#445]
It would be a lot easier to work with the Dockerfile if the part where it downloads and compiles the Go toolchain was a seperate RUN step from the compilation of prometheus, since otherwise it attempts to download and build Go every. single. time. you. run. docker. build.

**Comment by juliusv** [comment]
@discordianfish

**Comment by discordianfish** [comment]
@juliusv That's due to the fact that we're using the Makefile so we're using the same path to build with and without Docker. I can change it to use the golang base image which would be benificial for all Docker uses because of faster build and better reuse of images, but you suggest you also try to build the Docker image each time you change something (should be possible with travis/done etc I guess?).

**Comment by juliusv** [comment]
@discordianfish Hmm, the Makefile currently takes care of some things you'd have to duplicate if you didn't use it:

- creating a build environment with the right Go version and right versions of vendored dependencies (via godeps)
- generating the `build.go` file with build information
- potentially regenerating other things, but those are usually checked in anyways (lexer/parser/asset/protobuf files)

Btw., Go is downloaded every time now, but it's already a built package, so it's not actually compiled.

Docker-newbie question: Would it be possible to split the Dockerfile into two RUN steps: 1) `make dependencies`, 2) `make build`?

:+1: to building the Docker image as part of a CI test.
