### ISSUE TITLE
Node lifespan alerting problem

### ISSUE THREAD

**Issue by RRadziejewski** [prometheus/prometheus#4455]
## Proposal
Hello my nodes have lifespan of 1000 hours after this i have to change it.
Currently i think it's easy to make alert when node is up 1000 hours but that's not the case.
Because nodes can be restarted and in this way the lifetime would be set to 0.
Can some one help me with achieving a solution for this ?
Or when can i look for answers if it's not a right place ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
