### ISSUE TITLE
Prometheus Golang Dependency Resolution

### ISSUE THREAD

**Issue by swtch1** [prometheus/prometheus#4468]
## Bug Report
**What did you do?**
I tried to use [dep](https://github.com/golang/dep) to resolve dependencies, and also tried to use [go modules](https://research.swtch.com/vgo-module) with the [go1.11 beta 3](https://golang.org/dl/#go1.11beta3) to get the code.  

In trying to use Prometheus as a library (using data structures and methods for [config](https://github.com/prometheus/prometheus/blob/master/config/config.go) and [rulefmt](https://github.com/prometheus/prometheus/blob/master/pkg/rulefmt/rulefmt.go) validation) I am seeing several libraries whose code only exists within the [prometheus/vendor](https://github.com/prometheus/prometheus/tree/master/vendor) folder. These are the primary examples:

- github.com/Azure/azure-sdk-for-go/arm/compute
- github.com/Azure/azure-sdk-for-go/arm/network
- k8s.io/client-go/pkg/api
- k8s.io/client-go/pkg/api/v1
- k8s.io/client-go/pkg/apis/extensions/v1beta1

The crux of the issue is that this doesn't work:
`go get github.com/Azure/azure-sdk-for-go/arm/compute` which is a dependency.

**What did you expect to see?**
I expected for dependencies in prometheus/vendor to be externally resolvable.

**What did you see instead? Under which circumstances?**
I saw that these dependencies are not resolvable and do not exist, as far as I can tell, outside of the prometheus/vendor directory.

**Environment**
Windows 10 x64

* System information:

	[MINGW64_NT-10.0 2.10.0(0.325/5/3) x86_64](https://gitforwindows.org/)

* Prometheus version:

	prometheus 2.3.2

#### General Question
This code is not obviously prometheus specific.  Does this code in fact exist somewhere else that I can effectively resolve?

**Comment by juliusv** [comment]
This is why we vendor - because external dependencies can change vanish at any time ;)

For example, the `github.com/Azure/azure-sdk-for-go/arm/compute` package does exist, but in that repository, the current master version does not contain that package anymore. However, it still exists at the revision we vendored it at (the revision is in `vendor/vendor.json`): https://github.com/Azure/azure-sdk-for-go/tree/bd73d950fa4440dae889bd9917bff7cef539f86e/arm/compute

You could vendor it at the same revision using `dep` by putting a revision constraint into your `Gopkg.toml` file. I haven't played with Go modules yet.

**Comment by juliusv** [comment]
Closing this as it seems to be answered and is not a Prometheus issue. Please reopen if you think this was a mistake.
