### ISSUE TITLE
delta(risk_gateway_count[5m]) why value is double? shouldn't be int?

### ISSUE THREAD

**Issue by leejones92** [prometheus/prometheus#4483]
`"metric":{
                    "bizMethod":"m.api.risk.magic.tags",
                    "code":"0000",
                    "fee":"Y",
                    "handler":"RiskGatewayController.riskGateway",
                    "httpMethod":"GET",
                    "instance":"10.29.180.203:4089",
                    "job":"monitor_interfaces",
                    "msg":"操作成功",
                    "path":"/risk-gateway/api/gateway",
                    "status":"200",
                    "success":"true",
                    "tenantId":"991"
                },
                "value":[
                    1533780998.959,
                    "8.187257142857142"
                ]
                }`

 "8.187257142857142" ? why is zhis value? maybe it should be 8

**Comment by leejones92** [comment]
and "8.187257142857142" what's its unit?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by leejones92** [comment]
oh,sorry,ths u
