### ISSUE TITLE
Feature request : variation value

### ISSUE THREAD

**Issue by sachaarbonel** [prometheus/prometheus#4504]
## Proposal
**Use case. Why is this important?**

Hi guys great project :) I'm using prometheus collectors and prometheus to create alerts on financial data and the variation is quite useful to calculate the percent change of a value. I've implemented here https://github.com/Sach97/prometheus/tree/percent-change it needs some work as I've never programmed in go before but it doesn't change a lot from idelta. Let me know your suggestions / concerns and I'll make my pull request accordingly.

**Comment by brian-brazil** [comment]
Thanks for your PR. This seems like a fairly niche use case outside of our scope. It would be quite susceptible to noise, and we also encourage alerting on state rather than transitions, as it's more resilient generally.

I'm presuming you have completely regular data, could you use something like `idelta(x[1m]) / x offset 1m` or `idelta(x[1m]) / (x - idelta(x[1m]))` ?

**Comment by Sach97** [comment]
I did'nt see the offset in the documentation and it does the job thank's or the hint
