### ISSUE TITLE
Configure Prometheus to send a seperat message for every "Label"...

### ISSUE THREAD

**Issue by ManCon** [prometheus/prometheus#4531]
Hi

I think it is not a issue. It is just a question for the Prometheus configuration.
I have installed Prometheus and it works fine.

But in my case I like to receive for every "Label" a own "eMail".

For example:
3 Servers have a high CPU load.
At the moment I get one eMail with the information about the 3 servers who have the problem.

But:
I like to receive for every Lable a own eMail. (In this case separate 3 eMails)

How can I configure the Prometheus so that I get for every "ISSUE" a separate message? 

Thanks in advance

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
