### ISSUE TITLE
Unable to get http_requests_total metrics from latest version of the images

### ISSUE THREAD

**Issue by arunkumarmurugesan** [prometheus/prometheus#4540]
## Proposal
**Use case. Why is this important?**
*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**
I have tried to configure the k8s HPA using Prometheus http_request metrics. 

**What did you expect to see?**
Here the issue is, I can able to get the http_request metrics from Prometheus image v2.1.0. When pulled the latest version. i could not able to get the http_request metrics.
**What did you see instead? Under which circumstances?**

**Environment**
PROD
* Prometheus version:
Latest Versions: v2.3.1 and v2.3.2 (not getting the http_request metrics)
Old Version: v2.1.0 (getting the http_request metrics)

Please let me know how I can get the http_request metrics exposed from the latest version of Prometheus?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
