### ISSUE TITLE
How Prometheus server will collect counters (metrics)form application(if two instances of an application are running)

### ISSUE THREAD

**Issue by karunchinna** [prometheus/prometheus#4552]
hi team,
i have some Prometheus counter metrics from an application. and in Kubernetes i made two instances(pods) an application. now Prometheus Server is not collecting form two pods. it is collecting only form one Pod.  how to solve this issue.

thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by karunchinna** [comment]
thanks. i posted in prometheus-users mailing list.
