### ISSUE TITLE
why do i get different numbers of values using page queries and api queries?

### ISSUE THREAD

**Issue by ckyx** [prometheus/prometheus#4618]
i have a metric named 'test'  with  a  scrape_interval : 2s .  and  i get differrent numbers of values when using page queries and api queries .

like this "test[30s]" , i get only 3 values when using page queries but get 15 values when using api queries . 

Why do I get different numbers of values ​​using page queries and api queries?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
