### ISSUE TITLE
Prometheus Community Slack Channel

### ISSUE THREAD

**Issue by simplytunde** [prometheus/prometheus#4718]
## Proposal
**Use case. Why is this important?**
This is a community channel for those who are heavy on slack where you get support on questions and also discuss events going on in prometheus ecosystem. To join on slack, go to https://joinprometheus.herokuapp.com/

**Comment by gouthamve** [comment]
Well, while a community Slack would be good, we already have a platform, i.e, IRC / Riot, see: https://prometheus.io/community/ that we're not fully able to keep up with. Adding another platform would only add to the confusion.

**Comment by beorn7** [comment]
AFAIK Slack has become a walled garden like all the other IM silos.
I don't see any place for it in support of open-source communities.

**Comment by beorn7** [comment]
I think Kubernetes and Gophers Slack should have been switched off the moment Slack dropped the IRC gateway and XMPP support.

See also https://drewdevault.com/2015/11/01/Please-stop-using-slack.html , which was written at the time when the IRC gateway still existed.

**Comment by gouthamve** [comment]
Further, we do have a public slack-channel (#prometheus) in the CNCF slack: cloud-native.slack.com But it is disfunctional and any requests there are ideally routed to existing channels. If you'd like to lead a community slack group, it should ideally be that channel which already exists instead of a new Slack altogether.

re: channels, we don't see the big need for channels per-se as the IRC discussions we see rarely overlap on topics to need channels.

re: Helping and answering people, keeping up with just IRC and mailing list itself is hard for us and adding Slack to it is not something we are keen on. 

I am now going to close this issue but if you still think there is a potential scope for a slack channel, please feel free to open a thread on `prometheus-users` mailing list as that is a better forum for this.
