### ISSUE TITLE
Multiplication between two series returns no values

### ISSUE THREAD

**Issue by rmeleromira** [prometheus/prometheus#4729]
## Bug Report
**What did you do?**

Try to multiply two time series.

**What did you expect to see?**

The first value multiplied by the second value and then a final value.

**What did you see instead? Under which circumstances?**

I get no records back, if I hard code the multiplication it works.

**Environment**

* System information:

```
root@monitoring:~# uname -srm
Linux 4.4.0-130-generic x86_64
```

* Prometheus version:

```
root@monitoring:~# prometheus --version
prometheus, version 2.4.3 (branch: HEAD, revision: 167a4b4e73a8eca8df648d2d2043e21bdb9a7449)
  build user:       root@1e42b46043e9
  build date:       20181004-08:42:02
  go version:       go1.11.1
```

* Alertmanager version:

```
root@monitoring:~# alertmanager --version
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```

First query
```
secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}
```
output
```
0.0492
```
Second query
```
zen_usd_price{instance="localhost:7981",job="secure_nodes_exporter"}
```

output 
```
13.64
```

Multiplication
```
zen_usd_price{instance="localhost:7981",job="secure_nodes_exporter"}*secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}
```

No results

Hard coding the multiplication works
```
secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}*13.6
```

output
```
0.6691199999999999
```

**Comment by henridf** [comment]
You have no results because the two metrics have different names, so there is no pair of entries that matches. Try something like 

`zen_usd_price{instance="localhost:7981",job="secure_nodes_exporter"} * ignoring(__name__) secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}`

or 
`zen_usd_price{instance="localhost:7981",job="secure_nodes_exporter"}* on(instance, job) secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}`

Matching is described in detail here: https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching

**Comment by simonpasquier** [comment]
Label names need to match on both sides, use `ignoring`/`on` to specify on which labels you want to join:
```
zen_usd_price{instance="localhost:7981",job="secure_nodes_exporter"} * ignoring(instance) secure_nodes_last_earn{instance="localhost:7980",job="secure_nodes_exporter"}
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
