### ISSUE TITLE
Proposal: expose `/api/v1/write` enpoint for remote_write storage API

### ISSUE THREAD

**Issue by valyala** [prometheus/prometheus#4769]
## Proposal

Sometimes is is useful to have a single big Prometheus instance with all the data from other Prometheus instances located in different networks / datacenters.

## Solution
The most straightforward solution for this use case is to expose `/api/v1/write` endpoint for [remote_write storage API](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations) on the big Prometheus instance, so other instances could write to it using remote storage protocol.

**Comment by semyonslepov** [comment]
Have you tried Prometheus federation mechanism for this purpose yet?

**Comment by semyonslepov** [comment]
I'm not sure if anybody goes to allow direct writing to Prometheus TSDB apart from Prometheus server on the same machine itself and it seems as quite a bad idea to me too.
What might work as a workaround - set up all the Prometheus servers writing via `remote write` to a local TSDBs (InfluxDB, CrateDB, whatever) and then set up writing data from that "small" TSDB instances to a "single big" one. So, "single big" Prometheus will have access to all this data in the "single big" TSDB via `remote read`.

**Comment by valyala** [comment]
There is another use case for the exposed remote write API - seamless integration of push model via external adapter service that can collect metrics in various popular formats such as [InfluxDB's line protocol](https://www.influxdata.com/blog/influxdb-internals-101-part-one/), [various Graphite formats](https://graphite.readthedocs.io/en/latest/feeding-carbon.html) and formats based on message queues.

**Comment by juliusv** [comment]
Hi, this is basically a request for adding push support to Prometheus, which has come up a lot in the past, and which we've been very careful about so far.

First, a bit of background why push support hasn't been added yet to Prometheus so far: Prometheus is primarily a pull-based monitoring system (which just happens to include a TSDB, but we don't see Prometheus as a TSDB primarily), several of its core features assume that the server is in control of scraping metrics and attaching timestamps at its own configured pace. For example, recording and alerting rules are evaluated based on the server's notion of the current time. So the underlying metrics must arrive in lockstep with rule evaluations, which is best ensured with a pull model. Service discovery integration (with target metadata attaching etc.) and automatic target health monitoring are other features that rely on the pull model. So if we added a push endpoint and advertised it loudly, we would be worried that many users who don't know 100% what they are doing would shoot themselves in the foot, thinking that Prometheus supports "push" now.

However, I started a rough discussion doc a long while back about pros/cons of adding push support to Prometheus: https://docs.google.com/document/d/1H47v7WfyKkSLMrR8_iku6u9VB73WrVzBHb2SB6dL9_g/edit#heading=h.2v27snv0lsur

The consensus at the last dev summit was to add an item to the Prometheus roadmap to only allow backfilling of entire time series (not appending individual samples like via remote write): https://prometheus.io/docs/introduction/roadmap/#backfill-time-series

And yeah, in the originally described case, federation is the usually adopted architecture, which does require making individual Prometheus servers reachable from the central one.

**Comment by juliusv** [comment]
> And yeah, in the originally described case, federation is the usually adopted architecture, which does require making individual Prometheus servers reachable from the central one.

I need to qualify that comment: federation is *not* recommended for transferring *all* data from one Prometheus server to another, as neither the source TSDB is optimized for that, not is it resource-efficient to do single humungous scrapes. It's more meant to transfer over a select set of aggregated series in the thousands, not in the millions. So unless the data that needs to be federated into the global Prometheus server is small-ish, there is indeed no great solution for this at the moment with Prometheus. Mind you, remote write is super inefficient resource-wise too, though.

Maybe you are rather looking for something like [Thanos](https://github.com/improbable-eng/thanos), which gives you a global view, long-term storage, while being efficient at the transfer of large amounts of data too (much more so than remote write or federation).

**Comment by bwplotka** [comment]
To sum up, if you use Prometheus to push its metrics via remote write to another Prometheus (not possible, but requested in this issue) or some LTS storage, this is still *pull* model, because what matters is how data were collected, right? (: 

So if I understand this right, the main blocker for adding this one is to avoid *abuse* and pushing arbitrary samples from other non-pull collectors? (which is fair point)

I'm asking as we consider adding remote write receiver endpoint for Thanos system: https://github.com/improbable-eng/thanos/pull/659 and we need to educate users which one to choose (sidecar +  query for  fresh data) or remote write.

**Comment by bwplotka** [comment]
> You are effectively treating it as a TSDB mainly then, not a monitoring system first. 

Yup, totally agree.

**Comment by valyala** [comment]
> Mind you, remote write is super inefficient resource-wise too, though.

Why? From my experience it works quite well for Prometheus scraping 50K-100K samples/sec. Probably, it must be optimized somehow for Prometheus scraping millions of samples per second?

**Comment by juliusv** [comment]
@valyala On the sending side, remote write totally blows up memory usage (or at least used to, not sure about the current state of optimization) because normally sample ingestion is a very highly memory-tuned process that avoids allocations as much as possible, appends samples into the TSDB using internal TSDB series IDs when possible (rather than storing full label sets for every sample), etc. For remote write, every sample has to be re-encoded, buffered, and then sent over the wire in its fully expanded form, in protobuf format, in near-time (instead of larger compressed batches). In contrast, Thanos just ships completed (and very well-compressed) on-disk blocks, which requires much less memory memory and other resources.

I'm actually glad to hear that remote write still works well for you with 50K-100K samples/sec. I'd be curious to hear how much the same Prometheus server would use if you turned remote write off.

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub and @juliusv's responses already appear to cover it.

**Comment by valyala** [comment]
It looks like this issue must be re-opened according to https://twitter.com/TwitchiH/status/1339665862949826563 . See more details at https://docs.google.com/document/d/1iO1QHRyABaIpc6xXB1oqu91jYL1QQibEpvQqXfQF-WA/edit .

**Comment by RichiH** [comment]
Similarly to how we do not **demand** you take any particular action in your GitHub org, please refrain from **demanding** any particular action in our GitHub org.

Simply enabling an end point is not design; as per the document you linked, we will be working within a design doc first to come to a holistic solution which follows Prometheus design principles.

**Comment by roidelapluie** [comment]
#8307 is open ; any positive feedback is welcome.
