### ISSUE TITLE
Labels are overwritten even if honor_labels set to true

### ISSUE THREAD

**Issue by lgogolin** [prometheus/prometheus#4782]
## Bug Report
**What did you do?**

Having 2 prometheus instances:
1) instance in us-east-1 region with external_labels set:

```global:
        external_labels:
          project: monitoring
          region: "us-east-1"
```

2) instance in eu-central-1 region with external_labels set:

```global:
        external_labels:
          project: monitoring
          region: "eu-central-1"
```

Instance no.2 has also configured federate job, that scrape us-east-1 region prometheus.

```scrape_configs:

      - job_name: 'federate'
        scrape_interval: 15s

        honor_labels: true
        metrics_path: '/federate'

        params:
          'match[]':
            - '{__name__=~".+"}'

        static_configs:
          - targets:
            - 'prom-monitoring.us-east-1.domain.name'
```

**What did you expect to see?**

Metrics with both labels:
```
region="eu-central-1"
``` 

and

```
region="us-east-1"
```

**What did you see instead? Under which circumstances?**

All metrics have label 
```
region="eu-central-1"
```

 even those from us-east-1

* Prometheus version:

```
prometheus, version 2.4.3 (branch: HEAD, revision: 167a4b4e73a8eca8df648d2d2043e21bdb9a7449)
  build user:       root@1e42b46043e9
  build date:       20181004-08:42:02
  go version:       go1.11.1
```

**Comment by brian-brazil** [comment]
> All metrics have label

Where exactly are you seeing this? I'd expect to see us-east-1 and no value.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
