### ISSUE TITLE
CentOS 7 docker prometheus volume error "open /prometheus/lock: permission denied"

### ISSUE THREAD

**Issue by zhangjie2012** [prometheus/prometheus#4805]
I want mount `/prometheus` to host path `/data/prometheus`，so I create container like this: 

`docker run -it -d -p 9090:9090 --restart=always -v /data/prometheus:/prometheus -v /data/conf/prometheus.yml:/etc/prometheus/prometheus.yml docker.io/prom/prometheus`

start failure, docker logs show :  

```
...
 err="opening storage failed: lock DB directory: open /prometheus/lock: permission denied"
```

I had change host `/data/prometheus` dir owner and group to `nobody:nobody`.

**Comment by simonpasquier** [comment]
You are probably hitting the issue because of SELinux. See https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by zhangjie2012** [comment]
I had fix it.

1. create a `prometheus` container , `cat /etc/passwd` => `nobody:x:65534:65534:nobody:/home:/bin/false`
2. host set `/data/prometheus` owner and group to `65534`
