### ISSUE TITLE
Treat empty labels like unset labels

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#494]
`{x=""}` should return any time series which don't have the `x` label set, as well as series where it's empty. Optionally, we may also decide to drop empty labels completely upon ingestion. This makes it possible to find time series that don't have certain labels set at all (useful in rare cases for finding certain metrics), but also is more consistent with the syntax for unsetting labels on the left-hand-side in recording rules (by setting a label to empty, it is unset).

**Comment by fabxc** [comment]
Probably `{}` should be a valid query in that case. Otherwise hackish stuff like `{_=""}` is introduced to retrieve all time series.

**Comment by brian-brazil** [comment]
I'd overall prefer a hackish stuff to retrieve all time series. It's an advanced use case, and a great way to take out a prometheus server.

**Comment by fabxc** [comment]
Mh, at least have a label name that is guaranteed to be always unset? Probably the case for `_` anyway but it should be explicitly agreed on.

**Comment by brian-brazil** [comment]
{job~=".*"} will do it.

**Comment by fabxc** [comment]
Sure, under the whole "only if you know what you are doing assumption" this seems fair as well.

I would give this one a go. As far as I can see one needs to check all archived and in-memory series? Or did I overlook a better way?
I don't have enough background knowledge to judge the performance impact of this. It would iterate over the whole `archivedFingerprintToMetrics` index once.

**Comment by beorn7** [comment]
Recent discussions: Match for unset labels will be _very_ slow to process in a query. Not sure how much effort we should invest into making it faster.

But even if we do not allow the querying for unset labels, we should finally implement throwing away labels with empty values before storing and indexing them (but _after_ the whole relabeling shebang that happens during scraping, so that empty label values can be used to prevent auto-attaching labels).

**Comment by fabxc** [comment]
Closed via #810 with the limitation of requiring one or more matchers not matching the empty string.
