### ISSUE TITLE
how to clean up disk space

### ISSUE THREAD

**Issue by jackerzhou** [prometheus/prometheus#4960]
prometheus 1.6 ，Disk space is currently full，I try to shorten the time for storage.local.retention，but Disk space is not freed

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
