### ISSUE TITLE
Feature Request: Config resyncPeriod for kubernetes_sd_configs

### ISSUE THREAD

**Issue by pulord** [prometheus/prometheus#4984]
## Proposal
**Use case. Why is this important?**

We want get node target quickly after new node join cluster, but the [resyncPeriod](https://github.com/prometheus/prometheus/blob/56cda567d9ea68237900615ef756778d8f773133/discovery/kubernetes/kubernetes.go#L256) can't be config by ourself

Prometheus Can afford the way that change or update resyncPeriod for kubernetes_sd_configs?

**Comment by JensErat** [comment]
Prometheus uses client go's informers, which actually do a watch on the API server (compare with `kubectl get --watch`). Prometheus should get updates on new nodes with barely any latency.

In fact, `resync` of client go does (since some years) not even talk to the API server any more, but just sent all known objects again (in this case, to Prometheus). So this would only help if Prometheus would lose information on objects.

This might be a valid feature request for other reasons (I'm currently investigating how the resync period breaks monitoring of a successful service discovery), but changing the resync period will not help with the described use case, this should be pretty much live already anyway.

**Comment by bboreham** [comment]
Agreed, we don't want to do this because it has no useful effect.
