### ISSUE TITLE
Failed to start Prometheus

### ISSUE THREAD

**Issue by janeunbi** [prometheus/prometheus#5040]
I was trying to start the Prometheus but it doesn't work. However, it works two days ago.
SO, I don't think it's a conf file problem. 
If I try to turn on the service, it turns on for a second but it turns off automatically.
![image pasted at 2018-12-26 09-56](https://user-images.githubusercontent.com/46011780/50428557-f31ba700-08fb-11e9-86ad-a1aa8ecf11e8.png)
 

I expect to run the service!

Here's the version of my system and prometheus
![version](https://user-images.githubusercontent.com/46011780/50428531-c10a4500-08fb-11e9-82e1-7af077beeb56.PNG)

These are the prometheus.yml and prometheus.service files.
![prometheus yml](https://user-images.githubusercontent.com/46011780/50428572-23634580-08fc-11e9-87e1-b0afaaed1be2.PNG)
![prometheus service](https://user-images.githubusercontent.com/46011780/50428573-24947280-08fc-11e9-8fe0-a22896e409bc.PNG)

Here's the logs.

![logs](https://user-images.githubusercontent.com/46011780/50428649-ac7a7c80-08fc-11e9-9a41-7225b8030e1c.PNG)

Please let me give your hands.

**Comment by dannyk81** [comment]
The log screenshot that you've shown indicates that prometheus is unable to to red/access the specified configuration file.

The log line is truncated since `journalctl` doesn't wrap long lines by default (either use `|less` or set the `--no-pager` flag when running `journalctl`)

This really doesn't seem like a Prometheus issue, probably better to head over to the Prometheus user group for further assistance: https://groups.google.com/forum/#!forum/prometheus-users

**Comment by simonpasquier** [comment]
The last group (starting with `#docker`) in your Prometheus configuration file isn't properly indented. You can use the `promtool` binary to check your configuration file beforehand.
