### ISSUE TITLE
Make it run on MS Windows.

### ISSUE THREAD

**Issue by haroonabbasi** [prometheus/prometheus#505]
i tried to make a build but i got error. image attached.
![error_on_build](https://cloud.githubusercontent.com/assets/1297226/6060752/4fd394ca-ad62-11e4-8bb4-abf51812cc80.png)

**Comment by beorn7** [comment]
See https://github.com/prometheus/prometheus/issues/503 - in short, we haven't anticipated the different ways an architecture manifests in the Makefile vs. how the Go download addresses look like.

In different news, never has ever tried Prometheus on Windows. You'll probably run into other issues, too.

**Comment by juliusv** [comment]
Just one more Unix-specific thing I'm aware of that won't work on Windows at the moment: if you're using service discovery to discovery your targets (vs. statically configuring them), we currently hard-code `/etc/resolv.conf` as the resolver configuration: https://github.com/prometheus/prometheus/blob/master/retrieval/target_provider.go#L33

**Comment by beorn7** [comment]
Let's use this issue as a catch-all for things that need to be done for a Windows port.

(We are completely dependent on external contributors here, though. I don't think any Windows machines exist at SoundCloud...)

**Comment by juliusv** [comment]
@haroonabbasi Given that https://github.com/prometheus/prometheus/issues/503 was fixed now, it would be interesting to hear whether that also fixes the Go download step for you on Windows, and whether you encouter any more errors further down the line.

**Comment by etishor** [comment]
:+1: for having a timeseries db running on windows.

**Comment by juliusv** [comment]
@etishor please help us test it :)

**Comment by etishor** [comment]
Working on it :) cloned and trying to build on windows. I'm familiar with windows & unix dev environments, but i'm not familiar with go. Also "make" on windows...

As a side note, i'm looking for a good place to store data from my [Metrics project](https://github.com/etishor/Metrics.NET) and I hope prometheus can be that place.

**Comment by brian-brazil** [comment]
As an aside, if you have a working Python environment on Windows if you could verify the fix in https://github.com/prometheus/client_python/pull/28 that'd be great.

**Comment by smyrman** [comment]
One thing that would make cross-platform easier, is if you got rid of the Makefile, as that would get rid of a lot of unneeded dependencies. You could keep it for internal usage of course, but It would be better for everyone if you cold simply install with:

     $ go get -u github.com/prometheus/prometheus/...

For commit db4df06414c2c602bd60bf28f4ec0242d11949f3, I tried to do some experiments with building prometheus on Windows:

`make build` fails on "hostname -s":
```
$ make build
sethostname: Use the Network Control Panel Applet to set hostname.
hostname -s is not supported.
```

This is the same result as:
```
$ HOSTNAME.EXE -s
sethostname: Use the Network Control Panel Applet to set hostname.
hostname -s is not supported.
```

I can set the hostname, and solve this buy editng Makefile.INCLUDE to call "hostname" without any parameters. However, ther are some aditional problems for me at lest, trying to use make:
```
"c:\ProgramData\chocolatey\lib\make\tools\bin\make.exe": Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
```
I don't blame you for this, obviously if make was installed correctly, this _should_ not have happened...

Anyway, I tried building without a Makefile, to see how much needed doing to get that working.

````
$ cd $GOPATH/src/github.com/bin
$ go get -u ./...
$ go install ./...
# github.com/prometheus/prometheus/util/flock
util\flock\flock_windows.go:22: undefined: windowsFileLock
# github.com/prometheus/prometheus/web/blob
web\blob\blob.go:30: undefined: files
```
For line 22, I presume you really meant to say "windowsLock"', so I change the code a bit.
For the error in blob line 30, I realized you used a shell-script to generate static files. Trying to run this through bash however, I discover that xdd is not present on windows, and I didn't find it as a package on "Chocolately" (some windows package manager I stumbled upon).

So as a next step, I wrote some go:generate code using https://github.com/jteeuwen/go-bindata instead of your shell scrip. Please see:

https://github.com/prometheus/prometheus/pull/782

**Comment by fabxc** [comment]
Anyone knows about the status of this – or has a system to test it? @juliusv

**Comment by juliusv** [comment]
I do have a Windows for games lying around, but haven't tested it yet. I can give it a try sometime...

**Comment by brian-brazil** [comment]
Per @matthiasr on https://groups.google.com/forum/#!topic/prometheus-developers/ssKrXbSFlkE Prometheus works on Windows!
