### ISSUE TITLE
how to monitor processes within docker with prometheus

### ISSUE THREAD

**Issue by deep7710** [prometheus/prometheus#5070]
I want to monitor all process running with my docker container using prometheus. I have tried cadvisor but it only gets in stats pertaining to the container. I want to monitor all processes running inside my container.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
