### ISSUE TITLE
ec2_sd_config metrics_path not supported

### ISSUE THREAD

**Issue by paulca99** [prometheus/prometheus#5073]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by paulca99** [comment]
ec2_sd_config metrics_path not supported.

Using spring boot with the prometheus actuator.  Our endpoint is on /prometheus.  But the service discovery uses /metrics and cannot be changed.  Spring boot reserves /metrics for its own use.

**Comment by simonpasquier** [comment]
The EC2 service discovery has nothing to do with the scrape configuration. Your configuration is probably buggy. Otherwise if you want to override the metrics path through `relabel_configs`, the label name to use  is `__metrics_path__`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
