### ISSUE TITLE
Subtracting histogram buckets returns "No datapoints found."

### ISSUE THREAD

**Issue by elerer** [prometheus/prometheus#5118]
**What did you do?**

dns_latency_bucket{le="30.0"} - dns_latency_bucket{le="10.0"}

**What did you expect to see?**

The per bucket count i.e. query above, is the count of distinct value that fit the bucket (10-30]

**What did you see instead? Under which circumstances?**

"No datapoints found."

Each query (i.e. dns_latency_bucket{le="30.0"} ,   dns_latency_bucket{le="10.0"}) gives me a time series values

**Comment by hoffie** [comment]
You probably need to ignore the `le` label. Otherwise, Prometheus tries to match it:
https://prometheus.io/docs/prometheus/latest/querying/operators/#one-to-one-vector-matches

`dns_latency_bucket{le="30.0"} - ignoring(le) dns_latency_bucket{le="10.0"}`

This currently sounds like a usage question. It is suggested, to ask these on the mailing list or on IRC: https://prometheus.io/community/

**Comment by elerer** [comment]
works, Thanks!

**Comment by codesome** [comment]
As @hoffie said, this is a usage question. Please use user mailing list or IRC channel mentioned here https://prometheus.io/community/ for further queries.
