### ISSUE TITLE
Issue adding multiple deltas

### ISSUE THREAD

**Issue by ouraios** [prometheus/prometheus#5174]
## Bug Report
**What did you do?**
i made this query : 
`delta(app_stats{statsName="name1"}[5m])+delta(app_stats{statsName="name2"}[5m])+delta(app_stats{statsName="name3"}[5m])`

**What did you expect to see?**
I expected to see the addition result of the 3 deltas
**What did you see instead? Under which circumstances?**
It returned me an empty result

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
