### ISSUE TITLE
Exclude namespaces from service discovery

### ISSUE THREAD

**Issue by omerlh** [prometheus/prometheus#5190]
## Proposal
**Use case. Why is this important?**
I want to apply `sample_limit` to protect Prometheus from a service that exposes too many metrics. The challenge is applying the limit only on applicative namespaces - I want to exclude `kube-system` from the limit or apply a different limit to this namespace. To achieve that, I would like to define 2 service discovery jobs:
 * One that use `__meta_kubernetes_namespace` to scrape only `kube-system`.
 * One that scrapes all namespaces besides `kube-system`. 

I can achieve that by using `__meta_kubernetes_namespace` to specify all the namespaces that exist today. This solution will work, but is cumbersome and require changes each time a namespace is added. I would like to have a more dynamic solution.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by omerlh** [comment]
I asked first on the slack channel - you can see my message [here](https://kubernetes.slack.com/archives/CD0T3TQUR/p1549443671598200). I assumed the mailing list is similar to the mailing list.
