### ISSUE TITLE
update the latest version

### ISSUE THREAD

**Issue by 595979101** [prometheus/prometheus#5209]
If I only have one service, how do I update the latest version, how do I save the history data.Can you give me a detailed document?I didn't find it at https://prometheus.io.Thank you for your help

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
