### ISSUE TITLE
keep old data with hourly granular

### ISSUE THREAD

**Issue by daixiang0** [prometheus/prometheus#5379]
In a Production Environment, i set the time to delete data is `15d` and collect data every `15s`.

Now i want to view data trend graph in whole year(i think it is useful), but the data size of whole year is too large, so i want delete old data over one month, but not remove them all, just keep them with hour level, so that data size could be small.

Is it possible?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
