### ISSUE TITLE
Record rule and Alert rule expression needs to take dynamic values for the labels

### ISSUE THREAD

**Issue by yaminisridaran** [prometheus/prometheus#5391]
Record rule and Alert rule expression needs to take dynamic values for the labels
Example:
MetricName{"labels"=<runtime generated value>}

runtime generated value is not known during deployment time.
Required a promQL expression dynamic value for labels of metric
sum(MetricName{"labels"=<runtime generated value>})

Same for Alert Rules expression.

**Comment by brian-brazil** [comment]
This sounds more like a usage question, PromQL is already powerful enough for any label handling you should need.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
