### ISSUE TITLE
average of only successful scrape

### ISSUE THREAD

**Issue by echo-of-wind** [prometheus/prometheus#5407]
for every scrape, two metrics are gotten: 
1. probe_status, 0 for failure, 1 for success
2. probe_duration, duration for probe

so how to query avg of probe_duration for probes whose probe_status are success?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
