### ISSUE TITLE
support for logical binary operator between range vector

### ISSUE THREAD

**Issue by echo-of-wind** [prometheus/prometheus#5409]
probe_duration_seconds and probe_success are two metrics for every scrape, the following query attempts to query the five minutes interval range vector one hour ago, whose probe_success equals 1(now it prompts 'syntax error'):

probe_duration_seconds[5m] offset 1h and probe_success==1

from the doc, logical binary operator is only supported between two instant vectors.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
