### ISSUE TITLE
metrics don't show up in Prometheus GUI browser

### ISSUE THREAD

**Issue by candysmurf** [prometheus/prometheus#5412]
I have custom metrics showing up at http://localhost:2112/metrics. However, none of those metrics show up in http://localhost:9090/graph, Prometheus browser. I'm new to Prometheus. Anything I may miss? thanks.

prometheus.yml
```sh
global:
 scrape_interval:     10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: prometheus
   set_timestamp: false
   static_configs:
     - targets: ['localhost:2112']
remote_write:
 - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
 - url: "http://prometheus_postgresql_adapter:9201/read"
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
