### ISSUE TITLE
increase function calculate duplicate result, but metrics seems not duplicate

### ISSUE THREAD

**Issue by Erictsu1947** [prometheus/prometheus#5423]
## Bug Report

Hi, I use mysqld_exporter to collect mysql status.

It works well, but sometimes i find some original metrics seems not to be duplicate.
When I try some aggregate functions, such as increase/rate, the result i get seems 
calculate duplicate metric.
 
I got some metrics original as below

<img width="1280" alt="屏幕快照 2019-04-01 下午5 48 57" src="https://user-images.githubusercontent.com/8710449/55318999-93a6d780-54a6-11e9-8561-7dfe365e7cac.png">

and i got some metrics with increase function as below 

<img width="1275" alt="屏幕快照 2019-04-01 下午5 48 26" src="https://user-images.githubusercontent.com/8710449/55319035-a7ead480-54a6-11e9-822f-71d6f1820915.png">

here the result with rate function

<img width="1279" alt="屏幕快照 2019-04-01 下午5 53 31" src="https://user-images.githubusercontent.com/8710449/55319305-2778a380-54a7-11e9-9cfe-46b08b1fcaf1.png">

**Environment**

* System information:

	Linux 4.4.0-144-generic x86_64

* Prometheus version:

	2.7.1

**Comment by brian-brazil** [comment]
I don't see anything wrong or unusual here.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
