### ISSUE TITLE
Nessus reports CGI security issues on the prometheus server.

### ISSUE THREAD

**Issue by reachlin** [prometheus/prometheus#5439]
We found the following issues on the prometheus server by Nessus:

- CGI Generic Command Execution (time-based). It may be possible to run arbitrary code on the remote web server.
- CGI Generic SQL Injection (blind). A CGI application hosted on the remote web server is potentially prone to SQL injection attack.
- CGI Generic SQL Injection (blind, time based). A CGI application hosted on the remote web server is potentially prone to SQL injection attack.

**Comment by hoffie** [comment]
Can you provide som more details on the actual requests? Maybe Nessus has them, if not, try capturing them using tcpdump or debug logs.

I highly suspect that these are false positives. Prometheus does not execute external commands, so I don't see a way for code execution via shell injection. Classical buffer overflows are also unlikely due to usage of Go.

Regarding SQL injection: Nessus may detect the PromQL-supporting APIs as SQL injection. However, this is by design. I guess most people with critical production data bind Prometheus to localhost and permit external access via an authenticating reverse proxy only.

**Comment by reachlin** [comment]
```
 (TCP/30915) Vulnerability State: New
Using the GET HTTP method, Nessus found that :
+ The following resources may be vulnerable to arbitrary command execution (time based) :
+ The 'id' parameter of the /manager/logs CGI :
/manager/logs?id=650572%7C%7C%20sleep%205%20%26
-------- output --------
<html>
<head><title>Blackbox Exporter</title></head>
<body>
<h1>Blackbox Exporter</h1>
<p><a href="/probe?target=prometheus.io&module=http_2xx">Probe pro [...]
<p><a href="/probe?target=prometheus.io&module=http_2xx&debug=true [...]
<p><a href="/metrics">Metrics</a></p>
<p><a href="/config">Configuration</a></p>
9
<h2>Recent Probes</h2>
<table border='1'><tr><th>Module</th><th>Target</th><th>Result</th [...]
[...]
169.56.69.242 (TCP/30915) Vulnerability State: New
Using the GET HTTP method, Nessus found that :
+ The following resources may be vulnerable to arbitrary command execution (time based) :
+ The 'debug' parameter of the /probe CGI :
/probe?target=prometheus.io&module=http_2xx&debug=true%20;%20x%20%7C%7C%
20sleep%203%20%26
-------- output --------
------------------------
```

**Comment by beorn7** [comment]
- The reported output appears to be from the blackbox exporter, not from the Prometheus server.
- Prometheus doesn't use SQL databases.
- There is no `/manager/logs` endpoint. What you are seeing is the default page. It doesn't even process the `id` URL parameter.
- Certainly, the `/probe` endpoint does a lot of things. Some time based scanning method would be naturally noisy here.

This all looks like false positive. Nothing hints towards an actual problem.

**Comment by brian-brazil** [comment]
Agreed, dupe of https://github.com/prometheus/blackbox_exporter/issues/456

**Comment by amuessig** [comment]
@beorn7 When there is no SQL database in use, why does the documentation say that arbitrary SQL queries can be run? 

https://prometheus.io/docs/operating/security/
> The remote read feature allows anyone with HTTP access to send queries to the remote read endpoint. If for example the PromQL queries were ending up directly run against a relational database, then anyone with the ability to send queries to Prometheus (such as via Grafana) can run arbitrary SQL against that database.

**Comment by hoffie** [comment]
@amuessig I believe the docs are correct. They refer to the case where you enable Prometheus' remote read feature and point it to some kind of adapter which turns the read request into SQL queries. This is not done by Prometheus, but Prometheus provides the interface to implement something like this. The docs contain this note in order to warn anyone implementing this that it may have security implications.
