### ISSUE TITLE
Document memory planning guidelines

### ISSUE THREAD

**Issue by itaysk** [prometheus/prometheus#5469]
## Proposal
I would like to ask the prometheus dev community to consider adding some documentation around estimating the memory requirements of prometheus.  
The fact that prometheus is mostly being run in memory capped containers and is OOMkilled when reaching the mem limit is surprising many users who are accustomed to robust software that degrades instead of dying.

I've been running prometheus in production for a while which is occasionally OOMKilled. I have expanded the memory limits more than once to arbitrary limits but I would prefer to make an educated estimation for a reasonable limit given my workload.  
I have read the TSDB design paper which was super interesting but I don't feel that it gave me a practical hint to my problem, and even if I did, I think this is something the average user is far away from doing, and I'd consider this a development task rather then a usage question.  
Since being in this state I have also learned that many others are in the same situation and are just "living with it", which is unfortunate.

Can we please discuss this topic, and possibly document our conclusions in the readme?
(I understand that planning for queries is harder, so we can stick to planning for metrics ingestion only which is supposed to be predictable)

**Comment by DanielShor** [comment]
HI, Any insights about this?

**Comment by itaysk** [comment]
I still think this issue needs to be formally addressed, but it's worth mentioning that since opening this issue, Robust Perception posted this calculator: 
https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion

**Comment by nrchakradhar** [comment]
Is it possible to provide the formula or method of calculation used in the blog

**Comment by beorn7** [comment]
There is another insightful blog post: https://www.robustperception.io/why-does-prometheus-use-so-much-ram

**Comment by beorn7** [comment]
Hello from the bug scrub.

While we acknowledge that such a memory planning document would be super useful, we are chasing a moving target here. The code is continuously optimized (reducing the memory usage) and new features are added (potentially increasing memory usage), so any serious memory planning document will be out of date very soon. Furthermore, the question itself is very tough to answer because the shape of your data changes the memory usage.
Given that nobody has given a try to write up an official memory planning document in the last five years, it's probably best to tap into the wisdom of the crowd and search the web for experiences people have made in various situations.
This is not ideal, but we'll close this issue anyway because we just don't have a concrete plan of action how to go forward with this.
If somebody has a plan how to tackle this and wants to invest work in it, please follow up and we'll happily re-open.
