### ISSUE TITLE
remote read or local read

### ISSUE THREAD

**Issue by qianxiaozhoutao** [prometheus/prometheus#5474]
Prometheus Both remote data and local data exist，Chooses whether to read local data or remote data

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
