### ISSUE TITLE
Excessive WAL and block overlap

### ISSUE THREAD

**Issue by mknapphrt** [prometheus/prometheus#5476]
## Bug Report
(I don't know if this is really a bug or just a misunderstanding on WAL truncation)

**What did you do?**
No changes were made, just running prometheus.

**What did you expect to see?**
When the WAL compactions are triggered and blocks are created, the WAL that now overlaps with the blocks would be deleted.

**What did you see instead? Under which circumstances?**
There are several hours of WAL data still overlapping with the blocks. Taken at the same time:

```
$ ls -lah | tail
drwxr-xr-x   3 prom  prom     6 Apr 17 03:41 01D8N1GPC7F6SNHZYZA5CJ89HZ
drwxr-xr-x   3 prom  prom     6 Apr 17 05:40 01D8N8CDM7VGSACTSMNGB1KA2T
drwxr-xr-x   3 prom  prom     6 Apr 17 07:40 01D8NF85A9H74HAB2KYG8YWT8T
drwxr-xr-x   3 prom  prom     6 Apr 17 09:44 01D8NP3W4KKJPEKY4W5KKPH8P2
drwxr-xr-x   3 prom  prom     6 Apr 17 11:44 01D8NWZKCTQPH4DM108T93TKXJ
drwxr-xr-x   3 prom  prom     6 Apr 17 13:46 01D8P3VAMR9CBSZTQ036J1221B
drwxr-xr-x   3 prom  prom     4 Apr 17 15:00 01D8PAQ1WWBFNR3T05VRFH574Y.tmp
```

```
$ ls -lah wal | head
total 136G
drwxr-xr-x   3 prom  prom 2.0K Apr 17 15:04 .
drwxr-xr-x 177 prom  prom  178 Apr 17 15:00 ..
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642783
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642784
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642785
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642786
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642787
-rw-r--r--   1 prom  prom 128M Apr 17 09:51 00642788
-rw-r--r--   1 prom  prom 128M Apr 17 09:52 00642789
```

Should there be this much overlap? Is there a flag or setting that can control how much overlap there is? I don't really see the point in this redundancy in data storage. Any help or suggestions would be appreciated. Thanks

**Environment**

* Prometheus version: 2.6.1

**Comment by cstyan** [comment]
@mknapphrt it depends on how many segments you have. I suspect you have quite a lot, given how many segments you have in just that one pasted comment for a 1-2 minute time period.

When TSDB Head takes the last 2h of data and then a truncation is performed, at most the first 1/3 of segment files will be removed. A checkpoint is created with records from those segments for series that are still active, and then an attempt to delete those segment files.

https://github.com/prometheus/tsdb/blob/master/head.go#L556-L561

**Comment by cstyan** [comment]
Note: I'm assuming you haven't messed with any of the tsdb flags :) if you have, please let us know.

**Comment by krasi-georgiev** [comment]
the .tmp folder/files are not normal and should be fixed by https://github.com/prometheus/tsdb/pull/570

Checkpointing removes all samples/series that are already persisted to a block and I tested it locally that it runs at compaction when the WAL indexes have a difference of 5 or more (for example first wal file is 00000014 and last one is 00000019 . Which is 00000019-00000014 = 5 ) 

There will be a small overlap for systems under low load since sometimes the wal files index difference will be lower than 5 when the compaction runs, but since the file size would be also small don't think this should be of any concern.

as @cstyan mentioned if you have changed the tsdb block size settings `--storage.tsdb.min-block-duration` this affects how often runs the compaction so will also affect when the checkpointing removes the obsolete WAL data or if you set `--storage.tsdb.wal-segment-size` to some smaller value than the default this will cause Prometheus to create a new WAL file more frequently so the checkpointing will run more often, but again these flags are hidden as might cause other issues.

btw when you check the file time creation/modification and see time overlaps, that doesn't mean that the files include the same data. Compaction and wal checkpointing modifies the files so it is normal to see files/dirs with overlapping time ranges for the date creation/modification.

feel free to close the issue if that answers your question.

**Comment by krasi-georgiev** [comment]
I think we answered your question, but feel free to reopen if you have anymore comments.
