### ISSUE TITLE
How to smooth upgrade like nginx  for prometheus

### ISSUE THREAD

**Issue by vacheli** [prometheus/prometheus#5516]
1. I'am going to upgrade 2.92 from 2.81,but I don't find out smooth upgrade steps like nginx.
2. upgrading prometheus must stop it?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
