### ISSUE TITLE
https://xyz.:443/metrics: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by csesanram** [prometheus/prometheus#5522]
I've deployed prometheus in kubernates container and it's working fine. after that trying to run pushgateway with a separate container it working fine but when prometheus.yml file added below entry getting  **"metrics: x509: certificate signed by unknown authority "**

      - job_name: pushgateway
        honor_labels: true
        scheme: https
        static_configs:
          - targets: ['prom-pushgateway.com']
please let me know how to ersolve this issue.

I have downloaded the docker image from docker hub
image: prom/pushgateway

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
