### ISSUE TITLE
Null instead of zero with promql count

### ISSUE THREAD

**Issue by ozaaditya** [prometheus/prometheus#5526]
Prometheus query function count returns null instead of zero making arithmetic operation impossible.

Ex:
count(up{}) - sum(up{}) + count(100 - (avg by (instance) (irate(node_cpu{}[5m])) * 100) > 5)
 From above expected value is total count of exporters or servers down plus cpu utilization crossing 75 but instead above expression returns "Null" if none of cpu cross 75% threshold but 1 or more servers or exporters are down.

**Comment by brian-brazil** [comment]
https://www.robustperception.io/why-can-countx-5-not-return-0

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
