### ISSUE TITLE
Add ability to run remote write as a sidecar

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/prometheus#5539]
## Proposal
**Use case. Why is this important?**

Now that remote write is reading from the WAL, there is no requirement for remote write to share a process with Prometheus. Running remote write as a sidecar would have the following advantages:

1. A crash in remote write will not take down all of Prometheus
1. Ability to apply different resource constraints to each component

If a sidecar is desired, would it be better to have a separate binary or a mode from within the Prometheus binary?

Also, to be clear I am proposing this as an additive change, not a replacement of the in process mode.

cc: @cstyan curious what you think since you did the WAL reading work.

**Comment by brian-brazil** [comment]
The way I'm expecting things to go is that remote write backends would provide such a sidecar, including whatever more efficient protocol makes sense for them to talk to their backend.

**Comment by csmarchbanks** [comment]
I completely agree that backend vendors should provide a sidecar if they would like a custom protocol. However, I think it would be nice to have a first class example for the current protocol as well.

**Comment by cstyan** [comment]
I don't really have an opinion for or against this. My only concern is whether this would necessitate versioning and/or providing stability guarantees for the remote write code beyond the protobufs. If so, the discussion in #5523 is somewhat relevant I think.

**Comment by brian-brazil** [comment]
The plan of record is that we'll provide libraries to do the WAL watching, and it's up to users from there.

**Comment by valyala** [comment]
This is dubious idea because of the following reasons:

- Hard to synchronize access to WAL between Prometheus process and sidecar processes. In theory Prometheus could share IPC synchronization mechanism for WAL access. But this would complicate the architecture around WAL and leave potential issues at edge cases. For instance, how to synchronize WAL access from multiple concurrent sidecars?

- Hard to make changes to WAL architecture without breaking backwards compatibility with third-party sidecars. For instance, recently added WAL compression could break all the existing sidecars.

I'd recommend continue improving remote write capabilities inside Prometheus process instead of following dubious path with external sidecars. The following issues with remote write in Prometheus should be addressed first:
- High additional RAM usage after enabling remote write (users report +30% RAM usage when enabling remote write)
- High additional CPU usage after enabling remote write
- High egress network bandwidth usage because of ineffective labels transfer across the network - the same labels are repeatedly transfered with each remote_write request.

Existing sidecars like Thanos Sidecar already contain ugly hacks and requirements like disabling Prometheus compaction as a workaround for missing IPC synchronization for data files' access. I bet future sidecars would contain more such hacks.

**Comment by csmarchbanks** [comment]
I disagree with your analysis that the sidecar pattern is dubious. The current remote write path inside of Prometheus also does not do any WAL synchronization. In fact, each queue reads from the WAL separately which is effectively having multiple concurrent sidecars. In addition, there are already sidecars out there such as https://github.com/Stackdriver/stackdriver-prometheus-sidecar. I already experimented and made this work awhile ago by simply starting up the proper Prometheus components: https://github.com/csmarchbanks/remote-write-sidecar.

As far as version changes go, we already try to keep the WAL backwards compatible otherwise reverting Prometheus versions would lose data. But yes, if you turn on WAL compression you would need to have a sidecar version that supports it.

See https://github.com/prometheus/prometheus/issues/6333 for some ideas around issues with remote write.

That said, I am going to close this issue as I think having the sidecar in a separate repo is fine for those who want to run using a sidecar pattern.

**Comment by valyala** [comment]
>  In fact, each queue reads from the WAL separately which is effectively having multiple concurrent sidecars

This sounds like an issue which should be fixed. It is much easier to fix if remote_write component is located inside the same address space (aka `process`) as other components that may touch WAL. It would be much harder to fix for external processes aka sidecars.

**Comment by cstyan** [comment]
> > In fact, each queue reads from the WAL separately which is effectively having multiple concurrent sidecars
> 
> This sounds like an issue which should be fixed. 

This is by design; remote write pauses tailing the WAL if it isn't able to send to the remote endpoint instead of continuing to buffer samples. With each queue tailing the WAL separately this means that if any one remote write endpoint you've configured Prometheus to write to is having issues it doesn't block the rest.
