### ISSUE TITLE
Update Kubernetes deps; Update Kubernetes SD ingress role instead of deprecated API

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#5554]
The Kubernetes Ingress API is deprecated and being removed in 1.18: https://github.com/coreos/prometheus-operator/issues/2592#issuecomment-491059610

While that's still a fair bit out there, we should update the API to the new networking.k8s.io/v1beta1 Ingress API.

Thanks @liggitt for raising this early!

@krasi-georgiev @simonpasquier @metalmatze @squat @s-urbaniak

**Comment by metalmatze** [comment]
Sure, we can update right away. However, currently it would break all people running Kubernetes before 1.14. As we still have a lot of time until 1.18, I'd say that we wait for updating that API group until Kubernetes 1.16 or 1.17 are out. By that time, we shouldn't break as many people then.

**Comment by brancz** [comment]
Agreed.

**Comment by bwplotka** [comment]
We looked on this during bug scrub, this is still TODO and blocked on the inability to upgrade to `k8s.io/api v0.18.x` because of this https://discuss.circleci.com/t/install-golang-1-13-in-the-windows-default-image/33994

We also experience this blocker here: https://github.com/prometheus/prometheus/pull/7158

**Comment by roidelapluie** [comment]
Fixed in #7093
