### ISSUE TITLE
Why does the federate endpoint return all metrics as untyped?

### ISSUE THREAD

**Issue by SleepyBrett** [prometheus/prometheus#5589]
## Proposal
**Use case. Why is this important?**

I would like to export some metrics from a prometheus server upstream to datadog, I'm attempting to use the veneur-prometheus scraper to accomplish this.

Unfortunately it fails because all the metrics return as "untyped".

I found this related issue: https://github.com/prometheus/prometheus/issues/3935

But i find the response condescending and without explanation, the article linked does not seem to answer the question.

Why are all metrics on the federation endpoint typed 'untyped' I assume the types are stored in the prometheus database. I'm only looking to federate a very small number of metrics ( around a dozen.

Is the type not stored and therefore not passable?

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

Call /federate with a narrow query that returns a handful of metrics, but it's description blocks declare the timeseries as 'untyped'

**What did you expect to see?**
I expect the timeseries types to show up on the federation endpoint.

**What did you see instead? Under which circumstances?**

'untyped', always.

**Environment**

Prometheus 2.2.1  on kubernetes

* System information:

NA

* Prometheus version:

v2.2.1

* Alertmanager version:

NA

* Prometheus configuration file:
```
NA
```

* Alertmanager configuration file:
```
NA
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
The type is not stored, having datadog fetch the metrics directly would be better if you need them.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by SleepyBrett** [comment]
> The type is not stored

Why not? It seems unwise just to throw out useful data. It makes the whole system less usable. I think my scenario is perfectly valid as are many other federation type scenarios. Having to re-state in other systems scrape targets seems error prone and 'work for the sake of work'.

I guess what I'm saying is that /federate and federation seems half baked at best but is a useful feature that never seems to get any traction because all discussion of it is struck down with 'thats expected' and trying to push people off to a mailing list where they can be more easily ghosted.

> having datadog fetch the metrics directly would be better if you need them. 

This is not feasible at this time and is error prone. Datadog is not a great tool ( but I'm saddled with it ).

> It makes more sense to ask questions like this on the prometheus-users mailing list

Flippant and counterproductive. Also a mailing list for users is not a great response to what I see as a bug, even though you have stated multiple times, without explanation, that it's 'expected'. It's only expected in so far as the code says 'do this thing'. As a user I expect metrics types to persist into the datastore and be retrievable. I have yet to see an explanation as to why this isn't desirable.

**Comment by beorn7** [comment]
@SleepyBrett: You claim that we redirect the discussion to the mailing list so that it will “die”. What makes you think so? AFAIK, neither you nor the author of #3935 ever asked the question on the prometheus-users list. If nobody asks, no answers can be provided. And nobody can chime in. Thus, you will only ever talk to @brian-brazil because he happens to be the fastest in triaging issues. His style of answering seems to make you unhappy. That should be even more of a reason to start a thread on the mailing list and talk to others members of the community.

Community support for Prometheus is provided on a voluntary and unpaid basis. To keep the workload manageable, we decided to use GH issues for bugs and feature requests only, and use the mailing lists for explanations and overarching discussions. I understand that the current behavior of the federate endpoint looks like a bug to you, and that changing the behavior looks like a feature request. However, as @brian-brazil already said in #3935, it's more complicated than that. In fact, this particular issue of the federate endpoint has been a matter of concern from its very beginning. As has the general ignorance of metadata by the server, see https://prometheus.io/docs/introduction/roadmap/#server-side-metric-metadata-support .

If you want an explanation, I invite you to start a mailing list thread. That's the place where we would like to see this kind of discussions. In GH issues, they get mixed up with bugs and the details of feature implementation, which is not good for either.
