### ISSUE TITLE
Passing list as annotation value to prometheus rule.

### ISSUE THREAD

**Issue by DataSweeper** [prometheus/prometheus#5646]
## Proposal
**Passing List as annotation value to prometheus rule.**
*Reason:*  When generating an alert we have to associate multiple URLs with the alert. For example 
Loggging service url, Tracing service url that are related to the particular alert. If annotation value
can hold a list, It will help to generate dynamic templates in alertmanager side.

One use case is when multiple alerts rule is being configured, an annotation list variable can hold 
different size of list value of URLs. Through iteration an email template can be generated without 
any changes to the existing template code. 

## Feature request

**Environment**

* System information: kubernetes (v1.11.0)

* Prometheus version: 2.3.1 

* Alertmanager version: 0.14.0

**Comment by simonpasquier** [comment]
By design, annotations are key-value pairs of [`<labelname>/<labelvalue>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file), changing this would cause breakage which can't happen in the 2.x release. It would also require changes to the [AlertManager's  API](https://prometheus.io/docs/alerting/clients/).

Now to your request, I don't see how supporting arrays for annotation values would be much more convenient than defining `TracingURL`, `LoggingURL`, ... annotations in the alert definitions. And in any case, you would have to change the notification template to include the annotations, whether there's only one or several.

**Comment by DataSweeper** [comment]
Following are the points can be taken to consider:
  1) Value in template don't have be a yaml variable (example: TracingURL can be Tracing URL).
  2) It reduces the code in templates by using loop statement.
  3) In my case I wrote a helm package to automate the creation of prometheusrule CRD for prometheus operator. Using the helm package I created alarms based on RED, Here I want o pass any number of urls with their description **without any change in alertmanager email template**. Any one can use the rule helm package to configure alarms with URLs, Description like their own key values.

The following is the template code:
```
{{ range .Annotations.logurl }}
<strong style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font- 
 size: 14px; margin: 0;">{{ .name }} </strong><a href={{ .url }}>Click here</a><br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
{{ end }}
```

**Comment by simonpasquier** [comment]
The example you provide doesn't match with the initial description: IIUC you expect `logurl` to be a map rather than an array. In any case, the format of the alert payload isn't going to change any time soon, I'm afraid.

**Comment by simonpasquier** [comment]
Also you could do something like this already:

```
{{ range .Alerts }}
{{ range .Annotations.SortedPairs }}
{{ if match ".+URL$" .Name }}
<a href="{{ .Value }}">{{ .Name }}</a>
{{ end }}
{{ end }}
{{ end }}
```

**Comment by simonpasquier** [comment]
Is your :+1: an acknowledgment for closing this issue?

**Comment by DataSweeper** [comment]
Got it, Thanks.
