### ISSUE TITLE
About the number of API calls of prometheus service discovery on AWS

### ISSUE THREAD

**Issue by masuzuki1028** [prometheus/prometheus#5650]
Please let me know below.
Introduce node_exporter to thousands of EC2 / ECS instances per autoscaling region on AWS,
We will collect metrics on prometheus.
At that time, add a specific tag in ec2_sd_config.
Of course, because it is difficult to monitor several thousand units with one prometheus, it is limited to hundreds per prometheus.

In this case, it is EC2 to be added by service discover from each prometheus server or tag name by API call
I think that confirmation process is performed, but there is a concern that the API call limit limit of each AWS region may be reached.

Is there a case like this? I hope that you can teach us the processing outline if possible.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by masuzuki1028** [comment]
Thank you for your reply.
I will send questions to the mailing list.
