### ISSUE TITLE
limit the number of returning time-series

### ISSUE THREAD

**Issue by dmitsh** [prometheus/prometheus#5656]
## Proposal
**Use case. Why is this important?**
I'm proposing to add an optional "max-series" parameter to `/api/v1/query_range` HTTP API.
This parameter, if specified, will limit the number of returning time-series.
Here is the rationale:
In some cases the promql query results with high number of time-series, which makes it difficult to use the UX, from both usability and resource management perspective.
However, the user might not be aware of the abundance of time-series, until he/she runs the query (unless he/she runs `/api/v1/series` first, which doesn't happen when we are using Grafana or other UX tools).
With the proposed "max-series" parameter, the user will get no more than specified number of time-series, and a warning if this number has been exceeded.

**Comment by brian-brazil** [comment]
We already have various limits in place, and I'm not sure this would add to them. If you want this you can already emulate it somewhat with topk/bottomk.

**Comment by bboreham** [comment]
I want this too; haven't managed to find a usable alternative.

`topk` is not a good answer when used in `query_range` because:
 - each point in time can yield a different subset, hence the total number of series returned will likely be over `k`
 - graphing a set of series that appear and disappear over time is ugly.
 - `topk` is unreasonably CPU-intensive because it sorts all the samples at each point in time.

Previous similar request: #586 

Personally I would like to have a way to return the top N plus one more series "other" that aggregates everything else: this helps to know whether your visualisation is skewed by a lot of smaller values.

**Comment by brian-brazil** [comment]
Per #586, that simply isn't possible.

**Comment by dmitsh** [comment]
In our fork we have added an extra URL query parameter `max_series` to both `query` and `query_range` HTTP APIs. This way it is completely optional and doesn't break any functionality. I can create a PR if this is an accepted approach.

**Comment by brian-brazil** [comment]
Arbitrarily dropping series doesn't sound like a good idea to me.

**Comment by dmitsh** [comment]
> Arbitrarily dropping series doesn't sound like a good idea to me.

I forgot to mention that we also adding a warning saying how many time series have been dropped.

**Comment by brian-brazil** [comment]
That's returning incorrect results though, as they're truncated.

The problem you're trying to solve sounds like a UX problem, not a Prometheus server problem. I'd suggest solving this in your UI, rather than complicating the Prometheus APIs.

**Comment by dmitsh** [comment]
I understand your point, and I agree that this feature is solving UX problem. Similarly to `topk()`, we are trying to limit number of time series.

**Comment by beorn7** [comment]
For reference: The Grafana-solution for #586 is described here: https://www.robustperception.io/graph-top-n-time-series-in-grafana

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team.

We are fairly confident we cannot really implement this in a good way on the API level. UIs can do various things to help the user here. Therefore, we are closing this issue. Please follow-up if this is actually about the Prometheus internal _UI_ rather than the API.

**Comment by RichiH** [comment]
https://docs.google.com/document/d/18Jbl5LC_FPLqCqU12qY8XpjVMJLCtGt-ykbyAhYXcIc is relevant for this discussion. It's a different approach, but could be useful to anyone who stumbles onto this issue.

**Comment by bboreham** [comment]
Ref #7903
