### ISSUE TITLE
Questions about TLS version

### ISSUE THREAD

**Issue by SparkSnail** [prometheus/prometheus#5676]
Help! Our team use prometheus as the alert service, and got a problem about the TLS version when send email to smtp server, for the smtp server requires the client use TLS version over v1.2. I want to know that what is the default TLS version used in prometheus? Is it v1.0? How to set the TLS version used in prometheus, I want to use v1.2 or v1.3. Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by SparkSnail** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Thanks for your response, I'll ask this question in prometheus-users.
