### ISSUE TITLE
`--help` prints to stderr, not stdout

### ISSUE THREAD

**Issue by julien-lecomte** [prometheus/prometheus#5721]
## Bug

Unix software has always printed the results of `--help` to stdout, not stderr. Prometheus should respect this.

## Bug Report

```
/opt/prometheus/prometheus --help | grep web
# => nothing is grepped
```

**What did you expect to see?**

```
/opt/prometheus/prometheus --help | grep web
# a couple of lines
```

* Prometheus version:

```
prometheus, version 2.8.0-rc.0 (branch: HEAD, revision: d390497280d61918aa8792f87a2f458e5e231ec2)
  build user:       root@a52a12a3cf6b
  build date:       20190306-16:22:30
  go version:       go1.11.5
```

**Comment by simonpasquier** [comment]
FTR, the "fix" involves calling [*Application.UsageWriter()](https://godoc.org/gopkg.in/alecthomas/kingpin.v2#Application.UsageWriter) with `os.Stdout`. `promtool` should be patched too.

**Comment by brian-brazil** [comment]
This varies by Unix tool in my experience. Having to add extra code to every exporter and application seems a bit much.

**Comment by julien-lecomte** [comment]
It doesn't vary that much actually. There's a few oddball exceptions, prometheus being one of them.

I ran `for i in /usr/bin/* ; do echo -n $i: ; $i --help 2>&1 >/dev/null ; done` on a docker image of debian:stable. Out of 200+ binaries, 38 printed something on stderr. Of those 38 most did not support `--help` or similar (-h) such as awk, clear, and less than 5 binaries prints help to stderr (flock)

The most common thing, and by a far margin, is printing `--help` to stdout.

**Comment by beorn7** [comment]
The [dev summit on 2021-02-25](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit) expressed a consensus that "results of explicit user actions like --help and --version should go to STDOUT". We also agreed that we do not consider changing the output from stderr to stdout a sufficiently invasive change to require a major version bump.

In other words: This issue is up for grabs. (o:
