### ISSUE TITLE
Upgrade from 2.2.1 to 2.6

### ISSUE THREAD

**Issue by benamazing** [prometheus/prometheus#5751]
I want to upgrade my prometheus from 2.2.1 to 2.6, can i simply replace the binary and restart? Does it impact the local historical data query? Whether the built in tsdb engine changed?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
