### ISSUE TITLE
Specify a list of dynamic namespace to discover with kubernetes_sd_config

### ISSUE THREAD

**Issue by yeplaa** [prometheus/prometheus#5776]
## Bug Report
**What did you do?**

I use the kubernetes_sd_config to discover targets from Kubernetes.  
My list of namespace to discover will increase and I need this list can be updated as dynamically as possible. I do not want to discover all namespaces of cluster by default.

**What did you expect to see?**

With the **namespaces** section configuration of kubernetes_sd_config,  i would like to use a selection by pattern / match with wildcard on the namespace name instead of having to explicitly specify the names of the set of namespace.

**What did you see instead? Under which circumstances?**

When i try a namespace name in pattern format, the namespace is not recognized.

Currently the configuration like indicated on the documentation: 
 
             # Optional namespace discovery. If omitted, all namespaces are used.
             namespaces:
                     names:
                     [ - <string> ]

**Environment**

* System information:

	Openshift 3.9 

* Prometheus version:

	prometheus 2.11.1

**Comment by juliusv** [comment]
This would require Prometheus to first fetch a list of all available namespaces and keep that list up to date as well, so that it can theh filter that list. To be consistent, we would then also want to offer similar functionality for other SD and field types (why would k8s namespaces be special?), for example service names or tags in Consul. So in total I think this is a bit much to ask for in terms of extra functionality on the Prometheus side.

Currently you could already discover all namespaces and filter away targets from the wrong namespaces using target relabeling rules with regexes. Or are there so many namespaces that it becomes a performance implication to first discover them all and filter afterwards?

**Comment by genericgithubuser** [comment]
We've seen this in our environment, we have currently discover all namespaces, and then filter things down to just the relevant targets.  We have some small instances (just a few GB of RAM) that scrape <12 endpoints, with <6k head chunks with little churn.  In our lower environments (with almost identical targets and metrics), which has a few hundred fewer namespaces with tens of thousands less services/pods they use less than half the RAM, even for instances holding more metrics that update/change more frequently.  

In our case, we have namespaces all based on the customer name, but they have some dynamically generated namespaces.  So we need a way to discover pods/services inside of namespace "<customer name>-.*".  Since as you mention @juliusv , that isn't supported, so we use relabel_configs to keep things that just match the regex of namespaces that start with the customer name. 

I get the reasoning given what was mentioned above for not adding a wildcard supported discovery, but is there some other way we might look to be able to handle this that would reduce the memory requirements since 99% of the pods/services discovered this way are just dropped?


An example of our namespaces would be:
customer1-foo
customer1-bar
customer2-foo
customer3-baz

and for customer3-baz, we have them discover ALL of the pods/services across all namespaces, then just drop the things that don't come from theirs (which in some cases has it literally scraping just 2 pods). The challenge is that we can't just specify "customer3-baz" in the k8s namespace filter since there might be a customer3-tmp namespace created for 30m, then it go away.  

Thanks for any thoughts on how this might be addressed!

**Comment by juliusv** [comment]
Yeah, if this causes so much more memory usage, the feature request itself makes total sense. I'm just not sure how easy it is to do.

/cc-ing the people who have touched the Kubernetes SD the most @simonpasquier @brancz @tariq1890

**Comment by yeplaa** [comment]
In ma case, Prometheus doesn't have rights for access every namespace because it's a shared cluster with other projects. Prometheus has only access (by Rolebinding) to certain namespaces
 This is why i don't have currently discover all namespaces ..

**Comment by juliusv** [comment]
> We already allow specifying explicit namespaces by the user, so I'd say this could be done by the user updating the config file as the namespaces change.

If namespace changes become as dynamic as e.g. pod changes, then of course this becomes suboptimal, as now one has to implement their own namespace SD, and also reload Prometheus quite frequently (which is cheap, but not without any disruption).

**Comment by tariq1890** [comment]
Unless I am missing something, can't this be done the prometheus-operator?

**Comment by genericgithubuser** [comment]
And to Brian an Julis' comments, in our case, these very much are dynamic namespaces, so would be challenging to have edited in the config and reloaded on a frequent basis.  We have jobs running in namespaces that get spun up just for the run and then removed for each group, so namespaces frequently coming and going.  
We don't currently run the prometheus operator, so not sure if it already does this in a low-overhead way.  We'd love to be able to do this with native prometheus, but can add the operator on the list to review if it seems it'd do this in a better way.

**Comment by 030** [comment]
@yeplaa did you find a solution?

**Comment by yeplaa** [comment]
@030 No native solution with Prometheus. I plan to list from another external component the list of my namespace and to explicitly add in the configmap the names of the namespaces to discover.

**Comment by brancz** [comment]
Fwiw the prometheus operator allows doing this.

**Comment by 030** [comment]
@brancz Could you indicate how to do this? For example, we would like to restrict monitoring to a prometheus in namespaces with prefix x. In other words, the prometheus in namespace x is only allowed to monitor all namespaces that start with x.

x-prom is allowed to monitor x-*
y-prom is restricted to y-*

**Comment by brancz** [comment]
It's not by prefix, but you can use a namespace label selector to select the namespaces to monitor.

**Comment by 030** [comment]
@brancz Could you indicate where an example could be found? I only found ```enforcedNamespaceLabel``` [here[(https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md).

**Comment by 030** [comment]
@brancz I am using https://github.com/coreos/kube-prometheus/tree/release-0.1. Is the option included in this operator as well?

**Comment by brancz** [comment]
There are two things you can do, one of which you already discovered, but which only allows listing namespaces or selecting all (you can still limit the targets selected by using relabeling rules on the namespace meta label). The other option is to allow specifying the ServiceMonitor in the respective namespace, local to the application, and make use of the [`serviceMonitorNamespaceSelector`](https://github.com/coreos/kube-prometheus/blob/a4a143a9ab770d72eb0f7dd44bf8e72184347944/manifests/prometheus-prometheus.yaml#L30) (the empty selector selects all namespaces).

**Comment by 030** [comment]
@yeplaa Did you already create such a component? 

> I plan to list from another external component the list of my namespace and to explicitly add in the configmap the names of the namespaces to discover

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. We are not quite sure what there is left to do from the Prometheus side. @yeplaa could you clarify?

**Comment by haarchri** [comment]
@yeplaa  any progress ? can we support ? because we also need a feature like this - because we didn't have cluster scope rights ;/

**Comment by yeplaa** [comment]
@haarchri @beorn7 @030 sorry for the late return but on my side this project has been abandoned..

**Comment by beorn7** [comment]
If I understand things correctly, the state of this affair is the following:
- There is some need for this, but I'd say it's pretty niche.
- It is possible to solve this with the Prometheus operator.
- An implementation within Prometheus is not trivial.
- If this is really useful outside of a niche, it should be done in the same way for other SD mechanisms (i.e. we should at least have a plan how to proceed beyond a "K8s-only hack").
- Nobody is currently planning to work on this, apparently.

Therefore, I'll close this issue, but if anyone wants to make the point that this is worth implementing within Prometheus _and_ presents a plan and intentions to do so, we'll happily re-open.

**Comment by jzr1991** [comment]
Just registering my interest in this functionally.

The use case is that I don't have cluster admin privileges in my cluster, but teams give us access to their projects when they deploy our helm chart via a rolebinding template - thus dynamically, a service account in our project gets access to more and more projects as people deploy our chart. 

However, we cannot scan all namespaces because that requires cluster admin. Instead we'd want it to be able to discover those namespaces as they become available due to teams deploying our helm chart.
