### ISSUE TITLE
Prometheus metrics \"INVALID\" is not a valid start token in kubernetes env

### ISSUE THREAD

**Issue by jmdinis** [prometheus/prometheus#5779]
I deployed a keras mnist model using seldon core and I'm trying to monitor the model using seldon-core-analytics with grafana dashaboards. The cluster_monitoring dashboard looks fine but the Prediction Analytics doesn't find the my deployed model and all the panels are empty. I have installed kubeflow, the seldon-core and seldon-core-analytics in the same namespace and I have my model deployed in that same namespace.

After checking prometheus service logs in the same namespace I found the following message recurrently:

level=warn ts=2019-07-17T16:24:27.691294684Z caller=scrape.go:836 component="scrape manager" scrape_pool=kubernetes-pods target=http://192.168.49.198:16686/metrics msg="append failed" err=""INVALID" is not a valid start token"

Can you please advise on this?

Thanks.

**Comment by beorn7** [comment]
This usually happens if you have pointed Prometheus to an endpoint that is net emitting Prometheus metrics, or the endpoint is emitting syntactically wrong Prometheus metrics.

https://www.google.com/search?q="INVALID"+is+not+a+valid+start+token gives you a lot of good pointers how to start your investigation.

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
