### ISSUE TITLE
PromQL : default() function addition

### ISSUE THREAD

**Issue by jdelvecchio** [prometheus/prometheus#5806]
## Proposal
**Use case. Why is this important?**

It would be a nice addition in the promql functions, to be able to default an undefined or non existent variable, the same way you can do it in ansible using the jinja2 `default` filter :
`{{ some_variable | default(5) }}`.

In my usecase, I'm defining custom threshold for some VM, and would like to have only one alert for all of them, and to do so I need a way to default an undefined variable.

In promql, it would be something like this : 
`((vmware_vm_guest_disk_free * 100) / vmware_vm_guest_disk_capacity <= default(5,on(vm_name) group_left vm_disk_threshold))`

Hopefully it makes sense

**Comment by brian-brazil** [comment]
This is already possible with or.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
