### ISSUE TITLE
how to get real qps by rate

### ISSUE THREAD

**Issue by huwenbo** [prometheus/prometheus#5810]
I am a beginer, and try to get qps for a http service. I use counter .
I use rate(req_count[1m]) , can see trend of qps.  how can I get real qps number.
I want to know , every point real qps number

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
