### ISSUE TITLE
How to solve the problem that the alarm is allowed within a specified time?

### ISSUE THREAD

**Issue by h77626592** [prometheus/prometheus#5816]
such as

No special service alarm notification is allowed after 22 pm. How to realize it

**Comment by h77626592** [comment]
Very anxious

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
