### ISSUE TITLE
Could prometheus transfer label from one instant vector to another instant vector?

### ISSUE THREAD

**Issue by code1wind** [prometheus/prometheus#5820]
If I have two similar instant vectors by two querys. The two vectors have some same labels and some different labels. If i want copy some different label from one vector to another vector based on one or some same labels, is it possible? eg:
   A query vectors:
       Ametrics{"name" = "a"} 1
       Ametrics{"name" = "b"} 2
       Ametrics{"name" = "c"} 3
       .....
  B query vectors:
      Bmetrics{"name" = "a", "object" = "cat"} 1
      Bmetrics{"name" = "b", "object" = "dog"} 2
      Bmetrics{"name" = "c", "object" = "monkey"}  3

how I get the result:
       Ametrics{"name" = "a", "object" = "cat"} 1
       Ametrics{"name" = "b", "object" = "dog"} 2
       Ametrics{"name" = "c", "object" = "monkey"}  3

function 'label_join' and 'label_replace' seem make sense only in one vector.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by code1wind** [comment]
ok, thank you for your reply!
