### ISSUE TITLE
Prometheus,cpu túrán shēng gāo 18/5000 Prometheus, cpu suddenly rises

### ISSUE THREAD

**Issue by beibeii** [prometheus/prometheus#5838]
Prometheus, cpu suddenly rises for more than 1 minute, then falls down, what may be the reason
![vv](https://user-images.githubusercontent.com/14730487/62532624-6369ae00-b877-11e9-9ca1-21329e37fe55.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
