### ISSUE TITLE
Promql outer join support

### ISSUE THREAD

**Issue by garrettlish** [prometheus/prometheus#5841]
## Proposal
Outer join (especially left join & right join) are very useful. 
For example: We have one host level CPU alert (CPU > 70%), and we have another spatial aggregation metrics on pool level (host count in a pool). If we wants to get all pool alerting host rate, right join is required to implement it (since host level CPU alert metric doesn't have full set of the pools, only includes the pool which has host CPU > 70%).

**Comment by brian-brazil** [comment]
This is already possible with PromQL. As this is a usage question you're best off to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
