### ISSUE TITLE
Multiple remote_read for InfluxDB

### ISSUE THREAD

**Issue by barebu** [prometheus/prometheus#5855]
Hi.

There are 2 (or more) databases InfluxDB. They can be both within the same server or on different servers. Different Prometheus processes are recorded in each database. Need to be able to read data from both databases with one Prometheus process
I want to add several InfluxDB databases to the remote_read section. I tried like this
```
remote_read:
    - url: "http://127.0.0.1:8086/api/v1/prom/read?db=prometheus"
    - url: "http://127.0.0.1:8086/api/v1/prom/read?db=prometheus_scripts"
```
or
```
remote_read:
    - url: "http://127.0.0.1:8086/api/v1/prom/read?db=prometheus"
    - url: "http://127.0.0.22:8086/api/v1/prom/read?db=prometheus_scripts"
```
but this did not lead to a result. 
Prometheus refuses to read from two databases at once
Can this be somehow solved?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
