### ISSUE TITLE
idelta and similiar functions does not work with ALERTS

### ISSUE THREAD

**Issue by amnonh** [prometheus/prometheus#6003]
## Bug Report
What did you do?
idelta(ALERTS[1m])

What did you expect to see?
a time series showing the changes in the alerts

What did you see instead? Under which circumstances?
No point returned

Prometheus docker

Prometheus version:
tested with Prometheus 2.12 and 2.9.2
insert configuration here (if relevant to the issue)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by amnonh** [comment]
ok, but it does look like a bug
