### ISSUE TITLE
How to get metric type by PromQL

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#6064]
For example, i have metric `prometheus_notifications_dropped_total`, but i don't know exactly which metric type of it.  

How can i get metric type, such as 'Gauge', by PromQL?

**Comment by brian-brazil** [comment]
This isn't possible, but the _total indicates a counter.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment]
Hint: The current answer is https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata , for better or worse…
