### ISSUE TITLE
how can i get history alerts info？

### ISSUE THREAD

**Issue by lddlww** [prometheus/prometheus#6126]
/api/v1/alerts   api only get current active alerts
ALERTS metric can get history alerts，but Its value is 1

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
