### ISSUE TITLE
regex exp. in unit test

### ISSUE THREAD

**Issue by e-ykaratas** [prometheus/prometheus#6148]
Hey there,

Can we use regex exp. while creating a series in unit testing? I want to have a series like
```
kube_pod_container_status_restarts_total{container=~"proxy|ingress-controller",namespace=".*xxx"}
```
And i'm getting this error : operator must be one of ["=="], is "=~"

Thanks in advance.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
