### ISSUE TITLE
how to get the specified time metric value

### ISSUE THREAD

**Issue by fight-for-future-and-family** [prometheus/prometheus#6201]
I want to get the metric value of  increasement yesterday
eg [ yesterday 00:00:00 ] - [ yesterday 23:59:59]  
thanks a lot

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
