### ISSUE TITLE
Where can I see the prometheus pull data log?

### ISSUE THREAD

**Issue by yusu123** [prometheus/prometheus#6244]
For example, Prometheus has no data for several minutes, so I want to know that Prometheus didn't pull data, but the target project didn't generate data.

**Comment by yusu123** [comment]
For example, Prometheus has no data for several minutes, so I want to know that Prometheus didn't pull data, but the target project didn't generate data.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
