### ISSUE TITLE
Time Range in prometheus

### ISSUE THREAD

**Issue by raydenz** [prometheus/prometheus#6246]
Hello,

For a time series called for example **"number_of_request"** 
i want to get all values between 8.00am to 10.00pm for the 10 last days 

I know i can get **ALL** the values of the 10 last days with the range selector [10d] **number_of_request{namspace="ns"}[10d]**

but i want only the values between 8.00am and 10.00pm

Can you help me please?

thank you very much

Ray

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by raydenz** [comment]
I am sorry,
I close the topic , thank you very much

regards,
Ray
