### ISSUE TITLE
Multi-core CPU machine statistics CPU average usage

### ISSUE THREAD

**Issue by lwx294821** [prometheus/prometheus#6252]
one machine has 16 cores, how to get average cpu ? need one PromQL

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by lwx294821** [comment]
In my company, cannot access the website 
https://groups.google.com/forum/#!forum/prometheus-users
