### ISSUE TITLE
kube_hpa_status_current_replicas does not show the Deployment reference

### ISSUE THREAD

**Issue by VF-mbrauer** [prometheus/prometheus#6253]
When using this Prometheus Metric I am not able to identify the Deployment. So it just shows the value of the HPA itself. So basically the naming. But it doesn't show, to which deployment it belongs to. When using the command `kubectl get hpa -n <mynamespace>` you will face the `Reference`field where you can find it.

Can this be implemented as part of the Metrics as it would be helpful for further processing of data?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
