### ISSUE TITLE
DNS resolution not working!

### ISSUE THREAD

**Issue by MacGyver27** [prometheus/prometheus#6286]
Hi,

Using this image (2.13.1) DNS resolution isn't working within the container:

```
/prometheus # ping grafana
ping: bad address 'grafana'
/prometheus #
```

Google says it's the problem with alpine image and it hasn't been resolved for many years.. This is a blocker for me since I want to configure host itself as a target and there is no way to do that..

I am using dockerhost container to fix the problem with accessing host within the container under linux.. And since I am not able to perform `ping dockerhost` also prometheus is not able to connect to the target:
```
  - job_name: 'traefik'
    static_configs:
      - targets: ['dockerhost:8082']
```

Please advise what I can do in order to overcome this DNS resolution limitation. Thanks

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development because XXX

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.org/?channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

If you think this is not purely a support question, feel free to comment in here or take the underlying issues to our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
