### ISSUE TITLE
Does Prometheus consider docking the parameter configuration to the database?

### ISSUE THREAD

**Issue by Jacky2** [prometheus/prometheus#6288]
## Proposal
**Use case. Why is this important?**

Does Prometheus consider docking the parameter configuration to the database, or provide corresponding extension functions?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
