### ISSUE TITLE
Can not get deployment CPU usage in promethues?

### ISSUE THREAD

**Issue by zehuaiWANG** [prometheus/prometheus#6289]
I built a promethues for my kubernetes, and I think it works well now. It can get node and container/pod cpu, memory Usage data, but I don't know how to get the kubernetes CPU Usage in promethues. Because in my application, if pod restart, deployment will not get data before. So could anybody tell me how to do it in this case.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
