### ISSUE TITLE
Result of other range time is different

### ISSUE THREAD

**Issue by thachnv92** [prometheus/prometheus#6290]
Hello,

I have data in Prometheus.
I use Grafana to query to show it.

When I custom range time: Yesterday.
=> I got 1441 data point.
every 1m have 1 data point.

When I custom range time: Last 3 days
=> I got 2161 data point.
every 2s have 1 data point.

So I can't sum data for my purpose.
I want to fix to get every 1m have 1 data point.
Please help me to configure it.

Thanks.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
