### ISSUE TITLE
why I can't see some data on grafana?

### ISSUE THREAD

**Issue by andyzheung** [prometheus/prometheus#6299]
I try to deploy the prometheus and grafana on k8s first time,  just can see the base info:

![image](https://user-images.githubusercontent.com/22912347/68587180-66e98280-04c1-11ea-970f-0b1987f47e9c.png)

![image](https://user-images.githubusercontent.com/22912347/68587197-710b8100-04c1-11ea-8d8c-980ec4632135.png)

how to check if where is not OK?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
