### ISSUE TITLE
federate return 404

### ISSUE THREAD

**Issue by arrow2012** [prometheus/prometheus#6318]
prometheus1  config

  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"mysql.*"}'
    static_configs:
      - targets:
          - '192.168.20.102:19090'

and return 404
![image](https://user-images.githubusercontent.com/46478986/68838359-60dde680-06f9-11ea-934e-25ef90714b3c.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
