### ISSUE TITLE
Prometheus restart very slowly

### ISSUE THREAD

**Issue by liubog2008** [prometheus/prometheus#6322]
prometheus version: v2.11.1

Prometheus costs too much time(about 20min or more) to replay WAL. I find that `loadWAL` is quick enough but files are loaded one by one.

My problem is why WAL files can't be loaded concurrently.

A closed issue without resolution: https://github.com/prometheus/tsdb/issues/611

**Comment by brian-brazil** [comment]
They depend on each other, so must be loaded serially.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by codesome** [comment]
@liubog2008 to add that that, WAL is like a record of events that happened in TSDB, which is the record of ingestion and deletion of samples. So if you want to get the same state back, we have to process the file serially to _replay_ the events. By design it cannot be done in parallel.

You can expect some improvement in the restart time in early 2020 which is in our roadmap.
