### ISSUE TITLE
matches time series instead of filter

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/prometheus#6340]
Proposal
**Use case. Why is this important?**
It's a new feature request.

When graphing, it is common that  we want to show the lines which exceeding the given threshold instead of showing data points.

## Bug Report
**What did you do?**
there is no way to do that at present.

**What did you expect to see?**
the whole time series which have samples exceeding the given threshold.

**What did you see instead? Under which circumstances?**
only samples which exceeds the threshold

Prometheus does support operator like this:
`metric{} > bool 10`
this will output 0 or 1 as value for all time series, but I want raw value in this case.

something like
`metric{} > raw 10`
which can output those metrics having values > 10.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by alburthoffman** [comment]
Thx, will post one on that.
