### ISSUE TITLE
Prometheus and cAdvisor docker monitoring

### ISSUE THREAD

**Issue by Sunitha82** [prometheus/prometheus#6342]
I am monitoring several containers using Prometheus, cAdvisor and Prometheus Alertmanager. I want is to get an alert if a container goes down for some reason. I would need just one rule for all containers to check if it goes down, is that possible?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
