### ISSUE TITLE
Prometheus Target is running up in Windows server but in Unix it says Context deadline exeeded

### ISSUE THREAD

**Issue by RohitBharatai15** [prometheus/prometheus#6374]
Hi my prometheus target is not working in Linux but when I configured the same in windows then it was working fine.
any reason?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
