### ISSUE TITLE
unexpect result when using re2 syntax regular expression in prometheus

### ISSUE THREAD

**Issue by markGbug** [prometheus/prometheus#6398]
when i query something in prometheus using regex like tihs :
sort_desc(sum by(envoy_cluster_name)sort_desc(sum by(envoy_cluster_name)(increase(envoy_cluster_upstream_rq_total{cluster_name=\~"gateway-proxy-1", envoy_cluster_name=~"^[^prometheus-server].*$"}[172800s])))

i want exclude the prometheus-server cluster , and i don't want to use the operator `!~`

and i found that :

using expression `^[^prometheus-server].*$`, it would missing some other envoy_cluster_name

using `envoy_cluster_name=~".*"}`
![image](https://user-images.githubusercontent.com/26535864/69947980-bbfd3f00-1529-11ea-8c39-743c383a5fed.png)

using `envoy_cluster_name=~"^[^prometheus-server].*$"}`

![image](https://user-images.githubusercontent.com/26535864/69948077-f070fb00-1529-11ea-9ed8-9086bfafad9d.png)

please figure out whether i am wrong  and the solutions 

PS: 
![image](https://user-images.githubusercontent.com/26535864/69948458-a3415900-152a-11ea-8621-94b92d54602c.png)

and RE2 syntax
https://github.com/google/re2/wiki/Syntax

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
