### ISSUE TITLE
Prometheus with Telegraf

### ISSUE THREAD

**Issue by rajat23495** [prometheus/prometheus#6399]
Hi, 
I am using Telegraf to ship or say expose my metrics on /metrics path for my prometheus operator service monitor to capture application metrics....
But i am facing a problem like since i am parsing my logs using telegraf so for every new timestamp it is creating a new time series..
For example - metrix_x(time=t1), metric_x(time=t2) 
So logically it should create a single time series with these timestamps as my base timestamp but i am not sure how to achieve that via telegraf and prometheus. 
Need help on this...
<img width="1360" alt="Screenshot 2019-12-02 at 7 54 18 PM" src="https://user-images.githubusercontent.com/52070535/69967174-de00bc80-153d-11ea-8342-825cf536c370.png">

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
