### ISSUE TITLE
the server property of consul_sd_configs was escaped and can't access

### ISSUE THREAD

**Issue by 631359746** [prometheus/prometheus#6404]
consul behind a reverse proxy. if i set the server like this 
`- server: 'host.docker.internal/consul'`
log below
`level=error ts=2019-12-04T07:34:11.344Z caller=consul.go:269 component="discovery manager scrape" discovery=consul msg="Error retrieving datacenter name" err="Get http://host.docker.internal%2Fconsul/v1/agent/self: dial tcp: lookup host.docker.internal/spring-boot-admin-server: no such host"`
the slash in path was escaped to %2F .
`curl http://host.docker.internal/consul/v1/agent/self`  could show the result

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
