### ISSUE TITLE
React UI: allow for second timestamp

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6406]
In the new ui the timestamp selector is rounded to the minute.

Being able to select the second is a must.

**Comment by boyskila** [comment]
Hi, I'll take a look at this

**Comment by boyskila** [comment]
@juliusv @roidelapluie in the classic UI inc/dec time input threshold is 10s but in the React UI, there is a range input with predefined values which can be either switched by inc/dec buttons or to directly type into it. Regarding this, two questions appear.

1. Should the old behavior remain in terms of the 10s threshold? It would work the same way except if the chosen range is < 10s

2. Since we can type into the input shouldn't be better to remove the predefined values and to leave the user to enter whatever he wants. Of course, some validation needs to be done, something like whether it starts with number and ends with {sec, hours, day/s}

Also in the current inc/dec implementation, the time is formed by the formula
```basetime + (range * 1000) / 2```
which seems to not work as (at least I) expected.
https://github.com/prometheus/prometheus/blob/0a0a228db380c3d68decd720016ba568af8b4b6d/web/ui/react-app/src/TimeInput.tsx#L42-L50

The (incorrect) behavior is most noticeable when the range is in second
So removing the division is the fix but I guess there is a reason to be done this way.

**Comment by roidelapluie** [comment]
@boyskila To answer your questions, I like the way it is implemented in your PR!
