### ISSUE TITLE
PromQL showing different number of cores in Grafana than the actual in Azure Kubernetes Cluster (AKS))

### ISSUE THREAD

**Issue by farhan-accuv** [prometheus/prometheus#6411]
## Bug Report

I'm using the below PromQL in the Grafana dashboard to retrieve/display the number of cores in our Azure Kubernetes Cluster (AKS):

`sum (machine_cpu_cores{kubernetes_io_hostname=~"^$Node$"})`

![2-12 Cores](https://user-images.githubusercontent.com/58519785/70257828-14feea00-1759-11ea-8c2e-e95d3c6008da.JPG)

The actual number of cores showing in the Azure Portal > Kubernetes Services > Scale is **24**.

![4-12 Cores](https://user-images.githubusercontent.com/58519785/70257888-352ea900-1759-11ea-882c-6c4ad01899fd.JPG)

However, **PromQL is returning 12 cores** in the Grafana dashboard, which is exactly the half.

![1-12 Cores](https://user-images.githubusercontent.com/58519785/70257763-f4cf2b00-1758-11ea-883e-25308603c6ab.JPG)

Am I using the right query? Is there any other way to get the correct number of cores from AKS? Does the Azure VM size _Standard DS13-4_v2 (8 vcpus, 56 GiB memory)_ (with 3 nodes) have to do anything with this?

Please help!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
