### ISSUE TITLE
POST and GET request returns inconsistent result on different pods 

### ISSUE THREAD

**Issue by sainap** [prometheus/prometheus#6474]
## Bug Report
We have two prometheus pods in the same cluster and namespace and when start time is specified equal to the end time, one pod returns empty data and another pod returns multiple rows of data.

POST:
`curl -X POST "http://localhost:9091/api/v1/query_range?start=2019-12-11T00:00:00Z&end=2019-12-11T00:00:00Z&step=15s" -d 'query=(kube_pod_status_phase{phase="Running", namespace="default"} ==1)'`

GET:
`curl "http://localhost:9091/api/v1/query_range?start=2019-12-11T00:00:00Z&end=2019-12-11T00:00:00Z&step=15s" -d 'query=(kube_pod_status_phase{phase="Running", namespace="default"} ==1)'`

**Environment**
Kubernetes version v1.16.2

* System information:
Darwin 18.7.0 x86_64

prometheus, version 2.10.0
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
