### ISSUE TITLE
What is the meaning of help information？

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#6508]
type Desc struct {
	// fqName has been built from Namespace, Subsystem, and Name.
	fqName string
	// help provides some helpful information about this metric.
	help string
	// constLabelPairs contains precalculated DTO label pairs based on
	// the constant labels.
	constLabelPairs []*dto.LabelPair
	// VariableLabels contains names of labels for which the metric
	// maintains variable values.
	variableLabels []string
	// id is a hash of the values of the ConstLabels and fqName. This
	// must be unique among all registered descriptors and can therefore be
	// used as an identifier of the descriptor.
	id uint64
	// dimHash is a hash of the label names (preset and variable) and the
	// Help string. Each Desc with the same fqName must have the same
	// dimHash.
	dimHash uint64
	// err is an error that occurred during construction. It is reported on
	// registration time.
	err error
}

**Comment by fcddk** [comment]
I think Desc.help is meaningless, we pay more attention to the metric and its value. So far I don't know the adverse effects of not setting a value for it.
Is there anything I can learn from perspectives and experiences?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
