### ISSUE TITLE
How to assign values to user defined variables in prometheus datasource and fetch it in Grafana?

### ISSUE THREAD

**Issue by daarunraj** [prometheus/prometheus#6532]
How to assign values to user defined variables in prometheus datasource and fetch it in Grafana?
As of now we are getting data in grafana from prometheus but we want to store data in some variables and then we want to use those variables in prometheus query.

Ex: rate(ifHCInOctets{ifIndex="xxx", instance="xx.xx.xx.x"}[30s])*8

we want to assign the instance values into a variable then we need to use it in the query.
Is it possible in prometheus.?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
