### ISSUE TITLE
Can't run `go build` and get the web interface built.

### ISSUE THREAD

**Issue by Vaelatern** [prometheus/prometheus#6606]
## Proposal
**Use case. Why is this important?**

Majorly simplifies packaging in distributions, and worked prior to and including 2.10.0

## Bug Report
**What did you do?**

I ran our distribution's packaging which runs a `go get` command, and ran the resulting binary. Instead of the interface I knew and loved, I got 
```
$ curl localhost:9090/graph
error reading base template: open web/ui/templates/_base.html: no such file or directory
```

This worked under 2.10.0.

I tried inserting a `make assets` before the build step, but got the same outcome even though the build now required yarn and ran some build steps.

**Environment**

* Source source

https://github.com/prometheus/prometheus/archive/v2.14.0.tar.gz

* System information:

	Linux 4.19.67_1 x86_64

* Prometheus version:

	2.14.0, possibly previous versions

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Vaelatern** [comment]
https://is.gd/OPsXNR
