### ISSUE TITLE
How can I avoid histogram_quantile return  "NaN" 

### ISSUE THREAD

**Issue by workhardcc** [prometheus/prometheus#6611]
**What did you do?**
`histogram_quantile(0.99,sum by (aaa,bbb,le) (rate(my_metrics_bucket{namespace!="abc"}[5m])))  `
The result as below :
`{aaa="1",bbb="2"}    NaN`
![image](https://user-images.githubusercontent.com/3250719/72254075-02bc7980-363e-11ea-810a-8e18a773133d.png)

**What did you expect to see?**
Maybe we can change the NaN to another value just like  0. Because  if the result is NaN, you can't see anything in grafana, I think it's not a good idea (Maybe we should give users the right to   change the result freely).
I understood why NaN  as link : https://stackoverflow.com/questions/47056557/how-to-gracefully-avoid-divide-by-zero-in-prometheus. 
Can I have any trick to change that result?

**Environment**
* Prometheus version:
	v2.15.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
