### ISSUE TITLE
double amount of metrics when using federation endpoint with two replicas

### ISSUE THREAD

**Issue by urban-it-solutions** [prometheus/prometheus#6614]
I try to scrape from federation endpoint, which resides inside an openshift cluster. The openshift-prometheus-instance has two replicas. I am getting double amount of metrics, labeled with "prometheus_replica=replica_0"  and "prometheus_replica=replica_1".

I would be great, if I could filter the replicas in my scrape-config.

- job_name: prometheus_openshift_prod
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{job="kube-state-metrics"}'
      - '{job="kubelet"}'
      - '{job="kube-controllers"}'
      - '{job="apiserver"}'
      - '{job="node-exporter"}'
      - '{job="kubernetes-apiservers"}'
      - '{__name__=~"job:.*"}'

I use Version 2.15.0
The problem is also described here:

https://github.com/openshift/telemeter/issues/151

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
