### ISSUE TITLE
When checkpoint is not successful, next checkpoint is twice the size.

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6619]
## Bug Report
**What did you do?**

Start prometheus with aggressive settings (--storage.tsdb.max-block-duration=10m --storage.tsdb.min-block-duration=1m)

Wait for a checkpoint:
data/wal/checkpoint.000040/

Let's say that the checkpoint has a size of 5M

Copy the checkpoint to data/wal/checkpoint.000042.tmp

_It simulates the case where the tmp checkpoint is not written completely_

**What did you expect to see?**

when checkpoint 0000042 is written, its size is 5M

**What did you see instead? Under which circumstances?**

checkpoint 0000042 is 10M, because it contains the tmp that was not written successfully.

**Environment**

Linux

* Prometheus version:

2.15.2

**Comment by brian-brazil** [comment]
Why was the original checkpoint not successful?

**Comment by roidelapluie** [comment]
In this case it is not even about being successful or not @brian-brazil . Just shutdown Prometheus in the middle of the compression process is enough.

**Comment by brian-brazil** [comment]
What do we do for compactions in that case?

**Comment by roidelapluie** [comment]
I see that the next checkpoints still get that huge size

**Comment by brian-brazil** [comment]
I mean what happens to the temporary files compaction uses if we shutdown?

**Comment by mback2k** [comment]
I think https://github.com/prometheus/prometheus/issues/6408 could be related. I was the one reporting this issue here to @roidelapluie on IRC yesterday. I am running into this issue again and again, because the system running prometheus does not have enough memory (12 GB shared with some smaller apps) to compress the WAL in time before getting evicted/killed by OOM.
