### ISSUE TITLE
/api/v1/alerts，receive more than one message，status is resolved？

### ISSUE THREAD

**Issue by lddlww** [prometheus/prometheus#6636]
when I customize the implementation of the / api / v1 / alerts interface  and receive an alert from prometheus. If this alert is resolved, I will receive multiple messages from prometheus with a status of resolved

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
