### ISSUE TITLE
Remove labels.Labels from generated_parser

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6663]
> > because {a="a",a="b"} is a valid promql query. And {a="a",a="a"} is even a query that can produce a result.
> 
> Those are selectors, not labels :)

Following this, I wonder if we really need `labels.Labels` in `promql/generated_parser.y`
as matchers would probably be enough.

cc @slrtbtfs 

Note: Maybe we use it as an optimization.

**Comment by roidelapluie** [comment]
After digging we are probably only using that for fuzzing.

**Comment by slrtbtfs** [comment]
In general it would be good from a performance point of view to get the number of types in that "union" down, since it transpilesto a quite large struct (>200 bytes if I recall correctly), of which 16 instances are preallocated by the generated parser. This makes each parser instance use at least 4kb of memory.

However none of the union-like mechanisms in go are particularly nice. One would be using an `interface{}` type and typecast, the other one would be using `unsafe` mechanisms.

I tried out the first one. It didn't create a significant performance improvement at that time, but complicated the code a lot.

The second one just doesn't seem worth it.

---
> After digging we are probably only using that for fuzzing.

The `labels. Labels` type here is used by the `promql.ParseMetric()` func. While it isn't used so much inside prometheus, it seems to be used by a couple of other projects:

https://github.com/search?q=%22promql.ParseMetric%28%22&type=Code
