### ISSUE TITLE
Prometheus connection refused to target http://xx.xx.xx.xxx:9090/federate which is running on Openshift

### ISSUE THREAD

**Issue by prathap12** [prometheus/prometheus#6681]
Hi,
I faced with an issue while evaluating monitoring approach with Prometheus/federate on Openshift
Actually I have deployed successfully Prometheus I need to federate those all into one global instance/federate on all nodes.
But, installed each Prometheus different openshift  container  and created one more openshift  for federate those all instance into another instance 
Error: Get http://10.0.0.107:9090/federate: dial TCP 10.0.0.107:9090: connect: connection refused
Prometheus.yml file
 - job_name: federate
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
        - '{__name__=~"node_proc.*"}'
    static_configs:
      - targets:
        - <ip-address>:9090

can anyone help me on, please

Thank you

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
