### ISSUE TITLE
Count function and labels not working together

### ISSUE THREAD

**Issue by srijith-nediyedath** [prometheus/prometheus#6710]
I have a requirement for our monitoring setup where I have to count the occurrences for each labels using count function. 

Requirement: Identify More than 2 restarts in 1 hour span from any pods
The query "count(count (round(increase(kube_pod_container_status_restarts_total[24h])) > 2)  by (container)) "
returns the total occurrences but the element column is displayed as "{}" nil. MEanwhile if i use 
 count(kube_pod_container_status_restarts_total{container=~".*"} >  3) by (container)
![Capture](https://user-images.githubusercontent.com/46027487/73268941-2bb34180-41dc-11ea-9d0b-030f11726a86.PNG)

I get individual values for each container. I need to count all the containers from the final value. Will it be possible?

The idea is to get the count of all pods which are getting restarted in 1 hour time

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
