### ISSUE TITLE
Improve label formatting in Table view, to align with Graph view

### ISSUE THREAD

**Issue by marians** [prometheus/prometheus#6722]
## Proposal

The React UI has a nice little formatting feature for labels in the graph legend. See this screenshot:

![image](https://user-images.githubusercontent.com/273727/73440036-e6fce700-4350-11ea-98b0-1697fa12bac3.png)

The bold emphasis improved the readability of labels a great deal, in my opinion.

However the table view doesn't offer the bold emphasis:

![image](https://user-images.githubusercontent.com/273727/73440113-0267f200-4351-11ea-8590-90e3d0a0bf32.png)

I vote for applying the same strong emphasis on label names, in order to

- let users benefit from the improved readability in the table view
- foster consistency between the UI components

**Comment by boyskila** [comment]
IMO totally valid, @juliusv

**Comment by juliusv** [comment]
Yes, I had it formatted at first, but formatting introduces a lot of DOM elements that make long tables really noticeably slow to scroll :(

Theoretically there would be the option of react-virtualized tables that only render the currently visible DOM elements, but that comes with more disadvantages, such as not being able to do a page-wide search.

One thing we could think about is enabling formatting for small tables and turning it off for larger ones. And then showing a notice above the table like:

```tsx
      {rows.length > 100 && (
        <Alert color="secondary">
          <strong>Notice:</strong> Showing more than 100 series, turning off label formatting for performance reasons.
        </Alert>
      )}
```

**Comment by drumilpatel2000** [comment]
@juliusv Can I take up on this issue?
This can improve readability for small tables

**Comment by boyskila** [comment]
I make a test with 2000 (I just clone the result multiple times) and it went well. The only issue I found was that it takes a few seconds to render the content. Maybe we should consider ```SeriesName``` to be refactored a bit to use less HTML since now every word is wrapped in a span. I think the same effect can be achieved with just one <strong> tag around the label name. Also, the table - I'm not seeing it as such. Perhaps this can be refactored as well like to be a div with some custom CSS on top(for sure will be cheaper than the table)

**Comment by juliusv** [comment]
> I make a test with 2000 (I just clone the result multiple times) and it went well. The only issue I found was that it takes a few seconds to render the content.

@boyskila Keep in mind not every computer is equally fast, but I definitely had noticeable scrolling lag on a reasonably fast computer with many thousands of items, so I think it's good to be conservative (also, it probably causes huge memory usage). But yeah, I think 100 is maybe too conservative for turning off formatting. Maybe 1000 or so?

> Maybe we should consider SeriesName to be refactored a bit to use less HTML since now every word is wrapped in a span. I think the same effect can be achieved with just one <strong> tag around the label name.

Yeah, that is an option. I think first we should play around with what formatting we want visually (the currenty one is totally improvised), and then we can see if we can optimize it. I'm not sure if we actually should have bold in there, for example, maybe different colors would be better (IDEs also usually do not highlight with bold font, just with colors).

But generally I think we don't have to worry too much about optimizations as long as we turn formatting off for very long tables?

> Also, the table - I'm not seeing it as such. Perhaps this can be refactored as well like to be a div with some custom CSS on top(for sure will be cheaper than the table)

I'm not sure what you mean with "I'm not seeing it as such", since it's clearly a use case of tabular data? For actual tabular data, isn't it best to use a table (otherwise you have to add ARIA info, and it's less automatically clear that it's tabular data). In any case I had no speed issues due to the table itself yet, because the table is super fast with un-formatted time series in it, just not with super long series lists that are formatted.

**Comment by boyskila** [comment]
> I'm not sure if we actually should have bold in there, for example, maybe different colors would be better (IDEs also usually do not highlight with bold font, just with colors).

We can support theming, hehe. But Yeah coloring like in the IDEs would be great

**Comment by boyskila** [comment]
> I'm not sure what you mean with "I'm not seeing it as such",

I mean that I'm not seeing it as a regular table with a header, titles, columns, etc. - visual element specific for the tables

**Comment by juliusv** [comment]
> I mean that I'm not seeing it as a regular table with a header, titles, columns, etc. - visual element specific for the tables

I see it as just a regular table, with structured A -> B data displayed in two columns. The only reason why there's no column headers is that I hope that it's obvious to users what each column contains. The old UI did actually have column headers (http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=node_cpu_seconds_total&g0.tab=1).
