### ISSUE TITLE
promtool does not report error in rule file

### ISSUE THREAD

**Issue by mvoeckle** [prometheus/prometheus#6741]
### Promtool does not report all errors in rule file
In our case spell check does not work correctly within a rule. Prometheus is able to be reloaded via "reload" URL, but Prometheus will fail when Prometheus Pods are redeployed (within OpenShift).
See my rule below which does not fail within reload URL, but which causes Prometheus to fail during Pod redeployment
**This makes Prometheus reload via URL useless when modifying rules**
Our example rule:
`record: custom_container_running_requested_cpu_compute
expr: (0*sum(kube_pod_status_phase{phase="Running"} == 1) by (pod, namespace)) + on(pod,namespace) (sum(kube_pod_container_resource_requests_cpu_cores) by (pod, namespace, node) + on(node) group_left(label_node_role_kubernetes_io_compute) (0*kube_node_label {label_node_role_kubernetes_io_compute="true"}
))`
The "s" is missing in "kube_node_labels"
Promtool does not report this error, Prometheus is reloaded using the Reload-URL.
Prometheus restart (Delete Pod, create Pod) is failing.

### Bug Report
**What did you do?**
Prometheus reload (and "promtool check rules") does not report error in rule file
**What did you expect to see?**
Error is reported to make sure Prometheus is working correctly and Prometheus Pod redeployment is successful
**What did you see instead?**
`[user@computer prometheus-2.15.2.linux-amd64]$ ./promtool check rules ~/ansible-tests/prometheus/prometheus-record.rules
Checking /home/<user>/ansible-tests/prometheus/prometheus-record.rules
SUCCESS: 14 rules found`
**Environment**
Prometheus version: prometheus-2.15.2.

**Comment by brian-brazil** [comment]
That is a valid rule, so there's no issue for promtool to detect - you'd want unittests for that. Whatever issue you are having is not related to this typo.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
