### ISSUE TITLE
Support for making label value as metric values when label value is numeric and changes in each Scrape

### ISSUE THREAD

**Issue by deviojha09** [prometheus/prometheus#6759]
My snmp exporter is scraping OID values as below
currentSourceOffset{currentSourceOffset="-0.000000010"} 1
the actual value for the OID is -0.000000010 but this comes in as label, 

I understand, having a dynamic label for metric will put burden on Prometheus database, it would really handy if using relabel we can drop the label and make   -0.000000010 as the value.
and result metric could be as below.
currentSourceOffset  -0.000000010

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
