### ISSUE TITLE
Repeating resolved alerts for approximately 15 minutes

### ISSUE THREAD

**Issue by MCNVI** [prometheus/prometheus#6782]
Is there any opportunity to switch off repeating resolved alerts from prometheus? 
![image](https://user-images.githubusercontent.com/23380910/74011766-aa0ca200-4999-11ea-92f2-19c300972eb5.png)

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
