### ISSUE TITLE
Prometheus cert ssl expriry 

### ISSUE THREAD

**Issue by Daly123456** [prometheus/prometheus#6801]
Hi i got this problem while monitoring ssl expiry !

the 2 row got the same querry but i could"nt visualise the same thingh in both rows !

any help ?
![image](https://user-images.githubusercontent.com/46686877/74165927-1ac7ee80-4c26-11ea-85de-7a1868020ed5.png)

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
