### ISSUE TITLE
federate for Prometheus rules

### ISSUE THREAD

**Issue by teochenglim** [prometheus/prometheus#6809]
## Proposal
**Use case. Why is this important?**

I have tons of Prometheus (Kubernetes Prometheus Operator) rules already setup individually. But when I want to centerise multiple Prometheus, the metrics is there... but not the alerting rules. It would be nice Prometheus rules forwarded just as metrics

*“Nice to have” is not a good use case. :)*

Empower developer to create their own rules (Kubernetes CRD PrometheusRules) , . I am a lazy infra guy.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
