### ISSUE TITLE
Why does this setting trigger an alarm in five minutes? Shouldn't it be three minutes?

### ISSUE THREAD

**Issue by 15980583357** [prometheus/prometheus#6818]
<img width="588" alt="afef8825d4f3c35ad5d5b4d53af11af" src="https://user-images.githubusercontent.com/47803700/74493339-d2058380-4f0c-11ea-9c5a-b22416ef9f40.png">
<img width="406" alt="4457fd041a2a2aa0b49fbd74835ef41" src="https://user-images.githubusercontent.com/47803700/74493359-e47fbd00-4f0c-11ea-9c50-194d63dadee0.png">

**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
