### ISSUE TITLE
Unable to query with timestamp instead it display results in time series

### ISSUE THREAD

**Issue by prashanth-sams** [prometheus/prometheus#6842]
I have issues with prometheus queries on fetching exact data-points; instead it collects data as a time series as in this image

![image](https://user-images.githubusercontent.com/2948696/74755535-c60f1e00-528c-11ea-9f3a-cb092133c056.png)

I don't wish to display the excess data filling the gaps as a time series

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
