### ISSUE TITLE
Prometheus-services Showing zero

### ISSUE THREAD

**Issue by Srinivasa381224** [prometheus/prometheus#6846]
Hi am srinivasa am installed prometheus in my EKS cluster using Helm charts currently its running fine But my Project manager asking to do some modifications that is He needs a notifications Through Google chats or Email When Total service is goes down, But currently we are setup notifications in pod level But in my production we have lot of pods in single service its scaling up and down we are getting notifications but we dont need pod level notifications we need a notifications when all pods in that service goes down, In prometheus am seing one option kubernetes-services (0/0 up) it is showing 0 Please suggest me we have any option to trigger notifications when pods count goes 0 that is entire pods in service is goes down, Please help me for this configuration

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
