### ISSUE TITLE
Subquery with 1d resolution is incorrect

### ISSUE THREAD

**Issue by huynhsamha** [prometheus/prometheus#6862]
**What did you do?**
I've computed the average over **past 30 days** from now with the same minute **by day**.
Example, at _8:20 AM_, I'll compute the average of points which is data at _8:20 AM_ in the last 30 days from now.

My global resolution is **1 minute**.

I've _precomputed rate in 5m_ and I have the instant vector `req_stat:rate`

I've tried average with _resolution 1m (default resolution)_ and it's worked

```
req_stat:rate[2d:1m] offset 1d
```

But when I tried with _resolution 1d_, it always returns data at `07:00:00 GMT+0700` in every day

```
req_stat:rate[30d:1d] offset 1d
```

**What did you expect to see?**

I'd like it will return data points at the _minute which is same as now_. In my example, it should be return data at 8:20 AM in the last 30 days.

**What did you see instead? Under which circumstances?**

**Environment**

Linux, Centos

* System information:

	insert output of `uname -srm` here
Linux 3.10.0-514.21.1.el7.x86_64 x86_64

* Prometheus version:

	insert output of `prometheus --version` here
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Additionally, this blog post will provide you some hints to this particular request: https://www.robustperception.io/promql-subqueries-and-alignment
