### ISSUE TITLE
rate functions not working for Prometheus 

### ISSUE THREAD

**Issue by shivali-chauhan** [prometheus/prometheus#6863]
Hi  Team,

I have configure jmx exporter on my kafka server. 
and i am using grafna  for visualization.
i am not able to get kafka metrics value using rate() or irate() fuction.

query:
sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job="Kafka",topic!=""}[5m])) 

its working without rate () function could you please solve the issue

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
