### ISSUE TITLE
Support "without" operator for changes function

### ISSUE THREAD

**Issue by Guchman** [prometheus/prometheus#6871]
Hi,
We have a mesos/marathon exporter and we want to annotate restarts in our grafana.
The problem is that each new application creates new sequence with new mesos_task_id tag value.
It would be fine to use something like `changes(process_start_time_seconds{application="$application", instance="$instance"}[10m]) without mesos_task_id`
but "without" is not supported for changes function:( Thanks

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Guchman** [comment]
Mmm, I don't really think it's an question:) it's a feature request, correct me if I'm wrong, but changes() doesn't support "without" statement

**Comment by roidelapluie** [comment]
I think you want `count(process_start_time_seconds unless process_start_time_seconds offset 5m) without(mesos_task_id)`.

**Comment by roidelapluie** [comment]
or count(process_start_time_seconds - time() < 300) without(mesos_task_id)
