### ISSUE TITLE
avg_over_time() anomaly when input disappears

### ISSUE THREAD

**Issue by belm0** [prometheus/prometheus#6873]
**What did you do?**

`avg_over_time()` for [1h] on a metric with values in the set {0, 1} and which eventually disappears

**What did you expect to see?**

output series should end at value 0, one hour after input disappears 

**What did you see instead? Under which circumstances?**

output series has an anomaly, ramping up after input disappears and ending at the value 1

I noticed that the sum_over_time() output is fine, so I worked around this problem with sum_over_time() ÷ duration.

This graph shows the input, `avg_over_time()` output, and `sum_over_time() ÷ duration` output (with a slight Y offset for visibility).

![Screen Shot 2020-02-26 at 9 05 41 AM](https://user-images.githubusercontent.com/1708631/75299549-b4bfa600-5878-11ea-8159-50c7213ae419.png)

**Environment**

* Prometheus version: 2.9.2

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

In your case, avg_over_time will only use the last datapoints at the end when the output disappears, which is expected.

**Comment by roidelapluie** [comment]
sum_over_time() / duration is not equivalent.

**Comment by belm0** [comment]
I see-- avg_over_time() is only counting time with datapoints.  So as the majority of the time window covers undefined data, the output converges to the last datapoint.
