### ISSUE TITLE
Are samples returned by `chunkenc.Iterator` supposed to be sorted by time?

### ISSUE THREAD

**Issue by pstibrany** [prometheus/prometheus#6876]
It's not clear from `chunkenc.Iterator`, whether iterated samples are expected to be in ascending time order or not. (I always assumed yes, but now I'm not sure anymore). Can we please document expected behavior of iterators and returned samples?

https://github.com/prometheus/prometheus/blob/59c9d6ef4593757e3910e21cd08769d9c2d49a49/tsdb/chunkenc/chunk.go#L77

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pstibrany** [comment]
I was hoping to see this clarified in the documentation.

**Comment by pstibrany** [comment]
... to `chunkenc.Iterator` interface. That's where it belongs.

**Comment by bwplotka** [comment]
Yes, Feel free to propose a PR. I think this is guaranteed already, just let's state in comment.

**Comment by pstibrany** [comment]
Sent #6877 :)
