### ISSUE TITLE
Prometheus set GOMAXPROCS

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#6917]
During use, it was found that prometheus would have a very high CPU usage. It would fill up all cores and reach a peak value of 100%. However, adding code for Go's cpu core limit improves the situation.

**Comment by fcddk** [comment]
arm64 env:
cpu：
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           0x70
Model:               2
Stepping:            0x1
BogoMIPS:            100.00
NUMA node0 CPU(s):   0-15
Flags:               fp asimd evtstrm crc32 cpuid

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
