### ISSUE TITLE
Prometheus and loki as storage

### ISSUE THREAD

**Issue by fredbcode** [prometheus/prometheus#6946]
Hello,

Maybe I'm missing something but use loki as remote endpoints and storage is something realistic ?  
For now I'm using timescaledb with good performances but I'm thinking about something like elastic cluster that offers many benefits

There are already some storage methods https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage but no full grafana/prometheus/loki integration 

Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fredbcode** [comment]
Hello, maybe I'm wrong but my question is about enhancement not actual usage
