### ISSUE TITLE
how to monitor and set alert for 3xx redirection in servers.pls suggest.

### ISSUE THREAD

**Issue by continuum-pooja** [prometheus/prometheus#6969]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
