### ISSUE TITLE
prometheus graphics keep refreshing data will make an error

### ISSUE THREAD

**Issue by StandNorthStar** [prometheus/prometheus#6973]
We output the metrics through the program. At 15:30, a condition is artificially triggered and the output value is 1 at this time. But I keep refreshing this value will become the wrong value 2.

My config:
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 10m
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: pushgateway-test
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:

Correct graphics：
![ok](https://user-images.githubusercontent.com/18138867/76539861-50c5f000-64bc-11ea-9aae-c4d2fcf69e18.png)

Wrong graphics
![error](https://user-images.githubusercontent.com/18138867/76539939-6b986480-64bc-11ea-9e89-41f8fa0435bd.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
