### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#6984]
prometheus: version2.15.2

config:
global:
  scrape_interval: 1m
  scrape_timeout: 1m
  evaluation_interval: 1m

prometheus-center  pull the sub_prometehus
sub_prometheus log: 
level=error ts=2020-03-14T09:04:55.620Z caller=federate.go:184 component=web msg="federation failed" err="write tcp 10.151.16.31:9090->10.151.10.34:39190: write: connection reset by peer"

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
