### ISSUE TITLE
Node Exporter Targets needs to be automated on Prometheus.yml file

### ISSUE THREAD

**Issue by vikram-yerneni** [prometheus/prometheus#7007]
Node Exporter deamon running on nodes might auto-scale in Kubernetes/EKS/AWS world. Which means the node names/IP's will change and the prometheus.yml file needs to be automatically updated with the new nodes.
Any chance it can be included within?

Thanks
Vikram

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vikram-yerneni** [comment]
I did asked in the group to Brian. Let me close this one then...
