### ISSUE TITLE
different result between raw metric and metric of record rules

### ISSUE THREAD

**Issue by fzxbl** [prometheus/prometheus#7056]
![image](https://user-images.githubusercontent.com/31810871/77667439-29dbe380-6fbd-11ea-80a7-b51df3864802.png)
![image](https://user-images.githubusercontent.com/31810871/77667480-37916900-6fbd-11ea-8730-879199afc24f.png)
when I used metric generated of record rules and raw metric, there is a gap, about 10%. 
this is my record rules:
    rules:
    - record: sum:instance_cpu_quota:cell:product:marker:functional_marker
      expr: sum(instance_cpu_quota)by(cell,product,marker,functional_marker)
    - record: sum:instance_mem_quota:cell:product:marker:functional_marker
      expr: sum(instance_mem_quota)by(cell,product,marker,functional_marker)
    - record: sum:instance_mem_quota:cell:product:marker:functional_marker
      expr: sum(instance_mem_quota_bytes)by(cell,product,marker,functional_marker)
    - record: sum:instance_ssd_quota:cell:product:marker:functional_marker
      expr: sum(instance_ssd_quota_bytes)by(cell,product,marker,functional_marker)
    - record: sum:instance_hdd_quota:cell:product:marker:functional_marker
      expr: sum(instance_hdd_quota_bytes)by(cell,product,marker,functional_marker)
    - record: sum:instance_cpu_used:cell:product:marker:functional_marker
      expr: sum(instance_cpu_used)by(cell,product,marker,functional_marker)
    - record: sum:instance_mem_used:cell:product:marker:functional_marker
      expr: sum(instance_mem_anon_bytes)by(cell,product,marker,functional_marker)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
