### ISSUE TITLE
resets counter sometimes ignored

### ISSUE THREAD

**Issue by Ivanbmstu** [prometheus/prometheus#7074]
Hello everyone, sometimes prometheus handle multiple resets during service restarts, for example on screen you can see one resets on host and 20 resets on other host (one service per host).
![image](https://user-images.githubusercontent.com/6125943/78006516-cbf52600-7345-11ea-842d-8d14c40768d2.png)

Now request counter metrics are: 
![image](https://user-images.githubusercontent.com/6125943/78007522-13c87d00-7347-11ea-9631-bf62c2f1f6fb.png)

And finally, in grafana we see huge spike in the service rps (+3 GMT)
![image](https://user-images.githubusercontent.com/6125943/78007837-820d3f80-7347-11ea-9b36-563bdb07022f.png)

Is it bug or why prometheus handle 20 resets on service restart sometimes? 

**Environment**

* Prometheus version:

Version 2.12.0
Revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86
BuildUser: root@7a9dbdbe0cc7
BuildDate: 20190818-13:53:16
GoVersion: go1.12.8

**Comment by brian-brazil** [comment]
There's insufficient information here to indicate a bug, so I have to presume this is actually a support request.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
