### ISSUE TITLE
High scaping interval & timeout

### ISSUE THREAD

**Issue by Ebenolt** [prometheus/prometheus#7101]
Hello,
I'm new to Prometheus, i'd like to monitor wireless AP (Cisco Meraki ones) through SNMP, and Cisco made a centralized SNMP system, you only need to scrape one target and it will drop you metrics for all your APs.
I currently got 20 APs to monitor, so scraping takes a while (request times in seconds: https://share.ebenolt.com/08_04_20_0ee981.png )
Scrape interval can't go lower than scrape timeout (502 Bad Gateway) , but scrape interval can't go higher than 65s (context deadline exceeded). 
so my current job config times:
```
scrape_timeout: 60s
scrape_interval: 65s
```
Is there any way to allow Prometheus to scrape with a timeout ~= 120s ?
Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
