### ISSUE TITLE
Discover all EC2 tags and send as prometheus label

### ISSUE THREAD

**Issue by infa-kparida** [prometheus/prometheus#7110]
**What did you do?**
I would like to discover all ec2 tags and send it as label with all metrics generated from it 
Something like below 
 - job_name: 'my_ec2_discovery'
    ec2_sd_configs:
      - region: "us-west-2"
        refresh_interval: 300s
        port: 9100
        filters:
          - name: tag:Name
            values:
              - a
              - b
    relabel_configs:
      - source_labels: [__meta_ec2_tag_*]  <--------Applied to all tags 
        regex: (__meta_ec2_tag_)(.*)
        target_label: $2

**What did you expect to see?**
All the service tags going to prometheus as labels to all metrics 

**What did you see instead? Under which circumstances?**
I have to manually apply relabel_config to each and every tag that I need

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
