### ISSUE TITLE
win10  with spring metrics No datapoints found. 

### ISSUE THREAD

**Issue by drduan** [prometheus/prometheus#7111]
prometheus-2.17.1.windows-amd64 with

micrometer-registry-prometheus 1.3.6

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
