### ISSUE TITLE
What is the best way to prevent OOMKIilled error

### ISSUE THREAD

**Issue by nishant-ketu** [prometheus/prometheus#7113]
Even having the retention time set, the Prometheus pods are failing with OOMKilled error. How to remove WAL? Can I set up Cron Jobs for that?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
