### ISSUE TITLE
promtool: Add Data Importers for the most requested formats.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7119]
As per discussions [here](https://github.com/prometheus/prometheus/pull/5887#issuecomment-613293309), [here](https://matrix.to/#/!WaUKIfoqfiyWQhenET:matrix.org/$1586852036856415fvdsV:matrix.org?via=matrix.org) and [here](https://github.com/prometheus/prometheus/issues/535#issuecomment-613264216) we would love to clarify what format we need to enable on `promtool` to solve most of backfilling use cases Prometheus Ecosystem users have! :hugs: 

Please vote via this Tweet: https://twitter.com/PrometheusIO/status/1249983109497585667

EDIT: The 7-days vote on Twitter finished with the following results:

![image](https://user-images.githubusercontent.com/6950331/79998557-bbeae500-84b2-11ea-955c-a72a19c1c7d3.png)

Thanks all for voting!

It's worth to note that there was some "secret unknown" contributor who proposed JSON, but it did not get much attention. Maybe if it would part of the poll it would get bit higher. :upside_down_face: 

![image](https://user-images.githubusercontent.com/6950331/79998693-e89efc80-84b2-11ea-98ad-1098128d3700.png)

Based on that we could form some kind of priority:

## Priority

* [ ] Remote-write
* [ ] CSV file (potentially TSV)
* [ ] Streaming API with Open Metrics / Prometheus TEXT format
* [ ] Open Metrics file (Direction of https://github.com/prometheus/prometheus/pull/5887)
* [ ] JSON

I think this is the way we should go. Added as a topic for DevSummit as well.

Additionally, I've created a design doc for backfilling items that might be missing: https://docs.google.com/document/d/15wKdeFntgUmEnV8kqQ_5iQEIhXnwU8HNm0NKlkR0xk4/edit# and what decisions we need to still make as a community and team e.g How many of those formats we should support when we should say stop and allow others to add [prometheus-community](https://github.com/prometheus-community) projects rather?

**Comment by brian-brazil** [comment]
Streaming APIs and remote write would be push, which we should never add to Prometheus. I don't think we should be inventing new formats via CSV, and instead focus on existing exposition formats.

**Comment by bwplotka** [comment]
We never said it should be part of Prometheus or not. We are just talking what to *enable*. We can totally add `promtool` that accepts remote write and create vertical blocks :shrug: (: So this one is just implementation detail. However for anything we need to know what would be the facing API / format.

Also I added this topic for our Prometheus Dev Summit :hugs:

**Comment by gillg** [comment]
CSV could be simple, but it seems complicated to import unstructured data. Metrics could arbitrary have labels, so I have no ideas for a simple CSV import.

For "remote-write" feature, (as you already know) Thanos cluster could be a good source of inspiration. They implement a receiver component (in beta status actually), which is understanding remote-write from another prometheus (https://github.com/thanos-io/thanos/pull/811). But I'm a little according with @brian-brazil Streaming API should be avoided to not encourage "push" and lot of new issues... "Push" should be limited to promtool cli.

OpenMetrics is the native format of prometheus (modulo timestamp formats...). It is not optimised for huge volumes and could be very heavy but it's a good starting point.

Other "compacted" format should be very appreciables to ingest massively old metrics. Anyone has ideas ?

**Comment by brian-brazil** [comment]
> We can totally add promtool command that accepts remote write or streaming OpenMetrics and creates vertical blocks

As I've stated in other discussions promtool should only ever be a CLI tool, not a daemon.

> It is not optimised for huge volumes and could be very heavy 

I'm not sure where you're getting that idea, a Prometheus server can already ingest millions of samples per second in the text formats and it's not the parser that's the bottleneck.

**Comment by gillg** [comment]
> It is not optimised for huge volumes and could be very heavy
> I'm not sure where you're getting that idea, a Prometheus server can already ingest millions of samples per second in the text formats and it's not the parser that's the bottleneck.

I don't speak about capacity to ingest, data but about import data manipulation. In my tests, one OpenMetrics file must be sorted by timestamps and weight 20Go for 137 021 241 samples. It's not easy to build this uniq text file, sort it, manipulate it. I have no better ideas for now, but it's a perfectible point. For example a compacted format gziped with a set of sorted files instead of a huge uniq text file.

**Comment by brian-brazil** [comment]
> OpenMetrics file must be sorted by timestamps 

That's not quite the case, metrics must be grouped and within that for duplicate childs they must be sorted by time - however sorting on time is required for everything as the tsdb requires data to be ingested in-order.

**Comment by bwplotka** [comment]
Updated the description of this issue with following: 

The 7-days vote on Twitter finished with the following results:

![image](https://user-images.githubusercontent.com/6950331/79998557-bbeae500-84b2-11ea-955c-a72a19c1c7d3.png)

Thanks all for voting!

It's worth to note that there was some "secret unknown" contributor who proposed JSON, but it did not get much attention. Maybe if it would part of the poll it would get bit higher. :upside_down_face: 

![image](https://user-images.githubusercontent.com/6950331/79998693-e89efc80-84b2-11ea-98ad-1098128d3700.png)

Based on that we could form some kind of priority:

## Priority

* [ ] Remote-write
* [ ] CSV file (potentially TSV)
* [ ] Streaming API with Open Metrics / Prometheus TEXT format
* [ ] Open Metrics file (Direction of https://github.com/prometheus/prometheus/pull/5887)
* [ ] JSON

I think this is the way we should go. Added as a topic for DevSummit.

As remote write will be hard to add, starting with CSV would make sense. This will be quite easy in context of https://github.com/prometheus/prometheus/pull/5887 to just switch format, or add CSV on top of open metrics which is already (done?). I leave that decision to @krasi-georgiev and @dipack95 

I happy to attack remote write potential backfilling via some remote tool, in my free time will work adapting [my design doc](https://docs.google.com/document/d/15wKdeFntgUmEnV8kqQ_5iQEIhXnwU8HNm0NKlkR0xk4/edit#) for that. Anyone is welcome to take it from me anytime as well :hugs:

**Comment by brian-brazil** [comment]
> As remote write will be hard to add, 

That would be push and it's unclear to me how you'd go from e.g. an existing Graphite setup to this - you'd have to basically write Go code to speak remote write at which point you may aswell produce tsdb blocks more directly. The Thanos receiver also already does this.

> Streaming API with Open Metrics 

There is no such thing, OpenMetrics is not streaming.

> just switch format, or add CSV on top of open metrics which is already

I'd rather not end up in a position where we support N different formats.

> JSON

I think the point here is more that there should be an easy way to backfill recording rules, how that's actually done would hopefully be more of an implementation detail.

**Comment by bwplotka** [comment]
> That would be push and it's unclear to me how you'd go from e.g. an existing Graphite setup to this - you'd have to basically write Go code to speak remote write at which point you may aswell produce tsdb blocks more directly. The Thanos receiver also already does this.

Yea, the idea would be essentially small CLI Thanos Receive with some snapshot technique on exit which will put block in Prometheus dir / Thanos object storage.

> There is no such thing, OpenMetrics is not streaming.

Sure, the same with just "OpenMetrics" - it does not exist in the form of old "pages" gathered up.

> I'd rather not end up in a position where we support N different formats.

Cool, this means you suggest we should have CSV?

**Comment by bwplotka** [comment]
> I think the point here is more that there should be an easy way to backfill recording rules, how that's actually done would hopefully be more of an implementation detail.

For this, I planned to have totally separate component, which actually already exists: https://github.com/yeya24/backfiller We should start another ticket / discussion on how to embed it and if we want to.

I would see this as promethues-community project  :hugs: any thoughts @yeya24 ?

**Comment by brian-brazil** [comment]
> Yea, the idea would be essentially small CLI Thanos Receive with some snapshot technique on exit which will put block in Prometheus dir / Thanos object storage.

My question is, is this actually a useful way to backfill? I don't see why you'd need to hit the network in order to write a file to disk. If you can write Go to import the remote write encoder and speak http, you can write Go to import the tsdb appender - which is already possible today.

I've also gone over the original issue, and no one ever requested such an architecture as a way to do backfill - nor do I recall it coming up prior to this poll. The mentions are all about files. This makes me question how much weight should be put on the poll.

> For \[backfilling recording rules], I planned to have totally separate component,

I've always felt that this should be part of promtool, possibly with a little bit of scripting around it depending on how the implementation works out.

> Cool, this means you suggest we should have CSV?

That's a possibility, but I'd also prefer that we don't proliferate formats. What's the actual workflow we're aiming for here for say the use case of migrating an old Graphite database?

Keep in mind that "CSV" is not one format but a family of variously well defined formats, whereas we have formats like the text exposition format which are fully defined including things like escaping.

**Comment by yeya24** [comment]
> For this, I planned to have totally separate component, which actually already exists: https://github.com/yeya24/backfiller We should start another ticket / discussion on how to embed it and if we want to.
> 
> I would see this as promethues-community project 🤗 any thoughts @yeya24 ?

Thank you for mentioning me here. However, I have some concerns.

The recording rules backfilling is one of the gsoc projects this year. Does any student work on this project now?

I agree with Brian that this feature should be part of promtool. Since #5887 is still WIP, and my project uses part of that PR's code, I think it is better to get #5887 merged first. Then it is quite easy to add recording rules backfilling to promtool.  WDYT @bwplotka ?

But anyway, that project is just a toy/demo, it lacks tests. And it might not be correct since I didn't get any feedback about it. It would be very appreciated if anyone could help review it

**Comment by dipack95** [comment]
Regarding #5887, like I've said earlier, adding a CSV parser is something that can be done independent of the actual logic, and I suggest we merge the PR first, before we add support for alternative formats to import data.

**Comment by aleskandro** [comment]
Hi all, I needed to implement a back-filling job to import data from different sources (parquet files and mysql databases). I released it as a Golang library that can be easily used by providing (1) model structs with specific tags to convert them into TSDB and (2) a Go routing to send slices of models instances to a channel in order to be processed by the job. Here a link, if anyone is interested: https://github.com/aleskandro/go-prometheus-backfiller/tree/master

**Comment by jrab66b** [comment]
@aleskandro looks great, I believe I have a use case for your library :metal:

**Comment by bwplotka** [comment]
Hello from the bug scrub!

We added backfilling options in the past:

* From OpenMetrics file https://prometheus.io/docs/prometheus/latest/storage/#backfilling-from-openmetrics-format
* From recording rules https://prometheus.io/docs/prometheus/latest/storage/#backfilling-for-recording-rules

This means we delivered **some** data importers, but not the remote write.

Doing this via remote write is controversial as it's streaming vs here we talk about bulk import. I would say let's close this issue as it's satisfies a lot of import cases. If anyone want to have a full backfilling/bulk filling capable remote write APIs we can create another issue, but we need to talk about similar capability for client(senders) too, which is not trivial (: 

There is indeed a 3rd party exporter that allows you to code in your format (?) https://github.com/aleskandro/go-prometheus-backfiller/tree/master

Thanks everyone!
