### ISSUE TITLE
double amount of metrics when using federation endpoint with two replica

### ISSUE THREAD

**Issue by veer123prathap** [prometheus/prometheus#7123]
we are also facing same issue with federate Prometheus what you face earlier if you provide a solution to me it really helpful to me
I try to scrape from the federation endpoint, which resides inside an open shift cluster. The openshift-prometheus-instance has two replicas. I am getting the double amount of metrics, labeled with "prometheus_replica=replica_0" and "prometheus_replica=replica_1".

job_name: prometheus_openshift_prod
honor_labels: true
metrics_path: '/federate'
params:
'match[]':

-'{job="kube-state-metrics"}'

'{job="kubelet"}'
scheme: https
static_configs:
-targets:
- endpoint

Thanks,
Veera

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
