### ISSUE TITLE
the same value for different partition of system？

### ISSUE THREAD

**Issue by loveyang2012** [prometheus/prometheus#7140]
![image](https://user-images.githubusercontent.com/24237714/79629227-4d3c1d80-817a-11ea-9221-38be703ff73f.png)

when i use node_filesystem_size_bytes to get disk value ，i get the same value 。why ？
my system disk partition is like this：
![image](https://user-images.githubusercontent.com/24237714/79629255-a310c580-817a-11ea-9d73-b81554bc0220.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
