### ISSUE TITLE
How can I configure amount of data kept in memory?

### ISSUE THREAD

**Issue by steve1337** [prometheus/prometheus#7146]
In version 1.8 there was a flag (storage.local.target-heap-size) which allowed to configure how much data is kept in memory.

To my understanding this was removed in version 2.0+ due to the use of TSDB storage format. 

Where can I find documentation for configuring the amount of data kept in memory for the latest version (2.17)?

**Comment by roidelapluie** [comment]
Thanks for your report.

In the 2.x relase, you can not configure this. Prometheus will use the RAM it needs, no more, no less.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Tyrael** [comment]
hi @roidelapluie , is there any reason why this change is not documented at all?
no mention in either https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md or https://prometheus.io/docs/prometheus/latest/migration/

**Comment by roidelapluie** [comment]
In the migration I see:

```
-storage.local.* Prometheus 2.0 introduces a new storage engine, as such all flags relating to the old engine have been removed. For information on the new engine, see Storage.
```
