### ISSUE TITLE
How to use api to create or update or delete alert rule ?

### ISSUE THREAD

**Issue by wuguanyu** [prometheus/prometheus#7154]
https://github.com/prometheus/alertmanager/issues/2239

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by wuguanyu** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I can't open this url https://groups.google.com/forum/#!forum/prometheus-users  in my computer

I can't find any useful api docs in our website,So i open a issue to ask for help

**Comment by wuguanyu** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I need a identified reply I think you maybe not be closed this issue
