### ISSUE TITLE
To delay evaluation for newly created host

### ISSUE THREAD

**Issue by mohag1412** [prometheus/prometheus#7166]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

**Comment by mohag1412** [comment]
Use case: 
It filters unwanted alert getting triggered. Newly provisioned instances will take 5 mins atleast stabilize. If rules are evaluated before that time unwanted alerts gets triggered. This feature is very useful for cloud instances with ASG enabled.

**Comment by brian-brazil** [comment]
This is something to handle in your rules themselves (such as a predicate on uptime), as Prometheus has no notion of hosts being created.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
