### ISSUE TITLE
skipping data for higher step value

### ISSUE THREAD

**Issue by pavanmehtre69** [prometheus/prometheus#7202]
configured scrape interval 5s

Doing query from UI :-

query_range?query=sum(rate(container_cpu_usage_seconds_total{pod_name}[1m])) / sum(machine_cpu_cores{instance'}) * 100&start={args.start}&end={args.end}&step={args.steps}

start = x1 and end = x1 + 30sec  --> total duration around 30 sec

case 1. step = 15s

{"status":"success","data":{"resultType":"matrix","result":[]}}

case 2. step 10s

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1588671276,"0.1"]]}]}}

case3. step 5s

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1588671276,"0.1"],[1588671281,"0"]]}]}}

not getting data at a 15s step but getting some data at step 10s or 5s ?

Can anyone explain why that behaviour happening ?

can anyone suggest which is best out of rate(), irate() and avg_over_time(),  so that i should not miss my data?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pavanmehtre69** [comment]
Asked first there only,  But not getting reponse there that's why i asked here
