### ISSUE TITLE
calc query_range  martix ，include max，min，avg，sum，count？

### ISSUE THREAD

**Issue by lddlww** [prometheus/prometheus#7211]
use query_range api，return matrix type；
how can i use prometheus calc  the  matrix max，min，avg，sum，count  ，etc. ？

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
