### ISSUE TITLE
there are some errors when i use "go run main.go" cmd

### ISSUE THREAD

**Issue by Jasminetyt** [prometheus/prometheus#7212]
i use "go get " cmd get prometheus source code and excute "prometheus --config.file=xxx.yml" it is ok. But when i use "go run main.go" cmd ,there are some errors 
![image](https://user-images.githubusercontent.com/33971562/81156441-8668f000-8fb8-11ea-80ee-430d12903b2a.png)
even import this package into gopath it will appare same error

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
