### ISSUE TITLE
Grouping, Throttling criteria per route or reciever instead of global setting per prometheus

### ISSUE THREAD

**Issue by rnachire** [prometheus/prometheus#7247]
Grouping criteria per route or receiver instead of global setting per Prometheus

we will have single Prometheus + Alert manager system for most of the small to medium enterprise customers. It is expected that, they have different collection frequencies and alerting thresholds with various Raise timer.

For example:

Collection: Device Health data collected every 2mins and Performance metrics every 5mins. 
Alerting : Repeat the Health related alerts every 1 hour if they re occur and Performance once in day

Above 2 use case are common in any environment, we can't expect to have multiple prostheses instances for kind of metrics as each of subset might have different frequencies to collect and emit/repeat an alert.

So, if we could provide a way to provide the grouping params such group_by, repeat interval, group_interval, timeout etc per group based on regex, it will suffice the all the requirements..

Let me know your thoughts.

Regards,
Rajesh

**Comment by brian-brazil** [comment]
This sounds like an alertmanager issues rather than a Prometheus issue, but you can already use regexes for group routing that so this would seem like a usage question.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
