### ISSUE TITLE
Is this a security problem?

### ISSUE THREAD

**Issue by dongwangdw** [prometheus/prometheus#7260]
**What did you do?**
I run this api: https://url/static/vendor/rickshaw/vendor/d3.v3.js?v=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57

/static/vendor/moment/moment-timezone-with-data.min.js?v=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57

**What did you expect to see?**
nothing or it is good.
**What did you see instead? Under which circumstances?**
I see a lot of javascript. I do not think it is normal.
**Environment**
container. I have tested the official image and get the same result.
* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here
v2.8.0 and v2.15.2. Also the image in docker hub.
[untitled folder.zip](https://github.com/prometheus/prometheus/files/4627384/untitled.folder.zip)

**Comment by roidelapluie** [comment]
Thanks for your report. I want to draw your attention to our security disclosure guidelines:

https://prometheus.io/docs/operating/security/

Security issues should be reported privately to -team by email so that we can prepare patches in time.

Regarding this particular issue, those libraries are needed by the UI and loaded by the web browsers to display the graphes. This is expected.
