### ISSUE TITLE
Prometheus goes down with high CPU utilisation while running queries with high cardinality

### ISSUE THREAD

**Issue by varun-krishna** [prometheus/prometheus#7267]
While running queries with high cardinality . Prometheus goes down 
would also like to get some suggestion on the following : 

1) Memory optimization at linux kernel/GC opts for high cardinality
2) Having more prometheus instances for Thanos possibles ? If yes how many ? Design?
3) Query cache in the front end

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
