### ISSUE TITLE
kube_pod_container_status_restarts_total | to filter the last 3 created pods

### ISSUE THREAD

**Issue by nehagupta84** [prometheus/prometheus#7269]
Hi,

I need help in filtering the query on the last 3 most recently created pods. Any help will be appreciated.

Thanks
Neha

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
