### ISSUE TITLE
Node Exporter - Auto Discovery mechanism 

### ISSUE THREAD

**Issue by vikram-yerneni** [prometheus/prometheus#7278]
## Proposal
Why we dont have the auto discovery for the node exporter agents deployed on nodes within the same cluster? The cluster pulls the data for other metrics of how cluster is doing and can we also get the node exporter to get discovered and get populated within the Prometheus server configuration? 
Why is this important?: It will eases the automation part of the deployment. When we automate the deployment of these tools (Prometheus server, node exporter), its an additional manual step to add the node exporter node names or IP's to the Prometheus server configuration. Makes life much easier.

Thanks
Vikram

**Comment by brian-brazil** [comment]
We already have a selection of service discovery methods. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
