### ISSUE TITLE
Alertmanager - Auto Discovery in Prometheus Server setups

### ISSUE THREAD

**Issue by vikram-yerneni** [prometheus/prometheus#7279]
## Proposal
Why we dont have the auto discovery for the Alertmanager deployed within the same cluster? The cluster pulls the data for other metrics of how cluster is doing and can we also get the node exporter to get discovered and get populated within the Prometheus server configuration?
Why is this important?: It will eases the automation part of the deployment. When we automate the deployment of these tools (Prometheus server, Alertmanager), its an additional manual step to add the Alertmanager name or IP to the Prometheus server configuration. 

Thanks
Vikram

**Comment by brian-brazil** [comment]
This is already how it works. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vikram-yerneni** [comment]
Somehow it didn't worked for me when I deployed it on K8s Cluster. Will review the setups once again and will post the question in the mailing list.

Thanks
