### ISSUE TITLE
How to sum values of metrics via PromQL

### ISSUE THREAD

**Issue by organ2** [prometheus/prometheus#7325]
There is some resource for example git.company.com and it have 2 ip addresses: internal and external addresses.
I've got two metrics in prometheus:
probe_success{instance="192.168.0.2",job="blackbox_tcp_general"} 1
probe_success{instance="172.170.220.31",job="blackbox_tcp_general"} 1

When I try to do query in PromQL:
probe_success{instance="192.168.0.2",job="blackbox_tcp_general"} + probe_success{instance="172.170.220.31",job="blackbox_tcp_general"}

I expect that I'll get result 2. But I get result "no data".
How can I sum values of metrics?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
