### ISSUE TITLE
load rules from directory have‘t implemented yet？

### ISSUE THREAD

**Issue by Li-Menglong** [prometheus/prometheus#7337]
I find a issue from https://github.com/prometheus/prometheus/issues/2176,
I try to configure  the config like this 
![image](https://user-images.githubusercontent.com/64116165/83742113-98a77e00-a68b-11ea-8dbd-1b4bf0010855.png)
when I reloaded the prometheus.yml ,it catched an error like this
![image](https://user-images.githubusercontent.com/64116165/83742256-c5f42c00-a68b-11ea-9928-0eb3d93fbb83.png)
so the feature have't implemented or I got wront configuration

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
