### ISSUE TITLE
v2.8.1 remote_storage read merge error

### ISSUE THREAD

**Issue by lixy529** [prometheus/prometheus#7348]
remote_read:
  - url: "http://127.0.0.1:9201/read"
    read_recent: true

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roidelapluie** [comment]
This was fixed in #7361, and deployed to both v2.18.2 and v2.19.0.
