### ISSUE TITLE
Prometheus is giving data double i.e. when i search node_info then its showing same information twice..one from job=kube-state-metrics & another from job=kubernetes-service-endpoints due to which on grafana dashboard its showing total number of nodes and pods double as compared to actual number..

### ISSUE THREAD

**Issue by nagpalnitin0110** [prometheus/prometheus#7376]
Prometheus is giving data double i.e. when i search node_info then its showing same information twice..one from job=kube-state-metrics & another from job=kubernetes-service-endpoints due to which on grafana dashboard its showing total number of nodes and pods double as compared to actual number..

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
