### ISSUE TITLE
When Prometheus can be used vue.js ？

### ISSUE THREAD

**Issue by a102467** [prometheus/prometheus#7382]

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by a102467** [comment]
Thanks!
