### ISSUE TITLE
can't  resovle servicename in k8s 

### ISSUE THREAD

**Issue by Danfeng-Wang** [prometheus/prometheus#7388]
I find this problem in my kubernetes cluster :  

wangdf@ubuntu-16:~/works/github.com$ k exec -it prometheus-0 -n monitoring sh   
/prometheus $ nslookup kubernetes.default.svc
Server:         10.244.64.10
Address:        10.244.64.10:53

** server can't find kubernetes.default.svc: NXDOMAIN

*** Can't find kubernetes.default.svc: No answer

I think prometheus(busybox) container can't resolve service name in k8s.
I have tried other container , it was OK！ 
p
I think it is related to bosybox docker container, anyone will  help me ?😃

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
