### ISSUE TITLE
How to make prometheus automatically monitor nacos spring cloud application

### ISSUE THREAD

**Issue by shy000000** [prometheus/prometheus#7389]
I use nacos as the spring cloud microservices registry center.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
