### ISSUE TITLE
prometheus target for javamelody

### ISSUE THREAD

**Issue by shivamsoni640** [prometheus/prometheus#7404]
Hello all, I want to implement javamelody from the web app. It generates the metrics but gives the 404  error I can not access the queries. please give me your suggestion about what I do.

this prometheous.yml:
 job_name: 'test_jm_app'
    metrics_path: '/DemoServerMode/monitoring'

    params:
      format: ['prometheus']
    
    basic_auth:
      username: 'admin'
      password: 'admin'
      
    static_configs:
      - targets: ['localhost:5050']
        labels:
          env: 'unit'

this prometheous target:
![image](https://user-images.githubusercontent.com/62867333/84751300-9a0b6b80-afe6-11ea-8e24-99b70513ef4f.png)

when I hit the endpoint URL it shows the metrics.

![image](https://user-images.githubusercontent.com/62867333/84751592-f1114080-afe6-11ea-854a-a586064e2fdb.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
