### ISSUE TITLE
How? We have debugged it offline and the problem was the network.

### ISSUE THREAD

**Issue by borisgr04** [prometheus/prometheus#7436]
We have debugged it offline and the problem was the network.
Running the Prometheus container with "--network=host" solved the issue.

_Originally posted by @simonpasquier in https://github.com/prometheus/prometheus/issues/4419#issuecomment-408451914_

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
