### ISSUE TITLE
Environment variable to replace prometheus.yml mounting in Docker Environment.

### ISSUE THREAD

**Issue by asharabu** [prometheus/prometheus#7442]
## Proposal

Is there any Environment variable to replace prometheus.yml mounting in Docker Environment.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
