### ISSUE TITLE
Subquery support for alert rules

### ISSUE THREAD

**Issue by rahulraykor** [prometheus/prometheus#7455]
## Proposal
**Use case. Why is this important?**
It is useful in the scenarios where only sending alert to alert manager is not enough it also needs some background information about the alert or to help to decide root cause of the alert.

*“Nice to have” is not a good use case. :)*
Lets consider a case where we are generating alert for a node under high memory utilization from last 10 minutes. In this case when we send alert manager that this particular node is under high memory utilization in Swarm.
But with this feature in place we can send alert manager extra information like what are the services and their actual memory consumption on that node. In this way the alert manager can send useful information to user which can help him understand that this particular service is consuming more memory on the node.

**Comment by brian-brazil** [comment]
You can already do this via templating in alert annotations. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
