### ISSUE TITLE
alert fire select not work

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#7460]
v2.19.1

alert firing and pending select not work

![image](https://user-images.githubusercontent.com/9782796/85727892-fcbcdf80-b729-11ea-9158-b42e7895e7be.png)

**Comment by gouthamve** [comment]
Hi, what is the bug you're facing here? What is the behaviour you were expecting and what was the behaviour you saw?

The error in the console is not relevant as it's missing a source map, but the actual JS is working well.

**Comment by gouthamve** [comment]
Actually, I've tried in my Prometheus server and I can reproduce this. Clicking on `PENDING` and `FIRING` does nothing in the latest release.

**Comment by timchenxiaoyu** [comment]
any progress ?

**Comment by timchenxiaoyu** [comment]
any progress ?

**Comment by hoffie** [comment]
@timchenxiaoyu @gouthamve Can you share how to reproduce this issue?
Seems to work as expected with v2.19.1 on both Firefox (80.0.1) and Chromium (85.0.4183.102) for me.
Clicking `Firing` for the first time hides my only firing alert. Clicking it again makes it re-appear. Same for `Inactive` (currently don't have a `Pending` alert to test).

**Comment by timchenxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/9782796/93015050-b0769280-f5e8-11ea-951c-775c04e944f8.png)
![image](https://user-images.githubusercontent.com/9782796/93015072-d308ab80-f5e8-11ea-83b8-312dc4443683.png)
![image](https://user-images.githubusercontent.com/9782796/93015086-0b0fee80-f5e9-11ea-8a76-2be062c1329a.png)

click firing no response ，still appear all alert

**Comment by hoffie** [comment]
> click firing no response ，still appear all alert

Just to confirm: You are still seeing your 5 firing alerts in red with the current state (`Inactive` and `Pending` enabled in dark blue, `Firing` disabled in lighter blue), right?
The screenshot still looks as expected, but it obviously only contains a small part of your alerts.

What happens when hiding the large amount of Inactive alerts by clicking the `Inactive` button once?

(I think the buttons can easily be confused as tabs which one would expect to switch between the three categories. Instead, they are rather checkboxes which hide/unhide the categories. Disabling all three categories (i.e. making them light blue) should lead to an empty list of alerts.)

**Comment by timchenxiaoyu** [comment]
tks，i know。 it is not alert selection.
