### ISSUE TITLE
Prometheus Scraping issue

### ISSUE THREAD

**Issue by patilpravin557** [prometheus/prometheus#7462]
Hi,

Have developed db2 query exporter for Prometheus,
build this select query,
select name as "db2_mycounter_name", total as "db2_mycounter_total" from myfakecounter

and inserted 2 values into table
insert into myfakecounter values ( 'counter1', 100 )
insert into myfakecounter values ( 'counter2, 200 )

I'm able to see both values in Prometheus console.

However, after a while, i have deleted counter2 value i.e 200 from database.

But in Prometheus  i'm seeing 200 value still .
Its not showing me the existing results of select query i.e only counter 1 value which is 100

Kindly suggest?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
