### ISSUE TITLE
Query related to NFS Detach mount using node-exporter mountstats and nfs collector does not work .

### ISSUE THREAD

**Issue by satyam130** [prometheus/prometheus#7468]
Hi team ,

I should get alert when below given /mapr  nfs mount-point get detached .

I am using following 2 metrics  provided by node-exporter collector mountstats and nfs .
**query(1)-**   absent(node_filesystem_size_bytes { job="exporter_node",fstype="nfs" ,mountpoint="/mapr",instance=~".*:9100" }) ==1
**query(2)-**  rate(node_mountstats_nfs_age_seconds_total {export="localhost:/mapr"}[5m]) < 1

My first query is providing me desired output but i have to hard-code instance value on it. the regex used above does not work.
My second query with rate doesn't give me a stable value to put on alert .

Am i doing something wrong here?
Please provide any solution to resolve my problem .

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
