### ISSUE TITLE
subquery select data points doesn't align with start/end time

### ISSUE THREAD

**Issue by garrettlish** [prometheus/prometheus#7486]
**What did you do?**
Assume we have a subquery expression like `(sum(latency))[3d:1d]`, it returns 3 data points and every data point's timestamp is UTC 00:00 (no matter what is the start/end time). It is because subquery round the start time with step like https://github.com/prometheus/prometheus/blob/66dfb951c4ca2c1dd3f266172a48a925403b13a5/promql/engine.go#L1354-L1355. However, it doesn't align with start/end time (query range API) and time (query instant API).

**What did you expect to see?**
Our expectation is subquery should not round the start time with step and align with start/end time.

For example, if we are querying `(sum(latency))[3d:1d]` through instant query API with timestamp = June 25th, 2020 10:10:00, then it returns June 23th, 2020 10:10:00, June 24th, 2020 10:10:00, and June 25th, 2020 10:10:00 3 data points. Rather than UTC 00:00.

Any thoughts, please advise!

**Comment by brian-brazil** [comment]
This is the expected behaviour, Prometheus in general does not promise anything about the alignment of intervals and that includes subquery evaluation. Aside from that, subqueries would be completely impractical from a performance standpoint if we didn't do this as semantically query range is merely syntactic sugar on top of query.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by garrettlish** [comment]
@brian-brazil thanks for your feedback, but the problem is that matrix selector & range query & subquery behave differently, especially for subquery.
Sample: 
1. `latency[3d]` with timestamp = June 25th, 2020 10:10:00 (assume resolution=1m) returns data points from timestamp = June 22th, 2020 10:11:00 to timestamp = June 25th, 2020 10:10:00. 
2. `latency` with start=June 22th, 2020 10:10:00, end=June 25th, 2020 10:10:00, and step=1d, returns data points June 22th, 2020 10:10:00, June 23th, 2020 10:10:00, and June 24th, 2020 10:10:00.
3. `(latency)[3d:1d]` with timestamp = June 25th, 2020 10:10:00 returns data points: June 23th, 2020 00:00:00, June 24th, 2020 00:00:00, and June 25th, 2020 00:00:00.

**Comment by brian-brazil** [comment]
I see no inconsistency here. The results of 3 are within the bounds of 1 - the same as if you somehow had a daily scrape that happened to be happening exactly at midnight.
2 is not comparable, as that's not a range vector.
