### ISSUE TITLE
Facing instance down alert on Prometheus 2.17.0

### ISSUE THREAD

**Issue by rajanikantpatel** [prometheus/prometheus#7487]
facing instance down false alarm for go application in kubernetes container. surprisingly this error is only for go applications and not for other applications. all applications are containerized. 

Alert :
alertname="InstanceDown"
Prometheus version : 2.17.0
alert manager version : 0.20.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
