### ISSUE TITLE
can return string in promql?

### ISSUE THREAD

**Issue by MaPing01** [prometheus/prometheus#7525]
eg:
up{instance="localhost:9090",job="prometheus"}
how i can get the instance ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
