### ISSUE TITLE
https scheme for envoy

### ISSUE THREAD

**Issue by dnull88** [prometheus/prometheus#7534]
When I use job with https scheme and standart 443 https port, for example, 
- job_name: 'i-test'
  metrics_path: '/metrics'
  scheme: https
  static_configs:
  - targets: ['exporter.test.xyz']

prometheus generates target url as https://exporter.test.xyz:443/metrics. When scrapes this url, prometheus also puts Host header with value **exporter.test.xyz:443**. Some web servers (envoy for example) doesnt recognise this host as exporter.test.xyz and generates error (500 or 404)
Is it posible generate valid https://exporter.test.xyz/metrics url, not https://exporter.test.xyz:443/metrics ?

**Comment by roidelapluie** [comment]
What does the http specification say about the hostname http header and ports?

**Comment by roidelapluie** [comment]
It seems that it is a bug with envoy. Prometheus is following the spec as the port may be omitted of it is the standard port. This is not mandatory.

Which version is prometheus are you using?

**Comment by dnull88** [comment]
we use v2.16.0

**Comment by roidelapluie** [comment]
If you update to v2.19.0 https scrapes will use HTTP/2, which should not have the hosts header.

**Comment by roidelapluie** [comment]
We have looked at this question during our bug scrub and determined that this is not an issue with Prometheus itself.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
