### ISSUE TITLE
Scrape user-agent header signature (remove version)

### ISSUE THREAD

**Issue by ArcticB** [prometheus/prometheus#7535]
While scraping, user-agent is currently exposing the version number. Is it possible to add an extra option to hide the version ? This feature would be the same as the Apache server ServerTokens's option or an option that let us set the entire Header's section. Hide this information is needed while hardening servers configurations for security certifications.

**Comment by brian-brazil** [comment]
This is useful for debugging, and I'm not seeing any real security implications here. If you believe you've found an exploit, the procedure for reporting it can be found at https://prometheus.io/docs/operating/security/

**Comment by ArcticB** [comment]
Please go to https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html and ctrl+f "version". As I said this feature would be part of prometheus configurations hardening process, thus it should be implemented.
Thanks

**Comment by hoffie** [comment]
The article you've referenced seems to be primarily aimed at disclosure of vulnerabilities and explicitly mentions that versions are very helpful there.
I am aware that are documents which suggest removing version information. However, I am not sure that this is helpful. Most exploit code nowadays seems to just attempt to exploit a potential vulnerability instead of checking for a specific version first. Hiding such information is also often regarded as security by obscurity. In other words: The upsides are questionable while there are specific downsides (debugability).

Prometheus seems to have a pretty good security track record. Also, this request is about scraping. To be more specific: Hiding the version there will only hide it from attackers which already have full insight into your network (i.e. they are able to redirect your unencrypted traffic) or which have already taken over one of the targets which Prometheus is configured to scrape. I would not call these scenarios that common...

If you really need to, you could still place a (local) proxy between prometheus and your target which could drop/replace such a User-Agent header.

Are there any specific/public security certifications which require exactly such a behavior?

**Comment by ArcticB** [comment]
I didn't say that it as to be removed but that I think (and I need it for my infrastructure) there should be an option to hide it. Debug has always been a feature as far as I know and this little option would help for defence-in-depth in a production environment. You are right about the fact that security by obscurity isn't a good choice but it's a good additional layer of security (such as for obfuscation of code).

In the article I linked it's said that versions are helpful to retrieve public vulns on applications ("Which types of vulnerabilities are eligible for bounties (SSL/TLS issues? Missing HTTP security headers? Version disclosure?"). Besides that, it's true that Prometheus seems to have a pretty good security track record but it do not mean that it's not vulnerable.

To answer your question, certifications are not based on a checklist but on an overall security level. So my demand is part of the requirements. Then yes I can use a proxy to do it but it's a bit overkill for 3 letters.

Thanks

**Comment by roidelapluie** [comment]
We have looked at it during our bug scrub and determined that in order to get the version via that header, you should be scraped by Prometheus. There are many other places where we expose version and the prometheus UI is different enough between releases so that determining the version is trivial anyway. It is also exposed as metric by the prometheus server.

We have therefore decided to close this bug.
