### ISSUE TITLE
1 != bool 1 always conditions holding

### ISSUE THREAD

**Issue by bn0901** [prometheus/prometheus#7536]
**What did you do?**

Perform the following formula at prometheus UI: 
1 == bool 1  --------------->1
1 != bool 1 ---------------->0

but in prometheus rules, these two formula always alerting !

**What did you see instead? Under which circumstances?**
![image](https://user-images.githubusercontent.com/33149547/86992443-0fc4ba80-c1d4-11ea-97f7-3598d831d6d0.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
