### ISSUE TITLE
Can't load Prometheus

### ISSUE THREAD

**Issue by vinhdiesal** [prometheus/prometheus#7578]
I can't seem to get the Prometheus to load hence, Grafana won't be able to use it as a data source. 

I installed the Prometheus helm chart as follows: ` helm install prometheus stable/prometheus`
The helm chart stated that you can access the server URL at the following on port 80: 
```
prometheus-1594747558-server.default.svc.cluster.local
```
I typed in `http:prometheus-1594747558-server.default.svc.cluster.local:80` which results in a time out. 

I then tried the URL method as follows: 
```
export POD_NAME=$(kubectl get pods --namespace default -l "app=prometheus,component=server" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace default port-forward $POD_NAME 9090
```
This returns `http://localhost:9090` which gets me the following error: 
```
Handling connection for 9090
E0714 13:29:00.808770   37486 portforward.go:400] an error occurred forwarding 9090 -> 9090: error forwarding port 9090 to pod cb9638fdec4c997df3312a5928659836020664e5cd0480f04ade464b1652a42d, uid : exit status 1: 2020/07/14 13:29:00 socat[37807] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
```
Why is the pod rejecting the connection?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
