### ISSUE TITLE
idelta default Value at first data point

### ISSUE THREAD

**Issue by ZukenHammer** [prometheus/prometheus#7580]
``idelta`` on does not return an difference based on the first data-point. It would be greate to pass an optional value to idelta for the first data-point to compare with. I am facing the problem to get the timestamp when a server status changes.  
Actually working with the up-Metric and idelta gives greate results. Expect on the initial status.

Example would be something like: 
```
idelta(up[1y], -1)
```

My actual query facing this problem:
```
clamp_min(up{instance=~"$instance"} * time() - max_over_time(timestamp(idelta(up{instance=~"$instance"}[1y]) == 1)[1y:]), 0)
```

**Comment by brian-brazil** [comment]
The whole point of idelta is that it looks at only the last two data points - just as irate does - so a parameter like that would not make sense (and I'm not sure what this parameter would actually mean). In addition parameters that change fundamental function behaviour is something I try to avoid as that leads to confusing semantics for anyone try to understand an expression. Finally this particular example would be quite inefficient and likely hit resource limits, as you're pulling in an entire year worth of data.

idelta is intended for advanced use cases when standard PromQL functions aren't sufficient, usually via self-referential recording rules. However in general if you want a timestamp when something happens, get the server to expose it as a gauge rather than building up complex expressions in PromQL.

**Comment by ZukenHammer** [comment]
I agree with you. The query is heavy with the 1 year cache and limited. I had the wrong approach solving the problem. I need something like a service pinging the server check if the server is offline, track a 0 when or track the uptime if it is online.  
Thanks for the fast answer.
