### ISSUE TITLE
alerts debounce

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/prometheus#7595]
## Proposal
**Use case. Why is this important?**
Prometheus supports for field to alert if it keeps alerting for a given period.

The condition is too strong, and could not capture some alerting cases, like flapping. 
For example, one alert has condition like `A{} > 100`. 
If don't define for value, we might have lots of false alerts.
But if we define something like `for:"5m"`, some alerts will be missed because of flapping values. 
The metric might be up over 100 at some times, and then less than 100 at other times. 
It might because some remediation process tries to fix it.

So this might be more useful: alert when there are 3 alerts during 5 continues evaluations, noted as `3/5`

In another word, this debounce feature is more general. 
if one alerting rule is running every 1 minute, `for:"5m"` is equal to `5/5`.

*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment]
Thanks for your suggestion, this something you should solve in PromQL such as by using avg_over_time. See also https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0. 
It makes more sense to usage questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by alburthoffman** [comment]
@brian-brazil avg_over_time could not work well with alerting cases. for example:
`
groups:
- name: example
  rules:
  - alert: HighRequestLatency
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 30
    for: 3/5
    labels:
      severity:"{{ if (gt $value 60) }}fatal{{ else if (gt $value 30) }}critical{{ end }}"
    annotations:
      summary: High request latency
`
