### ISSUE TITLE
How Step is changed dynamically, what is the calculation behind it?

### ISSUE THREAD

**Issue by full-stack-pirates** [prometheus/prometheus#7600]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
