### ISSUE TITLE
Filter values when using range vectors

### ISSUE THREAD

**Issue by amiryeshurun** [prometheus/prometheus#7637]
Hello,

I am using the following query in order to get a range vector:

`api_timing{api_name="<NAME>"}[1d]`

Next, I want to get the average of the range vector. To do that, I am using avg_over_time - BUT, when there is a single `NaN` value inside the range vector, the operation returns `NaN`. I tried to run:

`avg_over_time(api_timing{api_name="<NAME"}[1d] >=0)`

and got the following error: 
```
Binary expression must contain only scalar and instant vector types
```

I think that it is very important to allow filtering values from range vectors. We would like to see it in the next versions of Prometheus.

Thank you!

**Comment by brian-brazil** [comment]
The NaN result is correct, and in general averaging averages will produce incorrect results. More generally it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
