### ISSUE TITLE
Will prometheus support cron expression config instead of interval configs?

### ISSUE THREAD

**Issue by xuhrc** [prometheus/prometheus#7674]
If there is a daily alert rule, It's that a way to specific evaluating time such as 3:00 AM？

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
