### ISSUE TITLE
federation failed，write: broken pipe

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#7704]
version: 2.15.2
os: x86_64

log:
level=error ts=2020-07-22T23:59:47.127Z caller=federate.go:184 component=web msg="federati
on failed" err="write tcp 100.101.138.62:9090->100.101.219.28:41340: write: broken pipe"

job sample:

scrape_samples_scraped{instance="prometheus:9090",job="1m-job",kubernetes_cluster_name="rdcenter-intact-manager"} | 1076323

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fcddk** [comment]
The question I want to verify is: Is it a network problem (network bandwidth) between nodes or two prometheus read and write processing performance problems?
Is it possible to locate and tune the deployment method of prometheus through some existing monitoring metric?
