### ISSUE TITLE
Able to specify bind port, but not address

### ISSUE THREAD

**Issue by jumble** [prometheus/prometheus#7734]
Latest prometheus, on RHEL8.

Tried command: `./prometheus`
Expected behavior: bind to `0.0.0.0:9090`
Observed behavior: bound to `127.0.0.1:9090`

Tried command: `./prometheus --web.listen-address=0.0.0.0:9090`
Expected behavior: bind to `0.0.0.0:9090`
Observed behavior: bound to `127.0.0.1:9090`

Tried command: `./prometheus --web.listen-address=0.0.0.0:9000`
Expected behavior: bind to `0.0.0.0:9000`
Observed behavior: bound to `127.0.0.1:9000`

**Comment by brian-brazil** [comment]
This sounds like a problem with your OS, not Prometheus. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
