### ISSUE TITLE
Implement a dark theme in the react UI

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#7735]
Well, hem that's a nice to have I know. But in case of an UI, it's always a bit a nice to have :).

Anyway a dark theme could be cool in Prometheus. And being able to manage some themes provides usually a good way to manage the css.

**Comment by roidelapluie** [comment]
Maybe we could have a dark theme, but complete theme management with css is clearly out of scope for Prometheus.

**Comment by juliusv** [comment]
In general, I see a dark theme as a nice-to-have, but we have to weigh the costs. My main reservations are:

* It will be more work to implement than it may seem at first. CSS styles are in inline styles in the JSX, in custom CSS, and in multiple third-party CSS files / libraries that need to be scrutinized closely first by anyone wanting to implement this.
* We also need to make sure that everything still looks ok in both light and dark modes after any new addition or change.

So overall both the initial work is pretty large, and the ongoing maintenance burden is there as well.

I wouldn't straight out say no to this, but anyone wanting to contribute this should IMO make a survey of what will be required in more detail in terms of the above two points.

**Comment by bwplotka** [comment]
I would love to see that TBH (I am dark side fan). I agree with maintenance. Can we drop the light theme then? 🙃 (See Grafana e.g).

Since we don't want to drop light, I feel it's fair to add dark them if anyone want to contribute.

**Comment by zerefwayne** [comment]
I would like to work on this feature @bwplotka 

Are there any style guidelines being followed by Prometheus? I'll sketch out some rough designs and share them here for feedback.

**Comment by roidelapluie** [comment]
Here is a good pointer: https://github.com/prometheus/prometheus/tree/master/web/ui/react-app

**Comment by zerefwayne** [comment]
IMO there should be an option to toggle between the themes and later on after the work on dark theme is complete we can maybe think of getting rid of the light theme.

**Comment by juliusv** [comment]
@zerefwayne I don't think we should get rid of the light theme, as I definitely prefer that and I think others will too. To me the question is more whether it's worth the extra maintenance to add the dark theme ;) Personally I've never really understood the hype around dark themes, but there seem to be a lot of people who care about them.

@bwplotka did you just volunteer to maintain that over time? ;)

In any case, I think this still stands before sending a long PR please:

> I wouldn't straight out say no to this, but anyone wanting to contribute this should IMO make a survey of what will be required in more detail in terms of the above two points.

**Comment by Nexucis** [comment]
> Personally I've never really understood the hype around dark themes, but there seem to be a lot of people who care about them.

It happens around 3 am when you are coding using an IDE with a dark them, and then you are going to a white website. You are sure you will yell : "My eyes, my eyes ! It's burning" haha

**Comment by prymitive** [comment]
I believe that current UI uses bootstrap for CSS and this creates a few challenges for a dark theme:
- bootstrap official theme only comes in a bright flavour, this could be solved by adding a dark theme from https://bootswatch.com
- bootstrap CSS files currently don't make it super easy to swap themes, the "css way" is to namespace all selector - have a "dark" or "bright" css class on root element (like body) and them have 2 css variants of the theme, one for each class - this works fairly well with static websites and can be made to work well with react, despite being less "react way" (react way is mostly some form of CSS-In-JS), but there might be some problems with resetting browser defaults (https://getbootstrap.com/docs/4.1/content/reboot/)
- visual testing is more difficult, I get around that by using storybook and https://percy.io/ for visual testing, including CI
- it's ideal to have lazy loading of themes setup in react when having multiple themes, to avoid loading dead code for themes that are never used
- modern browsers have media queries to tell you if dark or bright variant is preferred, which should be used so that the UI follows system preference and you don't end up with bright website when everything else is dark - https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by juliusv** [comment]
@prymitive Thanks for those good points! Yeah, I would imagine that themeing would use a mix of a React context that is wrapped around the whole app (for the more Reacty styles), plus a theme-specific CSS class on a root element (for the pure CSS styles).

It'll also be an interesting challenge in itself to make sure that all possible UI elements are really supported in both themes, as certain warnings or error messages or such only occur in certain weird situations. We already have a similar problem for the single theme we have now, so probably more automated visual testing would be good in any case.

Do you feel it would be worth maintaining two themes over time (and would you like to be part of that)?

**Comment by prymitive** [comment]
I think it's not that much work as long as you re-use a ready made theme (like bootswatch) or a customised bootstrap variant, since it doesn't seem like bootstrap will get a native dark mode anytime soon (https://github.com/twbs/bootstrap/issues/31175).

Overall I don't think there is a huge amount of maintenance required after the initial effort to add theming and storybook can be a great and easy tool for testing. So the cost IMHO isn't huge and worth having better UX. Happy to help with that work.

**Comment by juliusv** [comment]
@prymitive Ok, that sounds fair enough to me, so feel free to go ahead! :) Maybe if you start implementing it in Prometheus, you will discover some new aspects of the problem of course. In that case, it would be good to hear about those...

**Comment by prymitive** [comment]
Sure, I'll look into that over the weekend, feel free to assign me this ticket. Thanks!

**Comment by morremeyer** [comment]
@bwplotka I get that your "we could drop the light theme then" was not too serious, but I just want to document it here for anyone not aware of it:

Light text on dark background is pretty hard to read for people with astigmatism as it "glows".

Therefore, dropping a light theme in favor of a dark theme would make the UI less accessible and should definitely not be done.

**Comment by prymitive** [comment]
The good news is that there's a good dark variant for the default bootstrap theme - ForEvolve/bootstrap-dark
Latest one is for bootstrap 4.6 so I'll bump both bootstrap and reactstrap to avoid any glitches and bring us to the latest version.

After initial effort to find a dark variant it was very easy to add a context driven dynamic theme loader:

<img width="1041" alt="Screenshot 2021-03-14 at 22 48 48" src="https://user-images.githubusercontent.com/114288/111087063-72b2e200-8517-11eb-82dd-62886960f420.png">

 I still need to:

- [ ] add a UI toggle as I imagine (correct me if I'm wrong) we want 3 states - dark mode forced, light mode forced and auto (using browser preference), we'll use localStorage for saving user settings here as we do with every other setting
- [ ] add scss support so we can customise all the extra CSS, since it was written for the default theme, this will allow moving colours used in that extra css to variables specific to each theme, or inheriting colors from bootstrap scss, so that all UI element are consistent across both light and dark variant
- [ ] add storybook so we can have a test bed for easy comparison of all different UI elements in various states with both themes, looked into this a bit and there's some extra work needed to get react router working with that, need to research this a bit more as I didn't use router with storybook before
- [ ] will try to look into automated visual testing, there are some storybook add-ons that allow capturing storybook screenshots in CI for easier PR review, I've used percy.io for this but the free plan comes with "only" 5000 snapshots a month, so might not be a good fit here

**Comment by juliusv** [comment]
@prymitive Great! I hadn't heard of storybook before, it looks like a really awesome tool, and I guess https://storybook.js.org/docs/react/workflows/visual-testing is what we will need from it.

The rest sounds good, including the 3 states.

Regarding Percy: in 2018 we actually got an offer from them to get free hosting for Prometheus, but back then we really didn't need it yet (this was pre-React UI as well). There's a good chance they'd still be happy to have us though, if you think Percy makes sense. They've been since acquired by BrowserStack though, no idea if that changes things. Overall, if we can achieve our needs similarly well with an OSS tool, that would be preferred of course.

**Comment by prymitive** [comment]
Drafted #8604 with initial implementation, it includes a working dark theme but needs some more work and testing

**Comment by Talador12** [comment]
Request: could we update the dark mode page load order to show a dark screen while the page is loading? If you have it set to dark mode and it takes a minute to load, it shows a blinding white screen until the page is loaded.

**Comment by juliusv** [comment]
Dark mode was implemented & merged in https://github.com/prometheus/prometheus/pull/8604 now.

Closing this, for any follow-up improvements, please file follow-up PRs & issues.

**Comment by Nexucis** [comment]
awesome !! Thanks @prymitive !!
