### ISSUE TITLE
Add a possibility to use DNS load-balancing for remote write

### ISSUE THREAD

**Issue by AleksandrNull** [prometheus/prometheus#7774]
### **Is there a possibility to add dns resolving for a remove-write url on per-shard basis ?**

*From what I can see right now prometheus creates persistent connection to the remove-write destination on per-shard basis. The issue is that if one is having 100 heavy-loaded shards then all of them will land on IP which was resolved in the very beginning which requires to do additional load-balancing in front of receiver.*

*One more drawback is that if initially resolved address became unavailable prometheus will just stop shipping which I thing is another issue but directly related to the describe behavior*

**Comment by brian-brazil** [comment]
DNS-based load balancing doesn't tend to work too well for small numbers of server-based connections, I'd suggest looking at running a load balancer on your end to handle the connections, rather than trying to get the client to deviate from standard behaviour and ignore DNS TTLs.

The DNS resolution is also handled by Go, we have no control over it.

**Comment by AleksandrNull** [comment]
@brian-brazil 
Yeah, DNS-based load balancing is a necessary evil we can deal with. The problem is that number of connections aren't small.  We have ~2k total so fo us it will work much better than it works now. But under given circumstances we probably have to deal with lb in front of receivers then. Thanks.
