### ISSUE TITLE
npm_licenses.tar.bz2 is not shipped with the release tarballs

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7812]
We ship the NPM licenses with the docker image, but not in the tarball built by promu, even if the file is in the .promu.yml.

I think maybe we have a target missing the makefile.

**Comment by showuon** [comment]
@roidelapluie , I've investigated this issue, and found the root cause is that we didn't build the `npm_licenses.tar.bz2` before running `tarball` in `.promu.yml`. However, we currently don't support `make` command in the `promu`, nor customized commands to build the `npm_licenses.tar.bz2` (which is to yarn download modules and than tarball all the module license files). I suggest that we add the `make` command support to the `promu` tool. What do you think?

**Comment by roidelapluie** [comment]
From my 10,000 feet view, there are 2 issues:

- the file npm_licenses.tar.bz2 is in th promu.yml and promu does not complain that the file is not there
- there is a missing step in our release process to create that file (see https://app.circleci.com/pipelines/github/prometheus/prometheus/8468/workflows/c73170ea-191d-452b-a377-e334d420bd8c/jobs/37032 for our tests)

**Comment by showuon** [comment]
@roidelapluie , thanks for your response. But I think you're wrong. I checked the release process. Promu indeed complained the that the file doesn't exist.
But thanks for the info, I found an easy fix is to make the `npm_licenses` as the `build` dependency in Makefile. I'll make more tests and make sure it works well for all OS. Thanks. 
![image](https://user-images.githubusercontent.com/43372967/91025926-9de1ec80-e62c-11ea-9633-035fc6127b16.png)

**Comment by krajorama** [comment]
I'm working on 3.13 release, licenses are not in the tarballs , what's worse is that since pnpm switch over #18797 , the docker build in [release](https://github.com/prometheus/promci-images/blob/43087125ee33af44414b41d98d7180a45f1f6447/publish_release/action.yml#L37)  fails as pnpm is not present at the time. So docker image is not built.

Release CI 3.13: https://github.com/prometheus/prometheus/actions/runs/27826053865

We went now years without the licenses being bundled in the tarball and now the docker image is broken as well. What option to go for?

- Remove from docker image as well and not try to fix it
- Add pnpm to environment that builds the docker image ?
   - use golang-builder container as other targets
   - use pnpm setup-action
- Build npm_licenes in separate step, upload as build artifact and download where needed (my choice)

**Comment by krajorama** [comment]
Fixed by #18997  . Licenses now bundled with binary and downloadable from web ui..
