### ISSUE TITLE
Prometheus v2 docker tag

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7824]
We should publish a docker image with a v2 tag, so people can chose to stick to that one.

Currenly, they can chose a latest (which will break in 3.x) or a very specific v1.2.3 tag.

**Comment by roidelapluie** [comment]
Note for implementation that v2.19.3 was released after v2.20.0. In that case, we should not update the v2 tag.

**Comment by ysahil97** [comment]
Hi @roidelapluie

I believe this issue would be a good starting point for me in order to get hands-on with Prometheus and open source.
As per my understanding, we need to add a separate publish rule specifically for v2 releases so that the latest v2 release would be fetched from here directly. This should happen on the condition that the semantic version of the latest release should always be greater than it's previous release.
Please let me know if there are any points missed here.

**Comment by SuperQ** [comment]
It should only require an additional tag during the tagging process. See `common-docker-tag-latest` in the Makefile.common.

**Comment by vears91** [comment]
Hi! How long until `3.x` is coming along? I'd like to help with this. Would tagging for v2 in `common-docker-tag-latest` when the latest release (as in the `VERSION` file) matches the `DOCKER_IMAGE_TAG` work for this purpose?
