### ISSUE TITLE
Update GRPC to latest release

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7836]
@beorn7 @codesome

In the latest release, we had to rollback the GRPC release.

Can we now update GRPC for v1.31.0? (see #7621)

It is annoying not to update it because in the last month some dependencies depend on newer releases.

**Comment by codesome** [comment]
And looks like it is going to take some time https://github.com/etcd-io/etcd/issues/12124#issuecomment-674368288, but I see some push there. Upgrading gRPC in Prometheus would entirely block Cortex from vendoring Prometheus :/

If the dependencies in Prometheus which depend on latest gRPC are not critical to be upgraded or not blocking any work, we could consider waiting for it to be upgraded in etcd.

**Comment by zmt** [comment]
[This comment in go.mod](https://github.com/prometheus/prometheus/blob/v2.33.3/go.mod#L89) led me to this issue, but this issue can almost certainly be closed and that comment removed since I see [many newer versions of grpc in go.sum](https://github.com/prometheus/prometheus/blob/v2.33.3/go.sum#L1932-L1948)
