### ISSUE TITLE
Allow Different Scrape Config Jobs to Write to Different Remote Write URLs

### ISSUE THREAD

**Issue by AutonomicMattRoy** [prometheus/prometheus#7858]
## Proposal

You can currently configure multiple remote_write URLs/endpoints but only on a global level, meaning that all data/metrics scraped by your scrape config jobs will be written to all listed endpoints unless you have specific `write_relabel_configs` defined. If you only want certain data to go to one endpoint and certain scraped data to go to a different endpoint you have to configure your `write_relabel_configs` to use the `keep` action to only keep metrics with certain labels. 

If you are using something like `Cortex` which allows you to store different data in multiple/different tenants then you need have the ability to have prometheus remote_write data to different endpoints on a per job basis. If you want tenanted data in cortex then you most likely do not want the same data in both tenants.

**Comment by roidelapluie** [comment]
Thank you for your proposal.

Based on your own message, this is possible to use `keep` on the job label in the write_relabel_configs.
I would expect that in the case of cortex, the most common usecase is to use one prometheus per tenant.

**Comment by brian-brazil** [comment]
Indeed, I'm not clear what you're actually asking for here. Multi-tenancy is out of scope for Prometheus itself, so this seems more like a Cortex usage question. As Cortex is multi-tenanted I'd expect everything to go to one Cortex, and if you have multiple Cortexes then it'd be best to also have multiple Prometheuses.

**Comment by csmarchbanks** [comment]
As you pointed out, the supported way to do this is using `write_relabel_configs` combined with `keep` and `drop`. Though, it might be less error prone to separate the scrape jobs to different Prometheus instances based on tenant rather than mixing the data at all.

I am going to close this issue as we already support the behavior you are asking for. I am happy to reopen if we are misunderstanding something or it is impossible to split the data how you wish using `write_relabel_configs`.
