### ISSUE TITLE
Demerits of federated prometheus with multiple shards

### ISSUE THREAD

**Issue by dinesh4747** [prometheus/prometheus#7866]
Hi Team,

we have implemented huge number of shards in prometheus which scrapes 1000 target nodes across the enterprise 

we are currently in process of running some load test and ascertain the unknowns one below and need some guidance on the same - 

On what cases sharding approach can fail?

1. How do we quantify the load/scale requirements?
2. Is there any optimized settings/configurations or best practices we need to comply for sharing 
3. Any low level tuneable like recording rules/metrics_relabel_configs/scrape_internal and sample we ingest we need to accomodate and any pointers to it ?

Please do guide us through whether we think on right page and correct me incase of any misinterpretation

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
