### ISSUE TITLE
The deleted indicator data cannot be completely cleared

### ISSUE THREAD

**Issue by yuanyiran** [prometheus/prometheus#7891]
**What did you do? What did you see instead? Under which circumstances?**

I use Prometheus disk cleaning API to clean up the deleted index data. After successful execution, the data can be queried

Normal query results:
![image](https://user-images.githubusercontent.com/64528937/92088476-83173100-edff-11ea-8917-6141841e44bd.png)

After executing the delete index API, execute the clean disk API:
![image](https://user-images.githubusercontent.com/64528937/92088588-a5a94a00-edff-11ea-99e0-a875d6661252.png)
![image](https://user-images.githubusercontent.com/64528937/92088826-fcaf1f00-edff-11ea-9888-3c1c7ed14634.png)

Finally, query again:
![image](https://user-images.githubusercontent.com/64528937/92088654-b8bc1a00-edff-11ea-804f-3251b9c9c715.png)

**What did you expect to see?**

I hope that after I execute the clean disk API, the data will be completely deleted from the disk and will not be queried any more

**Environment**

* System information:

	Linux 3.10.0-957.21.2.el7.x86_64 x86_64

* Prometheus version:

	Prometheus v2.18.2

* Alertmanager version:

	Alertmanager v0.20.0-rc.0

**Comment by brian-brazil** [comment]
I see nothing wrong here at all. You deleted the data, and it is no longer returning in queries. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
