### ISSUE TITLE
pod restart - prometheus PromQL

### ISSUE THREAD

**Issue by prashantnitt07** [prometheus/prometheus#7892]
please provide the POD restart Prometeus PromQL or Metrics Name

Prometheus version : 2.19.3

Grafana version : 7.0.3

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
