### ISSUE TITLE
Filter time series with delta 0

### ISSUE THREAD

**Issue by benitogf** [prometheus/prometheus#7905]
## Proposal

Currently there's no querying option that could allow to filter time series with delta 0 (no change between start and end of the selected time range) 

![image](https://user-images.githubusercontent.com/1633813/92379764-8cbfd200-f13a-11ea-8535-cc6546e9958f.png)

Adding a filter to: https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators
- by value
- by delta

Maybe there's a way to achieve this behavior at the moment and I missed it, if so my apologies, thanks!

**Comment by brian-brazil** [comment]
This seems more like a usage question, and it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
