### ISSUE TITLE
prometheus is always oom killed

### ISSUE THREAD

**Issue by gupf0719** [prometheus/prometheus#7909]
* System information:

	kubernetes v.1.11

* Prometheus version:

	v2.3

[heap-ha0(1).svg.zip](https://github.com/prometheus/prometheus/files/5187321/heap-ha0.1.svg.zip)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
