### ISSUE TITLE
How to keep data of removed target/instance?

### ISSUE THREAD

**Issue by MartinEmrich** [prometheus/prometheus#7918]
Our prometheus contains metrics of our kubernetes cluster.

Today, I wanted to look at data of a node (EC2 instance on AWS) that has been removed yesterday. But all the data regarding the VM is gone.
In contrast, data of a Kubernetes Pod that has been terminated is still visible later.

The nodes are discovered using ec2_sd_configs, the Kuberneted Pod data is scraped via federation from another prometheus instance running inside the K8s cluster.

Apparently there is a difference in behaviour regarding removed targets. But I cannot find a configuration parameter.

How can I keep historic data of removed VMs (or other targets) when the target itself is no longer there?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
