### ISSUE TITLE
Scrape Timeout Value Metric

### ISSUE THREAD

**Issue by midnightconman** [prometheus/prometheus#7920]
## Proposal
**Use case. Why is this important?**
At the moment we have a scrape duration metric, but unfortunately we don't have a metric for the scrape timeout value. If we had this value, we would be able to determine trending and thresholding around scrape duration vs timeout, which would allow us to determine if a timeout has been persistently occurring or if a timeout might occur in the future based on prediction.

Another possible option would be a counter for scrape timeouts, which would allow us to rate timeouts to determine how often timeouts are occurring?

**Comment by brian-brazil** [comment]
This has been considered previously, and is not something that will be added as a per-scrape metric as it's of too little value considering the high cost of those. Plus you can already detect a timeout has been happening persistently plus all other scrape errors by checking if up is 0, and comparing against scrape_duration_seconds if you want to cross-check.

If you want to write recording rules for this, then you can have your configuration management that knows that settings you provided for the the timeout in the config file to interpolate it into your rules. Though usually you'll have only a single timeout value, so you can hardcode it.

> Another possible option would be a counter for scrape timeouts, which would allow us to rate timeouts to determine how often timeouts are occurring?

This isn't very useful as a metric about Prometheus, as /metrics are about the health of Prometheus itself. Prometheus timing out a scrape is a normal and correct operation, and doesn't indicate any problems with the scraping code. In addition /metrics is not available within the Prometheus itself, and this would likely be very noisy due to all the other ways that a scrape can fail.

**Comment by roidelapluie** [comment]
Thank you for your issue. I agree with brian that this is of little interest for most of our users.

In general I'd recommend you to use the same scrape interval and timeout for the same prometheus server, which would make that easier.

**Comment by roidelapluie** [comment]
We have looked at it in our bug scrub and decided to close this as per above comments.

**Comment by midnightconman** [comment]
Thank you guys for looking at this... I think the recording rule is what I will go with.
Also, my main candidate for this was kube-state-metrics... After the auto sharding I don't have this issue as much.
