### ISSUE TITLE
Proposal: add metrics to expose scrape failed reasons of "down" target

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#7965]
## Proposal
**Use case. Why is this important?**
For edge clusters/CDN, the network condition is complex and unstable. There are always hundreds of nodes scraped failed by  prometheus due to invalid network connection. We do not care about those "down" targets by "invalid network connection", but care about "down" targets returned abnormal HTTP status such as 500/401, which means bugs or configuration problems.

Currently, we can not distinguish the reason of failed scrape by metric "up". We have to call "/api/v1/targets" periodically, and send alerts if there are scrapes with 500 HTTP status. That is not an easy way.

**What is proposed?**

Add a metrics which expose the reason of failed scrape, i.e. "prometheus_scrape_failed_reason_count" per status and job.

**Example:**
"prometheus_scrape_failed_reason_count{status="HTTP status 400",job="cdn_exporter"} 6"

**Comment by brian-brazil** [comment]
I don't think this makes sense, as this has cardinality issues due to the unbounded number of potential error messages and this is also not relevant to the health of the Prometheus server itself so doesn't belong on /metrics - a failed scrape is perfectly normal from the Prometheus server standpoint.

If you need this level of detail I'd suggest using the blackbox exporter, as you're not doing whitebox monitoring here.
