### ISSUE TITLE
Question: how to get the value of  a given label of a metric 

### ISSUE THREAD

**Issue by Thor-wl** [prometheus/prometheus#7985]
Hi, all!
I've get a metric through some experssions, for example, the expression is **discovering_paas_clusters{cluster_id="XXX",exporter_replica="XXX"}** , 
and the metric i get is 
**discovering_paas_clusters{cluster_id="XXX",cluster_status="Hibernation",exporter_replica="XXX"}=1**.
Now what i want to get is the value of the label "cluster_status". How can it achieve the goal?
Thank you!

**Comment by wangyuqing4** [comment]
I have the same problem :(

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
