### ISSUE TITLE
inhibit not work when two related alert first arrived at same time

### ISSUE THREAD

**Issue by AllenzhLi** [prometheus/prometheus#8038]
**What did you do?**

test inhibit rules

**What did you expect to see?**

severity 1 inhibit severity 4

**What did you see instead? Under which circumstances?**

I receive two alert which contains severity 1 and severity4

**Environment**

cortex 1.4

* System information:

	Darwin 19.6.0 x86_64

* Prometheus version:

	prometheus 2.20

* Alertmanager version:

	master branch

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
