### ISSUE TITLE
linux 2.22 download problem

### ISSUE THREAD

**Issue by neoEvol** [prometheus/prometheus#8094]
I'm trying to learn prometheus so I'm starting at the beginning: download & install. From a linux machine I issue:
`curl -O https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz
`
to get the file = prometheus-2.22.0.linux-amd64.tar.gz

i can see it in the ls command.  initially i just tried to unpack and use, but i kept getting a 'not a gzip' error after issuing the tar command. i went ahead and issued the checkSum command
`sha256sum prometheus-2.22.0.linux-amd64.tar.gz`
and i cannot seem to get a match with 
b9894d2bf7fae235c924c7dadda0fbc214ffc18a2bb3e9306f6fbecb589d5263

each time i remove the prom...tar.gz and redownload, i get a new, non-matching check sum value.  

Can someone please help me?

**Comment by roidelapluie** [comment]
Please use `curl -L` to follow links.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by neoEvol** [comment]
beautiful, thanks so much.  Apologies for the wrong place; will do better next time.
