### ISSUE TITLE
High memory in Prometheus 2.15.2

### ISSUE THREAD

**Issue by veer123prathap** [prometheus/prometheus#8109]
What did you do?
We are running on Prometheus on openshift platform
we are scraping 170 jobs 
memory:64gb
cpu:5
Remote write to victoria metrics (standalone machine)
within a day Prometheus went down due to high memory usage
What did you expect to see?
Prometheus running at the memory.

Prometheus version:

insert output of prometheus --version here
Prometheus 2.15.2

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
