### ISSUE TITLE
kill command not working

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/prometheus#8124]
Hi I have deployed the Prometheus instance via operator so I just want to restart the server the server is running at PID 1 so I give the command like 
kill -SIGHUP 1
but it is not killing the process
when I use
kill 1
the entire container is restarting!

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
