### ISSUE TITLE
Remote write [Influxdb], too many data tags , resulting in high memory usage. Support to control which labels are written into tags

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8149]
Support distinguishing tags and fields when remotely writing to influxdb

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
