### ISSUE TITLE
crash loop when data partition gets full

### ISSUE THREAD

**Issue by ldemailly** [prometheus/prometheus#8159]
**What did you do?**
Setup using community helm chart (8Gi data volume, 15 days retention)

**What did you expect to see?**
Would run indefinitely without crashing

**What did you see instead? Under which circumstances?**
Entered crash loop after 13 days because the volume got full.

I expect instead some warning that older data is being deleted sooner than configured retention. or an alarm. Not a crash loop.

**Environment**
k8s

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
