### ISSUE TITLE
Not able to scrape metrics at namespace level

### ISSUE THREAD

**Issue by pankajingle** [prometheus/prometheus#8169]
Hi Team,

I am using shared cluster to install the pronetheus. I am able to install it using helm 2 and tiller. Able to add the alerts and rules. But unable to scrape the metrics. Its again went to access the clusyter where i dont have permission so the metrics are not showing in prometheus UI. 

How I can scrape the metrics for my pod and services in my namespace not the cluster level..??

error:
level=error ts=2020-11-10T01:41:15.515Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:rd-datanav-devtest:prometheus-server\" cannot list resource \"pods\" in API group \"\" at the cluster scope"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
