### ISSUE TITLE
Prometheus Pull the data which is in the past

### ISSUE THREAD

**Issue by linux5396** [prometheus/prometheus#8172]
I run a exporter  and use the MetricsWithTimestamp  ,format below：

TIME_IDKEY{Id="1",Key="2"} 124845 1605099470000

but  the time is before now ,  why the prometheus does not pull it?  （it pull but i cannot query data from it?） 

please give me your hand ,  i am anxious...  thank you.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
