### ISSUE TITLE
different metrics showed

### ISSUE THREAD

**Issue by situjianxiong** [prometheus/prometheus#8194]
**What did you do?**
I'm running prometheus2.22.2 in docker and select metric on page
**What did you expect to see?**
only container_cpu_usage_seconds_total can be selected
**What did you see instead? Under which circumstances?**
but i get container_memory_failcnt at the same time
**Environment**

* System information:

docker

* Prometheus version:

2.22.2

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by situjianxiong** [comment]
![Uploading 图片.png…]()

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
