### ISSUE TITLE
Vector matching with logical operator doesn't report many-to-many error

### ISSUE THREAD

**Issue by pbadenski** [prometheus/prometheus#8208]
Example input:
```
vector1{x = "a", y="foo"}
vector1{x = "a", y="bar"}
```

**What did you do?**
vector1 and on(x) vector1

**What did you expect to see?**
Error because there's many-to-many results.

**What did you see instead? Under which circumstances?**
It works - not really sure what the result is...

Note: `vector1 / on(x) vector1` reports the error correctly: `many-to-many matching not allowed: matching labels must be unique on one side"`

**Environment**

* System information: Linux 4.19.0-0.bpo.6-amd64 x86_64
* Prometheus version: 2.22.2

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pbadenski** [comment]
I wasn't intending to ask a question, but instead was submitting this as a bug report. I only now noticed that the documentation says:

`Grouping modifiers can only be used for comparison and arithmetic. Operations as and, unless and or operations match with all possible entries in the right vector by default.`. 

Surprising, but I suppose it's a "feature not a bug" bucket.
