### ISSUE TITLE
Logs persistent

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/prometheus#8224]
Hi I am using the Prometheus which is from operator base the current version of the Prometheus is 2.22.0 which i am using.
May i know where the logs are capturing inside the Prometheus Pod and how do I maintain the logs in side the persistent block means how do we can transfer the generation of the logs from original generating directory to some other directory which is in persistent..

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
