### ISSUE TITLE
Increase function should conside long miss value as counter reset.

### ISSUE THREAD

**Issue by dypublic** [prometheus/prometheus#8240]
## Proposal
We are using promethuse for our system. There are counters which count low volume requests. Like there are a few hours between two requests. 
The alarm rule we use is "increae(clinte_abc_request{status: success})[2h] < 1", which means no request in 2 hours, we will create a alarm.
So for example, a counter clinte_a_request{status: success} = 1 now. And after app restart,  clinte_a_request will not have the value with tag status:success. And after 1 hour, there is one request happen. So counter become clinte_a_request{status: success} = 1.
But rule "increae(clinte_abc_request{status: success})[2h] < 1" will be fire. Because counter = 1 to  counter = 1 means no increament. 
We know after a hours' Nan value, the new 1 value, means there is a reset there.
We don't know how to resolve the false alarm. We want to have a reset when long time no value in a counter.

**Comment by brian-brazil** [comment]
Thanks for your suggestion. This sort of thing has been previously considered at length, and it would be incorrect to do this. There is no way to distinguish based on the time series if it had no values due to, for example, network issues as against the target being down for multiple hours as part of a restart. Basically the existence or non-existence of a values for a counter gives us no usable information about its resets, as they're completely orthogonal in general.

In general trying to work with such low volume counters is hard, particularly if you're trying to detect zero traffic, and have tend to have restarts more often than requests. One thing you could consider would be a gauge for the last time a request was received, which combined with max_over_time should meet your needs.

> We know after a hours' Nan value

A counter should never have a NaN value, if you're seeing this then that's a bug in the client library in use.

**Comment by dypublic** [comment]
Really thanks for your explanation, I thought this question for a few days. But I don't know why a gauge will help on this.
I know there is a function absent_over_time(), would it possible to have a function like part_absent_over_time?
So I could know there are missing parts in the counter over time.
(BTW, promethues is a great work, it helps a lot for our project.)

**Comment by roidelapluie** [comment]
> Really thanks for your explanation, I thought this question for a few days. But I don't know why a gauge will help on this.
> I know there is a function absent_over_time(), would it possible to have a function like part_absent_over_time?
> So I could know there are missing parts in the counter over time.
> (BTW, promethues is a great work, it helps a lot for our project.)

You can use count_over_time(): count_over_time(foo[5m]) < 10

**Comment by dypublic** [comment]
> > Really thanks for your explanation, I thought this question for a few days. But I don't know why a gauge will help on this.
> > I know there is a function absent_over_time(), would it possible to have a function like part_absent_over_time?
> > So I could know there are missing parts in the counter over time.
> > (BTW, promethues is a great work, it helps a lot for our project.)
> 
> You can use count_over_time(): count_over_time(foo[5m]) < 10

Thank you. But it related to the scrape interval. So we can't tell the correct count in a time range if the user are not do the config.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and per the above this would not be correct. Hopefully in future we'll be able to do better here using the _created from OpenMetrics.
