### ISSUE TITLE
How to modify "Storage Retention" in runtime ?. Is any REST API available

### ISSUE THREAD

**Issue by SAbdulRahuman** [prometheus/prometheus#8251]
I'm using prometheus and want to modify "Storage Retention" using REST API ?. Could you share details on how to modify prometheus config at run time ?.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
