### ISSUE TITLE
React UI: Some colors are not visible

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8256]
In the React UI (Prometheus 2.20.0):

Some colors are not visible in the graph (here, very ligth blue):

![color](https://user-images.githubusercontent.com/291750/101147578-db3b1a80-361c-11eb-8536-29f805f7ce83.png)

We should hopefully exclude those colors in the react ui.

**Comment by roidelapluie** [comment]
Oh there is even a white color...

**Comment by peter-turner-hcl** [comment]
@roidelapluie Ok to grab this one? Want to try my hand at contributing...

**Comment by roidelapluie** [comment]
Yes, but now that I think of it I am not really sure it is that easy :)

**Comment by peter-turner-hcl** [comment]
Yeah was looking at the colour picker and it looks like at first scan that it generates them using offsets from base colours. SO I guess we would want to exclude the colours based on *whiteness*. I have generated some test data and trying to get it into Prometheus and then will play around with this.

Is this just for the React UI or does it affect the Classic AI too?

**Comment by roidelapluie** [comment]
Awesome. In 4 years I never noticed anything with the classic UI, so it is only with the react UI.

**Comment by peter-turner-hcl** [comment]
Hi,

There is a palette of 5 colours which are fixed. Should a graph need more than 5 colours, it then slightly modifies the original palette. The algorithm is custom to the React UI. It *basically* tends the colours towards lighter or darker but it's not an easy to explain shift.

Here are the first 10 colours:
<img width="234" alt="Screenshot 2020-12-09 at 16 30 57" src="https://user-images.githubusercontent.com/49562857/101658843-52b5e300-3a3d-11eb-8e21-b339b7cbcfc1.png">
<img width="237" alt="Screenshot 2020-12-09 at 16 36 57" src="https://user-images.githubusercontent.com/49562857/101658878-5b0e1e00-3a3d-11eb-8040-3cec1f8df4fa.png">

You can see from the original palette and the generated palette for the next 5 colours, that it does:
darker, lighter, darker, darker, lighter

Now, the *paleness* of a colour is what we want to avoid. The grey colour spectrum is obviously a key example of this - and that's when we have r=g=b. So I could play with forcing the generated colours to have the r,g,b components separated by at least x. So rgb(210, 255, 255) which is light blue in palette2 (colour 7) would be re-generated for example since g and b are equal. rgb(210, 255, 240) might also be regenerated as we would pick a value x such that the difference between two components is at least x (say 32). In that case the last example would be regenerated since 255-240 = 14 <  32. I believe that should give us "well-defined" non pale colours but would need to experiment with this.

Another option is to define a full palette if we know there's never more than y colours possible on a graph but I don't know enough about Prometheus to comment on that.

Will think about some approaches and propose some more ideas. Happy to hear your thoughts! Cheers :D

**Comment by roidelapluie** [comment]
Don't we have some kind of color safeties in place that are not enough?

**Comment by peter-turner-hcl** [comment]
Colour safeties? i think that's what needs to be added :) Just thinking about best approach

**Comment by harrismirza** [comment]
I think a good approach to this would be to convert to HSL space (or just the L component) and then ensure the lightness is less than some cutoff, we could also possibly ensure the saturation is high enough to avoid greys.

Lightness in the HSL space is just the midpoint of the RGB values ((max(R,G,B) + min(R,G,B))/2).

**Comment by peter-turner-hcl** [comment]
Thanks for the info! Definitely not an expert in colours :) Will give that a try 👍

**Comment by sdhoward** [comment]
Just to further confirm, I did not have this issue in the classic UI. In the new UI it impacts me quite often, especially when graphing metrics that have more than 10 or 20 different vectors.

**Comment by peter-turner-hcl** [comment]
Sorry for the silence - this was side-lined but picking it up again. Managed to get some data into Prometheus and can now generate the metrics required to trigger x graphs and therefore the full range of colours.

**Comment by stevekuznetsov** [comment]
Love to see this! Right now the "default" color for me in a graph with one time series seems to be an ugly and hard-to-read yellow :)
![Screenshot from 2021-03-16 10-28-23](https://user-images.githubusercontent.com/7328370/111355457-9f184c80-8644-11eb-8a0f-24d3351c88b1.png)

**Comment by stevekuznetsov** [comment]
I guess I'd note - even if this yellow is not pale, perhaps it would be good not to use it against a white background anyway.

**Comment by lucacavazzana** [comment]
for graphs with a lot of time-series, _white_ may pop in, which is something that should definitively be avoided.
Here an example while selecting a white one.

![Screenshot 2021-05-12 at 16 48 22 (2)](https://user-images.githubusercontent.com/2910614/117996981-e4a27e80-b342-11eb-97dd-75c39b7f5b92.png)

**Comment by sdhoward** [comment]
please make the classic UI the default if this isn't going to be fixed soon

**Comment by reinaldocomputer** [comment]
Hello guys,
May I help with something in this issue?
I'd like to contribute somehow lol.
Tks

**Comment by juliusv** [comment]
@reinaldocomputer Yes please!

**Comment by peter-turner-hcl** [comment]
Yeah sorry never quite worked out how to get the colours randomly selected but avoiding pale colours...

**Comment by harrismirza** [comment]
@peter-turner-hcl Did the lightness trick not work?

**Comment by juliusv** [comment]
https://stackoverflow.com/a/20129594 has some good ideas. Working in the HSL model instead of RGB it's easier to keep a given maximum Lightness, but just randomize the Hue over the number of series we got. Of course the challenge could be that we still want the colors to look somewhat "cool", so that's down to experimentation and taste in the end :)

**Comment by peter-turner-hcl** [comment]
I'll need to revisit this - let me try tomorrow and will at least commit something that should be better which can be reworked further if needed

**Comment by sdhoward** [comment]
You guys should really prioritize this. Now there's a dark mode, and dark-colored lines don't show up, as well as light-colored lines not showing up in light mode.

@peter-turner-hcl you keep saying you're going to work on this tomorrow which I think is deterring others from investing time on it.

**Comment by juliusv** [comment]
@peter-turner-hcl Any update from your side? In case you won't be getting to this soon, that is fine, just let us know so that maybe someone else will feel motivated to pick it up :)

**Comment by suyashtava** [comment]
Hi Team, If it is still pending, may I have a look into it. Think it's a good start for Open Source contributing.

@peter-turner-hcl incase u have had some work already done, can u pls share a Draft PR, on which I can work further to get things rolling quickly, as we are also facing the same issue of color coding in dark mode especially.

**Comment by juliusv** [comment]
@suyashtava It's still pending and it seems people haven't been responding anymore here, so taking a look would be appreciated!

**Comment by suyashtava** [comment]
Thanks @juliusv for allowing me to pick this up. Any lead already taken if known by anyone, pls do share, it will be helpful.

**Comment by suyashtava** [comment]
Spent some cycles on it, and saw we are using Rickshaw color palette directly([here](https://github.com/suyashtava/prometheus/blob/dfa5cb7462b7b93b53eebec6197da594c6f78aa2/web/ui/static/js/graph/index.js#L627))
Since we are not defining any pallet it is using colorwheel([here](https://github.com/shutterstock/rickshaw/blob/10ed07db7fa03a3667a276d55514c999e8c9ab72/src/js/Rickshaw.Color.Palette.js#L10)) by default(which is obs, not a good choice).

I will look into it if any other pallet mentioned there with some interpolation is better or not.

**Comment by juliusv** [comment]
@suyashtava Oh that's good that you comment because we only used Rickshaw in the old UI, which is going away at some point, while the new React UI is the default now and it uses Flot instead of Rickshaw. The current relevant code for generating colors for the graph is here: https://github.com/prometheus/prometheus/blob/dfa5cb7462b7b93b53eebec6197da594c6f78aa2/web/ui/react-app/src/pages/graph/GraphHelpers.ts#L161-L187

As you can see, it quite naive at the moment and doesn't integrate a lot of theory about how to best generate differentiatable, but contrast-rich sets of colors.

**Comment by suyashtava** [comment]
We can make a good assumption that if around 50 colors are coming diff, then it can be considered as good algo, bcoz after that similarity starts arising, bcoz we need sufficiently bright colors for Dark UI.

**Comment by suyashtava** [comment]
Was validating some of the approaches.....
Looks like these random gen colors are good to go(we are not generating very Pale or very bright color hence No Black and White)
<img width="875" alt="Screenshot 2022-01-05 at 8 24 42 PM" src="https://user-images.githubusercontent.com/47897931/148239131-15f3e4f9-8463-4954-8999-ce2fe2c16212.png">
<img width="853" alt="Screenshot 2022-01-05 at 8 31 20 PM" src="https://user-images.githubusercontent.com/47897931/148239347-c0ede6ed-85d9-457e-b5ac-f0967179703d.png">

**Comment by suyashtava** [comment]
If we increase brightness further, some of the colors start getting more and more similar

**Comment by alisakotliarova** [comment]
Would it be a good idea to add some sort of visual emphasis on a line that is being hovered over?  (Not in this ticket/PR).  For example, the line becomes thicker and gains a small shadow (perhaps a glow if using dark mode).  That way if a color is not visible enough, its line could still be made clear and distinct by hovering over it. This also would help when there are lines of a similar color.  This would also support accessibility, as there doesn't appear to be any accommodations for color blindness.
If people like this I can make a separate issue to work on it.  I am new to open source so I thought to drop a comment here first.  Thank you!

**Comment by juliusv** [comment]
@suyashtava Yeah I agree, beyond 50 colors or so, we shouldn't care too much anymore about being able to tell them apart, so maybe we only need to get the first 50 "right". Btw. one implicit "requirement" that wasn't stated here yet is that the resulting color scheme should still look somewhat aesthetically pleasing when used in a graph. So it would be good to see different color schemes applied to a real-world graph to get a sense of what it would look like.

Another thought I just had, since Julien mentioned that there's never been an issue with the classic UI (which uses Rickshaw): as a candidate for a future colorscheme, would just copying the old Rickshaw colorscheme make sense? At least as a comparison to any other new colorscheme it would be good to look at. However, the classic UI never had a dark mode, so in any case, we need to check that as well.

@alisakotliarova Adding additional visual emphasis to hovered-over lines is a great suggestion, in my opinion that would definitely make sense as a separate issue. Yes, definitely feel free to work on it!

**Comment by suyashtava** [comment]
@juliusv Yup, this was the first thought which had striked my mind to basically reuse Rickshaw approach in New UI, but dropped it as now we have dark mode aswell

**Comment by juliusv** [comment]
@suyashtava Though it seems to me that the Rickshaw colors also work pretty well on a dark background. To try it quickly, I just went to https://demo.promlabs.com/classic/graph?g0.range_input=1h&g0.expr=histogram_quantile(0.9%2C%20rate(demo_api_request_duration_seconds_bucket%5B5m%5D))&g0.tab=0 and added a CSS property of `background-color: #222` to the `rickshaw_graph` div element:

![rickshaw-colors-dark](https://user-images.githubusercontent.com/538008/148382573-76fa07b3-ef95-458e-b0be-659460983d81.png)

**Comment by suyashtava** [comment]
@juliusv I see even Rickshaw color looks good, but I remember seeing the repetition of color in Classic UI. After first 16 I guess.

Even the pic u shared u can see 3 pink of same RGB Value
<img width="195" alt="Screenshot 2022-01-07 at 11 43 57 AM" src="https://user-images.githubusercontent.com/47897931/148500457-dd18fe41-6458-4578-8668-4936a47705c0.png">


But since no one has reported it yet, we can stick to d3-hsl interpolation approach used by Rickshaw or we can even use Rickshaw directly even here. Because its combition is asthetically pleasing

**Comment by suyashtava** [comment]
Also 1 more thing, in classic we were using colorwheel schema, with hsl interpolation,  So it start giving repititive colors after 16.

So we can use some other bigger color scheme like munich or some other defined [here](https://github.com/shutterstock/rickshaw/blob/10ed07db7fa03a3667a276d55514c999e8c9ab72/src/js/Rickshaw.Fixtures.Color.js)

**Comment by juliusv** [comment]
@suyashtava Yeah, that repetition is not great, thanks for pointing it out. We could still let ourselves be inspired by that set of colors as a starting set, but perhaps improve on it.

> or we can even use Rickshaw directly even here

Rickshaw wasn't ideal in other ways: It's SVG-based (vs. Flot's canvas approach) and thus slower, and I think even less maintained than Flot. But I also think that it's not worth switching graphing libraries again just for a color scheme, since the colors can be independently controlled in both libraries, and integrating Rickshaw into the new React code would be much more work than just changing colors.

> So we can use some other bigger color scheme like munich or some other defined here

You can also see a live demo of these color schemes here: https://tech.shutterstock.com/rickshaw/examples/colors.html

The `munin` one is too "90s" for my taste (I guess it's inspired by the old-school 90s monitoring system Munin: https://munin-monitoring.org/). I think of those on that page, `colorwheel` (which the old UI uses) still looks best for our purposes, with `cool` coming in second place, but of course that is a matter of taste. One adjustment we could make to it (besides extending it with more colors): the first color starts with red, which alarmed some people if they see a single red line and interpreted red as being a problem :) So maybe starting with green or yellow etc. could make sense.

So my proposal would be: start by copying Rickshaw's `colorwheel` approach over, then experiment a bit with adding more colors to it and maybe reordering them so the first one is not red, then see how it feels to people.

**Comment by suyashtava** [comment]
Yup, makes sense, Also I read the algo on why Rickshaw was repeating those colors, I think I have a fix for it as well.(Simple Algo modification). Will try it this weekend, with flot only.

**Comment by juliusv** [comment]
@suyashtava Great!

**Comment by alisakotliarova** [comment]
@suyashtava will do, [here is the issue I made for it](https://github.com/prometheus/prometheus/issues/10133).

If anyone has any pointers on where this sort of code would go or how to do this I would greatly appreciate it, I've been looking through the source code a bit and it's still not totally clear to me.  "Inspecting" the graph I see the lines are basically fused into the graph in a `canvas` element so I can't use CSS on them.  I think I found the code related to the tooltip that appears when a line is being hovered over so I'm looking through that but still I'm not sure how I can interact with the lines to make them change format on the hover trigger.  If anyone has thoughts feel free to comment them on the issue I made as it is a bit off topic discussing here.

**Comment by juliusv** [comment]
@alisakotliarova Great, thanks! Will reply to that on that issue.

**Comment by suyashtava** [comment]
Hi Team, sorry for the long pause, got occupied with some stuff. Gave a couple of hours today.

Attaching PR: [here](https://github.com/prometheus/prometheus/pull/10172/files)

One can visualize the colors here: https://3000-prometheus-prometheus-x6mx3n9eoox.ws-us27.gitpod.io/graph?g0.expr=prometheus_http_response_size_bytes_bucket&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h


Looks good to me now in both light and dark mode

CC: @juliusv

**Comment by suyashtava** [comment]
900+ diff colors , I dont think, we need more. :)

**Comment by suyashtava** [comment]
Please use the update PR: https://github.com/prometheus/prometheus/pull/10179

Also contains ref. of discussion.

**Comment by juliusv** [comment]
Thanks again! Merged :)

I'll close this issue then.

**Comment by suyashtava** [comment]
Thanks @juliusv 
Thank you will be happy to contribute more, incase u find something on which I can work, pls tag me there aswell. :)

**Comment by juliusv** [comment]
@suyashtava Sounds good! Generally here's a list of issues concerning the React UI, in case anything catches your interest: https://github.com/prometheus/prometheus/labels/component%2Freact-ui
