### ISSUE TITLE
Prometheus metrics repeat, and cause the promql to be unavailable.

### ISSUE THREAD

**Issue by sowhat7** [prometheus/prometheus#8275]
I add a label for node 10.193.32.44, and I get repeat metrics from prometheus at a certain moment. 
And then my promql is unavailable, because many to many are not allowed.
![image](https://user-images.githubusercontent.com/20253793/101777198-15c91980-3b2d-11eb-9af9-6d56f49a0e94.png)
![image](https://user-images.githubusercontent.com/20253793/101777223-1d88be00-3b2d-11eb-9385-86deee4c88c2.png)
![image](https://user-images.githubusercontent.com/20253793/101777242-27122600-3b2d-11eb-9302-dc5bd5c9fcfe.png)
![image](https://user-images.githubusercontent.com/20253793/101777248-2aa5ad00-3b2d-11eb-9c35-48acf2b4ad0a.png)
prometheus version: 2.7.2
node-exporter version: 0.17.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
