### ISSUE TITLE
? in prometheus.yml metrics_path the urlEncoded

### ISSUE THREAD

**Issue by qq1244560904** [prometheus/prometheus#8283]
this is my prometheus.yml
`global:
  scrape_interval:     15s 
scrape_configs:
  - job_name: metrics
    metrics_path: "/actuator/swPort?taskName=alarm"
    scrape_interval: 14s
    scrape_timeout:  14s
    static_configs:
      - targets: ['localhost:8081']`

and in chrome url is http://localhost:8081:/actuator/swPort%3FtaskName=alarm
It leads to my endPoint is 404  and no data in prometheus
his state is down.  
I don't want this ? Be urlEncoded

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
