### ISSUE TITLE
Any way to set the time threshold after which Prometheus discovers an exporter has gone down?

### ISSUE THREAD

**Issue by SeanTse** [prometheus/prometheus#8295]
By some tests, I find the threshold is 5 minutes now. Is there any way to set this parameter?

**Comment by roidelapluie** [comment]
It looks as if this is actually a question about usage and not development.


I guess your are using an exporter which exposes timestamps, therefore staleness does not apply.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

When you do so, can you please provide some details about your setup, like which exporter is causing this.

**Comment by SeanTse** [comment]
I think the mailing list may helps.. Sadly, I am in a country where google's most websites are unavailable legally :stuck_out_tongue_closed_eyes: Thanks anyway!
