### ISSUE TITLE
query return no exist series 

### ISSUE THREAD

**Issue by RayHuangCN** [prometheus/prometheus#8297]
prometheus version 2.23.0

if i run a pod
![image](https://user-images.githubusercontent.com/23702523/102343852-0b4bcb80-3fd6-11eb-9bcd-76c5faae7eb5.png)

then, one of containers restart
![image](https://user-images.githubusercontent.com/23702523/102345178-ece6cf80-3fd7-11eb-9293-c8563b5bb22b.png)
![image](https://user-images.githubusercontent.com/23702523/102345365-3f27f080-3fd8-11eb-9706-1706c1b7aa25.png)

query  will  return old container series 
![image](https://user-images.githubusercontent.com/23702523/102345649-b067a380-3fd8-11eb-8fd4-d7a41783c352.png)

but the metrics return from kubelet is right
![image](https://user-images.githubusercontent.com/23702523/102345822-ed339a80-3fd8-11eb-801d-72ba63bde089.png)

this cause wrong result when use "sum"
![image](https://user-images.githubusercontent.com/23702523/102346013-34ba2680-3fd9-11eb-8ddf-491aa8fbe041.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
