### ISSUE TITLE
Support string literals in Prometheus' expfmt parser

### ISSUE THREAD

**Issue by XNorith** [prometheus/prometheus#8302]
Hi all, I would like it if the expfmt parser in Prometheus supported the the same semantics for the ', ", and ` characters that are described here: https://prometheus.io/docs/prometheus/latest/querying/basics/
It currently looks like 
https://github.com/prometheus/common/blob/20c99e7aa07352b599bd0517cd5ca945f4af0407/expfmt/text_parse.go#L322-L324 only allows for label values to be quoted with double-quotes.

My use case is that I want to use the text-file collector for node-exporter, which uses expfmt, to define metrics with names such as:
prometheus_response_time{query=`count(up{env="prod",prometheus_replica="p-a-0"})`}

which is easier for a human to read than
prometheus_response_time{query="count(up{env=\\"prod\\",prometheus_replica=\\"p-a-0\\"})"}

Thanks!

**Comment by brian-brazil** [comment]
That would be a breaking change to the text format, which has been stable for years, is ingested by numerous different monitoring systems, and is not going to change at this point as work is on OpenMetrics (which also does things this way also). Having multiple ways to escape things makes parsers harder to write, which is ultimately more likely to cause confusion and gotchas in parsers. The key point is that it is rendered and parsed correctly, as strings like these are produced and read primarily by computers - not humans.

**Comment by roidelapluie** [comment]
I agree with Brian. There is not forecoming changes to the text format foreseen.

If you want to discuss this further, you could ask on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially help you, and the whole community can benefit from the answers provided.
