### ISSUE TITLE
How to write the result of PromQL calculation to prometheus with a new tag

### ISSUE THREAD

**Issue by xewn** [prometheus/prometheus#8330]
How to write the result of PromQL calculation to prometheus with a new tag
eg:
newtag = 100 * (1 - avg (irate(node_cpu{mode='idle'}[5m])) by(job) )
Store newtag in Prometheus

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
