### ISSUE TITLE
field eureka_sd_configs not found in type config.plain

### ISSUE THREAD

**Issue by yuyivic** [prometheus/prometheus#8369]
**What did you do?**
I upgraded the prometheus to the latest version，and adding below eureka parameter to the configuration file，but failed to parse it：

scrape_configs:
  \- job_name: 'eureka'
    eureka_sd_configs:
      \- server: http://eureka1.test.com:18761/eureka/

sudo ./promtool check config conf.yml
Checking conf.yml
  FAILED: parsing YAML file conf.yml: yaml: unmarshal errors:
  line 178: field eureka_sd_configs not found in type config.plain

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
        CentOS Linux release 7.4.1708 (Core)

* System information:
	Linux 3.10.0-693.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.24.0 (branch: HEAD, revision: 02e92236a8bad3503ff5eec3e04ac205a3b8e4fe)
  build user:       root@d9f90f0b1f76
  build date:       20210106-13:48:37
  go version:       go1.15.6
  platform:         linux/amd64

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
