### ISSUE TITLE
Support SFP 10Gb Port

### ISSUE THREAD

**Issue by Hiiirad** [prometheus/prometheus#8371]
## Proposal
Using the Prometheus monitoring system is one of the best choices for me in different solutions. Unfortunately, we have lots of services that connect using SFP 10Gb ethernet. We have huge traffic coming to our servers, and we need to process them and analyze network traffic based on transmit and receive. This feature must be categorized as a high priority.

Thanks for your support

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
