### ISSUE TITLE
Monitoring on different port

### ISSUE THREAD

**Issue by Hiiirad** [prometheus/prometheus#8372]
## Proposal
Using the Prometheus monitoring system is one of the best choices for me in different solutions. Unfortunately, we use many ports on one network interface, which need to be monitored and analyzed. We have lots of services that talk to each other to handle customer's requests and analyze network traffic based on transmit and receive on those specific ports. This feature must be categorized as a high priority.

Thanks for your support

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
