### ISSUE TITLE
PromQL one to many matching with different label sets

### ISSUE THREAD

**Issue by jan-dubsky** [prometheus/prometheus#8390]
When I have a metric with different label sets, for example:
```
label_metric{foo="a", bar="b"} 0
label_metric{foo="a", bar="c"} 0

my_metric{foo="a", bar="b"} 5
my_metric{foo="a"} 3
```

---

When I use the following aggregation:
```
min by (foo, bar) (
  my_metric
)
```
I get an expected result:
```
my_metric{foo="a", bar="b"} 5
my_metric{foo="a"} 3
```

---

But when I instead use one to many operation:
```
label_metric
+ on (foo, bar) group_left()
my_metric
```
I would expect a following result:
```
{foo="a", bar="b"} 5
{foo="a", bar="c"} 3
```
as it would be consistent with the aggregation operations behaviour.

But instead, I get the following result:
```
{foo="a", bar="b"} 5
```

---

This is behaviour is inconsistent with the aggregation operation behaviour. Is there any reason for this inconsistency? The problem I see here is that the `group_left()` operation can silently drop data. This is confusing, but more importantly it doesn't seem to be right, given that this data could be correctly paired.

**Comment by brian-brazil** [comment]
This behaviour is consistent, and as expected.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
