### ISSUE TITLE
promethus cumsumer data from kafka ,and show the result at grafana

### ISSUE THREAD

**Issue by tonyC2016** [prometheus/prometheus#8395]
some metric will be used at many multiple ,so kafka is a good choice, how promethus consumer the kafka data?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
