### ISSUE TITLE
Use alertmanager API v2 by default

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8398]
I am proposing that in the Prometheus 2.25 release notes, we announce the future move to the alertmanager API v2 by default.

And 2.26 would make the switch to v2 by default.

Keep the option to use v1 for the time being.

**Comment by roidelapluie** [comment]
Mmh

https://prometheus.io/docs/prometheus/latest/stability/

It is not clear if we are allowed to do this.

**Comment by simonpasquier** [comment]
For the record, Alertmanager API v2 has been introduced in v0.16.0 (2 years ago) and I would say that we're on par with the API v1 since v0.19.0.
Agree that the docs make it sound contentious but if we remove API v1 from Alertmanager (which isn't covered by the same guarantees IIUC), one can argue that the best move for Prometheus is then to default to the API v2 (e.g.  "Some features, which are cosmetic, still under development, or **depend on 3rd party services**, are not covered by this.").

To be clear, I'm very much interested in dropping v1 support in Alertmanager :)

**Comment by roidelapluie** [comment]
We have looked at this during the bug scrub.

Prometheus 2.25 will have a warning note in the changelog about this. The plan is to default in 2.26 to api v2.

**Comment by gotjosh** [comment]
I think we can close this at this point @roidelapluie, given #8484 was merged and released.
