### ISSUE TITLE
Error using container_memory_usage_byte to check container is in running state 

### ISSUE THREAD

**Issue by avanichy25** [prometheus/prometheus#8408]
I am using query in Prometheus to check my containers are in running state or not using  container_memory_usage_byte but not getting response as 1 when stopped the container and used the below query.
-->

**What did you do?**
absent(container_memory_usage_bytes{name="container_name"})

**What did you expect to see?**
When container is down i should get the alert that container_name is not running

**What did you see instead? Under which circumstances?**
I am getting value as no data.

**Environment**
docker 

* Prometheus version:
   prometheus:v2.22.2

* Alertmanager version:
* alertmanager:v0.18.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
