### ISSUE TITLE
absent function doesnot support regex

### ISSUE THREAD

**Issue by gowrisankar22** [prometheus/prometheus#8409]
Regex for the absent function is not working. The absent function doesn't support?

I have 10 containers running example: 
`test_container_1 to test_container_10`  out of 10 containers 2 containers are down `test_container_5 and test_container_8`.

I trying to use absent to find out the same but this is not working.

```
absent(container_memory_usage_bytes{name=~"test.*"})

```

**Comment by alburthoffman** [comment]
this is expected. because absent will check if any outputs for ur query. 

In ur case, you want to find out test_container_5 and test_container_8. absent wont be able to do that because it does not know what used to exist. It's impossible to let absent remember all label values like 10m ago.

"unless" would be the solution for this case. like 
`(A offset 10m) unless A`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
