### ISSUE TITLE
Lazy load blocks for queries

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#8518]
Currently we m-map all the blocks that are present in the TSDB on startup which occupies a good chunk of working set memory that is used to kill a process as OOM.

Most of the queries that are performed is for recent data and occasionally on historical data (my definition of occasional here is more than few hours old), so there is no need to m-map all the blocks that are there on the disk.

My proposal here is that we un-map the blocks which have not been queried in last X minutes and only m-map when a query comes for that block (that means we only store the meta file in the memory). This has worked good for Cortex's store-gateway, so we might as well try this in TSDB. Care should be taken to avoid race between un-mapping and m-mapping to avoid panics on `[]byte` access.

/cc @pracucci 

Update: With Go 1.16, this behaviour of working set memory for m-mapped files will change (i.e. the process wont hold onto unused memory, [see](https://github.com/prometheus/prometheus/issues/8518#issuecomment-784183460)). So not a high priority at the moment.

**Comment by brancz** [comment]
I think this makes sense. Additionally we might want to look at what we can do in regards to what was attempted here https://github.com/prometheus/prometheus/pull/8495

**Comment by pracucci** [comment]
> This has worked good for Cortex's store-gateway, so we might as well try this in TSDB.

I confirm this. We did it in Thanos (Cortex's store-gateway is based on that) for the index-header which is the part of TSDB we keep on local disk (everything else is loaded on-demand from the object store):
https://github.com/thanos-io/thanos/blob/b30a135869f2770529f024dd9d993e940cc216d8/pkg/block/indexheader/reader_pool.go#L20-L24

**Comment by roidelapluie** [comment]
When would we un-mmap ?

**Comment by codesome** [comment]
> When would we un-mmap ?

My understanding: whenever we get a query on a block, we store something like `lastAccessed` in the meta.json. Check the blocks every minute for `lastAccessed`, and if it is more than X minutes old (configurable for TSDB), we un-map it.

**Comment by codesome** [comment]
To make this change safe and easy, I am thinking of a simple wrapper around the existing block
```go
type LazyBlock struct {
	meta BlockMeta
	blockMtx sync.RWMutex
	block *Block
}
```

And the corresponding function calls checking for a `nil` block and loading the block as we do right now.

**Comment by bwplotka** [comment]
>  startup which occupies a good chunk of working set memory that is used to kill a process as OOM.

Yea I think this is broken on Kubernete's side, so let's make sure we are tracking the progress there.

### Some thoughts: 

1. Let's reuse Thanos/Cortex code (or actually port and import Thanos/Cortex one from Prom).
2. Let's not modify meta.json. It's a very tricky topic that can go sideways easily. We don't need persistence for this.

**Comment by pracucci** [comment]
Yesterday we tried to switch a Cortex cluster back to `GODEBUG=madvdontneed=1` and, from preliminary results, look like the workingset memory issue has been solved. Go 1.16 may solve the workingset memory issue which originated this issue, but doesn't mean lazy loading blocks would be a bad idea (eg. would reduce the number of memory map areas, which has a per-process limit on Linux).

**Comment by bwplotka** [comment]
Nice! 

Cool, yes, so in order to make Prometheus bit more scalable, such improvement would be nice - but not high priority though.

**Comment by Harkishen-Singh** [comment]
How does this sound like a rough approach?

I am not very used to tsdb code (so please correct me) but based this is based on my understanding.

Right now at the start, we mmaps all the blocks (mmaps Index, Chunks) in the dir. We also mmap head_chunks which is good but is not related to the problem here. Focusing on the blocks on disk, Prometheus will continue to mmap blocks at the start (as it requires verifying the health of each block). Once the blocks are loaded and db is up, we start a routine that checks every minute which blocks were queried last.

The information related to last queried will be a struct

```golang
type blockQueryInfo struct {
    ref *Block
    isMMapped bool 
    lastQueried time.Time
}
```
The `blockQueryInfo` struct will be a part of `DB` as a slice of blocks on disk.

This information will be in memory and does not require to be in the block metafile. Initially, the value of `lastQueried` for all blocks will be `time.Now()`. When the routine starts, it looks for those blocks which were queried in the last 10 minutes (or some duration), and takes a lock (per block, which means `Block` struct will contain a mutex). Then we unmap the blocks and release the lock.

There can be a query during the unmapping process that overlaps the unmapping block. Assuming unmapping can take a while, this can cause the query to wait until till the lock on the block gets released which overlaps the query time range. I don't know how much significant time this would be, but my guess is it should be fine, as there have been 10 minutes for this block to not receive any query.

If we receive a query for an unmapped block (which we can know from `isMMapped`), we will map the block and update the `lastQueried`.

**Comment by bwplotka** [comment]
Some details:
* mmap is not causing OOM
BUT
* There are baseline heap allocations every block due to struct fields (1/32 posting index, 1/32 symbols)
* There is a limit to how much stuff you mmap (or number of mmap files)

Also do you mind checking if we can use exact same implementation of Thanos (and this is what Cortex is using).

**Comment by beorn7** [comment]
@jesusvazquez @codesome @bwplotka We were running into this during our bug scrub. How relevant is this still? It sounds a bit that Go 1.16 made it enough of a non-issue to not invest more effort here. But we don't want to make this call on our own. Could you help us?

Generally, it feels needlessly complex to have the OS mmap logic and then put another layer of memory management on top. To take a step back, maybe we should reconsider using mmap'ing at all? There are known issues of bad interaction of OS paging and the Go concurrency model…

**Comment by bboreham** [comment]
No response, so closing after 6 months.
Please re-open if you have further input.
