### ISSUE TITLE
Promql should limit the possible duration

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8526]
I think we should error propery when we overflow the duration.

**What did you do?**

execute `max_over_time(vector(1)[1000y:1000y])` 

execute `max_over_time(vector(1)[2000y:2000y])`

**What did you expect to see?**

execute `max_over_time(vector(1)[1000y:1000y])`  => 1

execute `max_over_time(vector(1)[2000y:2000y])` => 1

**What did you see instead? Under which circumstances?**

execute `max_over_time(vector(1)[1000y:1000y])`  => empty set

execute `max_over_time(vector(1)[2000y:2000y])` => 1

**Environment**

* System information:

	https://prometheus.demo.do.prometheus.io/

* Prometheus version:

	prometheus 2.24.0

**Comment by wfelipew** [comment]
This problem occurs because the "time.Duration" on Go is limited to 290 years. When you exceed this limit you get unexpected behaviours. 
In this case "1000y" will be parsed as "-5357488147419103232".
I will try to fix this by validating if the input range exceeds 290 years on "func ParseDuration(durationStr string) (Duration, error)".
