### ISSUE TITLE
Remote storage adapter for nodejs backend

### ISSUE THREAD

**Issue by alexandruluca** [prometheus/prometheus#8611]
I am currently trying to write a storage adapter for a nodejs backend.

I have setup a http server and I am trying to read the request body.
I am trying to read the body by using following body parser, however I am getting an error message

```
app.use(bodyParser.raw({type: 'application/x-protobuf'}));
```

```
UnsupportedMediaTypeError: unsupported content encoding "snappy"
```

All remote exporters are written in golang, I would like to use nodejs for several reasons. Is there any documentation on how to parse the incoming request or any examples of storage exporters written for a nodejs backend?

**Comment by roidelapluie** [comment]
Hello,

Thanks for your interest in Prometheus.

In addition to protobuf, the requests are also compressed with Snappy. There seem to be snappy libraries for nodejs:
https://www.npmjs.com/package/snappy


It is better to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by alexandruluca** [comment]
@roidelapluie Thank you for the answer. I had a look over that before posting the issue but I didn't really try to uncompress the request as it looked too cumbersome to start with. 

I gave it now a try and it seems to work. I am working on an example right now. When I'm finished, if you want, I can post an example for nodejs, maybe other users find it useful as well since I didn't find any useful material while I researched.

If you don't think it is needed, please feel free to close the issue

**Comment by roidelapluie** [comment]
Hello,

We are not able to keep examples up to date, but you are very welcome to host your example code in a public github repository. If your final product is public, we can also link it from our documentation.

Thanks.
