### ISSUE TITLE
Whether it is possible to configure the duration of the alarm to the present in the alarm rules

### ISSUE THREAD

**Issue by liuyanmei069** [prometheus/prometheus#8635]
是否可以实现在告警规则上配置发出告警到目前的持续时间，如何在rule文件配置去获取当前时间并减去触发时间
Whether it is possible to configure the duration of the alarm to the present in the alarm rules, and how to obtain the current time and subtract the trigger time in the rule file configuration

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
