### ISSUE TITLE
component=tsdb msg="compaction failed" err="persist head block: mkdir /prometheus/01F1MQRW4QTJ12KYV6TRXZKWMD.tmp: permission denied"

### ISSUE THREAD

**Issue by bharangit** [prometheus/prometheus#8646]
Hi,

Prometheus configured on AKS cluster in two namespaces (dev, stage). It is working in dev but not in stage. 

If i go to stage prometheus portal and check status-> Targets I all are targets are unhealthy in stage but works in dev.

stage target error : _level=warn ts=2021-03-25T12:48:27.946Z caller=manager.go:572 component="rule manager" group=./stage.rules msg="rule sample appending failed" err="write to WAL: log samples: create new segment file: open /prometheus/wal/00000002: permission denied"_

Could you pls help what could be the cause and what is the fix. thanks

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
