### ISSUE TITLE
Use a common TS PrometheusClient between codemirror-promql and prometheus

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#8686]
I just noticed that in https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/pages/graph/PanelList.tsx#L134 there is a way to retrieve the list of the metric.

Do you think it would be a good idea to actually use the PrometheusClient that has been implemented here: https://github.com/prometheus-community/codemirror-promql/blob/master/src/lang-promql/client/prometheus.ts#L83

I hope you will find it a bit cleaner and it will share the way to contact Prometheus in TS.

I don't know if it makes sense to put this client in a single library to provide a TS HTTP Prometheus Client.

By the way, I wasn't sure if it is the correct way to ask for this kind of "refactoring". So please let me know, if I was wrong to do it like that :).

**Comment by Nexucis** [comment]
I guess the answer should come from you @juliusv ^^ (following the code ownership)

**Comment by juliusv** [comment]
@Nexucis We use the `useFetch()` hook on every page to fetch info from the API (not just data-related info), which I think is a fine and React-ish way of doing things, and doesn't need features such as client-side caching (since it's always just a single request upon page / component load). The Prometheus client in cm-promql is focused around metadata querying only, and currently I don't see a good reason to extend and integrate it into the rest of Prometheus for the other purposes yet.

But yeah, I was thinking earlier that it could be nice if Prometheus (or any other user) could pass in the list of metrics that it already has to the codemirror-promql layer upon initialization, so it doesn't have to be fetched twice.

**Comment by Nexucis** [comment]
mmm ok. So you are more thinking about injecting a list of data into the promClient of cm-promql ?

> currently I don't see a good reason to extend and integrate it into the rest of Prometheus for the other purposes yet.

Well we could think about creating a TS lib that would contains a complete Prometheus Client covering the whole API like it has been done in Golang and other language.
