### ISSUE TITLE
remote_url influxdb prometheus

### ISSUE THREAD

**Issue by diaosichen** [prometheus/prometheus#8725]
i need to use influxdb to store prometheus data on the remote_url:
but i only store some metrics data to A database，store some other metrics data to B database，how can i config the remote_url?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
