### ISSUE TITLE
Dropping metrics by metrics value at scrape time

### ISSUE THREAD

**Issue by iwctwbai** [prometheus/prometheus#8745]
The metrics looks like this
```
ifHCInOctets{ifIndex="30",instance="111.63.32.254",}    0
ifHCInOctets{ifIndex="31",instance="111.63.32.254",}    0
ifHCInOctets{ifIndex="32",instance="111.63.32.254",}    21342334
ifHCInOctets{ifIndex="33",instance="111.63.32.254",}    12342321111
```

I want to filter all data with a value of 0
```
write_relabel_configs: # 写入前
    - source_labels: [ifHCInOctets]
      regex: "0"
      action: drop
    - source_labels: [ifHCOutOctets]
      regex: "0"
      action: drop
```

it doesn't work

**Comment by iwctwbai** [comment]
@Harkishen-Singh  can you help me

**Comment by Harkishen-Singh** [comment]
I am not strong in relabel configs, but I think the regex part corresponds to the value in a label. I can be very wrong.

**Comment by roidelapluie** [comment]
You can not drop metrics by value.

It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
