### ISSUE TITLE
Time calulation for probe_success 0

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/prometheus#8750]
HI let we take an example like the probe_success metrics here the promethes can able to show the values 1 or 0 for a probe so I want to display like if the probe_success is 0 over a time of last 5 min then only it should be display other wise nothing to show. So may i konw how to calulate this measuremnt.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
