### ISSUE TITLE
Prometheus target is giving server returned HTTP status 404 Not Found Error

### ISSUE THREAD

**Issue by Satyasreegoli** [prometheus/prometheus#8815]
Hi

I have installed Prometheus instance in Openshift 4.5. I am trying to monitor MongoDB services which are in different namespace. Able to see MondoDB service in Prometheus Targets but State is showing as DOWN with server returned HTTP status 404 Not Found Error.
Any suggestions are appreciated.

Thanks
Satyasree

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
