### ISSUE TITLE
Support named port resolution using /etc/services

### ISSUE THREAD

**Issue by ekpdt** [prometheus/prometheus#8848]
## Proposal

Support [hosts](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#host) with named services (e.g. `foo:namedservice`) in addition to the traditional port number `foo:8080` descriptor. Named ports should be resolved by consulting the OS (`/etc/services` / `netdb.h` on *nix, `%WINDIR%\system32\drivers\etc\services` on Windows). 

**Use case. Why is this important?**

This helps organizations that already rely on named services (for example, to minimize port conflicts) continue to use that mechanism when adopting Prometheus. Without this feature, users need to replicate their OS-level configuration in their Prometheus config files.

**What happens today?**

The `/targets` page of the Prometheus web gui complains about named services:
`parse "http://host1:service1/metrics": invalid port ":service1" after host`

**Comment by roidelapluie** [comment]
Thank you for your interest in Prometheus. We use the upstream HTTP library, which does not support that.
I think such a feature adds a lot of complexity for little gains for the majority of our users. I do not know of any other software doing that extra step. Do you have examples of other software vendors doing this?

**Comment by ekpdt** [comment]
Thanks for considering this feature.

> We use the upstream HTTP library, which does not support that.

At the very least, the golang stdlib supports lookups based on /etc/services (though I note that the implementation parses the services file instead of using the posix call from netdb.h). https://golang.org/src/net/port_unix.go

> Do you have examples of other software vendors doing this?

/etc/services is the preferred way to do address resolution support by https://man7.org/linux/man-pages/man3/getaddrinfo.3.html . I don't have a good sense what third-party software supports this, though many unix tools do. It's common for "enterprise" organizations to use centrally provisioned /etc/services files to manage port assignment across a large organization. It seems to me that Prometheus should not reject URLs that are generally accepted elsewhere by the system. (Note that Prometheus respects /etc/hosts just fine, though I'm not sure if that's happening at the Prometheus, golang, or posix level!)

**Comment by roidelapluie** [comment]
Thank you for you request. We have looked at this during our bug scrub and it seems that we should not deviate from what the upstream golang http library is doing. We have decided to close this issue. This particular use case seems pretty niche.

As an alternative, you could maybe generate relabeling_configs to map those names to port numbers.

> Prometheus should not reject URLs that are generally accepted elsewhere by the system.

Note that Prometheus not reject it, we pass it as is to the golang http library.

If you disagree, please contact the  [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) because that change would need to be propagated to alertmanager, blackbox exporter and other components of the ecosystem.
