### ISSUE TITLE
Prometheus remote writes too many metrics metadata at once.

### ISSUE THREAD

**Issue by pstibrany** [prometheus/prometheus#8870]
## Proposal

We're seeing that Prometheus with lot of metrics is remote-writing messages with 117273 metrics metadata, producing 25 MiB big messages.

We would like to have more control over how metadata messages are generated (eg. using batching, configurable max size of message, or max number of metrics to include in single metadata message).

**Use case. Why is this important?**

Cortex is able to ingest metadata sent by Prometheus, but Cortex also imposes limits on message size that it can receive. Unfortunately messages sizes with metrics metadata currently seem to be unbounded.

**Comment by pstibrany** [comment]
According to @gotjosh Prometheus already uses batching mechanism when remote-writing metadata. In our scenario however, there are many metrics with the same name, but different HELP string produced by different jobs. Such metrics would end up in the same batch.

**Comment by gotjosh** [comment]
Apologies @pstibrany, I must have misremembered that we changed the implementation during #6815. We actually decided to move away from batching it in favour of a direct collect and send to simplify the logic. So metadata collected is not effectively batched at the moment.

I think we have two avenues:

We can start following the lead of remote write with a `max_metadata_per_send` and split that particular batch into multiple requests.

```
# Maximum number of samples per send.
  [ max_samples_per_send: <int> | default = 500]
  ```
  
  or we can start looking into leverage the sharding strategy from remote write, I'd prefer to go with the first option as it would be quite simple to implement. I don't favour the latter because I'd rather have us spend the time wrangling https://github.com/prometheus/prometheus/pull/7771 into shape which is meant to send metadata alongside samples.

**Comment by gotjosh** [comment]
WDYT @roidelapluie ?

**Comment by cstyan** [comment]
@gotjosh I agree with your take. Since we're still planning to put work into both transactional remote write and #7771 at some point, doing the simplest thing here for now seems best. 

The only concern is introducing yet another config option that will likely go away in the near future. Might be a bit more work given that we compress the message, but if there's a nice way to limit each metadata message to 4MB (pretty sure this is the Go GRPC default max message size) that would be ideal IMO.

@csmarchbanks any thoughts?

**Comment by csmarchbanks** [comment]
I agree, max_samples_per_send in the metadata_config seems like a great short term solution. The entire `metadata_config` block is marked as it may change or go away anytime so adding another field there seems OK to me.

**Comment by roidelapluie** [comment]
Let's indeed have this as short-term solution, marked experimental.
