### ISSUE TITLE
Generate huge prometheus data (100GB) to take a snapshot

### ISSUE THREAD

**Issue by LavanyaVaddavalli** [prometheus/prometheus#8922]
I'm trying to test how much time it takes to get a snapshot if I have huge Prometheus data (100 GB). The problem is how do I generate such huge data that will be considered for snapshot?

[ for taking a snapshot, I'm using the admin api: "POST /api/v1/admin/tsdb/snapshot" ]
[I downloaded using docker image, version 2.15.1]

**Comment by roidelapluie** [comment]
Hello,

Snapshots are supposedly instant -at least on linux- as they use hard links. I recommend you to post your question on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
