### ISSUE TITLE
Add ability to configure scraping port for eureka discovery targets

### ISSUE THREAD

**Issue by drax68** [prometheus/prometheus#8957]
## Proposal
**Sometimes metrics endpoint on target services registered in eureka are exposed on a specific non-business port, let's say using "adminPort" metadata property.**
Looking into eureka discovery plugin code, I can see that only Port, SecurePort properties are utilized from service eureka metadata.
It would be great to have that property configurable so end users can choose any numeric property as a target port for actual metrics scrapes.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development, as this should be possible via relabeling.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
