### ISSUE TITLE
consul.go watchTimeout may cause gateway timeout

### ISSUE THREAD

**Issue by t00350320** [prometheus/prometheus#8979]
we have a request to consul cluster by gateway,but the gateway always give a timeout alert when there is no update for consul informations,  because the lastindex not changed in global systerm.
costs: 30163ms
context:
getConnectionMs=138,writeDoneMs=138,getResponseMs=30163,url=/v1/catalog/service/xx/10.175.*.*?dc=tshouse&index=68643534&stale=&wait=30000ms
errorinfo:
SocketTimeoutException:connect#11681742[10.171.xx:8500] read timeout.
=====
files:
func() watch
prometheus/prometheus/blob/main/discovery/consul/consul.go
watchTimeout = 2 * time.Minute

so we wonder why above paramter "watchTimeout" is so biger as default.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
