### ISSUE TITLE
If i use Prometheus remote write integration in a high-availability (HA) configuration, how can i make sure my Prometheus servers not send multiple copies of the same metrics

### ISSUE THREAD

**Issue by tcjin** [prometheus/prometheus#8993]
If i use Prometheus remote write integration in a high-availability (HA) configuration, how can i make sure my Prometheus servers not send multiple copies of the same metrics

**Comment by darshanime** [comment]
tracked here - https://github.com/prometheus/prometheus/issues/8885

**Comment by roidelapluie** [comment]
Hello, it is different from #8885.

It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
