### ISSUE TITLE
Multiple Prometheus monitor the same targets, and each node's Prometheus will call the remote write, resulting in data duplication

### ISSUE THREAD

**Issue by tcjin** [prometheus/prometheus#9002]
Multiple Prometheus monitor the same targets, and each node's Prometheus will call the remote write, resulting in data duplication

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
