### ISSUE TITLE
If the AlertManager nodes communicate with each other using Gossip protocol, it is possible to derepeat the alerts. Why are the Prometheus nodes independent of each other, and cannot realize the existence of other nodes, and can not make the master node to become the master node when the master node fails? And that creates a lot of redundancy, right? Have you considered doing this feature? We can have a poll

### ISSUE THREAD

**Issue by tcjin** [prometheus/prometheus#9003]
If the AlertManager nodes communicate with each other using Gossip protocol, it is possible to derepeat the alerts. Why are the Prometheus nodes independent of each other, and cannot realize the existence of other nodes, and can not make the master node to become the master node when the master node fails? And that creates a lot of redundancy, right? Have you considered doing this feature? We can have a poll

**Comment by roidelapluie** [comment]
Hello,

This is the core architecture of Prometheus. Before being a metrics collection system, Prometheus is a monitoring solution. As such, by design, we do not have any mesh or ring or cluster principles. You would be free to work with other tools (e.g. pacemaker/corosync) to do that work, but I would not endorse it.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
