### ISSUE TITLE
The PromeValues machine configuration has not been touched, and it suddenly failed to start today

### ISSUE THREAD

**Issue by tcjin** [prometheus/prometheus#9011]
![image](https://user-images.githubusercontent.com/83052513/123773605-5c326a00-d8ff-11eb-942f-40f39ea27f4b.png)
![image](https://user-images.githubusercontent.com/83052513/123773840-82580a00-d8ff-11eb-8c31-7ab31ab28ef6.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
