### ISSUE TITLE
why Prometheus continues to send alert data even after the alarm has been restored

### ISSUE THREAD

**Issue by huangyong1991** [prometheus/prometheus#9037]
When receiving the alarm data sent by Prometheus, I returned the status of 200 in the program. When the alarm was lifted, there was no alarm in the alarm page, but Prometheus was still sending the previous alarm message。
please help

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
