### ISSUE TITLE
Can multiple directories be configured with the storage.tsdb.path option

### ISSUE THREAD

**Issue by ktpktr0** [prometheus/prometheus#9039]
I use docker swarm to create Prometheus service. I create multiple copies for it on the same node, but a directory can only be mounted by one. Therefore, can multiple data directories be configured

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
