### ISSUE TITLE
Scrape Interval not working for push gateway 

### ISSUE THREAD

**Issue by kustav123** [prometheus/prometheus#9060]
My pushgateway is getting new value every 15m so I have set the interval as 15m. As expected there should be 1 value in every 15m but as I can see it's stretching 5m for every single value. Please find the screenshot. 
 
![image](https://user-images.githubusercontent.com/47721564/124639489-d9368400-dea9-11eb-9405-d3241bfae5a7.png)
![image](https://user-images.githubusercontent.com/47721564/124639619-0125e780-deaa-11eb-8cb4-7e9772019de1.png)

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
