### ISSUE TITLE
Params has encoded

### ISSUE THREAD

**Issue by lianyiwork** [prometheus/prometheus#9095]
Hello everyone!
I found this answer from [stackoverflow:](https://stackoverflow.com/questions/40172415/question-mark-in-prometheus-metrics-path-gets-encoded)
scrape_configs:
  - job_name: 'somename'
    params:
      prefix: ['finatra']
      url: ['http://:9090/admin/metrics.json']

When i do that,i also get params encoded:
url=http%3A%2F%2F%3A9090%2Fadmin%2Fmetrics.json

Is there any idea?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
