### ISSUE TITLE
prometheus federation hava a bug

### ISSUE THREAD

**Issue by thirdcountry** [prometheus/prometheus#9172]
montior link :
promtheus（central node）<- prometheus（federation node）-> job: node_exporter -> consul_sd_configs ->  some_node 172.1.1.1:9100

when some_node  port 9100 is down, central node consider federation node is down，and then whole federation node  is not available...

![FZVTXFDH)47 XMRMY3RZDPE](https://user-images.githubusercontent.com/49510674/128605818-2256fd11-0705-4593-9cb2-09dfe11f3ac7.png)

**Comment by git-kundan** [comment]
In a simple test set-up that I did, the central node always reported federated node as 'up' as long as it was running. This is because following params matches always succeed on a running federated Prometheus server.
 ```yaml
   params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'
````
I notice 'context deadline exceeded' error message in the screenshot. This could be due to the prom query failing for something specific in your environment. Please provide the central/federated/node_exporter version and config files to reproduce the issue.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
