### ISSUE TITLE
Alarm refresh

### ISSUE THREAD

**Issue by 1093358332** [prometheus/prometheus#9220]
**What did you do?**
I use Prometheus. Due to resource problems, some indicators always reach the alarm threshold

**What did you expect to see?**
I hope that some alarms will continue to be reported without interruption

**What did you see instead? Under which circumstances?**
After a period of time, some of the alarms were interrupted, and the alarm was re-alerted a few minutes later. In this process, the indicator has always reached the alarm threshold

**Environment**
A multi-node federated cluster

* Prometheus version:
	2.15

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
