### ISSUE TITLE
Codemirror PromQL: Imprecise error message for undefined functions

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#9249]
**What did you do?**

I entered an undefined PromQL function in the editor, for example, `hello()`.

**What did you expect to see?**

The `function not defined` error message when hovering over the expression, which I believe is specified here:

https://github.com/prometheus/prometheus/blob/54dfee02b29180bd5353b1ba843ef600f802366c/web/ui/module/codemirror-promql/src/lang-promql/parser/parser.ts#L258

**What did you see instead? Under which circumstances?**

The `unexpected expression` error message.

https://prometheus.demo.do.prometheus.io/graph?g0.expr=hello()&g0.tab=1&g0.stacked=0&g0.range_input=1h

Note: The response from the API is fine, this is just the message the editor displays.

**Environment**

* Prometheus version:

	`2.27.0` and `2.29.1`

**Comment by Nexucis** [comment]
Yeah I think the line you are pointing is not reachable actually. You are going to this part of the code if the word `hello` is already identified as a function.

So if `hello` is not associated to a function, then the resulting tree won't have the node corresponding to the `function`.

To summarize, codemirror-promql is not able to tell you it's an incorrect function because it is not able to linked `hello()` to a function.

Probably we will have to build something on top of codemirror to be able to identify this kind of error.

Not so easy from my perspective unfortunately :(.

**Comment by Nexucis** [comment]
the condition https://github.com/prometheus/prometheus/blob/54dfee02b29180bd5353b1ba843ef600f802366c/web/ui/module/codemirror-promql/src/lang-promql/parser/parser.ts#L257-L259

is present more for sanity check and also because if it's not present then typescript is yelling that `funcID` can be undefined.

**Comment by LeviHarrison** [comment]
OK makes sense. Thanks!
