### ISSUE TITLE
The same query condition continuously click query to get different conditions

### ISSUE THREAD

**Issue by lklkxcxc** [prometheus/prometheus#9341]
**What did you do?**
The same query condition to get different results graph trend line,Continuous click query.
```ceph_osd_apply_latency_ms``` 

**What did you expect to see?**
The same graph trend line
**What did you see instead? Under which circumstances?**

**Environment**

* System information:
Linux 3.10.0-693.el7.x86_64 x86_64
* Prometheus version:
2.10.0
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
