### ISSUE TITLE
Update the existing custom metrics

### ISSUE THREAD

**Issue by atifsayeedi** [prometheus/prometheus#9353]
I have a metrics like this device{deviceID=“dev1”,code=“3”,status=“Connected”} 1.0 and the value of the labels like code and status changes after certain conditions then promethius inserts a new metrics for this.

Please suggest how to update the existing metrics.

device{deviceID=“dev1”,code=“3”,status=“Connected”} 1.0
to
device{deviceID=“dev1”,code=“4”,status=“Not Connected”} 1.0

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
