### ISSUE TITLE
Crashes in `promql.ParseMetricSelector()`

### ISSUE THREAD

**Issue by msiebuhr** [prometheus/prometheus#939]
After fuzzing `ParseMetricSelector()` for a few hundred iterations (see https://github.com/prometheus/prometheus/issues/667#issuecomment-125750642), it is found to crash on inputs `.٩`, `G.٩` and `.٩٩٩٩٩٩٩٩٩٩٩٩٩٩٩٩٩`.

The first two lead to errors in the lexer and the latter hangs the parser (i.e. it takes more than 10s to complete; the limit looks to be imposed by go-fuzz).

See

**Comment by juliusv** [comment]
Whoa, pasing `.٩` into the Prometheus expression text area in the browser and then hitting the left-arrow button moves the cursor all the way to the left of the input field and then freezes my Chrome tab. Seems like Prometheus isn't the only piece of software disliking that character combination...

**Comment by juliusv** [comment]
Hah. So this symbol is an Arabic 9, which is categorized as a digit by `unicode.IsDigit()`.

http://play.golang.org/p/TsuLx8f2pO

Same for the other "digits" in the Arabic Unicode block: https://en.wikipedia.org/wiki/Arabic_(Unicode_block)

This probably throws off our parser because we use `unicode.IsDigit()` in multiple places in the lexer in the expectation that it would only match `[0-9]`.

Filed https://github.com/prometheus/prometheus/pull/942 to fix this.

I definitely learned something new today.

**Comment by juliusv** [comment]
@msiebuhr Btw., were you inspired by this Fuzz-athon? https://groups.google.com/forum/#!topic/golang-nuts/4PmyYvcnpIs
