### ISSUE TITLE
Agent: Adjust UI for no current Agent capabilities.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#9612]
![image](https://user-images.githubusercontent.com/6950331/139480420-7c6a0af9-dacf-4277-9df7-480b4caccea7.png)

I believe we need to adjust UI so it does not show
* graph
* alerts
* rules

Otherwise UI is essential 🤗 

cc @rfratto

**Comment by LeviHarrison** [comment]
I wonder how we would do this. I guess we could use [`/status/flags`](/status/flags), but that would have to update both https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/index.tsx and https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/Navbar.tsx from the result, which could be tricky.

Also, what would become the homepage?

**Comment by roidelapluie** [comment]
I would just serve a variable in the html like we do for the console links. Let's avoid an extra api call

**Comment by roidelapluie** [comment]
For the homepage:

I would avoid the runtime page because it seems not useful to have that data exposed directly to users who would stumble upon it by accident.

The targets page and TSDB status pages are also not users friendly, I would avoid them. Targets page also has performance issue.

I would just propose
![status](https://user-images.githubusercontent.com/291750/139957578-267251dd-58ff-4f51-9184-71c277894a16.png)
 a custom home page like this:

**Comment by LeviHarrison** [comment]
Looks good. Perhaps this is a good time to bring https://github.com/prometheus/prometheus/issues/7971 back up.

**Comment by LeviHarrison** [comment]
Now that #9943, #9941, #9941, #9851, and #9649 are merged, I think we're good.
