### ISSUE TITLE
Agent TSDB is not locked

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#9616]
Currently, it is possible to run 2 agents on the same TSDB. The agent should get the same locking mechanism as Prometheus does to avoid multiple instances to run on the same directory.

**Comment by rfratto** [comment]
Relevant code: 

Lock created here: https://github.com/prometheus/prometheus/blob/be2599c853840eb3a86500e2682b8c1f392d4e3d/tsdb/db.go#L675 
Released here on shutdown of the TSDB: https://github.com/prometheus/prometheus/blob/be2599c853840eb3a86500e2682b8c1f392d4e3d/tsdb/db.go#L1454

There's also a `prometheus_tsdb_clean_start` metric that should also be brought over to the agent.

I'm thinking this is a good case for sharing some logic between tsdb/agent since it'll mostly be the same minus the metric name.
