### ISSUE TITLE
The same PROMQL statement aggregation query return different results

### ISSUE THREAD

**Issue by daicheng123** [prometheus/prometheus#9718]
![image](https://user-images.githubusercontent.com/42512975/141289108-9b86e9b2-1af1-406b-9ba0-2b008007eafb.png)
![image](https://user-images.githubusercontent.com/42512975/141289184-3a0120a7-385a-4bdd-9a81-77b84e71e4c4.png)

**Comment by GiedriusS** [comment]
This is expected because rate() does extrapolation and as time goes on, your steps might fall on different timestamps as in your screenshots giving different results :smiley: Something like `query-frontend` from Thanos/Cortex can do query alignment according to the step parameter so that you wouldn't see such "anomalies". I hope this helps.
