### ISSUE TITLE
Unnecessary series creating in function `func (s *stripeSeries) getOrSet`

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/prometheus#9799]
This function will create series first no matter whether stripeSeries having the same series. 

function ref:
https://github.com/prometheus/prometheus/blob/7d5abdcf221c2cc20d1b96f50b9808d7084aa742/tsdb/head.go#L1416

code:
```
	// Create the series first
	var series *memSeries
	if preCreationErr == nil {
		series = createSeries()
	}

	i := hash & uint64(s.size-1)
	s.locks[i].Lock()

	if prev := s.hashes[i].get(hash, lset); prev != nil {
		s.locks[i].Unlock()
                // return the prev, and the series created before is not used
		return prev, false, nil
	}
```

**Comment by roidelapluie** [comment]
cc @codesome could you look into this? thanks!

**Comment by codesome** [comment]
That is not an issue. It get's called only when a matching series does not exist. Discarding it is rare and only happens when you are appending samples from same series in parallel.

But moving that line a bit below is acceptable too if you are willing to send a PR :)

**Comment by codesome** [comment]
I just remembered why we have it there: We want to keep the series creation outside the lock so that no unnecessary heavy operations is done when lock is held, because when Prometheus starts, there will be a lot of series creation and we want to avoid spikes in latency.

Closing this issue since it is not a problem and we don't want to move it below.
